### ISSUE TITLE
支持在 template 的 is 标签中使用模板语法

### ISSUE THREAD

**Issue by AdvancedCat** [redengineer/redmini#1]
## 新功能是为了解决什么问题(必填)？
使用Taro生成小红书小程序

## 期望的API是什么形式的(写下新功能调用方式的伪代码，选填)
请小红书研发大佬们快快支持一下  「is 标签中使用模板语法」 的功能吧，这是Taro生成xhsml的基础

目前Taro已创建了「小红书小程序平台插件」仓库，但是需要使用template的is标签支持模板语法，目前走不下去了
插件地址：https://github.com/NervJS/taro-plugin-platform-xhs

**Comment by AdvancedCat** [comment]
RedMini文档里提到 template is标签支持 mustache 语法，但实际并没有支持

https://miniapp-open.xiaohongshu.com/docs/frame/template

**Comment by Edge00** [comment]
> RedMini文档里提到 template is标签支持 mustache 语法，但实际并没有支持
> 
> https://miniapp-open.xiaohongshu.com/docs/frame/template

template 标签的 is 属性支持 mustache 语法将在 3~4 月支持，文档会修正下，感谢！

**Comment by l644738595** [comment]
现在支持了么

**Comment by Edge00** [comment]
@l644738595  该功能正在测试中，开发者工具 1.59.23.beta5，基础库 3.18.1 已经支持！

**Comment by l644738595** [comment]
@Edge00 这个版本我们可以先用么 在哪里下载呀

**Comment by Edge00** [comment]
@l644738595  可以的：
- Windows: https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/30892261-2810-45d6-8231-548c1237672f/xhs-mpide-1.59.23-beta.15.exe
- Mac: https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/578d7f39-429d-4e08-ab3d-fd6b593787bb/xhs-mpide-1.59.23-beta.15.dmg

**Comment by l644738595** [comment]
@Edge00 有没有taro3 的例子呀  自己启动不起来

**Comment by xutm** [comment]
> 

官方文档已经更新，看看能不能解决你的问题。
https://miniapp.xiaohongshu.com/docs/ide/frameworkdevelop#Taro
