### ISSUE TITLE
Taro @tarojs/plugin-platform-xhs 编译 button onGetPhoneNumber回调方法不执行

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#100]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [x] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 服务主体（如：小红书）
小红书
## 基础库版本或小红书APP版本(必填)
3.28.1
## 重现步骤 和 复现问题的最小demo Github链接
![image](https://user-images.githubusercontent.com/63334662/177703449-17339944-bac6-4794-8b40-980ceee97fe7.png)

## 期望结果 和 实际结果(必填)
onGetPhoneNumber正常响应
## 补充(猜测可能的原因是什么，你有啥想法，选填)
https://github.com/NervJS/taro-plugin-platform-xhs/blob/2acea8e9148d5779ebb52b68e354352fdcc66577/src/components.ts#L9
添加'bindgetphonenumber':''

**Comment by Hubmeat** [comment]
您好，后续版本会跟进修复，修复后会在 issue 下通知
