### ISSUE TITLE
小红书小程序页面分享生成的二维码链接，在类似微信等场景识别跳转问题

### ISSUE THREAD

**Issue by Limborx** [redengineer/redmini#1002]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
微盟

## 平台
IOS

## 小红书版本信息
8.11
 
## 基础库版本
v3.67.2

## 发生问题的时间 
2023-10-31 16:04:07 至 2023-10-31 16:04:07

## 问题描述
我们测试反馈了一个问题，我们分享页面生成的二维码，通过微信聊天界面识别二维码，可以唤起小红书app，也可以进入页面，但是页面报错，应该是参数丢失导致的。

这个二维码小红书App直接扫是可以正常进入的

## 期望结果
正常跳转到小红书小程序页面

## 重现步骤和复现问题的最小demo Github链接
1、小红书分享页面，生成二维码图片

2、微信聊天界面长按图片识别二维码

3、触发小红书App唤起

4、一定概率进入授权页面、或者进入小程序页面，但是小程序页面报错

二维码解析如下
https://www.xiaohongshu.com/miniapp/qrcode?background_transparent&#x3D;true&amp;disableNativeLoading&#x3D;yes&amp;fullscreen&#x3D;true&amp;i&#x3D;616e5a35c52bb0000110bad3&amp;k&#x3D;16&amp;s&#x3D;1_11_4ldssio&amp;p&#x3D;cms%2Ftransform
![企业微信截图_16987389233761](https://github.com/redengineer/redmini/assets/37734145/98ab4cf4-c4a2-4269-8898-86e04f5e5337)

这个是我把二维码解析出来的结果

**Comment by ohaq-hue** [comment]
二维码解析有误
