### ISSUE TITLE
分享好友卡片预览版小程序无法打开

### ISSUE THREAD

**Issue by zhoufeng133435** [redengineer/redmini#1003]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
太目

## 平台
IOS, Android

## 小红书版本信息
8.11.1
 
## 基础库版本
v3.66.5

## 发生问题的时间 
2023-10-31 16:38:46 至 2023-10-31 16:38:46

## 问题描述
预览版小程序分享好友卡片后，无法打开小程序

## 期望结果
希望修复此问题，感谢

## 重现步骤和复现问题的最小demo Github链接
预览版小程序分享好友卡片后，在聊天的页面中无法打开小程序，报错：未找到该小程序，请重新确认链接或二维码是否正确

**Comment by ohaq-hue** [comment]
暂不支持该能力
