### ISSUE TITLE
navigationBarBackgroundColor: "#fff"设置不生效

### ISSUE THREAD

**Issue by fengchunsun2016** [redengineer/redmini#101]
## 系统环境(必填)
- [ 有问题 ] IOS 
- [ 正常 ] Android
- [ 正常 ] IDE

## 问题模块(必填)

- [ 小程序全局和页面配置 navigationBarBackgroundColor ] API

- [ v7.46(7460332) ] 客户端

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [ ] 有赞
- [ ] 微盟
- [ 1 ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 服务主体（如：小红书）
  小红书

## 基础库版本或小红书APP版本(必填)
  小程序基础库版本：3.28.1
  小红书APP版本：v7.46(7460332)

## 重现步骤 和 复现问题的最小demo Github链接
  小程序全局配置
  ```
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '直客通',
    navigationBarTextStyle: 'black',
  },
  ```
  配置的navigationBarBackgroundColor值为‘#fff’白色，但是在ios客户端显示的是黑色背景，导致黑色字体不可见

## 期望结果 和 实际结果(必填)
  期望navigationBarBackgroundColor: '#fff'，客户端小程序顶部背景显示为白色

## 补充(猜测可能的原因是什么，你有啥想法，选填)
  设置navigationBarBackgroundColor值为‘#ffffff’后客户端显示正常白色的背景色

**Comment by AngryBrotherXiang** [comment]
iOS 7.48 fix
