### ISSUE TITLE
请帮忙提供贵方服务器出口ip以便我司加入安全网关白名单访问

### ISSUE THREAD

**Issue by liang-kai** [redengineer/redmini#1012]
## Issue类型
feature

## 所属的服务商
中信银行信用卡

## 这个功能解决的问题
小程序上用来验证业务域名的那个服务，是否有固定的互联网IP地址。我们有内网的小程序业务域名配置，需要开通IP白名单才能访问，以方面开发测试进行验证。如有，麻烦提供，谢谢

**Comment by ohaq-hue** [comment]
###
