### ISSUE TITLE
onshow不会触发，需要进入其他页面并返回后才会触发

### ISSUE THREAD

**Issue by mocerliu** [redengineer/redmini#1018]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
PFT

## 平台
IDE

## 小红书版本信息
2.0.7
 
## 基础库版本
v3.71.1

## 发生问题的时间 
2023-11-10 16:40:15 至 2023-11-10 16:40:15

## 问题描述
1. 页面在packs.json中设置： 
	list: [
		{	"pagePath": "pages/my/index",
				"text": "我的"}
		]
2. 进入pages/my/index页面时不会触发onshow ， 需要再次进入其他页面（B），从B页面返回后，才会触发onshow 

## 期望结果
正常使用正常使用正常使用正常使用

## 重现步骤和复现问题的最小demo Github链接
// pages/my/index

```
<!-- @format -->

<template>
  <view class="box">
    <view class="s">这是页面</view>
    <view class="ss" @click="clickHandler"> 跳转到其他页面 </view>
  </view>
</template>

<script>
export default {
  onShow() {
    console.debug("onshow--");
  },

  methods: {
    clickHandler() {
      uni.navigateTo({
        url: "/pagesContent/notice/notice",
      });
    },
  },
};
</script>

<style></style>
```

**Comment by mocerliu** [comment]
![image](https://github.com/redengineer/redmini/assets/30655615/e1f916bc-7691-4928-830c-e430b10817d1)
× 为不触发

**Comment by boysfantasy** [comment]
这个问题大概什么时候修复，我们这边也有遇到。很紧急

**Comment by yujon** [comment]
这个今天看下。你在群里么，@我们下，我到时候给个新包

**Comment by yujon** [comment]
> 这个问题大概什么时候修复，我们这边也有遇到。很紧急

这个今天看下。你在群里么，@我们下，我到时候给个新包

**Comment by yujon** [comment]
uniapp转换插件的问题，已修复
