### ISSUE TITLE
小程序webview页面 长按图片无法保存

### ISSUE THREAD

**Issue by zhoufeng133435** [redengineer/redmini#1020]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
太目

## 平台
IOS, Android

## 小红书版本信息
8.14
 
## 基础库版本
v1.0.0

## 发生问题的时间 
2023-11-14 10:49:26 至 2023-11-14 10:49:26

## 问题描述
小程序webview页面 长按图片无法保存，浏览区环境下没问题

## 期望结果
修复，过渡阶段我们来做兼容

## 重现步骤和复现问题的最小demo Github链接
太目小程序中，点击云仓，进入商家端后，分享商品，生成海报，海报长按无法保存

**Comment by taiyiandr** [comment]
8.16+版本已经支持
