### ISSUE TITLE
页面中弹窗，滑动事件无法禁止冒泡

### ISSUE THREAD

**Issue by zhoufeng133435** [redengineer/redmini#1031]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
太目

## 平台
IOS

## 小红书版本信息
8.14
 
## 基础库版本
v3.44.0

## 发生问题的时间 
2023-11-20 10:20:24 至 2023-11-20 10:20:24

## 问题描述
页面中的弹窗滑动事件，弹窗组件滑动结束会引起事件冒泡， 无法禁止冒泡

## 期望结果
希望能够修复，或者给出相关的兼容方案

## 重现步骤和复现问题的最小demo Github链接
页面中的弹窗，在弹窗中触发的catchtouchmove事件，会产生页面的事件冒泡，Android端可以阻止，但是iOS端无法阻止

**Comment by Hubmeat** [comment]
麻烦提供下最小复现 demo ？我们确认下你的页面结构

**Comment by zhoufeng133435** [comment]
https://github.com/zhoufeng133435/redmini_interflow

**Comment by zhoufeng133435** [comment]
用了一个自封装弹窗，辛苦有空看下@Hubmeat https://github.com/zhoufeng133435/redmini_interflow

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
