### ISSUE TITLE
发送客服消息 返回系统异常

### ISSUE THREAD

**Issue by nimaou** [redengineer/redmini#1039]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
吾叙酒旅通

## 平台
IOS, Android, IDE

## 小红书版本信息
8.15
 
## 基础库版本
v3.52.1

## 用户ID 
2fefb36ed0a17312a2c438f9989e6c8ecc690b546e513580f9f946991b64a25d

## 发生问题的时间 
2023-11-23 17:40:37 至 2023-11-23 17:40:37

## 问题描述
在收到客人发送消息后，为客人发送消息的时候，提示
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;\u7CFB\u7EDF\u5F02\u5E38\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5&quot;,&quot;code&quot;:2}
为服务商模式

## 期望结果
希望能够发送消息给客户

## 重现步骤和复现问题的最小demo Github链接
客人通过小程序button发送客服消息。服务端收到消息后，通过第三方模式调用发送客服消息接口，小红书返回{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;\u7CFB\u7EDF\u5F02\u5E38\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5&quot;,&quot;code&quot;:2}

**Comment by ZiWee** [comment]
@nimaou 可以提供下消息内容和发送时间吗？

**Comment by nimaou** [comment]
{
  "msgType": "text",
  "content": "1111",
  "openId": "2fefb36ed0a17312a2c438f9989e6c8ecc690b546e513580f9f946991b64a25d"
}


2023-11-27 16:06   发送的
