### ISSUE TITLE
request中 没有referer字段

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#104]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [ ] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 服务主体（如：小红书）
小红书
## 基础库版本或小红书APP版本(必填)
7.46
## 重现步骤 和 复现问题的最小demo Github链接
网络请求中没有referer字段

**Comment by xutm** [comment]
native 748 fix
