### ISSUE TITLE
rich-text组件，在基础库版本不同的情况下表现不一致

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#1044]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
自我游

## 平台
IOS, Android, IDE

## 小红书版本信息
8.14.3
 
## 基础库版本
v3.71.1

## 发生问题的时间 
2023-11-27 12:19:31 至 2023-11-27 12:19:31

## 问题描述
8.4.1 rich-text 富文本组件显示正常
8.14.3 rich-text 富文本组件显示不正常，图片溢出，经过查询，全局样式在 8.14.3 中对富文本内容无效

## 期望结果
全局样式能够作用到 rich-text 组件中

## 重现步骤和复现问题的最小demo Github链接
基础库版本  &gt;&#x3D; 3.71.1 都存在这个问题，&lt;&#x3D; 3.70.3 都正常

**Comment by jonsen-liu** [comment]
![6CB17C05-3A6F-41b0-B4FE-D31369DC6CDA](https://github.com/redengineer/redmini/assets/26186472/42fb24ee-e40a-45f9-82b5-12b67518c052)
![image](https://github.com/redengineer/redmini/assets/26186472/cd9896bf-b021-4abc-8af0-e1d13f064bf4)

**Comment by jzhmcoo1** [comment]
你好，8.14我们启用了web-component组件，这边确实存在全局样式作用不到的问题，我们这边修复下。
除了图片宽度需要指定，还有什么需要指定吗
