### ISSUE TITLE
小红书聚光里边显示商品规格异常

### ISSUE THREAD

**Issue by huang-shen** [redengineer/redmini#1048]
## Issue类型
operator

## 问题模块
商品笔记

## 所属的服务商
票星球

## 小红书版本信息
8.16

## 运营场景描述
小红书聚光里边笔记发布广告显示商品规格状态异常，但是同步均为已上架状态 。
![企业微信截图_7f1e0cc2-ed44-4f92-b712-5aa133935e15](https://github.com/redengineer/redmini/assets/53030164/4dc30cd0-34ce-48cf-88dc-45ddb9858c08)
![企业微信截图_75f5b8f7-e9bd-4fe4-8041-4d9554ec7564](https://github.com/redengineer/redmini/assets/53030164/9b733f6c-942f-4d92-8965-2407fbd945c6)
![image](https://github.com/redengineer/redmini/assets/53030164/8de93fe4-4a4b-436e-bf13-52dad1dbd0e4)

## 发生问题的时间 
2023-12-04 12:27:27 至 2023-12-04 12:27:27

## 期望结果
期望商品可以在小红书聚光正常发布广告

## 业务基础信息（选填）
appId:637728b449d1490001569235
out_product_id:652a8ff08445650001eaaee1
笔记id：656c51e500000000380326f9

**Comment by lindaxia1** [comment]
需要提供下聚光的投放账号，以及聚光报错的计划ID，感谢！

**Comment by lindaxia1** [comment]
> **@记星@喵斯** 聚光brandid：5f4cac6b0000000001001a56 计划id：21752009（当前商销的计划都报错） 笔记id：656c51e500000000380326f9
> 
> 商销的笔记报错： “该笔记关联的商品规格由于无库存、已下架、已删除或非本店铺商品等原因无法正常投放，请调整该商品规格，商品规格id：6550aa550971bf00011d9103”。但实际上商品规格id：6550aa550971bf00011d9103的status是在架

排查结论：库存为0导致
<img width="1408" alt="企业微信截图_77439773-7c1b-48f9-948d-3605bfb7fb71" src="https://github.com/redengineer/redmini/assets/152942743/72b8e79b-51d4-4d33-83e0-285066587c59">
