### ISSUE TITLE
input标签placeholderClass样式真机上不生效

### ISSUE THREAD

**Issue by dhumans** [redengineer/redmini#1049]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
领悦

## 平台
IOS

## 小红书版本信息
8.16
 
## 基础库版本
v3.74.2

## 发生问题的时间 
2023-12-01 13:24:51 至 2023-12-05 13:24:51

## 问题描述
input输入框制定placeholderClass样式不生效
真机 IOS 

## 期望结果
期望生效，和模拟器一致

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by jzhmcoo1** [comment]
真机上现在开启的是同层组件，所以和模拟器效果不一致。目前验证下来双端的placeholder-class行为都有些问题，你这边先用placeholderStyle做下，后续我们排期修复下

**Comment by dhumans** [comment]
ok
