### ISSUE TITLE
我在小程序下单并支付完成后，将订单状态同步至已完成（7：已完成),然后发起结算，提示报错信息：【msg":"当前订单数据状态错误，不可结算】；麻烦问一下，是不是只有创建售后单才能进行结算，或者说什么情况下才能发起结算

### ISSUE THREAD

**Issue by czyxhcxy** [redengineer/redmini#1052]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
卡里司马

## 平台
IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.75.2

## 发生问题的时间 
2023-12-06 10:26:27 至 2023-12-06 10:26:27

## 问题描述
我在小程序下单并支付完成后，将订单状态同步至已完成（7：已完成),然后发起结算，提示报错信息：【msg&quot;:&quot;当前订单数据状态错误，不可结算】；麻烦问一下，是不是只有创建售后单才能进行结算，或者说什么情况下才能发起结算

## 期望结果
期望知道 
1:是不是 一定要创建售后单才能进行结算?
2: 订单什么状态下才能发起结算?

## 重现步骤和复现问题的最小demo Github链接
1：先在小程序下单，并支付，
2： 同步状态到小红书为已完成，然后发起结算请求

**Comment by wdvxdr** [comment]
提供一下订单号，需要具体case看

**Comment by czyxhcxy** [comment]
外部订单号 是 412312061010012072
