### ISSUE TITLE
小红书的订单（小程序下的单）列表, 点击跳转订单详情提示报错:【未找到该小程序,请重新确认链接或二维码是否正确】】

### ISSUE THREAD

**Issue by czyxhcxy** [redengineer/redmini#1053]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
卡里司马

## 平台
IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.75.2

## 发生问题的时间 
2023-12-06 10:48:36 至 2023-12-06 10:48:36

## 问题描述
创建小红书订单号，path路径传的（/pages/order/orderDetails?tradeNo&#x3D;412312050920011692）,订单列表点击跳转报错，错误信息：【未找到该小程序,请重新确认链接或二维码是否正确】;请问是不是一定要先把小程序发布才行 

## 期望结果
期望能正确跳转至订单详情 

## 重现步骤和复现问题的最小demo Github链接
先在小红书的小程序下一笔订单，然后到小红色app的订单列表里，点击该笔订单，跳转到订单详情时，提示报错：【未找到该小程序,请重新确认链接或二维码是否正确】

**Comment by xutm** [comment]
要有生产包才行。先做下发布吧

**Comment by czyxhcxy** [comment]
小程序发完生产包上线之后，是不是所有用户都能看到了， 
你们小红书有没有去白的操作，让其他用户看不到，只能让我们开发者能够看到。这样我们既能验证下我们调整是否正常，
也能不影响用户
