### ISSUE TITLE
我们想提前打小程序的生产包，看看订单详情页跳转是否正常，但是又不想让线上用户看见，只有我们开发者可以调试看见，这种你们小红书有没有什么白名单的方法可以实现

### ISSUE THREAD

**Issue by czyxhcxy** [redengineer/redmini#1055]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.75.2

## 发生问题的时间 
2023-12-06 11:47:24 至 2023-12-06 11:47:24

## 问题描述
我们想提前打小程序的生产包，看看订单详情页跳转是否正常，但是又不想让线上用户看见，只有我们开发者可以调试看见，这种你们小红书有没有什么白名单的方法可以实现

## 期望结果
期望能提前发布小程序，但是不想让正常线上用户看见，我们开发者可以调试

## 重现步骤和复现问题的最小demo Github链接
我们想提前打小程序的生产包，看看订单详情页跳转是否正常，但是又不想让线上用户看见，只有我们开发者可以调试看见，这种你们小红书有没有什么白名单的方法可以实现

**Comment by xutm** [comment]
方案已经出了，计划下个双月支持
