### ISSUE TITLE
scroll-view组件内部元素绝对定位，手机预览点击后内部元素会消失问题

### ISSUE THREAD

**Issue by Healsc** [redengineer/redmini#1058]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
猫眼

## 平台
IOS

## 小红书版本信息
v8.16
 
## 基础库版本
v3.38.0

## 发生问题的时间 
2023-12-06 19:42:50 至 2023-12-06 19:42:50

## 问题描述
使用scroll-view组件，内部view元素绝对定位position: absolute，在手机预览时点击scroll-view组件元素或内部view元素，内部元素会消失

## 期望结果
使用scroll-view组件，内部view元素绝对定位position: absolute;，在手机预览时点击scroll-view组件元素或内部view元素，内部元素不消失

## 重现步骤和复现问题的最小demo Github链接
&lt;scroll-view scroll-x&#x3D;&quot;{{true}}&quot; style&#x3D;&quot;background:blue;height: 65vh; position: relative;&quot;&gt;
  &lt;view  style&#x3D;&quot;width: {{500}}px;height: {{330}}px; background:red; position: absolute; top:0; left: 100px;&quot;&gt;
      123
  &lt;/view&gt;
&lt;/scroll-view&gt;
初始时两个颜色块正常展示，点击红色或块蓝色块，红色元素消失
这段代码在某信小程序中是正常的

**Comment by jzhmcoo1** [comment]
![wecom-temp-1644-6541345fda6c14e6a68a5442d6c1725d](https://github.com/redengineer/redmini/assets/55695299/3653c030-a9f9-44cc-b67e-b7bd680edeb3)
用这个基础库试一下，能解决不
