### ISSUE TITLE
长页面滚动时，左上角偶尔出现“拷贝”提示

### ISSUE THREAD

**Issue by duanjianbo** [redengineer/redmini#1060]
![1](https://github.com/redengineer/redmini/assets/36756592/e3006fcc-be5a-4c31-bd8e-c381c7e56829)
![2](https://github.com/redengineer/redmini/assets/36756592/5d2191ff-1a23-42a5-944a-ed42767a42e5)
![3](https://github.com/redengineer/redmini/assets/36756592/1fbcad7a-44ee-4560-b48b-57112a29dce2)
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
迪奥

## 平台
IOS

## 小红书版本信息
v8.16
 
## 基础库版本
v3.75.2

## 发生问题的时间 
2023-12-07 13:35:31 至 2023-12-07 13:35:31

## 问题描述
长页面滚动时，左上角偶尔出现“拷贝”提示

## 期望结果
不出现这个“拷贝”提示

## 重现步骤和复现问题的最小demo Github链接
不局限某一个页面，任何长页面，似乎是滚动到底部的时候，偶尔就会出现这个 “拷贝” 提示。 出现机型（IOS v8.16 8160536）。问题页面代码中亦没有使用过setClipboardData  api

**Comment by wernerpeng** [comment]
请检查下是否有隐藏文本或链接，误触发了拷贝弹框，可以看下拷贝的内容是什么

**Comment by bestMrY** [comment]
我们也出现了这个问题，请问你们解决了吗 @duanjianbo
