### ISSUE TITLE
小红书生命周期执行顺序和微信不一致

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1066]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
绿云

## 平台
IOS, IDE, Android

## 小红书版本信息
8.17.0
 
## 基础库版本
v3.76.1

## 发生问题的时间 
2023-12-13 17:01:41 至 2023-12-13 17:01:41

## 问题描述
vue3编译到小红书小程序 onLoad的触发时间晚于onMounted 
由于是多端输出 其他小程序的执行时间都是onLoad早于onMounted onload获取参数 onMounted拿到参数后获取接口内容

## 期望结果
vue3编译到小红书小程序 onLoad的触发时间早于onMounted 

## 重现步骤和复现问题的最小demo Github链接
onLoad((options) &#x3D;&gt; {
  console.log(&quot;onLoad生命周期&quot;);
});
onMounted(() &#x3D;&gt; {
  console.log(&quot;onMounted生命周期&quot;);
});

**Comment by Hubmeat** [comment]
这个是架构差异导致的，目前在你们场景下导致了什么问题呢？

**Comment by heiyantutu** [comment]
> 这个是架构差异导致的，目前在你们场景下导致了什么问题呢？

因为我们是需要通过onLoad获取query参数 然后通过onMounted把query参数传递进去请求 现在的问题就会导致接口参数没有 接口无法正常返回数据 影响较大 因为这个项目还是编译了微信和H5的 这2个上的顺序都是对的

**Comment by heiyantutu** [comment]
onload获取参数 onMounted初始化数据 onShow 每次页面展示触发 这个逻辑你看下应该是合理的

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jzhmcoo1** [comment]
替换插件后已解决
