### ISSUE TITLE
小程序后退重载页面

### ISSUE THREAD

**Issue by satin520** [redengineer/redmini#1067]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
绿云

## 平台
IOS, Android, IDE

## 小红书版本信息
8.18
 
## 基础库版本
v3.78.0

## 发生问题的时间 
2023-12-13 17:05:45 至 2023-12-13 17:05:45

## 问题描述
才用uniapp开发的小红书小程序，进入页面后退会重载页面，data数据重置，mounted也重新执行

## 期望结果
小程序后退不重载页面，mounted不执行

## 重现步骤和复现问题的最小demo Github链接
进入任意小程序页面，后退复现

**Comment by jzhmcoo1** [comment]
替换插件后已解决

**Comment by dinghr537** [comment]
请问替换什么插件解决的？我这里后退页面还是会重新mount，用的是uniapp，小红书版本8.47，基础库版本3.99.1，同样的项目在h5或其他小程序平台未发现重新mount的问题

**Comment by jzhmcoo1** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/ide/frameworkdevelop#di-er-bu-ban-ben-ti-huan-he-patch
参考下这个

**Comment by dinghr537** [comment]
> https://miniapp.xiaohongshu.com/docs?path=/docs/ide/frameworkdevelop#di-er-bu-ban-ben-ti-huan-he-patch 参考下这个

感谢！看样子是uniapp版本不够新导致的
