### ISSUE TITLE
小程序开发者工具更新不稳定吗？

### ISSUE THREAD

**Issue by jiangyh123** [redengineer/redmini#1068]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
太目

## 平台
IDE

## 小红书版本信息
2.0.9
 
## 基础库版本
v3.78.1

## 发生问题的时间 
2023-12-14 10:06:12 至 2023-12-14 10:06:12

## 问题描述
我开发者工具编译代码后，手机预览样式乱了，咋回事呀，我现在要回退工具版本到2.0.7，我又找不到版本了

## 期望结果
能不能把2.0.7版本的工具放出来

## 重现步骤和复现问题的最小demo Github链接
你自己试试

**Comment by yujon** [comment]
win： https://picasso-static.xiaohongshu.com/electron-app-updater-cli/2.0.7/xhs-mpide-2.0.7.exe
mac：https://picasso-static.xiaohongshu.com/electron-app-updater-cli/2.0.7/xhs-mpide-2.0.7.dmg

**Comment by yujon** [comment]
截图看下详情面板？看下这个
<img width="1256" alt="image" src="https://github.com/redengineer/redmini/assets/16963584/86c0e667-e2ab-460d-939e-b292bf188fb5">
