### ISSUE TITLE
scroll-view中的fixed定位错误

### ISSUE THREAD

**Issue by Suntgr** [redengineer/redmini#1072]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
微盟

## 平台
IOS

## 小红书版本信息
8.17
 
## 基础库版本
v3.76.1

## 发生问题的时间 
2023-12-14 15:11:18 至 2023-12-14 15:11:18

## 问题描述
scroll-view中的fixed定位，位置错误。croll-view组件我并没有加任何影响fixed定位的属性，但是结果是定位没有相对于视窗

## 期望结果
scroll-view中的fixed定位相对于视窗定位

## 重现步骤和复现问题的最小demo Github链接
// 代码很简单，下面的复制过去就可以复现  
&lt;scroll-view style&#x3D;&quot;height:100vh&quot; scroll-y&gt;
    &lt;view style&#x3D;&quot;height:200vh;background:grey&quot; bind:tap&#x3D;&quot;click&quot; /&gt;
    &lt;view style&#x3D;&quot;position:fixed;bottom:0;width:100vw;height:50vh;background-color:orange;&quot;&gt;
      scroll-view中的fixed定位
    &lt;/view&gt;
  &lt;/scroll-view&gt;

**Comment by Suntgr** [comment]
我们scroll-view中的内容涉及别的团队，别的组件。虽然可以把fixed定位移到外面，但是成本很大。
我们同一套代码，微信小程序正常。所以觉得是你们的一个bug。希望修复

**Comment by jzhmcoo1** [comment]
这个我们短期无法支持，如果需要支持的话需要改变下拉刷新的方案，成本比较大
