### ISSUE TITLE
radio组件，选中了，禁用了，但是还能操作

### ISSUE THREAD

**Issue by jiangyh123** [redengineer/redmini#1074]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
太目

## 平台
Android

## 小红书版本信息
8.17.0
 
## 基础库版本
v3.76.1

## 用户ID 
187310322

## 发生问题的时间 
2023-12-14 18:09:40 至 2023-12-14 18:09:40

## 问题描述
选中状态，禁止操作，但是禁止操作情况下，选中状态还能写好，只是样式是置灰的，勾选不勾选能交互

## 期望结果
选中状态，禁止操作，但是禁止操作情况下，选中状态还能写好，只是样式是置灰的，勾选不勾选不能交互

## 重现步骤和复现问题的最小demo Github链接
&lt;radio color&#x3D;&quot;#FF2F28&quot; checked&#x3D;&quot;{{selectAll}}&quot; disabled&#x3D;&quot;{{disabled}}&quot; bindtap&#x3D;&quot;checkAll&quot;&gt;&lt;/radio&gt;

**Comment by jzhmcoo1** [comment]
8.20版本，会将disabled后的radio bindtap事件禁止
