### ISSUE TITLE
vue3编译小红书小程序 事件触发存在问题

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1075]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
绿云

## 平台
IOS, Android, IDE

## 小红书版本信息
8.17.0
 
## 基础库版本
v3.77.0

## 发生问题的时间 
2023-12-15 14:29:32 至 2023-12-15 14:29:32

## 问题描述
点击按钮会触发其他事件 代码层面已经自查 没有逻辑性问题 其他编译平台 如微信小程序 H5展示都正常 而且更加神奇的是 当前页面下拉刷新 事件触发又正常 但是其他地方的调用又有问题

## 期望结果
对应事件点击后 应该触发对应的事件 而非错误触发

## 重现步骤和复现问题的最小demo Github链接
https://github.com/redengineer/redmini/assets/11535505/27f0f2f7-7a2f-4f6c-b1ba-fa766185392b
github链接:https://github.com/heiyantutu/uniapp-xhs 其中xhsReplace是需要替换的文件 由于uniapp没有发版

**Comment by jzhmcoo1** [comment]
替换后插件patch后，已解决
