### ISSUE TITLE
内页右划返回触发区域过大

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#1076]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
迪奥

## 平台
IOS, Android

## 小红书版本信息
8.18
 
## 基础库版本
v3.38.0

## 发生问题的时间 
2023-12-15 14:29:28 至 2023-12-15 14:29:28

## 问题描述
小程序内页touch事件右划时，会被系统的右划返回上一页影响到，一滑动就会返回上一页

## 期望结果
将返回上一页的触发阈值减少  可以参考

## 重现步骤和复现问题的最小demo Github链接
进入内页 - 右划

**Comment by leeligang1027** [comment]
目前平台规范，产品侧会进行调研后迭代，请关注开放平台文档中心！
