### ISSUE TITLE
需要支持setPageStyle API实现弹窗滚动穿透

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1078]
## Issue类型
feature

## 这个功能解决的问题
在微信小程序中 提供了如何API 可以让开发者限制滚动 由于小程序不能操作dom 每个页面传递弹框状态也不够优雅 希望增加
wx.setPageStyle({
        style: {
          overflow: &quot;hidden&quot;,
        },
      });和wx.setPageStyle({
        style: {
          overflow: &quot;&quot;,
        },
      });

**Comment by jzhmcoo1** [comment]
试下这个

```js
xhs?.setBodyStyle({
   style: "overflow: hidden;",
});
```

```js
xhs?.setBodyStyle({
   style: "",
});
```
