### ISSUE TITLE
在scroll-view中 z-index为-1的覆盖了z-index为4的上方 

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1080]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
绿云

## 平台
IOS, Android, IDE

## 小红书版本信息
8.17.0
 
## 基础库版本
v3.76.1

## 发生问题的时间 
2023-12-17 21:17:51 至 2023-12-17 21:17:51

## 问题描述
在scroll-view中 z-index为-1的覆盖了z-index为4的上方 

## 期望结果
根据CSS的层叠规范 应该是在下方的

## 重现步骤和复现问题的最小demo Github链接
![image](https://github.com/redengineer/redmini/assets/11535505/5af94250-980a-4496-8e58-52338fc34e04)

**Comment by jzhmcoo1** [comment]
scroll-view的下拉刷新策略会在容器内加transform属性，导致定位不正常。8.20版本会先将非下拉刷新的scroll-view的transform去除，后续会排期重构下拉刷新的实现
