### ISSUE TITLE
使用 taro(3.6.20) 最新版本生成最小 tarodemo 运行在 ide 上报错

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#1083]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
8.18
 
## 基础库版本
v3.76.1

## 发生问题的时间 
2023-12-19 16:44:31 至 2023-12-19 16:44:31

## 问题描述
用 taro(3.6.20)最新版本打包生成的小红书包运行不成功 控制台报错 
index.864e08e6.js:2 GET http://127.0.0.1:56865/miniapp/v1/app.json 500 (Internal Server Error)
index.864e08e6.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading &#x27;map&#x27;)
    at l_ (index.864e08e6.js:2)
    at index.864e08e6.js:2
l_ @ index.864e08e6.js:2
(anonymous) @ index.864e08e6.js:2

## 期望结果
能正常运行代码 ide 能用

## 重现步骤和复现问题的最小demo Github链接
https://static.dingdandao.com/library/superC/dist.zip 打包后的内容地址

**Comment by collincheng** [comment]
<img width="862" alt="image" src="https://github.com/redengineer/redmini/assets/49746060/8f222927-d75a-48a6-93a0-4e026fc978c1">
<img width="792" alt="image" src="https://github.com/redengineer/redmini/assets/49746060/816026d4-0306-4752-a48a-92135bf0cdc3">
看着是 app.json 文件读取不到导致 undefined 错误

**Comment by yujon** [comment]
> <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/49746060/291531713-8f222927-d75a-48a6-93a0-4e026fc978c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMwMTUsIm5iZiI6MTcwMjk4MjcxNSwicGF0aCI6Ii80OTc0NjA2MC8yOTE1MzE3MTMtOGYyMjI5MjctZDc1YS00OGE2LTkzYTAtNGUwMjZmYzk3OGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZGE1ZDdlOWE3MmQ0NmZmMjQ4YjZmOWJiNzNjNzlkYTRkMWRmZTU0Mzg5NTYyZGQyMmJiMWI2ODkwMGVmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.STQNij6jHJo_A6bmSYCyBHT1rVF6pBlYjKtqwRFoD68"> <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/49746060/291531775-816026d4-0306-4752-a48a-92135bf0cdc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMwMTUsIm5iZiI6MTcwMjk4MjcxNSwicGF0aCI6Ii80OTc0NjA2MC8yOTE1MzE3NzUtODE2MDI2ZDQtMDMwNi00NzUyLWE0OGEtOTIxMzViZjBjZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDBlZGQ0NWY1MjVjYTRmODJhMmJjODc2NDM0MGVjOGVlOWQ4MDliNzUwZDQwYjUzOGZkMzVjZDhkZGQ1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwXPZ3YDLPrKAoK8IjjNG1_SlS40XTsVmbyp36v9hig"> 看着是 app.json 文件读取不到导致 undefined 错误

ide 用的什么版本，升级到2.0.9以上。并且project.config.json内，添加个setting: {}字段
