### ISSUE TITLE
点击按钮只拉起一次定位授权，【允许】后不会再弹出授权弹框

### ISSUE THREAD

**Issue by muluolanke** [redengineer/redmini#1085]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
上汽大众

## 平台
IOS

## 小红书版本信息
v8.12.1
 
## 基础库版本
v3.79.0

## 发生问题的时间 
2023-12-20 12:15:12 至 2023-12-20 12:15:12

## 问题描述
页面按钮点击，拉起定位授权；
授权弹框点击【允许】后，再次弹出定位授权弹框。

## 期望结果
点击按钮只拉起一次定位授权，【允许】后不会再弹出授权弹框

## 重现步骤和复现问题的最小demo Github链接
https://github.com/muluolanke/test-xhs

**Comment by wernerpeng** [comment]
安全起见第一次调用xhs.authorize和xhs.getLocation都会有授权弹窗，可以考虑只调用getLocation
