### ISSUE TITLE
picker组件mode="time"显示有误

### ISSUE THREAD

**Issue by satin520** [redengineer/redmini#1087]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
绿云

## 平台
IOS, Android, IDE

## 小红书版本信息
8.18
 
## 基础库版本
v3.79.1

## 发生问题的时间 
2023-12-20 14:44:53 至 2023-12-20 14:44:53

## 问题描述
picker组件mode&#x3D;&quot;time&quot;显示有误

## 期望结果
现在显示有误，显示为时间格式时分

## 重现步骤和复现问题的最小demo Github链接
uniapp 中picker组件mode&#x3D;&quot;time&quot;显示有误，显示为年

**Comment by jzhmcoo1** [comment]
如何复现？uniapp 测试工程中的 case 下 未复现

```html
<view class="uni-title uni-common-pl">时间选择器</view>
    <view class="uni-list">
    <view class="uni-list-cell">
    <view class="uni-list-cell-left">
	    当前选择
    </view>
    <view class="uni-list-cell-db">
	    <picker mode="time" :value="time" start="09:01" end="21:01" @change="bindTimeChange">
		    <view class="uni-input">{{time}}</view>
	    </picker>
    </view>
    </view>
</view>
<view class="uni-picker-tips">
    注：选择 09:01 ~ 21:01 之间的时间, 不在区间内不能选中
</view>
```

**Comment by jzhmcoo1** [comment]
目前mode=time，暂不支持往start和end中传入日期，请先传入时间
