### ISSUE TITLE
小程序IDE编译错误 SplitChunksPlugin Cache group "default" conflicts with existing chunk

### ISSUE THREAD

**Issue by h172144754** [redengineer/redmini#1092]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
贝泰妮

## 平台
IDE

## 小红书版本信息
8.18
 
## 基础库版本
v3.75.1

## 发生问题的时间 
2023-12-22 14:02:04 至 2023-12-22 15:44:06

## 问题描述
小程序IDE编译错误 
SplitChunksPlugin
Cache group &quot;default&quot; conflicts with existing chunk.
Both have the same name &quot;service-common&quot; and existing chunk is not a parent of the selected modules.
Use a different name for the cache group or make sure that the existing chunk is a parent (e. g. via dependOn).
HINT: You can omit &quot;name&quot; to automatically create a name.
BREAKING CHANGE: webpack &lt; 5 used to allow to use an entrypoint as splitChunk. This is no longer allowed when the entrypoint is not a parent of the selected modules.
Remove this entrypoint and add modules to cache group&#x27;s &#x27;test&#x27; instead. If you need modules to be evaluated on startup, add them to the existing entrypoints (make them arrays). See migration guide of more info.

## 期望结果
小程序开发者工具可以正常编译运行

## 重现步骤和复现问题的最小demo Github链接
有一个组件在tabbar页面和分包中的二级页面同时使用,这个组件可以理解为一个页面,

**Comment by yujon** [comment]
麻烦提供个复现demo
