### ISSUE TITLE
安卓机型内嵌webview页面，跳转H5页面有问题

### ISSUE THREAD

**Issue by hileslie** [redengineer/redmini#1098]
## Issue类型
bug

## 问题模块
小程序容器(Android)
 
## 所属的服务商
有赞

## 平台
Android

## 小红书版本信息
v8.16.0
 
## 基础库版本
v3.80.1

## 发生问题的时间 
2023-12-27 00:00:00 至 2023-12-28 19:11:35

## 问题描述
安卓机型内嵌webview页面，使用location.href等js跳转方式跳往另一个h5页面，会先跳转一个空白页，再跳转目标页，回页面后会提示【小程序页面不存在】。
iOS任意机型和版本没有问题。

## 期望结果
安卓机型内嵌webview页面跳转，无空白中间页

## 重现步骤和复现问题的最小demo Github链接
任意安卓机，搜索【谭帮主】用户，进入店铺小红书小程序，进入个人中心后，点击任意页面跳转

**Comment by LaoChen1994** [comment]
在开发者工具中会碰到webview内a标签无法跳转问题，不知道是否有碰到过
