### ISSUE TITLE
小程序第一个页面不是tabbar的页面 switchTab 跳转 报错 

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#11]
![image](https://user-images.githubusercontent.com/49746060/167243907-fca86e97-43d1-4b62-b21b-a61f678a8be4.png)
导致进入首页失败 白屏

**Comment by collincheng** [comment]
![image](https://user-images.githubusercontent.com/49746060/167243907-fca86e97-43d1-4b62-b21b-a61f678a8be4.png)

**Comment by Yaxian** [comment]
麻烦提供一下 IDE 版本

**Comment by xutm** [comment]
IDE 1.59.26 已修复，建议下载最新版
