### ISSUE TITLE
专业号后台没有绑定上小程序

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#1109]
## Issue类型
operator

## 问题模块
专业号后台没有绑定上小

## 所属的服务商
有赞

## 小红书版本信息
V8.12

## 运营场景描述
专业号后台没有绑定上小程序，导致无法在专业号设置店铺入口 

## 发生问题的时间 
2024-01-09 10:26:09 至 2024-01-09 10:26:09

## 期望结果
专业号后台绑定上小程序店铺。

## 业务基础信息（选填）
appid：647444bfed6af9004e03b235

**Comment by xutm** [comment]
自研小程序白名单 和 开发白名单 没有加上

**Comment by lhwzqqz** [comment]
自研小程序白名单 和 开发白名单 这个白名单是在什么地方申请。
