### ISSUE TITLE
canvas中drawImage的image用getImageInfo的path，无法绘制图片。用网络图片链接可以正常绘制，但是canvasToTempFilePath生成的图片没有drawImage内容

### ISSUE THREAD

**Issue by caiyan1** [redengineer/redmini#1116]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
有赞

## 平台
IOS, Android

## 小红书版本信息
8.20
 
## 基础库版本
v3.76.1

## 发生问题的时间 
2024-01-17 10:00:00 至 2024-01-17 18:41:58

## 问题描述
使用xhs.getImageInfo返回的path，传参给canvas的drawImage函数，开发者工具可以正常渲染，但是真机调试无法在canvas中绘制图片。如果ctx.drawImage传网络图片链接，canvasToTempFilePath获取到的图片又没有canvas中绘制的图片

## 期望结果
期望传getImageInfo的path可以在ios和Android上正常渲染且canvasToTempFilePath可以正常渲染

## 重现步骤和复现问题的最小demo Github链接
const ctx &#x3D; Taro.createCanvasContext(&#x27;myCanvas&#x27;);
xhs.getImageInfo({url: &#x27;https://intl-image.yzcdn.cn/images/2023/12/04/4f577d853cc0ad75b4919410dd36bd07.jpg?w&#x3D;1125&#x27;}).then({path, width, height} &#x3D;&gt;{
  ctx.drawImage(path, 0,0 canvasWidth, canvasHeight, 0, 0, width, height)
  ctx.draw(true, () &#x3D;&gt; {
       xhs.canvasToTempFilePath({
      x: 0,
      y: 0,
      width: canvsWidth,
      height: canvasHeight,
      canvasId: &#x27;myCanvas&#x27;,
      fileType: &#x27;png&#x27;,
      quality: 1,
      success: (result) &#x3D;&gt; {
        console.log(result.tempFilePath) // 期望这张图片的效果是正常的。即便drawImage用网络连接，canvas正常渲染，但是canvas生成的临时文件没有这种图片，ios必现
      },
    })
  })
})

**Comment by Hubmeat** [comment]
canvasToTempFilePath 目前只支持返回 base64
