### ISSUE TITLE
使用beta版本基础库，小程序预览码浏览小程序，点击小程序右上角三个点，再点击分享，点击无反应，无法正常唤起联系人列表。

### ISSUE THREAD

**Issue by caiyan1** [redengineer/redmini#1119]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
有赞

## 平台
Android

## 小红书版本信息
8.22.0
 
## 基础库版本
v3.82.0

## 用户ID 
490275287

## 发生问题的时间 
2024-01-19 15:00:00 至 2024-01-19 16:24:41

## 问题描述
扫码更换为beta版本基础库，再扫开发者预览码，点击分享小程序，没有反应

## 期望结果
和已经发布的基础库版本一样，预览码小程序也能正常点击分享唤起联系人列表

## 重现步骤和复现问题的最小demo Github链接
设备：HUAWEI P30 Pro，型号代码：VOG-AL10，系统：HarmonyOS 3.0.0

**Comment by caiyan1** [comment]
补充：分享传的imageUrl用的canvasToTempFilePath返回的base64，才会触发这个问题。之前的基础库没有问题

**Comment by Hubmeat** [comment]
分享的 imageUrl 不支持 base64 啊

**Comment by caiyan1** [comment]
> 分享的 imageUrl 不支持 base64 啊

实际是支持且可以正常展示，不过是太大的base64不支持。

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
