### ISSUE TITLE
小程序分享到聊天对话框的时候，shareAppMessage的imageUrl可以传canvasToTempFilePath生成的base64

### ISSUE THREAD

**Issue by caiyan1** [redengineer/redmini#1120]
## Issue类型
feature

## 所属的服务商
有赞

## 这个功能解决的问题
商品分享，期望在分享的图片上展示商品图片、商品价格、原价、立即购买等自定义内容，这些数据都是动态的，所以需要一张在点分享按钮之前一定存在的图片。
目前用canvas绘制图片是最快的，然而canvasToTempFilePath生成的tempFilePath是base64，当这个base64太大的时候，shareAppMessage分享点击无反应，base64较小的时候才可以。

期望：shareAppMessage的imageUrl可以传canvasToTempFilePath返回的base64，且不限制大小。

或者期望canvasToTempFilePath可以返回本地临时文件路径，shareAppMessage的imageUrl支持传临时文件路径，类似微信的效果。

**Comment by caiyan1** [comment]
期望支持canvas的measureText

**Comment by xutm** [comment]
已经支持

https://github.com/redengineer/redmini/issues/1215

https://github.com/redengineer/redmini/issues/1213
