### ISSUE TITLE
小红书小程序需要协助解绑。开发时用的账号，是直接调用接口创建的订单（没有落库），这部分订单没有取消导致解绑不了

### ISSUE THREAD

**Issue by Fudeveloper** [redengineer/redmini#1127]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
票付通

## 小红书版本信息
v8.4.1

## 运营场景描述
这是开发时使用的账号，直接调用接口创建的订单（没有落库），这部分订单没有取消导致解绑不了。

 

## 发生问题的时间 
2024-01-25 10:35:49 至 2024-01-25 10:35:49

## 期望结果
希望有一个接口查询账号下的所有订单；或者协助查询哪些订单没有取消

## 业务基础信息（选填）
APPID：6509707a9b400b004033c1c0

**Comment by leeligang1027** [comment]
当前已满足解绑条件，可以进行解绑
