### ISSUE TITLE
请支持图片压缩 compressImage  https://uniapp.dcloud.net.cn/api/media/image.html#compressimage

### ISSUE THREAD

**Issue by motopia** [redengineer/redmini#1135]
## Issue类型
feature

## 所属的服务商
票星球

## 这个功能解决的问题
上传图片，对于过大图片需要做压缩处理，目前其他小程序已经支持此 API

**Comment by xutm** [comment]
已经支持 https://miniapp.xiaohongshu.com/docs?path=/docs/api/compressImage， 客户端 8.27 支持
