### ISSUE TITLE
小程序提审后查询审核状态报错

### ISSUE THREAD

**Issue by xiaotiantianya** [redengineer/redmini#1137]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
天时同城

## 小红书版本信息
v8.23.2

## 运营场景描述
小红书小程序提交审核发布，查询审核状态时报错：小红书错误提示:{&quot;error_code&quot;:500,&quot;error_msg&quot;:&quot;Request failed, please contact our system administrator 请求失败, 请和系统管理人员联系&quot;,&quot;success&quot;:false}[107167] 

## 用户ID 
65499f5c0000000002013fcb

## 发生问题的时间 
2024-02-01 14:35:46 至 2024-02-01 14:35:46

## 期望结果
希望小程序正常发布上线

## 业务基础信息（选填）
小程序APPID：65a5f55011c77d0052c595de

**Comment by wdvxdr** [comment]
已企微群回复

**Comment by Marmot93** [comment]
遇到相同的问题
小程序ID：65e1847054da35005890ec50
第三方开发商ID: 631af81c7c9aee000172a776
