### ISSUE TITLE
开放能力-接收客服消息48hr限制

### ISSUE THREAD

**Issue by davidgu0323** [redengineer/redmini#1141]
## Issue类型
feature

## 所属的服务商
迪奥

## 这个功能解决的问题
能否有办法能够解决48hr内客人未联系坐席的情况下，坐席能够对客人发送消息；
以及H5页面客人点击后跳转客服，能否让客服主动与客人进行会话。
以上，非常急，谢谢！

**Comment by leeligang1027** [comment]
平台内统一规则，暂不支持超时后主动联系平台内用户
