### ISSUE TITLE
小红书小程序有没有像 微信小程序（miniprogram-ci ）这样的ci模块，方便上传代码，还是只能通过开发者工具上传？

### ISSUE THREAD

**Issue by TracyWalt** [redengineer/redmini#1145]
## Issue类型
feature

## 这个功能解决的问题
方便开发者通过ci自动化上传代码

**Comment by yujon** [comment]
目前暂时没有，计划下个双月支持

**Comment by xutm** [comment]
已经支持 https://miniapp.xiaohongshu.com/docs?path=/docs/ide/xhs-mp-cli

**Comment by yixinagqingyuan** [comment]
> 已经支持 https://miniapp.xiaohongshu.com/docs?path=/docs/ide/xhs-mp-cli

高版本的 node 无法下载，14 版本以上下载报错
