### ISSUE TITLE
xhs.onNetworkStatusChange 安卓端没有返回isConnected字段

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1146]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
绿云

## 平台
Android

## 小红书版本信息
8.24
 
## 基础库版本
v3.83.1

## 发生问题的时间 
2024-02-22 11:08:09 至 2024-02-22 11:08:09

## 问题描述
xhs.onNetworkStatusChange 安卓端没有返回isConnected字段

## 期望结果
xhs.onNetworkStatusChange 安卓端需要返回isConnected字段和文档一致

## 重现步骤和复现问题的最小demo Github链接
https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/guide/frameworkAPI 根据小红书文档 应该是存在isConnected 而真机安卓测试发现联网状态下没有返回 导致res.isConnected为undefined 走了false逻辑
![微信图片_20240222111511](https://github.com/redengineer/redmini/assets/11535505/f3f9bcf4-a3d0-41e4-836c-dfc3febc3687)

**Comment by YaoPB** [comment]
会在 8.30版本上增加该字段( isConnected)，敬请关注
