### ISSUE TITLE
样式兼容问题，红米K30、红米Note 12

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#1150]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
其他

## 平台
Android

## 小红书版本信息
8.24.5
 
## 基础库版本
v0.0.1

## 发生问题的时间 
2024-03-01 14:54:47 至 2024-03-01 14:54:47

## 问题描述
页面中有复杂样式的情况，红米K30、红米Note 12 这两款机型容易出现样式错层，其他机型未发现这个问题

## 期望结果
与其他机型保持一致，无样式兼容问题

## 重现步骤和复现问题的最小demo Github链接
页面中有复杂样式的情况，红米K30、红米Note 12 这两款机型容易出现样式错层，其他机型未发现这个问题

**Comment by jonsen-liu** [comment]
正常情况下
![cde3d91d9106a74a551760557e5c7b62](https://github.com/redengineer/redmini/assets/26186472/1fde3fc0-a3dd-4525-95b5-09cd4b609b7e)


出现样式问题情况
![974f48adefa988a09c8bae9617628124](https://github.com/redengineer/redmini/assets/26186472/97fbd408-7276-4c23-8682-4ad3d32a27d8)

**Comment by jonsen-liu** [comment]
同机型 在微信小程序环境下正常

![48819355e08e983918839da5f20b19e3](https://github.com/redengineer/redmini/assets/26186472/cab596f5-2cfe-465f-b741-f83147a3c97f)

**Comment by jonsen-liu** [comment]
同机型  在抖音小程序下正常

![2e02af0e2e243db25171dec7913e3c51](https://github.com/redengineer/redmini/assets/26186472/90e5b57e-54a4-4c0f-9c89-cf9a7035abd4)

**Comment by hhuwc** [comment]
请提供 小红书小程序的 appId  或者 小程序名字

**Comment by jonsen-liu** [comment]
> 请提供 小红书小程序的 appId 或者 小程序名字

小程序名：乐周末度假
appid：62f36e67606f580017ecf2f0

**Comment by hhuwc** [comment]
<img width="523" alt="企业微信截图_d1ee9d19-87ae-454a-abb4-fb51e52140f0" src="https://github.com/user-attachments/assets/fd62ec5f-7b78-41d7-aba7-1a663966597f">

**Comment by hhuwc** [comment]
真机实测无问题
