### ISSUE TITLE
使用taro3.6.x初始化项目无法在真机正常渲染

### ISSUE THREAD

**Issue by yuuk** [redengineer/redmini#1171]
## Issue类型
bug

## 问题模块
小程序框架

## 所属的服务商
DFS

## 平台
IOS, Android

## 小红书版本信息
8.28
 
## 基础库版本
v3.87.0

## 发生问题的时间 
2024-03-20 12:50:45 至 2024-03-20 12:50:45

## 问题描述
使用taro3.6.x初始化项目无法在真机正常渲染，模拟器渲染没有问题，具体可以看我提供的仓库地址。

![image](https://github.com/redengineer/redmini/assets/9426456/bc668dd7-53a0-43fc-8064-f8627c091a86)
![image](https://github.com/redengineer/redmini/assets/9426456/8b1079ec-4d96-458e-9443-a886226ba860)

## 期望结果
能和模拟器表现一样，正常渲染

## 重现步骤和复现问题的最小demo Github链接
https://github.com/yuuk/xhs-miniapp-sandbox

**Comment by jzhmcoo1** [comment]
https://github.com/NervJS/taro-plugin-platform-xhs/pull/19

参考下这个改动，可以拉下来本地build下，然后替换下dist或者patch一下node_modules

**Comment by yuuk** [comment]
运行无问题了

**Comment by yuuk** [comment]
但发现一个新问题，我搜了一下好像是taro的老bug，https://github.com/NervJS/taro/issues/8168
