### ISSUE TITLE
mp-html富文本引入错误

### ISSUE THREAD

**Issue by fanzuwang** [redengineer/redmini#1178]
## Issue类型
feature

## 问题模块
小程序框架
 
## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.89.0

## 发生问题的时间 
2024-03-28 12:30:44 至 2024-03-28 12:30:44

## 问题描述
项目中引入mp-html报错，把微信小程序的mp-html复制过来 把后缀进行修改xhsml   css 

## 期望结果
能够正常使用mp-html富文本格式化工具

## 重现步骤和复现问题的最小demo Github链接
引入mp-html富文本格式化工具报错 load page module has uri error: missing route resource, route: pages/productDetail/mp-html/index

**Comment by hhuwc** [comment]
已解决
/s

**Comment by hhuwc** [comment]
Duplicate of #https://github.com/redengineer/redmini/issues/1177
