### ISSUE TITLE
可以支持界面渲染pixijs吗？

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1182]
## Issue类型
feature

## 这个功能解决的问题
前端需要展示动画

**Comment by Hubmeat** [comment]
暂不支持，如果基于 webGL 的话，短期内也无法支持到

**Comment by FengXinKai** [comment]
有其他类似的支持方案吗？

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
