### ISSUE TITLE
上传不了代码

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1190]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
kimo

## 平台
IDE

## 小红书版本信息
8.31.0
 
## 基础库版本
v3.84.1

## 发生问题的时间 
2024-04-12 14:10:48 至 2024-04-12 14:10:48

## 问题描述
提示sjs引入需要静态路径，但已经是静态路径了

## 期望结果
解决问题，希望能尽快解决

## 重现步骤和复现问题的最小demo Github链接
	&lt;sjs from&#x3D;&quot;./../../util/number.sjs&quot; module&#x3D;&quot;number&quot;/&gt;

**Comment by hhuwc** [comment]
你好代码贴一下

**Comment by hhuwc** [comment]
<img width="532" alt="image" src="https://github.com/redengineer/redmini/assets/20037388/2155f03d-d4f2-484b-ba9e-8877b369175b">
语法写错了，不是from 是 src
