### ISSUE TITLE
xhs.scanCode的原生页面不一致

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1191]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
绿云

## 平台
IOS

## 小红书版本信息
8.31
 
## 基础库版本
v3.90.0

## 发生问题的时间 
2024-04-16 11:45:07 至 2024-04-16 11:45:07

## 问题描述
IOS打开扫码的页面和xhs.scanCode不一致 安卓是一致的 

## 期望结果
IOS打开扫码的页面和xhs.scanCode一致 

## 重现步骤和复现问题的最小demo Github链接
这是IOS 分别从xhs.scanCode进入和小红书扫码的进入的样式
![0fea9a4ca2ec5ffbc1e9a193f6fb007](https://github.com/redengineer/redmini/assets/11535505/561a1381-d6d5-4c4e-8a5b-db4c339827c8)
![81c67e280a4aa1fb4fe249306f53fdd](https://github.com/redengineer/redmini/assets/11535505/b04bf431-333f-43bf-8a51-6e4de58cdd8c)
这是安卓分别从xhs.scanCode进入和小红书扫码的进入的样式
![23e26b0cac5b1aedb48386221208fd5](https://github.com/redengineer/redmini/assets/11535505/a6f377c3-af9a-4ca0-8683-d7004a892361)
![50b0da27e90f94af30103ad67d76a7e](https://github.com/redengineer/redmini/assets/11535505/22dc9f49-000a-43fb-a74f-99357f906657)

**Comment by wernerpeng** [comment]
两个扫码用的不同实现，我们尽快排期对齐
