### ISSUE TITLE
小程序的商品没有在客服后台显示，但是分页有显示有记录

### ISSUE THREAD

**Issue by 350050183** [redengineer/redmini#1194]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
广州三毛信息科技有限公司

## 平台
IOS, Android

## 小红书版本信息
8.32
 
## 基础库版本
v3.90.0

## 发生问题的时间 
2024-04-16 18:45:59 至 2024-04-17 13:45:59

## 问题描述
1、小程序的商品没有在客服工作后台显示，但是分页有显示有记录
2、可以通过接口获取同步过的商品信息，均正常审核通过了

## 期望结果
客服后台可以正常显示商品列表并能发送给客户

## 重现步骤和复现问题的最小demo Github链接
无。

**Comment by xutm** [comment]
你用的客服是哪个平台

**Comment by 350050183** [comment]
千帆后台下载的客户端软件
https://ark.xiaohongshu.com/

**Comment by 350050183** [comment]
![image](https://github.com/redengineer/redmini/assets/12798824/2edb3155-fa37-4667-a3e3-34b56ca24aa6)
后面显示是这样，有分页，但没有商品，我们的小程序还没上线（体验版中），有没有关系

**Comment by 350050183** [comment]
![image](https://github.com/redengineer/redmini/assets/12798824/e43bd64d-3350-4c04-bfb0-ed69af8ae2bd)
小红书小程序的客服功能可以推送商品信息

**Comment by xutm** [comment]
千帆是 原生电商 体系，小程序不支持

**Comment by 350050183** [comment]
但是能在小程序对接进来呢？消息收发，小程序推送商品这些都正常，千帆后台也都能看到（上面有截图）。而且小程序上架的商品也是可以显示在原生电商体系的。
这是APP更新的记录所说的：https://miniapp.xiaohongshu.com/docs?path=/docs/change-log/prdUpdateLog
![5e54e659a5652508631ebff9b383b7fe](https://github.com/redengineer/redmini/assets/12798824/f4faaf18-774f-4b12-a87b-130cf5cf774e)

所以理论上在千帆后台是要能正确显示小程序推送的商品信息的（而且底下的分页都有显示，只是商品没显示而已）。
