### ISSUE TITLE
xhs.request未正确返回接口报错信息

### ISSUE THREAD

**Issue by bestMrY** [redengineer/redmini#1195]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
DFS

## 平台
IOS

## 小红书版本信息
8.32
 
## 基础库版本
v3.90.0

## 发生问题的时间 
2024-04-17 14:13:55 至 2024-04-17 14:13:55

## 问题描述
使用xhs.request调用接口，接口返回http状态码400及response，在安卓及模拟器端接收到的与接口返回一致，在iOS端接收到的http状态码为9，且response为空
![image](https://github.com/redengineer/redmini/assets/71256474/2abeeb3a-70c9-44a4-81e3-85ef679ca96c)

![image](https://github.com/redengineer/redmini/assets/71256474/c1a55944-b182-4d09-954f-408d474c0e23)

## 期望结果
iOS端接收到的表现应与安卓一致

## 重现步骤和复现问题的最小demo Github链接

xhs.request({
                url: &#x27;https://xxxxxxxxxxxx&#x27;,
                success: (res) &#x3D;&gt; {
                    console.error(&#x27;success&#x27;, res);
                },
                fail: (err) &#x3D;&gt; {
                    console.error(&#x27;fail&#x27;, err);
                },
                complete: (res) &#x3D;&gt; {
                    console.error(&#x27;complete&#x27;, res);
                },
            })

**Comment by wernerpeng** [comment]
问题已定位，我们尽快修复下，跟版8.35，预计5.6号上线
