### ISSUE TITLE
接口返回404:page not found 接口路径不存在

### ISSUE THREAD

**Issue by leihaodegg** [redengineer/redmini#1196]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
只有红楼梦戏剧幻城

## 平台
IOS, IDE, Android

## 小红书版本信息
1
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-04-17 18:09:45 至 2024-04-17 18:09:45

## 问题描述
调用「商品同步-生活服务」接口报错：{&quot;error_code&quot;:404,&quot;error_msg&quot;:&quot;page not found 接口路径不存在&quot;,&quot;success&quot;:false}

## 期望结果
正确返回正确返回正确返回正确返回

## 重现步骤和复现问题的最小demo Github链接
Client error: &#x60;POST https://miniapp.xiaohongshu.com/api/rmp/mp/deal/poi/product/upsert?appid&#x3D;65a0a214f958370056950b21&amp;access_token&#x3D;aec5a2f15bbf46059e587b3b14427f71&#x60; resulted in a &#x60;404 Not Found&#x60; response:
{&quot;error_code&quot;:404,&quot;error_msg&quot;:&quot;page not found 接口路径不存在&quot;,&quot;success&quot;:false}

**Comment by ohaq-hue** [comment]
POST https://miniapp.xiaohongshu.com/api/rmp/tp/poi/product/upsert，详见：https://miniapp.xiaohongshu.com/docs?path=/third/api-3rd/post-api-rmp-tp-poi-product-upsert
