### ISSUE TITLE
Dior时装小程序客服消息报应用访问令牌不匹配

### ISSUE THREAD

**Issue by DavidGuu** [redengineer/redmini#1197]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
迪奥

## 平台
IDE

## 小红书版本信息
8.31.0
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-04-16 16:55:27 至 2024-04-17 19:55:27

## 问题描述
小红书通过API调用第三方token，客服发送消息给客人报错410101

## 期望结果
了解报错发生情况并改善

## 重现步骤和复现问题的最小demo Github链接
1、小红书调用token，客服发送消息给客人报错410101
2、发生时间4-16  17：18    appid：62c6a1671b7001000117ac6f，密钥：3X92E9tBemfGrIhSdv4e43IOd3JE4yljVS30RNppdzV
![应用访问令牌不匹配](https://github.com/redengineer/redmini/assets/156289295/483fce02-8ec7-41fd-bb67-1c58d7b3813e)

**Comment by ohaq-hue** [comment]
这个问题还存在吗
