### ISSUE TITLE
最新版小红书App打开小程序后，xhs.setStorage存储的值失效，每次进入小程序缓存都被清空

### ISSUE THREAD

**Issue by biao-code** [redengineer/redmini#1199]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
小蚁路书

## 平台
Android, IOS

## 小红书版本信息
8.32.0
 
## 基础库版本
v3.90.0

## 发生问题的时间 
2024-04-18 15:42:05 至 2024-04-18 15:42:05

## 问题描述
小程序的登录状态存储在Storage中，现在用户每次打开小程序都需要重新登录。
经调试发现，重新进入小程序后，Storage中的数据被清空了。

## 期望结果
Storage功能正常使用。

## 重现步骤和复现问题的最小demo Github链接
在代码中调用xhs.setStorage缓存数据。
进到请他页面请求xhs.getStorage数据，数据仍然存在。
关闭小程序，重新进。
进到请求xhs.getStorage数据的页面，数据为空。

下面正常的Storage数据：
![WechatIMG3614](https://github.com/redengineer/redmini/assets/23007720/9280a165-e0de-4321-ab7a-0983b4de4bdd)

下面是关闭小程序后，重新进来的数据：
![image](https://github.com/redengineer/redmini/assets/23007720/602c2e4a-b054-4b7c-b2e7-b42391b2479f)

**Comment by taiyiandr** [comment]
Android 8.31、8.32 存在问题，8.33已经修复
