### ISSUE TITLE
调用xhs.createSelectorQuery等api报错"Uncaught ReferenceError: vue is not defined"

### ISSUE THREAD

**Issue by WeiJietao** [redengineer/redmini#12]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [X] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [X] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)

1.59.23-beta.22

## 期望结果 和 实际结果(必填)

你好，我们在调用xhs.xxx api时报错"Uncaught ReferenceError: vue is not defined"，但实际上我们用的是react技术栈，根本没有用vue，如下图：

![截屏2022-05-07 下午5 53 07](https://user-images.githubusercontent.com/18640419/167249302-c1c4d09e-daae-4316-b846-6abf1a91dec1.png)

**Comment by Hubmeat** [comment]
这个问题肯能是  IDE 编译过程可能有问题导致，目前小红书 IDE 的存在一些问题，后续版本可能会修复。

先尝试重启 IDE，在尝试功能是否可用。
