### ISSUE TITLE
小程序支付功能被禁用，请小程序开发者重新申请

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1200]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
上海卡里司马科技有限公司

## 平台
IDE

## 小红书版本信息
V8.27
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-04-18 15:15:31 至 2024-04-18 19:15:31

## 问题描述
requestOrderPayment fail：小程序支付功能被禁用，请小程序开发者重新申请

## 期望结果
点击支付后，正常唤起收银台
小程序appID：6603a66501b4f3006071a553

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by Murphy3389** [comment]
如果需要提供其他内容，请联系我提供

**Comment by Murphy3389** [comment]
机型：小米11
安卓版本：12
有问题

**Comment by Murphy3389** [comment]
请问需要提供什么资料么？

**Comment by duguosong** [comment]
解决掉了吗。新接入的小程序，在开发版所有情况都是requestOrderPayment faik 小程序支付功能被禁用，请小程序开发者重新申请
@xutm @Murphy3389
