### ISSUE TITLE
火车铁路、机场接送以及租车类商品如何同步到小红书商品中心

### ISSUE THREAD

**Issue by imsimplise** [redengineer/redmini#1205]
![screenshot-20240422-114212](https://github.com/redengineer/redmini/assets/12131101/fa04f7f1-6ec4-4d31-861c-004a612d92d8)
![screenshot-20240422-114252](https://github.com/redengineer/redmini/assets/12131101/46eace80-ddf2-4d83-92ec-d40ee20cb359)
![screenshot-20240422-114920](https://github.com/redengineer/redmini/assets/12131101/e549c57f-6426-456c-8e0f-899cec03ad2f)
## Issue类型
feature

## 这个功能解决的问题
1. 火车铁路、机场接送类、租车类商品不是标准的商品，我们抽象了SPU和SKU，想看下用户下单以及商品挂载笔记并跳转到商品详情页是否可以？
2. 火车铁路商品：东京-新大阪就是一个商品ID，各个车次、坐席是SKU，商品详情页为东京-新大阪的所有车次页面
3. 机场接送类商品：接机或送机的机场作为一个商品ID，比如曼谷机场接机，商品详情页为曼谷机场接机到达不同下车地点的页面
4. 租车类商品：取还车地点作为一个商品ID，比如曼谷机场租车，不同车型是SKU，商品详情页为曼谷机场租车的所有车型页面

**Comment by leeligang1027** [comment]
请参考商品同步-生活服务接口进行同步！
