### ISSUE TITLE
小程序已经登录的状态下，关闭再重新进入，安卓手机会出现登录掉线的问题

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1206]
## Issue类型
bug

## 问题模块
小程序容器(Android)
 
## 所属的服务商
上海卡里司马科技有限公司

## 平台
IDE

## 小红书版本信息
V8.32
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-04-22 00:00:00 至 2024-04-23 11:04:58

## 问题描述
在代码中调用xhs.setStorageSync缓存数据。
进到请他页面请求xhs.getStorageSync数据，数据仍然存在。
关闭小程序，重新进。
进到请求xhs.getStorageSync数据的页面，数据为空。

## 期望结果
解决安卓手机在退出小程序再进入时，是正常登录状态

## 重现步骤和复现问题的最小demo Github链接
无，具体见问题描述

**Comment by Murphy3389** [comment]
请问有具体解决方法么

**Comment by taiyiandr** [comment]
8.33+ 版本已修复
