### ISSUE TITLE
小程序白屏

### ISSUE THREAD

**Issue by Avenmemety** [redengineer/redmini#1208]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
订单来了

## 平台
IOS, Android

## 小红书版本信息
8.24.5
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-04-23 16:50:40 至 2024-04-23 16:55:40

## 问题描述
开发者工具中能正常运行，审核也能通过，但是在生产环境中白屏了。
同一个小程序版本下，一般只会有个别商家会偶发这个问题。不用改代码，重新发一个新的版本，更新后此问题就会解决。

## 期望结果
小程序在开发者工具审核环境和生产环境展示一致。

## 重现步骤和复现问题的最小demo Github链接
在小红书中打开”湖州长颈鹿庄园“小程序，显示白屏。本地代码无法复现。

**Comment by Hubmeat** [comment]
目前看，你们场景下使用的是 taro 框架吗？看到 taro 的更新数据中 root 数据为空：
```js
 { root: cn: [] }
```
不确定你们的业务场景，可以尝试将数据写死，看看初始化数据是否可以正常展示在页面上

**Comment by Avenmemety** [comment]
> 目前看，你们场景下使用的是 taro 框架吗？看到 taro 的更新数据中 root 数据为空：
> 
> ```js
>  { root: cn: [] }
> ```
> 
> 不确定你们的业务场景，可以尝试将数据写死，看看初始化数据是否可以正常展示在页面上

是taro的。这个无法在开发环境下复现，即使是线上环境也是偶发的，所以没什么办法改。都不用数据写死，重新传一版代码就可以恢复正常了。以前我们用的都是很老的开发者工具，今年升级成最新的之后这个问题就开始出来了，不知道和这个有没有关系。

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hhuwc** [comment]
很老的开发工具版本还记得是多少嘛？

**Comment by Avenmemety** [comment]
> 很老的开发工具版本还记得是多少嘛？

xhs-mpide-1.59.24.dmg

**Comment by hhuwc** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/ide/overview

建议您去下载最新版本ide,
<img width="1499" alt="image" src="https://github.com/redengineer/redmini/assets/20037388/e0a01fcc-87c1-4898-9c40-c9f2d2a49829">

并在设置中勾选 轻量编译器试试

<img width="1250" alt="image" src="https://github.com/redengineer/redmini/assets/20037388/1691a8b6-6c77-4a28-a68b-2142c818a6f2">

**Comment by Avenmemety** [comment]
> https://miniapp.xiaohongshu.com/docs?path=/docs/ide/overview
> 
> 建议您去下载最新版本ide, <img alt="image" width="1499" src="https://private-user-images.githubusercontent.com/20037388/325054578-e0a01fcc-87c1-4898-9c40-c9f2d2a49829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjY0NDgsIm5iZiI6MTcxMzkyNjE0OCwicGF0aCI6Ii8yMDAzNzM4OC8zMjUwNTQ1NzgtZTBhMDFmY2MtODdjMS00ODk4LTljNDAtYzlmMmQyYTQ5ODI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAyMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMWQ0ZTkwZGY5YzE4ZDNjNjFkNzA0MDcwOTNiZTQ5OTUxNTNiMmU4OTg1MzUzNTc3YmZjNWE3OTY1MzhlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_WqNfbjFk0nlv0bUzhdpO5gipx-bnutAmKKp5Inlnc">
> 
> 并在设置中勾选 轻量编译器试试
> 
> <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/20037388/325055086-1691a8b6-6c77-4a28-a68b-2142c818a6f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjY0NDgsIm5iZiI6MTcxMzkyNjE0OCwicGF0aCI6Ii8yMDAzNzM4OC8zMjUwNTUwODYtMTY5MWE4YjYtNmM3Ny00YTI4LWE2OGItMjE0MmM4MThhNmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAyMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzY1MDdiYWZlNmVjNzI0ZGQ2ODNmZGM3N2QxMWQxYTcyZjgyMmQwMWNkNmRiNjQyYmI4NTNiN2Y5N2NhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFNT2S0C5LPOLOKN1H8OOUgXcfbUKf6zxi6Nq-JTuwk">

我们现在就是用的最新的。这几个选项是默认勾选的，一开始我们没去掉这几个选项，传上去就都白屏了，通不过审核。

**Comment by hhuwc** [comment]
你们用的taro 版本是多少呢？

**Comment by Avenmemety** [comment]
> 我们现在

<img width="704" alt="image" src="https://github.com/redengineer/redmini/assets/22796600/350d6dc4-1f42-42c7-8764-102548c830f6">

**Comment by Avenmemety** [comment]
> 你们用的taro 版本是多少呢？package.json 贴一下

`{
    "name": "superc",
    "version": "7.4.0",
    "private": true,
    "description": "订单来了C端",
    "templateInfo": {
        "name": "default",
        "typescript": true,
        "css": "sass"
    },
    "scripts": {
        "serve": "node bin/run.js",
        "build:pro": "yarn && cross-env API_ENV=pro node bin/build.js",
        "build:test": "yarn && cross-env API_ENV=test node bin/build.js",
        "checkV": "node bin/check.js",
        "inspect": "taro inspect --type weapp >> test.js",
        "ts-coverage": "typescript-coverage-report",
        "upload:weapp": "node ./upload/uploadWeapp",
        "upload:tt": "node ./upload/uploadTiktok",
        "pub:test": "LC_ALL=C node ./bin/publish",
        "build:swan:test": "yarn && cross-env API_ENV=test taro build --type swan",
        "dev:swan:test": "npm run build:swan:test -- --watch",
        "build:alipay:test": "yarn && cross-env API_ENV=test taro build --type alipay",
        "dev:alipay:test": "npm run build:alipay:test -- --watch",
        "build:tt:test": "yarn && cross-env API_ENV=test taro build --type tt",
        "build:tt:pre": "yarn && cross-env API_ENV=pre taro build --type tt",
        "build:tt:pro": "yarn && cross-env API_ENV=pro taro build --type tt",
        "dev:tt:test": "npm run build:tt:test -- --watch",
        "dev:tt:pro": "npm run build:tt:pro -- --watch",
        "build:h5:dev": "yarn && cross-env API_ENV=dev taro build --type h5",
        "build:h5:test": "yarn && cross-env API_ENV=test taro build --type h5",
        "build:h5:pre": "yarn && cross-env API_ENV=pre taro build --type h5",
        "build:h5:pro": "yarn && cross-env API_ENV=pro taro build --type h5",
        "dev:h5:dev": "npm run build:h5:dev -- --watch",
        "dev:h5:test": "npm run build:h5:test -- --watch",
        "dev:h5:pre": "npm run build:h5:pre -- --watch",
        "dev:h5:pro": "npm run build:h5:pro -- --watch",
        "build:weapp:pro": "yarn && cross-env API_ENV=pro taro build --type weapp",
        "build:weapp:pre": "yarn && cross-env API_ENV=pre taro build --type weapp",
        "build:weapp:test": "yarn && cross-env API_ENV=test taro build --type weapp",
        "dev:weapp:test": "cross-env API_ENV=test npm run build:weapp:test -- --watch",
        "dev:weapp:pro": "cross-env API_ENV=test npm run build:weapp:pro -- --watch",
        "build:xhs:test": "yarn && cross-env API_ENV=test taro build --type xhs",
        "build:xhs:pre": "yarn && cross-env API_ENV=pre taro build --type xhs",
        "build:xhs:pro": "yarn && cross-env API_ENV=pro taro build --type xhs",
        "dev:xhs:test": "npm run build:xhs:test -- --watch",
        "dev:xhs:pre": "npm run build:xhs:pre -- --watch",
        "dev:xhs:pro": "npm run build:xhs:pro -- --watch"
    },
    "browserslist": [
        "last 3 versions",
        "Android >= 4.1",
        "ios >= 8"
    ],
    "dependencies": {
        "@babel/runtime": "^7.7.7",
        "@sentry/tracing": "^6.17.6",
        "@sentry/vue": "^6.17.6",
        "@tarojs/components": "^3.6.15",
        "@tarojs/plugin-framework-react": "^3.5.6",
        "@tarojs/plugin-framework-vue3": "^3.6.15",
        "@tarojs/plugin-platform-h5": "^3.6.15",
        "@tarojs/plugin-platform-xhs": "1.1.0",
        "@tarojs/runtime": "^3.6.15",
        "@tarojs/taro": "^3.6.15",
        "@tarojs/webpack5-runner": "^3.6.15",
        "@vue/reactivity": "3.2.30",
        "Promise": "^1.0.5",
        "chalk": "^4.1.2",
        "dayjs": "^1.10.5",
        "debug": "^4.3.4",
        "js-base64": "^3.7.2",
        "mini-html-parser2": "^0.3.0",
        "prerender-spa-plugin": "^3.4.0",
        "promise": "7.3.1",
        "qdll-canvas": "^1.0.34",
        "qiniu": "6.1.13",
        "sa-sdk-miniprogram": "^1.17.2",
        "sentry-miniapp": "^0.11.1",
        "shelljs": "^0.8.5",
        "simple-git": "^3.17.0",
        "slash": "^3.0.0",
        "terser-webpack-plugin": "^5.3.7",
        "tt-ide-cli": "^0.1.15",
        "vant": "^3.4.5",
        "vue": "^3.0.0",
        "weixin-js-sdk": "^1.6.0"
    },
    "devDependencies": {
        "@babel/core": "^7.8.0",
        "@tarojs/cli": "^3.6.15",
        "@types/sass": "1.43.1",
        "@types/webpack-env": "^1.13.6",
        "@typescript-eslint/eslint-plugin": "^4.15.1",
        "@typescript-eslint/parser": "^4.15.1",
        "@vue/babel-plugin-jsx": "^1.1.1",
        "@vue/compiler-sfc": "^3.0.0",
        "@vue/eslint-config-typescript": "^8.0.0",
        "axios": "^1.3.4",
        "babel-plugin-import": "^1.13.3",
        "babel-preset-taro": "^3.6.15",
        "cross-env": "^7.0.3",
        "eslint": "^6.8.0",
        "eslint-config-prettier": "^6.0.0",
        "eslint-config-taro": "^3.6.15",
        "eslint-plugin-prettier": "^3.3.1",
        "eslint-plugin-vue": "^8.0.0",
        "execa": "5.1.1",
        "file-loader": "^6.2.0",
        "inquirer": "^8.0.0",
        "miniprogram-ci": "^1.8.35",
        "ora": "5.4.1",
        "prettier": "^2.2.1",
        "stylelint": "9.3.0",
        "typescript": "^4.1.0",
        "typescript-coverage-report": "^0.6.1",
        "vue-loader": "^16.0.0-beta.8",
        "webpack-bundle-analyzer": "^4.5.0"
    }
}
`

**Comment by Avenmemety** [comment]
{
    "name": "superc",
    "version": "7.4.0",
    "private": true,
    "description": "订单来了C端",
    "templateInfo": {
        "name": "default",
        "typescript": true,
        "css": "sass"
    },
    "scripts": {
        "serve": "node bin/run.js",
        "build:pro": "yarn && cross-env API_ENV=pro node bin/build.js",
        "build:test": "yarn && cross-env API_ENV=test node bin/build.js",
        "checkV": "node bin/check.js",
        "inspect": "taro inspect --type weapp >> test.js",
        "ts-coverage": "typescript-coverage-report",
        "upload:weapp": "node ./upload/uploadWeapp",
        "upload:tt": "node ./upload/uploadTiktok",
        "pub:test": "LC_ALL=C node ./bin/publish",
        "build:swan:test": "yarn && cross-env API_ENV=test taro build --type swan",
        "dev:swan:test": "npm run build:swan:test -- --watch",
        "build:alipay:test": "yarn && cross-env API_ENV=test taro build --type alipay",
        "dev:alipay:test": "npm run build:alipay:test -- --watch",
        "build:tt:test": "yarn && cross-env API_ENV=test taro build --type tt",
        "build:tt:pre": "yarn && cross-env API_ENV=pre taro build --type tt",
        "build:tt:pro": "yarn && cross-env API_ENV=pro taro build --type tt",
        "dev:tt:test": "npm run build:tt:test -- --watch",
        "dev:tt:pro": "npm run build:tt:pro -- --watch",
        "build:h5:dev": "yarn && cross-env API_ENV=dev taro build --type h5",
        "build:h5:test": "yarn && cross-env API_ENV=test taro build --type h5",
        "build:h5:pre": "yarn && cross-env API_ENV=pre taro build --type h5",
        "build:h5:pro": "yarn && cross-env API_ENV=pro taro build --type h5",
        "dev:h5:dev": "npm run build:h5:dev -- --watch",
        "dev:h5:test": "npm run build:h5:test -- --watch",
        "dev:h5:pre": "npm run build:h5:pre -- --watch",
        "dev:h5:pro": "npm run build:h5:pro -- --watch",
        "build:weapp:pro": "yarn && cross-env API_ENV=pro taro build --type weapp",
        "build:weapp:pre": "yarn && cross-env API_ENV=pre taro build --type weapp",
        "build:weapp:test": "yarn && cross-env API_ENV=test taro build --type weapp",
        "dev:weapp:test": "cross-env API_ENV=test npm run build:weapp:test -- --watch",
        "dev:weapp:pro": "cross-env API_ENV=test npm run build:weapp:pro -- --watch",
        "build:xhs:test": "yarn && cross-env API_ENV=test taro build --type xhs",
        "build:xhs:pre": "yarn && cross-env API_ENV=pre taro build --type xhs",
        "build:xhs:pro": "yarn && cross-env API_ENV=pro taro build --type xhs",
        "dev:xhs:test": "npm run build:xhs:test -- --watch",
        "dev:xhs:pre": "npm run build:xhs:pre -- --watch",
        "dev:xhs:pro": "npm run build:xhs:pro -- --watch"
    },
    "browserslist": [
        "last 3 versions",
        "Android >= 4.1",
        "ios >= 8"
    ],
    "dependencies": {
        "@babel/runtime": "^7.7.7",
        "@sentry/tracing": "^6.17.6",
        "@sentry/vue": "^6.17.6",
        "@tarojs/components": "^3.6.15",
        "@tarojs/plugin-framework-react": "^3.5.6",
        "@tarojs/plugin-framework-vue3": "^3.6.15",
        "@tarojs/plugin-platform-h5": "^3.6.15",
        "@tarojs/plugin-platform-xhs": "1.1.0",
        "@tarojs/runtime": "^3.6.15",
        "@tarojs/taro": "^3.6.15",
        "@tarojs/webpack5-runner": "^3.6.15",
        "@vue/reactivity": "3.2.30",
        "Promise": "^1.0.5",
        "chalk": "^4.1.2",
        "dayjs": "^1.10.5",
        "debug": "^4.3.4",
        "js-base64": "^3.7.2",
        "mini-html-parser2": "^0.3.0",
        "prerender-spa-plugin": "^3.4.0",
        "promise": "7.3.1",
        "qdll-canvas": "^1.0.34",
        "qiniu": "6.1.13",
        "sa-sdk-miniprogram": "^1.17.2",
        "sentry-miniapp": "^0.11.1",
        "shelljs": "^0.8.5",
        "simple-git": "^3.17.0",
        "slash": "^3.0.0",
        "terser-webpack-plugin": "^5.3.7",
        "tt-ide-cli": "^0.1.15",
        "vant": "^3.4.5",
        "vue": "^3.0.0",
        "weixin-js-sdk": "^1.6.0"
    },
    "devDependencies": {
        "@babel/core": "^7.8.0",
        "@tarojs/cli": "^3.6.15",
        "@types/sass": "1.43.1",
        "@types/webpack-env": "^1.13.6",
        "@typescript-eslint/eslint-plugin": "^4.15.1",
        "@typescript-eslint/parser": "^4.15.1",
        "@vue/babel-plugin-jsx": "^1.1.1",
        "@vue/compiler-sfc": "^3.0.0",
        "@vue/eslint-config-typescript": "^8.0.0",
        "axios": "^1.3.4",
        "babel-plugin-import": "^1.13.3",
        "babel-preset-taro": "^3.6.15",
        "cross-env": "^7.0.3",
        "eslint": "^6.8.0",
        "eslint-config-prettier": "^6.0.0",
        "eslint-config-taro": "^3.6.15",
        "eslint-plugin-prettier": "^3.3.1",
        "eslint-plugin-vue": "^8.0.0",
        "execa": "5.1.1",
        "file-loader": "^6.2.0",
        "inquirer": "^8.0.0",
        "miniprogram-ci": "^1.8.35",
        "ora": "5.4.1",
        "prettier": "^2.2.1",
        "stylelint": "9.3.0",
        "typescript": "^4.1.0",
        "typescript-coverage-report": "^0.6.1",
        "vue-loader": "^16.0.0-beta.8",
        "webpack-bundle-analyzer": "^4.5.0"
    }
}

**Comment by hhuwc** [comment]
目前我们未针对taro 3.6版本做适配，您的电脑是什么平台的

**Comment by Avenmemety** [comment]
> 目前我们未针对taro 3.6版本做适配，您的电脑是什么平台的

intel

**Comment by Avenmemety** [comment]
> 目前我们未针对taro 3.6版本做适配，您的电脑是什么平台的

我们升级到3.6已经很久了，一直没啥问题的。
现在的情况是：
1 :同一个版本只有个别商家（几十个里有1个，2个的样子）会出现这个问题
2: 重新传下代码就能解决白屏问题
3: 审核都能通过，但是线上会偶发

近几个月内发了3次版本，三次都是这种情况。基本排除了是本地代码的原因。如果你们那边比较难定位到问题，我们打算先回退到老的开发者工具了

**Comment by hhuwc** [comment]
等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏

**Comment by Avenmemety** [comment]
> 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> 
> mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg

好的好的，打不开呢这个链接
![image](https://github.com/redengineer/redmini/assets/22796600/a933c221-fee3-4fa2-bd95-6c811a87a6ac)

**Comment by Avenmemety** [comment]
> 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> 
> mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg

好的好的，这个链接打不开唉
![image](https://github.com/redengineer/redmini/assets/22796600/d282e5f8-339a-4e89-8bdb-ffe0398f64a8)

**Comment by hhuwc** [comment]
> > 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> > mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg
> 
> 好的好的，这个链接打不开唉 ![image](https://private-user-images.githubusercontent.com/22796600/325073348-d282e5f8-339a-4e89-8bdb-ffe0398f64a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzE5NDksIm5iZiI6MTcxMzkzMTY0OSwicGF0aCI6Ii8yMjc5NjYwMC8zMjUwNzMzNDgtZDI4MmU1ZjgtMzM5YS00ZTg5LThiZGItZmZlMDM5OGY2NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjN2Q3OGQ0MTFkYjYyNzg3ODU0ZDk1ZGUwN2ExOGFmYzk1MGQ5Mjk4MjAwOGE1YTNkYWY0MGQyMmRiMTRiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SanSUgXD-d7yn6dXUwCS9kYHGnJzC5yTrK380ccKBc)

上面重新更新了链接，你再试试

**Comment by Avenmemety** [comment]
> > > 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> > > mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg
> > 
> > 
> > 好的好的，这个链接打不开唉 ![image](https://private-user-images.githubusercontent.com/22796600/325073348-d282e5f8-339a-4e89-8bdb-ffe0398f64a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzE5NDksIm5iZiI6MTcxMzkzMTY0OSwicGF0aCI6Ii8yMjc5NjYwMC8zMjUwNzMzNDgtZDI4MmU1ZjgtMzM5YS00ZTg5LThiZGItZmZlMDM5OGY2NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjN2Q3OGQ0MTFkYjYyNzg3ODU0ZDk1ZGUwN2ExOGFmYzk1MGQ5Mjk4MjAwOGE1YTNkYWY0MGQyMmRiMTRiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SanSUgXD-d7yn6dXUwCS9kYHGnJzC5yTrK380ccKBc)
> 
> 上面重新更新了链接，将链接粘贴到一个空白tab，打开试试

好的，可以了。辛苦了。

**Comment by hhuwc** [comment]
> > > > 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> > > > mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg
> > > 
> > > 
> > > 好的好的，这个链接打不开唉 ![image](https://private-user-images.githubusercontent.com/22796600/325073348-d282e5f8-339a-4e89-8bdb-ffe0398f64a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzE5NDksIm5iZiI6MTcxMzkzMTY0OSwicGF0aCI6Ii8yMjc5NjYwMC8zMjUwNzMzNDgtZDI4MmU1ZjgtMzM5YS00ZTg5LThiZGItZmZlMDM5OGY2NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjN2Q3OGQ0MTFkYjYyNzg3ODU0ZDk1ZGUwN2ExOGFmYzk1MGQ5Mjk4MjAwOGE1YTNkYWY0MGQyMmRiMTRiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SanSUgXD-d7yn6dXUwCS9kYHGnJzC5yTrK380ccKBc)
> > 
> > 
> > 上面重新更新了链接，将链接粘贴到一个空白tab，打开试试
> 
> 好的，可以了。辛苦了。

试试用这个版本发布上线后，页面是否正常，有结论同步我们一下

**Comment by Avenmemety** [comment]
> > > > > 等会儿我打个ide给你，taro 3.6改成了递归模板实现，我们的代码逻辑中一直是不允许递归的，理论上就是会白屏
> > > > > mac 版本： https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/0be60d77-e423-44b1-a023-c023331187f8/xhs-mpide-2.0.15.dmg
> > > > 
> > > > 
> > > > 好的好的，这个链接打不开唉 ![image](https://private-user-images.githubusercontent.com/22796600/325073348-d282e5f8-339a-4e89-8bdb-ffe0398f64a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzE5NDksIm5iZiI6MTcxMzkzMTY0OSwicGF0aCI6Ii8yMjc5NjYwMC8zMjUwNzMzNDgtZDI4MmU1ZjgtMzM5YS00ZTg5LThiZGItZmZlMDM5OGY2NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjN2Q3OGQ0MTFkYjYyNzg3ODU0ZDk1ZGUwN2ExOGFmYzk1MGQ5Mjk4MjAwOGE1YTNkYWY0MGQyMmRiMTRiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SanSUgXD-d7yn6dXUwCS9kYHGnJzC5yTrK380ccKBc)
> > > 
> > > 
> > > 上面重新更新了链接，将链接粘贴到一个空白tab，打开试试
> > 
> > 
> > 好的，可以了。辛苦了。
> 
> 试试用这个版本发布上线后，页面是否正常，有结论同步我们一下

好的

**Comment by hhuwc** [comment]
我发现你们已经用我发的ide更新了一版，请问下这个版本是符合预期的嘛？

**Comment by Avenmemety** [comment]
> 我发现你们已经用我发的ide更新了一版，请问下这个版本是符合预期的嘛？

重发后白屏问题没了，但是我用老的IDE重新发包后也会变正常的。要验证问题解决与否还要等下次批量发版验证一下。

**Comment by Avenmemety** [comment]
> 我发现你们已经用我发的ide更新了一版，请问下这个版本是符合预期的嘛？

使用新的ide打包还是有偶发的白屏问题：【”平潭猫头乾游记民宿“小程序】

**Comment by hhuwc** [comment]
> > 我发现你们已经用我发的ide更新了一版，请问下这个版本是符合预期的嘛？
> 
> 使用新的ide打包还是有偶发的白屏问题：【”平潭猫头乾游记民宿“小程序】

你们代码中是否有 <block></block>  空标签呢?

**Comment by Avenmemety** [comment]
> > > 我发现你们已经用我发的ide更新了一版，请问下这个版本是符合预期的嘛？
> > 
> > 
> > 使用新的ide打包还是有偶发的白屏问题：【”平潭猫头乾游记民宿“小程序】
> 
> 你们代码中是否有 <block></block> 空标签呢?

没有哦。

**Comment by hhuwc** [comment]
你们能提供个在ide上能复现白屏的demo 嘛？

**Comment by Avenmemety** [comment]
> 你们能在ide上能复现一下白屏嘛？
> 
> 然后将taro代码提供一下

ide上从来没有复现过，连生产环境都是偶发的。
而且修改这个问题也不用改代码，把对应的小程序重新发一下就恢复正常了。

**Comment by hhuwc** [comment]
方便加一下我的微信嘛 hhu-wc
