### ISSUE TITLE
CanvasContext.measureText，

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1213]
## Issue类型
feature

## 这个功能解决的问题
不支持有没有其他的替代方法

**Comment by Hubmeat** [comment]
你好，请问你这边的服务商是哪家

**Comment by FengXinKai** [comment]
奇陌科技



---Original---
From: ***@***.***&gt;
Date: Sat, May 11, 2024 17:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [redengineer/redmini] CanvasContext.measureText， (Issue #1213)




 
你好，请问你这边的服务商是哪家

**Comment by Hubmeat** [comment]
需要支持自定义字体吗？自定义字体的话周期会更长，建议用系统字体




670306423
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月11日(星期六) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] CanvasContext.measureText， (Issue #1213)





 奇陌科技 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Sat, May 11, 2024 17:26 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [redengineer/redmini] CanvasContext.measureText， (Issue #1213) 
 
 
 
 
   
 你好，请问你这边的服务商是哪家

**Comment by xutm** [comment]
已经支持，客户端 8.39
