### ISSUE TITLE
希望webview支持xhs.miniProgram.openLocation？或者代替解决方案

### ISSUE THREAD

**Issue by xmasong** [redengineer/redmini#1217]
## Issue类型
feature

## 这个功能解决的问题
使用场景是业务内嵌webview页面中也有唤起内置地图诉求，但是目前xhs只支持在原生组件中唤起（xhs.openLocation）
能否支持或者有其他的代替方案？
目前 wx、douyin小程序已支持，如 https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html

**Comment by jzhmcoo1** [comment]
你好，可以引 3.9.2 版本的 webview jssdk
https://fe-static.xhscdn.com/xhs-mp/open/js/xiaohongshu-3.9.2.js
稍后会更新在文档中
