### ISSUE TITLE
专业号后台，版本审核被拒绝，原因”白屏“

### ISSUE THREAD

**Issue by xijiasheng** [redengineer/redmini#1225]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
DFS

## 小红书版本信息
v8.33.0

## 运营场景描述
专业号后台，版本审核被拒绝，原因”白屏“，品牌自查无问题希望给出具体的原因，帮助修复或给出解决建议，帮助通过审核。
4.26初次审核不通过
5.6换了一个版本的小程序依然不通过
拒绝原因均为&quot;白屏” 

## 用户ID 
无，审核环节

## 发生问题的时间 
2024-04-26 15:37:57 至 2024-05-06 15:37:57

## 期望结果
专业号后台，版本审核被拒绝，原因”白屏“，品牌自查无问题希望给出具体的原因，帮助修复或给出解决建议，帮助通过审核。

## 业务基础信息（选填）
小程序id：65f17fd3b04b500052cc3a7a

**Comment by yujon** [comment]
报错： <img width="1000" alt="image" src="https://github.com/redengineer/redmini/assets/16963584/9e930f82-41e5-4dca-8421-fd485c4daf71">

**Comment by bestMrY** [comment]
> 报错： <img alt="image" width="1000" src="https://private-user-images.githubusercontent.com/16963584/328111116-9e930f82-41e5-4dca-8421-fd485c4daf71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODMyODYsIm5iZiI6MTcxNDk4Mjk4NiwicGF0aCI6Ii8xNjk2MzU4NC8zMjgxMTExMTYtOWU5MzBmODItNDFlNS00ZGNhLTg0MjEtZmQ0ODVjNGRhZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4MDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjIyNWJiNWIxODg3YjY2ZTg3MDI2YWQ3MGM5ZTlhOGMyMTRhYjg4Yzc3ZGU5MGZhZmExNTliYzAxMDMxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8v-FVaZHSjjRgwMgtI5Sr3RldDSF1CX2utpGEhRQw38">

能提供下报错的基础库版本吗
