### ISSUE TITLE
命令行工具支持token免密登陆

### ISSUE THREAD

**Issue by alexlees** [redengineer/redmini#1226]
## Issue类型
feature

## 所属的服务商
懂车帝

## 这个功能解决的问题
命令行工具支持token免密登陆

**Comment by yujon** [comment]
1.2.0 已支持。文档还未更新，可以看附件
[README.md](https://github.com/user-attachments/files/15585153/README.md)
[SECRET.md](https://github.com/user-attachments/files/15585156/SECRET.md)
