### ISSUE TITLE
在小程序唤起登录界面，是否让用户可以操作 关注，有操作的交互逻辑。

### ISSUE THREAD

**Issue by HDHunter** [redengineer/redmini#1228]
## Issue类型
feature

## 所属的服务商
游道易

## 这个功能解决的问题
更好进行商务推广。

**Comment by xutm** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/api/followOfficialAccount
看看这个 API 是否能满足需求

**Comment by erqiu-sj** [comment]
> https://miniapp.xiaohongshu.com/docs?path=/docs/api/followOfficialAccount 看看这个 API 是否能满足需求

您好。这个API调用时，返回必须要是用户触发我用button的bindtap方法也报同样的错误。有遇到过吗？
