### ISSUE TITLE
ticket推送中断

### ISSUE THREAD

**Issue by wlyznb** [redengineer/redmini#1230]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
1.0.2
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-05-06 14:36:00 至 2024-05-07 18:06:55

## 问题描述
从5.6号下午14:36分后 每间隔10分钟推送的ticket中断,到目前为止 没有收到任何的ticket推送

## 期望结果
请尽快恢复推送ticket,以便后续的开发工作

## 重现步骤和复现问题的最小demo Github链接
从5.6号下午14:36分后 每间隔10分钟推送的ticket中断,到目前为止 没有收到任何的ticket推送

**Comment by Tokysky** [comment]
请问下具体是谁没有收到ticket推送，麻烦提供一下appid（或者提供一下之前收到的ticket消息）
