### ISSUE TITLE
小红书小程序无法获取密钥

### ISSUE THREAD

**Issue by Zoeyzoey1226** [redengineer/redmini#1231]
## Issue类型
operator

## 问题模块
小红书小程序开发者登陆

## 所属的服务商
D1M

## 小红书版本信息
8.34.1

## 运营场景描述
通过小红书专业号平台，点击小程序-小程序基础设置-重置密钥后，弹窗中的「复制」键无法点击，无法获取密钥。
使用的浏览器是谷歌浏览器，已经尝试过重新登陆、重启电脑、更换不同设备操作，均没用。 

## 用户ID 
548918e0b4c4d6271c608f72

## 发生问题的时间 
2024-05-07 18:23:49 至 2024-05-08 14:23:49

## 期望结果
正确获取小程序密钥的方式，能够正常操作

## 业务基础信息（选填）
小程序id:
6555873bd5423a0041271d65

**Comment by leeligang1027** [comment]
无法复现此问题，请退出登录后重试！
