### ISSUE TITLE
mac环境ide预览码页面报错

### ISSUE THREAD

**Issue by tcBestEngineer** [redengineer/redmini#1233]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
自开发

## 平台
IDE

## 小红书版本信息
1.0.0
 
## 基础库版本
v3.91.0

## 发生问题的时间 
2024-05-06 10:42:26 至 2024-05-11 10:42:26

## 问题描述
mach环境下
1.开发者工具2.0.16，基础库3.54.3或者3.91.0，执行预览操作后，主包样式崩坏，分包样式正常，初步排查发现&lt;view&gt;&lt;view&gt;aaa&lt;/view&gt;&lt;/view&gt;会被编译成一个view空标签，改成&lt;view&gt;aaa&lt;/view&gt;则正常展示。
2.使用xhs-mp-cli执行预览操作，主包页面表现正常，但是跳转分包时报错路径无法找到
项目本身是taro开发的，只有打包后预览模式有此问题，在开发者工具内表现正常，另在window系统内一切正常

## 期望结果
开发者工具与xhs-mp-cli保持预览效果一致性

## 重现步骤和复现问题的最小demo Github链接
苹果环境有此问题，试了三台苹果打包后扫预览码均有问题，试了两台windows，均正常展示

**Comment by hhuwc** [comment]
<view><view>aaa</view></view>

这个页面的代码贴一下
