### ISSUE TITLE
xhs.getUserProfile接口ios调用失败，安卓正常

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1234]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
奇陌

## 平台
IOS

## 小红书版本信息
8.25
 
## 基础库版本
v3.84.0

## 发生问题的时间 
2024-05-11 11:11:22 至 2024-05-11 11:11:22

## 问题描述
xhs.getUserProfile接口ios调用失败

## 期望结果
xhs.getUserProfile接口ios调用成功，请尽快修复

## 重现步骤和复现问题的最小demo Github链接
&lt;button class&#x3D;&quot;buttonone&quot; open-type&#x3D;&quot;getUserInfo&quot;  bindgetuserinfo&#x3D;&quot;getUserInfo&quot;&gt;授权头像&lt;/button&gt;    
getUserInfo(e) {
        console.log(e)
        xhs.setStorageSync(&#x27;avatarUrl&#x27;, e.detail.userInfo.avatarUrl)
        xhs.setStorageSync(&#x27;nickName&#x27;, e.detail.userInfo.nickName)
        var ths &#x3D; this
        xhs.showLoading({
            title: &#x27;正在登录&#x27;,
            mask: true
        }); //加载订单列表
        ths.login(this.data.code, e.detail.userInfo)
    },

**Comment by wernerpeng** [comment]
尝试更新到最新版小红书试试；
若还不行，请提供下userId；

**Comment by FengXinKai** [comment]
更新了也不行，这个userid是指小红书号吗？

**Comment by wernerpeng** [comment]
不是，打开小红书"我的" ==>点击右上角"分享"图片，里面有个复制链接，链接中的appuid提供一下

**Comment by FengXinKai** [comment]
好的 ，appid：6614d87700000000070046b0

**Comment by wernerpeng** [comment]
延迟授权弹框的自动隐藏，已修复
