### ISSUE TITLE
webview配置白名单没有生效

### ISSUE THREAD

**Issue by ggaier** [redengineer/redmini#1235]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
粗门

## 平台
Android, IOS

## 小红书版本信息
8.34.0
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-11 14:02:14 至 2024-05-11 15:02:14

## 问题描述
在服务商后台设置了小程序业务域名，webview组件加载，仍然提示域名配置白名单为空。

## 期望结果
域名设置后能生效，正确的加载网页地址。

## 重现步骤和复现问题的最小demo Github链接
1. 一个webview组件
2. 加载一个配置了域名的地址
3. 提示域名校验列表配置为空。

**Comment by Tokysky** [comment]
您好，当前流程给服务商配置域名白名单一般是服务商在沟通群中联系小红书产研人员然后我们人工处理

**Comment by ggaier** [comment]
> 您好，当前流程给服务商配置域名白名单一般是服务商在沟通群中联系小红书产研人员然后我们人工处理

好的好的
