### ISSUE TITLE
uniapp没有分享微信朋友的钩子回调（onShareChat），目前只有分享朋友圈的钩子回调（onShareTimeline）

### ISSUE THREAD

**Issue by 350050183** [redengineer/redmini#1236]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
广州三毛信息科技有限公司

## 平台
IOS, Android

## 小红书版本信息
8.35
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-13 11:48:29 至 2024-05-13 11:48:29

## 问题描述
uniapp没有分享微信朋友的钩子回调（onShareChat），目前只有分享朋友圈的钩子回调（onShareTimeline）

## 期望结果
针对uniapp框架添加onShareChat回调钩子方法

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by jzhmcoo1** [comment]
你好，这个已经支持了，参考一下这个 commit
https://github.com/jzhmcoo1/uni-app/commit/36b4234b7fd640d5b4fc206083431576243566ee

**Comment by 350050183** [comment]
@jzhmcoo1 可以再加一个uniapp的 onCopyUrl 事件的回调支持吗？
