### ISSUE TITLE
code2session授权码不匹配

### ISSUE THREAD

**Issue by wlyznb** [redengineer/redmini#1237]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
v8.34.1
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-13 16:48:16 至 2024-05-13 16:48:16

## 问题描述
code2session刷新最新的code 调用code2session 都返回授权码不匹配

## 期望结果
成功返回opinid和sessionkey

## 重现步骤和复现问题的最小demo Github链接
https://miniapp.xiaohongshu.com/api/rmp/tp/auth/session?appid&#x3D;65df0534ce96df0001c49b47&amp;auth_access_token&#x3D;ef2e522514904bac8bc0d6d15d222452&amp;code&#x3D;1aa79a56421543c6b5132c15896f6471
auth_access_token和code为有效期内的  但是返回code[410103], msg[授权码不匹配]

**Comment by wlyznb** [comment]
https://miniapp.xiaohongshu.com/api/rmp/tp/auth/session?appid=65df0534ce96df0001c49b47&auth_access_token=ef2e522514904bac8bc0d6d15d222452&code=1aa79a56421543c6b5132c15896f6471

**Comment by Tokysky** [comment]
您好，根据url的信息查询结果如下：
服务商appid为65df0534ce96df0001c49b47，根据auth_access_token查询到的商户小程序appid为662f54dc685b450051a8a9db，授权码code=1aa79a56421543c6b5132c15896f6471与商户小程序非绑定关系，所以接口返回授权码不匹配

**Comment by wlyznb** [comment]
我们是用授权小程序 调用xhs.login() 返回的code + 商户小程序的authAccessToken 和 服务商的appid ,如果是非绑定关系,要如何绑定

**Comment by wlyznb** [comment]
接口文档不是写用服务商appid吗

**Comment by Tokysky** [comment]
> 我们是用授权小程序 调用xhs.login() 返回的code + 商户小程序的authAccessToken 和 服务商的appid ,如果是非绑定关系,要如何绑定

这个参数的取值看起来是没有问题的，请问有没有服务商沟通的微信或者企业微信群，可直接在群内与小红书的产研沟通确认参数是否有问题哈

**Comment by AdrianTzm** [comment]
您好，请问解决了吗？我和您遇到一样的问题，文档不明确，如果您解决了，我们可以交流一下，谢谢 @wlyznb @wlyznb

**Comment by AdrianTzm** [comment]
@Tokysky @Tokysky @leeligang1027 @wlyznb @cruelwen
