### ISSUE TITLE
你们这逼玩意小程序开发者工具，日志不能复制?

### ISSUE THREAD

**Issue by wnagchi** [redengineer/redmini#1240]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
珑骧

## 平台
IOS, IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-13 17:39:47 至 2024-05-13 17:39:47

## 问题描述
你们这个逼玩意小程序开发者工具显示日志，不让复制？逗逼呢啊

## 期望结果
能复制日志，把这个破壁兼容性整好点

## 重现步骤和复现问题的最小demo Github链接
sbsbsbsbsb傻逼

**Comment by yujon** [comment]
IDE什么版本？哪里的日志，编译日志么？
