### ISSUE TITLE
小程序视频如何实现？

### ISSUE THREAD

**Issue by DarYeahLee** [redengineer/redmini#1242]
## Issue类型
operator

## 问题模块
广告投放

## 所属的服务商
广发

## 小红书版本信息
8.35

## 运营场景描述
小程序的视频怎么实现？我看文档写着要传个视频 id，这个 id 在哪里可以生成？
“string videoId video 组件的 id” 

## 发生问题的时间 
2024-05-13 20:36:14 至 2024-05-13 20:36:14

## 期望结果
文档已经看了，但还是不太清晰。期望小程序内实现视频的上传，辛苦解答以上问题。

**Comment by xutm** [comment]
看文档，使用姿势，和微信小程序一致

**Comment by xijiasheng** [comment]
> 看文档，使用姿势，和微信小程序一致

 视频这个客户反馈微信小程序这边是，先在视频号上传一个视频，在视频号的后台会有个视频 id，然后在小程序这里，调用视频组件，传入视频 id 就可以了。那对比到小红书是不是在专业号发视频，然后链接上会有视频id，就是这个id就行了？
