### ISSUE TITLE
onShareTimeline、onShareChat返回的query参数不生效

### ISSUE THREAD

**Issue by bestMrY** [redengineer/redmini#1248]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
DFS

## 平台
IOS, Android, IDE

## 小红书版本信息
8.35.0
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-15 10:51:32 至 2024-05-15 10:51:32

## 问题描述
在onShareTimeline、onShareChat中return了query属性，但实际分享出去的链接中未携带query参数

## 期望结果
携带配置的query参数

## 重现步骤和复现问题的最小demo Github链接
onShareTimeline() {
    return {
      query: {
        dfs: &quot;dfs share timeline&quot;,
      },
    };
  },

**Comment by jzhmcoo1** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/frame/Page#onShareChat

看下文档，我们的 query 是 string 格式，暂不支持对象

**Comment by bestMrY** [comment]
> https://miniapp.xiaohongshu.com/docs?path=/docs/frame/Page#onShareChat
> 
> 看下文档，我们的 query 是 string 格式，暂不支持对象
@jzhmcoo1 
sorry，我贴的代码有问题，我们实际确实是用query的，但分享出来的链接上并没有携带参数
`onShareTimeline() {
        return {
            query: `dfs_scene_type=share&id=111`,
        };
    }
    onShareChat() {
        return {
            query: `dfs_scene_type=share&id=111`,
        };
    }`
