### ISSUE TITLE
小程序授权服务商失败，初次授权提示已授权且无法解除授权

### ISSUE THREAD

**Issue by fubiaoLiu** [redengineer/redmini#1251]
## Issue类型
operator

## 问题模块
小红书小程序授权服务商

## 所属的服务商
有赞

## 小红书版本信息
8.33

## 运营场景描述
创建小程序后通过授权码扫码登录专业号授权小程序给服务商。提示授权失败，已授权给“有赞运营小助手”。点击解除授权，页面空白，无法操作。 

## 发生问题的时间 
2024-05-17 12:35:58 至 2024-05-17 12:35:58

## 期望结果
授权成功，且能正常通知服务商授权结果。

## 业务基础信息（选填）
appid：66458401c06b8e0001b8210f

这两个有好几个商家遇到了问题，帮忙尽快处理一下。相关视频截图已发送到企微对接群里了。

**Comment by Tokysky** [comment]
您好，小程序appid：66458401c06b8e0001b8210f经查询在2024-05-14 22:23:07已经授权给有赞运营小助手了
