### ISSUE TITLE
"requestOrderPayment fail: requestOrderPayment方法不支持"

### ISSUE THREAD

**Issue by smallico** [redengineer/redmini#1252]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IOS

## 小红书版本信息
v8.36
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-17 16:00:27 至 2024-05-17 16:07:29

## 问题描述
&quot;requestOrderPayment fail: requestOrderPayment方法不支持&quot;

## 期望结果
支持一下api的使用

## 重现步骤和复现问题的最小demo Github链接
  xhs.requestOrderPayment({
    orderInfo:{
      payToken:payToken,
      orderId:order_id,
      payMethod:paymentId,
      zfbUrl:redirectUrl,
    },
    success: (res) &#x3D;&gt; {
      console.log(res,&#x27;res&#x27;)
    },
    fail: (f) &#x3D;&gt; {
      console.log(f,&#x27;f&#x27;)
    },
    complete: (c) &#x3D;&gt; {
      console.log(c,&#x27;c&#x27;)
    },
  })

**Comment by jzhmcoo1** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/api/requestOrderPayment
根据文档的示例是否能调通？payMethod 传`third`

**Comment by smallico** [comment]
刚才试了下api在真机上可以调用，"requestOrderPayment fail: call function: 'requestOrderPayment', 支付URL域名校验失败"， https://open-sea-global.alipayplus.com/api/open/v1/ac/cashier/self/codevalue/checkout.htm?codeValue=https%3A%2F%2Fglobal.alipay.com%2F281002040091kpNv2t2qy32AF730m9H8ZCE6&loadMode=2 用的是 阿里支付,就提示了这个。

**Comment by jzhmcoo1** [comment]
> 刚才试了下api在真机上可以调用

所以是在开发者工具调用时候提示的失败对么？开发者工具暂不支持这个 API~

**Comment by smallico** [comment]
是的，你可以帮我看一下 上面  支付URL域名校验失败的问题吗
