### ISSUE TITLE
阿里pay支付h5链接如何唤起?

### ISSUE THREAD

**Issue by smallico** [redengineer/redmini#1255]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IOS

## 小红书版本信息
v8.36
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-20 19:19:57 至 2024-05-20 19:19:57

## 问题描述
调用此xhs.requestOrderPayment api后，如何唤起alipay 的h5链接呢?目前是通过xhs.requestOrderPayment打开了一个h5链接,但是无法中转到alipay的h5支付链接

## 期望结果
希望给出可以唤起alipay链接的方法 

## 重现步骤和复现问题的最小demo Github链接
希望可以打开 此链接 https://open-sea-global.alipayplus.com/api/open/v1/ac/cashier/self/codevalue/checkout.htm?codeValue&#x3D;https%3A%2F%2Fglobal.alipay.com%2F281002040091kpNv2t2qy32AF730m9H8ZCE6&amp;loadMode&#x3D;2

**Comment by zane418** [comment]
解决了吗？

**Comment by shuaidawang** [comment]
解决了吗
