### ISSUE TITLE
真机调试一直加载失败

### ISSUE THREAD

**Issue by gaojunwei1** [redengineer/redmini#1257]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
领凯科技

## 平台
IDE

## 小红书开发者工具版本
2.0.16

## 基础库版本
v3.92.0

## 发生问题的时间
2024-05-22 10:48:14 至 2024-05-22 10:48:14

## 问题描述
真机调试一直加载失败，预览一直ok...................（确定同一局域网内，流量都关了）

## 期望结果
可以使用真机调试................

## 重现步骤和复现问题的最小demo Github链接
sb

**Comment by yujon** [comment]
手机端是安卓还是ios，有什么报错么
