### ISSUE TITLE
基础库版本v3.92.0，授权手机号解密为乱码

### ISSUE THREAD

**Issue by xijiasheng** [redengineer/redmini#1258]
## Issue类型
operator

## 问题模块
授权手机号

## 所属的服务商
LoroPiana

## 小红书版本信息
v3.92.0

## 运营场景描述
小红书第一次授权登录后，获取手机号解密会出现乱码， 重新获取，加密密文解密后又正常了，业务场景的影响是：小程序上因为已经完成授权，就不会再显示授权button，且一个用户只能提交一次，提交过一次信息后不会再有入口提交第二次，但后端数据拿到的手机号是乱码，品牌无法获取正确的信息，目前品牌有一定概率授权到无效手机号码，影响留资 

## 发生问题的时间 
2024-05-10 11:16:29 至 2024-05-22 11:16:29

## 期望结果
希望帮助定位并解决用户第一次授权手机号为乱码的情况。

## 业务基础信息（选填）
小程序ID：6555873bd5423a0041271d65
加密密文：{&quot;encryptedData&quot;:&quot;w0HHY59Pd1vZGVK0K3VP7M2pBKUkN47ekVO7wct1tyJvaLH4R+7TS7F5UUSMQhndPY0RDd+JxHUqNxUP+EOne5an+WMon/tl3Yd0Mkp0mz4SixyPrDKuJlnIIU6nDNAm7eUpn5y3UJZQ37oQeXlb3Run/U9Trx/9SAPoCpJ8ctrPbiVi492LXXvPvmy63hg8Z3pzVNmNiPPfyCJDUTDUBQ&#x3D;&#x3D;&quot;,&quot;iv&quot;:&quot;dE9SZXBnY2lzeDVFSW9nQg&#x3D;&#x3D;&quot;} 
sessionKey : ZmZvYmtYU3ZkU2hGOGdEQw&#x3D;&#x3D;

**Comment by jzhmcoo1** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/guide/openPhoneNumber
是不是因为重复调用了 xhs.login 刷新了登录态？看下文档注意事项再试下
