### ISSUE TITLE
小程序发布以后，线下门店看不到商品，专业号后台也无法设置小程序店铺在主页显示

### ISSUE THREAD

**Issue by woaichiludan** [redengineer/redmini#1260]
## Issue类型
operator

## 问题模块
商品笔记

## 所属的服务商
宝寓

## 小红书版本信息
v8.36

## 运营场景描述
同步商品报错“该应用不具有小程序交易组件能力” 

## 发生问题的时间 
2024-05-23 16:59:11 至 2024-05-23 16:59:11

## 期望结果
近期较多用户遇到此类问题，希望尽快查明原因并告知处理办法

## 业务基础信息（选填）
案例APPID:6645c50a87cdee00014e12ef

**Comment by leeligang1027** [comment]
需切换担保交易后使用
