### ISSUE TITLE
xhs.hideShareMenu不生效

### ISSUE THREAD

**Issue by bestMrY** [redengineer/redmini#1261]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
DFS

## 平台
IOS, Android

## 小红书版本信息
8.37.2
 
## 基础库版本
v3.89.0

## 发生问题的时间 
2024-05-24 15:23:15 至 2024-05-24 15:23:15

## 问题描述
调用xhs.hideShareMenu后，分享按钮未被隐藏

## 期望结果
右上角分享按钮被隐藏

## 重现步骤和复现问题的最小demo Github链接
使用你们的官方demo的分享功能就能复现
<img width="383" alt="image" src="https://github.com/redengineer/redmini/assets/71256474/6420c9c2-e46a-4e10-aec1-ac74591940f7">

**Comment by jzhmcoo1** [comment]
什么环境，开发者工具还是 IOS 还是安卓？

**Comment by bestMrY** [comment]
> 什么环境，开发者工具还是 IOS 还是安卓？

三个都试过，点击后都没有隐藏右上角分享

**Comment by jzhmcoo1** [comment]
![image](https://github.com/redengineer/redmini/assets/55695299/e292b7f5-1278-40cd-8e44-060ef0ec7a3e)
真机是可以的，demo 的文字叙述有点问题，后面我们改一下
