### ISSUE TITLE
xhs.getSystemInfoSync接口返回数据希望能与微信保持一致，现在返回的不稳定

### ISSUE THREAD

**Issue by yhz0206** [redengineer/redmini#1266]
## Issue类型
feature

## 所属的服务商
冰甜短剧

## 这个功能解决的问题
问题一：同一部手机，app版本不同，返回的数据不同
复现手机：小米11青春版：sdk版本3.92.0（app版本8.37.2）返回screenheight&#x3D;957；3.82.0（app版本8.23.0））返回screenheight&#x3D;825
问题二：不同机型，有的 返回windowHeight&#x3D;0,有的safaArea里面height为0，
这返回数据有点乱啊，希望能统一 一下，文档上标注清楚以哪个为准

**Comment by YaoPB** [comment]
在 8.34～8.37该 api存在问题，在 8.38+版本上已修复问题，可以使用高版本测试
