### ISSUE TITLE
video组件首次播放没触发onplay，执行暂停也没触发onpause，show-play-btn设置不生效

### ISSUE THREAD

**Issue by yhz0206** [redengineer/redmini#1267]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
冰甜短剧

## 平台
Android

## 小红书版本信息
8.23.0
 
## 基础库版本
v3.82.0

## 用户ID 
9251268025

## 发生问题的时间 
2024-05-25 16:24:14 至 2024-05-28 00:00:00

## 问题描述
video组件首次播放没触发onplay，执行暂停也没触发onpause，show-play-btn设置不生效

## 期望结果
播放按钮不展示，暂停能正常使用。video播放是出发onplay

## 重现步骤和复现问题的最小demo Github链接
&lt;video xhs:if&#x3D;&quot;{{videoUrl}}&quot; id&#x3D;&quot;video-dom&quot; vslide-gesture-in-fullscreen&#x3D;&quot;{{false}}&quot;
            data-dramaNum&#x3D;&quot;{{playingVideo.dramaNum}}&quot; class&#x3D;&quot;video&quot; enable-play-gesture loop&#x3D;&quot;{{false}}&quot; poster&#x3D;&quot;{{videoInfo.thumb}}&quot;
            enable-progress-gesture&#x3D;&quot;{{false}}&quot; show-center-play-btn&#x3D;&quot;{{false}}&quot; show-play-btn&#x3D;&quot;{{false}}&quot; controls&#x3D;&quot;{{false}}&quot; src&#x3D;&quot;{{videoUrl}}&quot;
            object-fit&#x3D;&quot;{{fit}}&quot; bindplay&#x3D;&quot;onPlay&quot; bindpause&#x3D;&quot;onPause&quot; bindended&#x3D;&quot;onEnded&quot; binderror&#x3D;&quot;onError&quot;
            bindtimeupdate&#x3D;&quot;onTimeUpdate&quot; bindwaiting&#x3D;&quot;onWaiting&quot; bindprogress&#x3D;&quot;onProgress&quot;
            bindloadedmetadata&#x3D;&quot;onLoadedMetaData&quot; catch:tap&#x3D;&quot;clickVideoHandle&quot;
            bindfullscreenchange&#x3D;&quot;onFullScreenChange&quot;&gt;
          &lt;/video&gt;

**Comment by jzhmcoo1** [comment]
更新 App 版本可以吗？基础库版本迭代中已经升级了 SDK 依赖，升级后再看看有没有问题
