### ISSUE TITLE
真机调试报错，IDE使用模拟器新架构报错

### ISSUE THREAD

**Issue by yangyonghong** [redengineer/redmini#1269]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
秀动

## 平台
IOS, Android, IDE

## 小红书开发者工具版本
2.0.16

## 基础库版本
v3.92.0

## 发生问题的时间
2024-05-29 10:39:55 至 2024-05-29 10:39:55

## 问题描述
开发工具勾选“使用模拟器新架构”运行时报错，取消“使用模拟器新架构”开发工具模拟器可正常运行，但使用真机调试时会报错。

## 期望结果
使用真机调试能正常运行

## 重现步骤和复现问题的最小demo Github链接
开发工具勾选“使用模拟器新架构”运行时报错，取消“使用模拟器新架构”开发工具模拟器可正常运行，但使用真机调试时会报错。

**Comment by yangyonghong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yujon** [comment]
- 新模拟器架构的问题应该已经修复；
- 真机调试报错，麻烦提供下报错截图

**Comment by yangyonghong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yangyonghong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
