### ISSUE TITLE
创建订单接口 有时候会返回：invalid product_infos.sale_price 

### ISSUE THREAD

**Issue by wlyznb** [redengineer/redmini#1271]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
v8.36
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-05-29 10:01:43 至 2024-05-29 13:00:00

## 问题描述
创建订单的时候 基本上同样的请求参数 有时候可以创建成功,有时候会返回。参数错误：invalid product_infos.sale_price

## 期望结果
能够解决为什么会有这种情况发生,并且告知原因

## 重现步骤和复现问题的最小demo Github链接
请求参数:
成功的: (outOrderId&#x3D;1245335478897561600, openId&#x3D;58638ca25ec5a7076f0f3292d4f502b789998afde96e65482144019bcb760472, path&#x3D;pages/orderConfirm/index, bizCreateTime&#x3D;1716952718, bizUpdateTime&#x3D;1716952718, orderExpiredTime&#x3D;1716954518, productInfos&#x3D;[OrderUpsertRequest.ProductInfosDTO(outProductId&#x3D;696_-1_1365, outSkuId&#x3D;1365-ddbafa41-d076-4db9-b30a-678662a00638, num&#x3D;2, salePrice&#x3D;76, realPrice&#x3D;76, image&#x3D;null, discountInfos&#x3D;null)], priceInfo&#x3D;OrderUpsertRequest.PriceInfoDTO(orderPrice&#x3D;76, freightPrice&#x3D;null, extraPriceInfos&#x3D;null))

失败的:
(outOrderId&#x3D;1245344849059729408, openId&#x3D;58638ca25ec5a7076f0f3292d4f502b789998afde96e65482144019bcb760472, path&#x3D;pages/orderConfirm/index, bizCreateTime&#x3D;1716954953, bizUpdateTime&#x3D;1716954953, orderExpiredTime&#x3D;1716956753, productInfos&#x3D;[OrderUpsertRequest.ProductInfosDTO(outProductId&#x3D;696_-1_1354, outSkuId&#x3D;1354-ddbafa41-d076-4db9-b30a-678662a00638, num&#x3D;2, salePrice&#x3D;283, realPrice&#x3D;283, image&#x3D;null, discountInfos&#x3D;null)], priceInfo&#x3D;OrderUpsertRequest.PriceInfoDTO(orderPrice&#x3D;283, freightPrice&#x3D;null, extraPriceInfos&#x3D;null))

**Comment by Tokysky** [comment]
直连支付中要求salePrice除以商品数量可以除尽，例如283/2 = 141.5除不尽
