### ISSUE TITLE
请问小红书小程序商品的语言是英文的话是否可以通过审核

### ISSUE THREAD

**Issue by Melissa3313** [redengineer/redmini#1272]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
订单来了

## 小红书版本信息
8.34.1

## 运营场景描述
我们帮海外的酒店商家上架房间至小红书小程序，有可能他们在系统里输入的是英文的商品名称， 想问下英文是否可以通过审核？ 

## 发生问题的时间 
2024-05-29 10:28:36 至 2024-05-29 10:28:36

## 期望结果
小程序商品英文可以通过审核

**Comment by ohaq-hue** [comment]
可以的
