### ISSUE TITLE
小程序已经发布了，但是在哪显示呢？也没有二维码什么的。

### ISSUE THREAD

**Issue by simplephper** [redengineer/redmini#1280]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
镜流开合

## 平台
IOS, Android

## 小红书版本信息
8.38
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-06-03 10:02:13 至 2024-06-03 10:02:13

## 问题描述
已经发布了，但是没有查看的入口，专业号主页的“自定义菜单”，也没有添加小程序显示的地方，只有个“店铺”，但是店铺里面什么也没有。

## 期望结果
在文档上面看到可以在账号主页进行展示，但是现在没找到配置的入口，希望能在主页展示

## 重现步骤和复现问题的最小demo Github链接
已经发布了，但是没有查看的入口，专业号主页的“自定义菜单”，也没有添加小程序显示的地方，只有个“店铺”，但是店铺里面什么也没有。

**Comment by leeligang1027** [comment]
可以通过【专业号平台-小程序-小程序入口配置】进行设置！
