### ISSUE TITLE
「订单-状态同步」接口无法使用，一直报错

### ISSUE THREAD

**Issue by liril-net** [redengineer/redmini#1283]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
来位

## 平台
IOS, Android

## 小红书版本信息
8.38
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-06-03 15:04:53 至 2024-06-03 15:04:53

## 问题描述
「订单-状态同步」一直报错，提示「参数不合法：担保支付订单仅支持取消（998）」，&#x60;code&#x60; 返回 &#x60;400001&#x60;，无论 &#x60;status&#x60; 传任何值（包括 998），都报这个错误。

## 期望结果
订单可以正常同步，允许跳转到其他状态。

## 重现步骤和复现问题的最小demo Github链接
暂无

**Comment by Tokysky** [comment]
您好，麻烦提供一下请求的链接和参数，我这边排查一下

**Comment by Tokysky** [comment]
可以在你们服务商的群里沟通，或者加我的企业微信
<img width="353" alt="image" src="https://github.com/redengineer/redmini/assets/7045837/d1dff255-e1ee-4dfb-9c12-946e70b36f2d">
