### ISSUE TITLE
本地生活担保支付下单跳转支付宝白屏

### ISSUE THREAD

**Issue by Aasom1** [redengineer/redmini#1284]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
订单来了

## 小红书版本信息
v8.36

## 运营场景描述
本地生活担保支付下单，跳转支付宝白屏 

## 发生问题的时间 
2024-06-04 11:50:17 至 2024-06-04 11:50:17

## 期望结果
正常跳转支付。且不要卡死
目前无论从小红书小程序下单，或者通过小红书订单去支付，都会卡死白屏

**Comment by Aasom1** [comment]
可复现的小程序：
小红书搜索专业号：青城山墅院·温泉度假别墅
小红书号：4104961876
从主页的店铺进入下单

**Comment by YaoPB** [comment]
该业务使用并非担保支付，仍然采用了 requestOrderPayment 支付方式；
目前看下来，业务提供的支付 H5 页面存在问题，端侧不能拦截到跳转行为（类似alipays:// xxx）
解决方案：
1.检查 H5页面逻辑，保证正常执行，并发生页面跳转行为（让客户端能拦截到）
2.长期可以考虑接入担保支付 requestGuaranteeOrderPayment

**Comment by taiyiandr** [comment]
最新状态，业务已经接入了担保支付 requestGuaranteeOrderPayment。流程正常。
