### ISSUE TITLE
picker 省市区选择框 山东省菏泽市的“菏”错了

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1285]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
奇陌

## 平台
IOS, Android, IDE

## 小红书版本信息
8.36
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-06-04 14:54:26 至 2024-06-04 14:54:26

## 问题描述
picker 省市区选择框 山东省菏泽市的“菏”错了

## 期望结果
解决这个重大bug。

## 重现步骤和复现问题的最小demo Github链接
&lt;picker mode&#x3D;&quot;picker&quot;&gt;

**Comment by jzhmcoo1** [comment]
这个会和 picker 的地区配置一起更新修复

**Comment by ohaq-hue** [comment]
已经修复了
