### ISSUE TITLE
小程序下单，报应用失效

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1289]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
上海卡里司马科技有限公司

## 平台
IDE

## 小红书开发者工具版本
2.0.16

## 基础库版本
v3.93.2

## 发生问题的时间
2024-06-14 15:46:20 至 2024-06-14 15:46:20

## 问题描述
小程序下单，报应用失效
公司有的两个小程序中，只有这个小程序有问题

## 期望结果
解决应用失效的问题，可以正常下单

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by hhuwc** [comment]
请提供下appid

**Comment by Murphy3389** [comment]
65699316489715004d5b25d2，请查收

**Comment by Murphy3389** [comment]
有结果么

**Comment by Murphy3389** [comment]
？很多天了，没什么解释？

**Comment by Tokysky** [comment]
这个小程序的状态是没问题的，麻烦提供一下请求的入参和出参，方便定位哈
