### ISSUE TITLE
小程序-服务端-订单-新增/修改接口调用, 出现商品数据异常

### ISSUE THREAD

**Issue by ing0127** [redengineer/redmini#1292]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
i游安阳

## 平台
IDE

## 小红书版本信息
8.39.2
 
## 基础库版本
v3.93.2

## 发生问题的时间 
2024-06-16 19:54:54 至 2024-06-16 19:54:54

## 问题描述
商品，都已经通过【商品-新增/删除】接口同步成功并且是上架状态；
调用订单-新增/修改接口, 接口响应:{&quot;msg&quot;:&quot;商品数据异常，请确定是担保支付的商品&quot;,&quot;code&quot;:510010,&quot;success&quot;:false}。

## 期望结果
能够正确进行下单，或给出更详细的问题信息。

## 重现步骤和复现问题的最小demo Github链接
调用订单-新增/修改接口

**Comment by ing0127** [comment]
已解决，通过【商品同步-生活服务】接口同步商品可成功下单。

**Comment by panla** [comment]
@ing0127 你好商品类型-1-团购，2-酒旅预售券，3-酒旅日历商品，假如自己小程序的商品类型都不太符合时，有什么处理方案吗?
