### ISSUE TITLE
ide对于报错的提示信息太少，没法定位具体文件

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#1293]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
微盟

## 平台
IDE

## 小红书开发者工具版本
2.0.16

## 基础库版本
v3.93.2

## 发生问题的时间
2024-06-17 19:16:31 至 2024-06-17 19:16:31

## 问题描述
ide对于报错的提示信息太少，没法定位具体文件，            表达式编译错误：【  】： Unexpected end of expression
只有以上一句话

## 期望结果
希望能提示出具体文件和位置信息

## 重现步骤和复现问题的最小demo Github链接
不知道什么原因，你们自己看着弄下吧

**Comment by yujon** [comment]
麻烦提供下代码片段
