### ISSUE TITLE
getlocation地址定位获取失败

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1294]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
上海卡里司马科技有限公司

## 平台
IOS, Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.93.2

## 发生问题的时间 
2024-06-19 11:06:14 至 2024-06-19 11:06:14

## 问题描述
使用小程序api中的getlocation地址定位返回定位失败
接口文档如下：https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/api/getLocation

## 期望结果
要解决可以正常使用getlocation问题

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by Murphy3389** [comment]
什么时间可以解答

**Comment by Murphy3389** [comment]
> @Murphy3389 你好，请确认客户端版本是否 7.88？如果是的话请升级到最新的小红书客户端版本尝试一下

ide本地调接口的时候就挂了，还没到真机调试这一步

**Comment by Murphy3389** [comment]
@redbook-miniapp-robot

**Comment by yujon** [comment]
> > @Murphy3389 你好，请确认客户端版本是否 7.88？如果是的话请升级到最新的小红书客户端版本尝试一下
> 
> ide本地调接口的时候就挂了，还没到真机调试这一步

ide暂不支持该api，请用真机预览
