### ISSUE TITLE
input输入框，设置:adjust-position="false"无效，机型华为p40

### ISSUE THREAD

**Issue by yhz0206** [redengineer/redmini#1297]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
冰甜好剧

## 平台
Android

## 小红书版本信息
v8.40.0
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-06-21 14:00:48 至 2024-06-21 15:00:48

## 问题描述
input输入框，设置:adjust-position&#x3D;&quot;false&quot;无效，机型华为p40

## 期望结果
设置:adjust-position&#x3D;&quot;false&quot;时，键盘弹起时，不上推页面

## 重现步骤和复现问题的最小demo Github链接
&lt;input class&#x3D;&quot;search-input&quot; focus value&#x3D;&quot;{{pageFrom.keyword}}&quot; maxlength&#x3D;15 type&#x3D;&quot;text&quot; placeholder&#x3D;&quot;剧名、剧ID&quot; placeholder-style&#x3D;&quot;font-size:40rpx&quot; :adjust-position&#x3D;&quot;false&quot; bindblur&#x3D;&quot;bindblur&quot; bindinput&#x3D;&quot;bindinput&quot; bindconfirm&#x3D;&quot;bindconfirm&quot;&gt;&lt;/input&gt;

**Comment by yhz0206** [comment]
![Uploading 8b72f7da502c876d10bd0ea4d095ea98.jpg…]()

**Comment by jzhmcoo1** [comment]
目前同层渲染相关属性不支持
