### ISSUE TITLE
xhs.vibrateShort方法不存在

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#1298]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
迪奥

## 平台
IOS, Android, IDE

## 小红书版本信息
8.41.1
 
## 基础库版本
v3.38.0

## 发生问题的时间 
2024-06-21 15:42:22 至 2024-06-21 15:42:22

## 问题描述
xhs.vibrateShort is not a function

## 期望结果
api正常使用，可以触发手机震动

## 重现步骤和复现问题的最小demo Github链接
xhs.vibrateShort

**Comment by jzhmcoo1** [comment]
这个 API 目前只透出给小游戏使用

**Comment by jzhmcoo1** [comment]
3.95.0及以上基础库版本已支持
