### ISSUE TITLE
获取定位信息和用户信息等api，对应code码文档未提供

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#13]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.22.2
## 期望结果 和 实际结果(必填)
希望提供需授权API对应的code码文档

**Comment by xutm** [comment]
计划 5.16 日支持

**Comment by xutm** [comment]
https://miniapp.xiaohongshu.com/docs/guide/apiErrorCode
