### ISSUE TITLE
上架商品时选择结算类型为门店结算，下单时会报错

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#1301]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
有赞

## 平台
Android, IOS, IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.95.0

## 发生问题的时间 
2024-06-26 14:07:33 至 2024-06-26 14:07:33

## 问题描述
上架商品时选择结算类型为门店结算，发起预约会报错&quot;{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;com.xiaohongshu.sns.rmp.base.common.common.exception.BizException&quot;,&quot;code&quot;:510010}&quot;，选择结算类型为总店结算就没问题，但该商家的公司类型收款账户无法绑定银行卡，这就形成了闭环
 {&quot;url&quot;:&quot;https://miniapp.xiaohongshu.com/api/rmp/component/deal/pre_sale/book?appid&#x3D;64478fc017525100014ab2b9&amp;auth_access_token&#x3D;07c5fea45dcd49879d0f8d6b16f34437&amp;access_token&#x3D;07c5fea45dcd49879d0f8d6b16f34437&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;http_code&quot;:200,&quot;time_ms&quot;:449.266,&quot;request&quot;:{&quot;headers&quot;:{&quot;Content-Length&quot;:&quot;418&quot;,&quot;Host&quot;:&quot;miniapp.xiaohongshu.com&quot;,&quot;User-Agent&quot;:&quot;Hostex/V4.0.0&quot;,&quot;Content-Type&quot;:&quot;application/json&quot;},&quot;body&quot;:&quot;{\&quot;product_type\&quot;:3,\&quot;open_id\&quot;:\&quot;17cd4547cbf44e25f75f68077b9dcb23255839c66a0887541bb594b56f540590\&quot;,\&quot;out_product_id\&quot;:\&quot;66790c0f71dd7a500e384a4d\&quot;,\&quot;out_order_id\&quot;:\&quot;667b9ac4f9027202e518b617\&quot;,\&quot;out_sku_id\&quot;:\&quot;66790c0f71dd7a500e384a4d\&quot;,\&quot;poi_id\&quot;:\&quot;1577790631087435262\&quot;,\&quot;book_info\&quot;:{\&quot;out_book_order_id\&quot;:\&quot;667b9ac4f9027202e518b617\&quot;,\&quot;total_price\&quot;:10,\&quot;book_detail\&quot;:[{\&quot;price\&quot;:10,\&quot;check_in_date\&quot;:\&quot;2024-06-26\&quot;,\&quot;check_out_date\&quot;:\&quot;2024-06-27\&quot;}]}}&quot;},&quot;response&quot;:{&quot;headers&quot;:{&quot;Date&quot;:&quot;Wed, 26 Jun 2024 04:36:26 GMT&quot;,&quot;Content-Type&quot;:&quot;application/json;charset&#x3D;UTF-8&quot;,&quot;Transfer-Encoding&quot;:&quot;chunked&quot;,&quot;Connection&quot;:&quot;keep-alive&quot;,&quot;Server&quot;:&quot;nginx&quot;,&quot;Set-Cookie&quot;:&quot;acw_tc&#x3D;36f4478b76b881d63ac9aea610e9d58998f7dd51c3f49d1afecd6c6abafdb0ca;path&#x3D;/;HttpOnly;Max-Age&#x3D;1800&quot;,&quot;Cat-Msg-Id&quot;:&quot;openapiminiapp-gateway-default-ac19494e.0058361-477604-35845&quot;},&quot;body&quot;:&quot;{\&quot;data\&quot;:null,\&quot;success\&quot;:false,\&quot;msg\&quot;:\&quot;com.xiaohongshu.sns.rmp.base.common.common.exception.BizException\&quot;,\&quot;code\&quot;:510010}&quot;}}
商家小程序id：665446da33828a0001beff11

## 期望结果
小红书订单正常结算后可以提现至对应的银行账户

## 重现步骤和复现问题的最小demo Github链接
上架商品时选择结算类型为门店结算，调用 https://miniapp.xiaohongshu.com/api/rmp/component/deal/pre_sale/book发起预约

**Comment by leeligang1027** [comment]
门店结算需使用平台担保交易商家认领门店后，可使用商品同步接口确认可使用门店和分账方式，并在核销时传相应门店进行结算。直连支付的历史商家不支持使用！
