### ISSUE TITLE
小程序服务端API【订单-新增/修改】响应结果和文档描述不一致，且疑似有bug

### ISSUE THREAD

**Issue by gniria** [redengineer/redmini#1303]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
哇喔相机

## 平台
IOS (实际跟平台和小程序app版本无关，是后端接口问题)

## 小红书版本信息
8.42
 
## 基础库版本
v3.95.0

## 用户ID 
4169117131

## 发生问题的时间 
2024-06-28 10:29:58 至 2024-06-29 10:29:58 （目前依然存在）

## 问题描述
https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/api-backend/post-api-rmp-mp-deal-order-upsert  【订单-新增/修改】接口里response定义的是code/msg, 接口返回的是error_code/error_msg，另外报错信息非有效文案，而是疑似java堆栈异常

## 期望结果
API接口可以正常实现订单新增/修改

## 重现步骤和复现问题的最小demo Github链接
订单新增/修改接口 ： https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert?appid&#x3D;6642fcb087cdee00014e128c&amp;access_token&#x3D;14d530722df847e1a1268d5e4a61413a
参数(body)：{&quot;out_order_id&quot;:&quot;202407011039519472&quot;,&quot;open_id&quot;:&quot;cfe4e2cca992699fbe7fa95c9ca9324f711e5d071bb2ec3f5c929ef1c2ec3861&quot;,&quot;path&quot;:&quot;\/vip_packages\/pages\/member\/member?type&#x3D;1&quot;,&quot;biz_create_time&quot;:1719801591,&quot;biz_update_time&quot;:1719801591,&quot;order_expired_time&quot;:1800,&quot;product_infos&quot;:{&quot;out_product_id&quot;:&quot;xhs_product_id&quot;,&quot;out_sku_id&quot;:&quot;xhs_sku_id&quot;,&quot;num&quot;:1,&quot;sale_price&quot;:99,&quot;real_price&quot;:&quot;19&quot;},&quot;price_info&quot;:{&quot;order_price&quot;:&quot;19&quot;,&quot;freight_price&quot;:0}}

实际响应结果：
{
    &quot;error_code&quot;: -9012,
    &quot;error_msg&quot;: &quot;JSON parse error: Cannot deserialize instance of &#x60;java.util.ArrayList&#x60; out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of &#x60;java.util.ArrayList&#x60; out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 269] (through reference chain: com.xiaohongshu.fls.mercury.server.domain.rmp.request.UpsertOrderRequest[\&quot;product_infos\&quot;])&quot;,
    &quot;success&quot;: false
}

**Comment by Tokysky** [comment]
product_infos是列表结构
"product_infos": [
    {
      "out_product_id": "xhs_product_id",
      "out_sku_id": "xhs_sku_id",
      "num": 1,
      "sale_price": 99,
      "real_price": "19"
    }
  ]
