### ISSUE TITLE
picker 省市区选择器  广东省 东莞市 之后没有可以选择的区县

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1305]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
奇陌

## 平台
Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-07-01 17:39:47 至 2024-07-01 17:39:47

## 问题描述
picker 省市区选择器  广东省 东莞市 之后没有可以选择的区县

## 期望结果
处理一下

## 重现步骤和复现问题的最小demo Github链接
picker 省市区选择器  广东省 东莞市 之后没有可以选择的区县

**Comment by FengXinKai** [comment]
![3989a7b9ff8ed41d6ea35e997b691ea](https://github.com/redengineer/redmini/assets/119713060/1dc70ded-4198-4584-8a3b-0f79e3d1b339)

**Comment by jzhmcoo1** [comment]
https://www.mca.gov.cn/mzsj/xzqh/2022/202201xzqh.html

你好 我们参考的是这份文件，下面确实没有列出区域，你这边可以提供一份标准文件 我们来替换即可

**Comment by ohaq-hue** [comment]
已经修复了
