### ISSUE TITLE
商家已开通担保支付，调用商品同步服务报错未开通担保支付

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#1307]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
百居易

## 平台
IDE, Android, IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.94.1

## 发生问题的时间 
2024-07-02 16:31:38 至 2024-07-02 16:31:38

## 问题描述
商家已开通担保支付，调用商品同步服务报错未开通担保支付
商家AppId：66581e7e9619150001a3ca59

## 期望结果
可以正常同步房间信息

## 重现步骤和复现问题的最小demo Github链接
{&quot;url&quot;:&quot;https://miniapp.xiaohongshu.com/api/rmp/tp/poi/product/upsert?appid&#x3D;64478fc017525100014ab2b9&amp;auth_access_token&#x3D;18f4aac54ec043cb830db3ac66121562&amp;access_token&#x3D;18f4aac54ec043cb830db3ac66121562&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;http_code&quot;:200,&quot;time_ms&quot;:407.945,&quot;request&quot;:{&quot;headers&quot;:{&quot;Content-Length&quot;:&quot;984&quot;,&quot;Host&quot;:&quot;miniapp.xiaohongshu.com&quot;,&quot;User-Agent&quot;:&quot;Hostex/V4.0.0&quot;,&quot;Content-Type&quot;:&quot;application/json&quot;},&quot;body&quot;:&quot;{\&quot;out_product_id\&quot;:\&quot;6666da3a3404ee531b2ad931\&quot;,\&quot;name\&quot;:\&quot;\\u6843\\u592d\\u9601-\\u7985\\u610f\\u5927\\u5e8a\\u623f\\/\\u5de8\\u5e55\\u6295\\u5f71\\/\\u82b1\\u56ed\\u5ead\\u9662\\/\\u667a\\u80fd\\u9a6c\\u6876+\\u6c49\\u670d\\u4f53\\u9a8c\&quot;,\&quot;short_title\&quot;:\&quot;\\u6843\\u592d\\u9601-\\u7985\\u610f\\u5927\\u5e8a\\u623f\\/\\u5de8\\u5e55\&quot;,\&quot;desc\&quot;:\&quot;1\\u5367 | \\u5b9c\\u4f4f2\\u4eba\&quot;,\&quot;path\&quot;:\&quot;pages\\/house\\/detail\\/detail?house_id&#x3D;6666da3a3404ee531b2ad931\&quot;,\&quot;top_image\&quot;:\&quot;https:\\/\\/qiniu.myhostex.com\\/brand\\/logos\\/1719844642755.jpg\&quot;,\&quot;category_id\&quot;:\&quot;627a3405cf7e32000167bd35\&quot;,\&quot;biz_create_time\&quot;:1718016570,\&quot;biz_update_time\&quot;:1719908596,\&quot;poi_id_list\&quot;:[\&quot;1577996606402178443\&quot;],\&quot;skus\&quot;:[{\&quot;out_sku_id\&quot;:\&quot;6666da3a3404ee531b2ad931\&quot;,\&quot;name\&quot;:\&quot;\\u6843\\u592d\\u9601-\\u7985\\u610f\\u5927\\u5e8a\\u623f\\/\\u5de8\\u5e55\\u6295\\u5f71\\/\\u82b1\\u56ed\\u5ead\\u9662\\/\\u667a\\u80fd\\u9a6c\\u6876+\\u6c49\\u670d\\u4f53\\u9a8c\&quot;,\&quot;sku_image\&quot;:\&quot;https:\\/\\/qiniu.myhostex.com\\/brand\\/logos\\/1719844642755.jpg\&quot;,\&quot;origin_price\&quot;:26800,\&quot;sale_price\&quot;:26800,\&quot;status\&quot;:1}],\&quot;product_type\&quot;:3,\&quot;settle_type\&quot;:1}&quot;},&quot;response&quot;:{&quot;headers&quot;:{&quot;Date&quot;:&quot;Tue, 02 Jul 2024 08:27:33 GMT&quot;,&quot;Content-Type&quot;:&quot;application/json;charset&#x3D;UTF-8&quot;,&quot;Transfer-Encoding&quot;:&quot;chunked&quot;,&quot;Connection&quot;:&quot;keep-alive&quot;,&quot;Server&quot;:&quot;nginx&quot;,&quot;Set-Cookie&quot;:&quot;acw_tc&#x3D;20f4732636a8c42b1d6609a674341547704319baec302977e2dae56f6ecccdc2;path&#x3D;/;HttpOnly;Max-Age&#x3D;1800&quot;,&quot;Cat-Msg-Id&quot;:&quot;openapiminiapp-gateway-default-ac19c64d.0029362-477752-56123&quot;},&quot;body&quot;:&quot;{\&quot;data\&quot;:null,\&quot;success\&quot;:false,\&quot;msg\&quot;:\&quot;商家未开通担保支付\&quot;,\&quot;code\&quot;:510012}&quot;}}

**Comment by Tokysky** [comment]
这个可能是之前同步读取专业号状态导致的，后面已经修复了，请问下现在还会失败吗？
