### ISSUE TITLE
小程序内可以发起分享笔记的功能吗？

### ISSUE THREAD

**Issue by MuRyanice** [redengineer/redmini#1310]
## Issue类型
feature

## 这个功能解决的问题
你好，我们是摄影小程序，用户生成照片之后，可以直接调用发笔记的功能吗？

**Comment by MuRyanice** [comment]
目前没有看到相关的发笔记的api，但是我看到部分以及上线的小程序具备了直接发笔记的功能

**Comment by leeligang1027** [comment]
https://miniapp.xiaohongshu.com/docs?path=/docs/component/post-note-button
