### ISSUE TITLE
我们小程序走担保支付的时候无法选择微信支付，只有支付宝支付

### ISSUE THREAD

**Issue by MuRyanice** [redengineer/redmini#1312]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 平台
IOS, Android

## 小红书版本信息
8.34
 
## 基础库版本
v3.96.2

## 发生问题的时间 
2024-07-04 11:08:49 至 2024-07-04 11:08:49

## 问题描述
我们小程序在支付的时候，只有支付宝一种支付方式，api也没有地方让我们支持多种支付（微信和支付宝）

## 期望结果
希望同时支持微信支付

## 重现步骤和复现问题的最小demo Github链接
我们小程序在支付的时候，只有支付宝一种支付方式，api也没有地方让我们支持多种支付（微信和支付宝）

**Comment by zane418** [comment]
@MuRyanice 问题有解决吗？我们也需要使用微信支付。
