### ISSUE TITLE
小红书ci工具在服务器打包失败

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#1313]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
领克

## 平台
IDE

## 小红书版本信息
8.42
 
## 基础库版本
v3.96.2

## 发生问题的时间 
2024-07-04 17:23:18 至 2024-07-04 17:23:18

## 问题描述
使用服务器打包的时候会因为服务器时间校准问题报错

## 期望结果
使用服务器上传的时候能成功上传

## 重现步骤和复现问题的最小demo Github链接
见群聊

**Comment by hhuwc** [comment]
你好，发现你们在使用beta 版本的cli 工具，请问这是为什么？

**Comment by shiminJ** [comment]
> 你好，发现你们在使用beta 版本的cli 工具，请问这是为什么？

在调试这个问题

**Comment by yujon** [comment]
问题已解决，请升级到最新版本
