### ISSUE TITLE
我们小程序在支付的时候，只有支付宝一种支付方式，api也没有地方让我们支持多种支付（微信和支付宝）

### ISSUE THREAD

**Issue by MuRyanice** [redengineer/redmini#1314]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
哇喔相机

## 平台
IOS, Android

## 小红书版本信息
8.34
 
## 基础库版本
v3.96.3

## 发生问题的时间 
2024-07-04 19:42:36 至 2024-07-04 19:42:36

## 问题描述
我们小程序在支付的时候，只有支付宝一种支付方式，api也没有地方让我们支持多种支付（微信和支付宝）

## 期望结果
需要支持支付宝和微信

## 重现步骤和复现问题的最小demo Github链接
我们小程序在支付的时候，只有支付宝一种支付方式，api也没有地方让我们支持多种支付（微信和支付宝）

**Comment by ohaq-hue** [comment]
暂不支持，后续会进行产品迭代

**Comment by MuRyanice** [comment]
但是我看到其他小程序支持微信，这个是什么原因呢
