### ISSUE TITLE
帐号详情页隐藏「商品」Tab

### ISSUE THREAD

**Issue by liril-net** [redengineer/redmini#1315]
## Issue类型
feature

## 所属的服务商
来位

## 这个功能解决的问题
某些商品属于内部商品，不能公开展示。 需要下掉「商品」Tab。

对应 AppID: `665424f49619150001a3c9e6`

类似商家截图：
![image](https://github.com/redengineer/redmini/assets/16029685/e54b3f14-3fd3-40c7-b070-12b45bda414a)

**Comment by leeligang1027** [comment]
已解决
