### ISSUE TITLE
下单时提示 担保支付订单不允许自定义图片

### ISSUE THREAD

**Issue by panla** [redengineer/redmini#1317]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
索迈特AI

## 平台
Android

## 小红书版本信息
8.43.1
 
## 基础库版本
v3.96.3

## 发生问题的时间 
2024-07-05 11:46:57 至 2024-07-05 11:46:57

## 问题描述
已调用 商品-新增/修改接口之后。
下单时提示，510010，担保支付订单不允许自定义图片
请问有什么排查流程吗？

## 期望结果
希望获得问题排查方法，以及解决方案。

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by ohaq-hue** [comment]
暂不支持，后续会进行产品迭代
