### ISSUE TITLE
downloadFile api 如果URL过长，会导致下载失败

### ISSUE THREAD

**Issue by gniria** [redengineer/redmini#1318]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
哇喔

## 平台
IOS, Android

## 小红书版本信息
8.42
 
## 基础库版本
v3.96.0

## 发生问题的时间 
2024-07-05 22:52:38 至 2024-07-05 22:52:38

## 问题描述
调用 xhs.downloadFile({url, success: ...}) 下载网络图片到local，如果url过长（比如300个字符），会报错，fail： call funcion &#x27;downloadFile&#x27;, params is nil .

## 期望结果
别报错，成功解析URL并下载图片到临时目录。

## 重现步骤和复现问题的最小demo Github链接
参考代码：

```
xhs.downloadFile({
    url,
    success: (e) => {
       // success !  do something...
    },
    fail: (err) => {
      console.log('uni.downloadFile fail :', err);
    }
  });
```

测试参数：
1. 较短URL（可正常下载）： https://static.aipedias.com/aicamera/photo-gen/20240705/1720190593234930.png?imageMogr2/strip
2. 较长URL（下载报错）： https://static.aipedias.com/aicamera/photo-gen/20240705/1720190593234930.png?imageMogr2/strip|watermark/1/image/aHR0cDovL2RyYXctMTMxNTY0MDI0Ni5jb3MuYXAtc2hhbmdoYWkubXlxY2xvdWQuY29tL2FpY2FtZXJhL2NvbW1vbi9haWNhbWVyYS13YXRlcm1hcmstbW5wLTIwMjQwNzAyLnBuZw/dissolve/80/dx/0/dy/220/gravity/south/scatype/3/spcent/60

**Comment by wernerpeng** [comment]
没有截断，但上述URL 写法不规范(query中为啥是path)会造成转换url时失败，导致未正常发送请求；建议使用规范的URL格式再次尝试；
另外后续的报错提示会将nil和转换报错做下区分；

**Comment by gniria** [comment]
> 没有截断，但上述URL 写法不规范(query中为啥是path)会造成转换url时失败，导致未正常发送请求；建议使用规范的URL格式再次尝试； 另外后续的报错提示会将nil和转换报错做下区分；

url里的【?】是腾讯云约定的样式参数分隔符，具体做法参考这里：
https://www.tencentcloud.com/zh/document/product/1045/33443。
如果是预设样式，分隔符可以是：中划线（-）、下划线（_）、斜杠（/）和感叹号（!）。
非预设样式，则是url query默认的?。
由于业务变化比较频繁，预设样式不满足需要，所以使用非预设样式，自行拼接处理参数。

**Comment by gniria** [comment]
已解决。
处理方案：对?后面的处理参数进行urlencode，即可正常解析下载。
