### ISSUE TITLE
小红书后台生成秘钥报错

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1320]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
绿云

## 平台
IDE

## 小红书版本信息
8.43.1
 
## 基础库版本
v3.96.3

## 发生问题的时间 
2024-07-06 18:44:21 至 2024-07-06 18:44:21

## 问题描述
小红书后台生成秘钥JS报错,无法生成秘钥

## 期望结果
小红书后台生成秘钥不报错

## 重现步骤和复现问题的最小demo Github链接
见下图
<img width="1240" alt="微信图片_20240706184828" src="https://github.com/redengineer/redmini/assets/11535505/27928a8a-3c20-4f66-ab1b-93a1990d94ce">

**Comment by MrFangyulong** [comment]
您好，专业号平台生成代码上传秘钥报错这个问题我们于7月10号已发版修复，辛苦同学再次尝试使用此功能，还有其他问题欢迎向我们反馈~

**Comment by heiyantutu** [comment]
> 您好，专业号平台生成代码上传秘钥报错这个问题我们于7月10号已发版修复，辛苦同学再次尝试使用此功能，还有其他问题欢迎向我们反馈~

我这边测试已经修复好了 并且正常上传
