### ISSUE TITLE
下载了jssdk3.8.0 然后使用xhs.miniProgram.postMessage api 报undefined

### ISSUE THREAD

**Issue by gicbeenLee** [redengineer/redmini#1321]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
招商银行

## 平台
IDE, Android, IOS

## 小红书版本信息
v8.43.1
 
## 基础库版本
v3.54.3

## 发生问题的时间 
2024-07-08 11:21:11 至 2024-07-08 11:21:11

## 问题描述
小红书小程序 webview 的h5 拉起分享 看了下https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/component/web-view 文档  下载了jssdk3.8.0 然后使用xhs.miniProgram.postMessage api 报undefined,我这边的操作是下载jssdk3.8.0然后放到项目 然后import 使用

## 期望结果
h5项目能正常使用xhs.miniProgram.postMessage api 将分享参数传递给小红书小程序

## 重现步骤和复现问题的最小demo Github链接
我这边的操作是下载jssdk3.8.0然后放到项目 然后import 使用

**Comment by gicbeenLee** [comment]
有没有路过的大神遇到过的,求分享!求指导!
期待官方的老师们尽快回复下!!
在此抱拳了!!!

**Comment by gicbeenLee** [comment]
试了下用3.9.2可以,不知3.8.0为啥不行!

**Comment by gicbeenLee** [comment]
小红书小程序 体验版和开发者工具预览 vconsole都不出来是什么原因?

**Comment by Hubmeat** [comment]
>  3.99.x 已修复
