### ISSUE TITLE
小红书小程序webview需要支持打开小红书域名的链接

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#1322]
## Issue类型
feature

## 所属的服务商
绿云

## 这个功能解决的问题
场景用户有自己的文章比如有一个攻略性质的种草文章 他们可以放到小程序里面进行看 对应的产品下的种草攻略 作为旅游产品的详情的补充 
![微信图片_20240708155526](https://github.com/redengineer/redmini/assets/11535505/85243d02-0451-413f-bafa-4b92697b86b4)
比如友商公众号就可以内嵌

**Comment by leeligang1027** [comment]
暂不支持，请关注开放平台文档中心！

**Comment by heiyantutu** [comment]
好的 我的建议是小红书自己这层放开类似微信小程序能打开自己的公众号文章
