### ISSUE TITLE
体验版和小红书开发者工具预览 均无vconsole,给调试带来巨大阻塞!

### ISSUE THREAD

**Issue by gicbeenLee** [redengineer/redmini#1327]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
招商银行

## 平台
IOS, Android, IDE

## 小红书版本信息
v8.43.1
 
## 基础库版本
v3.54.3

## 发生问题的时间 
2024-07-09 10:42:35 至 2024-07-09 10:42:35

## 问题描述
体验版扫码进去,vconsole一闪后消失,小红书开发者工具的预览不显示vconsole(小红书开发者工具调试器的console是有正常输出日志的),现在对于一些只能在真机上定位调试的场景带来了巨大的阻塞(打的console.log看不到vconsole,右上角的三个点的开发调试已开启),麻烦帮忙定位下!

## 期望结果
体验版二维码和小红书开发者工具预览的二维码进去的可以看到vconsole,以便开发调试定位问题!

## 重现步骤和复现问题的最小demo Github链接
扫描体验版二维码或者小红书开发者工具预览的二维码 可以展示vconsole!
把地址转二维码 用小红书app扫码打开 https://www.xiaohongshu.com/miniapp/status?link&#x3D;xhsdiscover%3A%2F%2Fminiapp%2F65952109ae075a0053edf56e_trial%2Fentry%2Findex%2Findex&amp;fullscreen&#x3D;true

**Comment by jzhmcoo1** [comment]
链接扫不开

**Comment by gicbeenLee** [comment]
![219c5bef1dc95dfed689a99bec6d6e9](https://github.com/redengineer/redmini/assets/174984079/9e7b114a-f4c9-44fd-b6ca-31569f155b17)

**Comment by gicbeenLee** [comment]
开发者工具的console是正常有的,但是体验版 或者 开发者工具预览 vconsole不出来
![b39d7ff821f3c7735bc830b607fd467](https://github.com/redengineer/redmini/assets/174984079/6370dd56-5173-43f3-9098-9f6bc853fc26)

**Comment by gicbeenLee** [comment]
> 链接扫不开

我这边提供了一个二维码你扫扫试下,我这边扫可以的

**Comment by gicbeenLee** [comment]
https://github.com/redengineer/redmini/assets/174984079/ea60f899-fd75-4b2a-a640-6018bd5c16b7

**Comment by gicbeenLee** [comment]
@jzhmcoo1 老师求指导,诉求就是小红书小程序能出来vconsole(webview的h5页面能出来的,小程序本身的vconsole怎么才能出来,因为涉及调试h5页面通过xhs.miniProgram.postMessage传值的接受打印的情况)

**Comment by badKid1109** [comment]
我遇到过类似的问题，是我的一个组件层级太高挡住了，你可以看看是不是类似的问题

**Comment by Hubmeat** [comment]
您好，麻烦更新至最新 3.99.2 版本的基础库，再试试看还有没有问题
