### ISSUE TITLE
小程序后台配置消息通知推送URL出错

### ISSUE THREAD

**Issue by gniria** [redengineer/redmini#1328]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
哇喔

## 平台
IDE

## 小红书版本信息
8.42
 
## 基础库版本
v3.97.0

## 发生问题的时间 
2024-07-09 14:38:07 至 2024-07-09 14:38:07

## 问题描述
小程序后台配置消息推送，提交时提示：https://drawai.aipedias.com/api/xxxxx 未返回 echostr 参数内容。
我们通过第三方工具测试接口能正常响应GET、POST请求。而访问日志里并没有收到小红书发来的验证请求。

## 期望结果
成功配置消息推送URL

## 重现步骤和复现问题的最小demo Github链接
URL： https://drawai.aipedias.com/api/pay/notifyXhs
Token（令牌）：任意
EncodingAESKey（消息加密密钥）： 任意

**Comment by MuRyanice** [comment]
这个问题对我们影响挺大的，请尽快修复下，感谢

**Comment by MuRyanice** [comment]
> 您好开发者, 我们已收到你的问题, 已通知开发团队进行处理！ 如您未阅读我们的开发文档，可先参阅开发文档 [小红书问题处置流程](https://miniapp.xiaohongshu.com/docs/guide/exceptionPerformanceWhiteScreen) ✨ 感谢您的提问！✨

这个问题对我们影响挺大的，请尽快修复下，感谢

**Comment by Tokysky** [comment]
在设置接收消息URL的时候，我们会做校验，校验逻辑如下：
通过get请求URL（会自动拼接上一些参数）
https://drawai.aipedias.com/api/pay/notifyXhs?nonce=xxxx&timestamp=xxxx&signature=xxxx&echostr=xxx
你们需要将收到的echostr字符串作为response返回

**Comment by gniria** [comment]
> 问日志里并没有收到小红书发来的验证请求。

我们遇到的问题是：在小程序后台配置URL，点击提交时提示 【未返回 echostr 参数内容】，但我们的接口并没有收到小红书的验证请求，而不是接口对参数的处理是否正确（还没到这一步）。

**Comment by gniria** [comment]
> > 问日志里并没有收到小红书发来的验证请求。
> 
> 我们遇到的问题是：在小程序后台配置URL，点击提交时提示 【未返回 echostr 参数内容】，但我们的接口并没有收到小红书的验证请求，而不是接口对参数的处理是否正确（还没到这一步）。




> 在设置接收消息URL的时候，我们会做校验，校验逻辑如下： 通过get请求URL（会自动拼接上一些参数） https://drawai.aipedias.com/api/pay/notifyXhs?nonce=xxxx&timestamp=xxxx&signature=xxxx&echostr=xxx 你们需要将收到的echostr字符串作为response返回

以你提供的demo链接为例，直接点开（相当于GET请求），能正常访问到我们配置的URL，我们的访问日志也正常记录，但在小程序后台点提交时，按理说小红书会发送检测请求，但我们没有收到。这是比较奇怪的地方。

**Comment by Tokysky** [comment]
已解决
