### ISSUE TITLE
webview加了bindmessage后 右上角第二次分享失效!

### ISSUE THREAD

**Issue by gicbeenLee** [redengineer/redmini#1331]
https://github.com/redengineer/redmini/assets/174984079/30b8bea9-2c64-4aea-b0e4-b0b23f1eb326

## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
招商银行

## 平台
IOS, Android, IDE

## 小红书版本信息
v8.43.1
 
## 基础库版本
v3.54.3

## 发生问题的时间 
2024-07-10 10:45:54 至 2024-07-10 10:45:54

## 问题描述
webview加了bindmessage后 右上角第一次分享无论是小红书好友还是微信好友还是微信朋友圈都正常,但是第二次分享失效,h5页面再触发postMessage右上角分享第一次正常,再点右上角三个点右上角分享失效!

## 期望结果
webview加了bindmessage后 右上角分享 功能正常(不管第几次)

## 重现步骤和复现问题的最小demo Github链接
h5 postMessage, 小程序 webview 加 bindmessage

**Comment by ohaq-hue** [comment]
已经修复了
