### ISSUE TITLE
页面管理后台添加主页小程序显示已生效 但是主页前端不显示店铺入口

### ISSUE THREAD

**Issue by lemomentcaviar** [redengineer/redmini#1332]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
有赞

## 小红书版本信息
V8.43.1

## 运营场景描述
页面管理后台添加主页小程序显示已生效 但是主页前端不显示店铺入口 

## 用户ID 
62c7e0bb000000001902ffe1

## 发生问题的时间 
2024-07-09 10:05:19 至 2024-07-12 10:05:19

## 期望结果
前端显示店铺入口，可以直接跳转至小程序

## 业务基础信息（选填）
666915a56fff380001aef612

**Comment by lhxleslie** [comment]
小红书小程序就是一坨屎，搞成这样，开发尼玛呢，折磨我们开发人员是吧，傻逼玩意

**Comment by ohaq-hue** [comment]
现在主态看不到入口，但是客态可以看到
