### ISSUE TITLE
开发者工具真迹调试扫描二维码不能打开小程序

### ISSUE THREAD

**Issue by zhouhaipeng** [redengineer/redmini#1340]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
惜食物魔法袋

## 平台
IDE

## 小红书开发者工具版本
2.0.17

## 基础库版本
v3.96.2

## 发生问题的时间
2024-07-15 18:08:35 至 2024-07-15 18:08:35

## 问题描述
开发者工具真机调试扫描二维码不能打开小程序，提示小程序加载失败，提交到体验版小程序可以正常加载

## 期望结果
真机调试扫描二维码可以正常打开小程序

## 重现步骤和复现问题的最小demo Github链接
点击模拟器真机调试扫描二维码

**Comment by lhxleslie** [comment]
小红书小程序就是一坨屎，搞成这样，开发尼玛呢，折磨我们开发人员是吧，傻逼玩意

**Comment by antonySee** [comment]
> 小红书小程序就是一坨屎，搞成这样，开发尼玛呢，折磨我们开发人员是吧，傻逼玩意

不要侮辱屎

**Comment by zhouhaipeng** [comment]
?????郛贍?,?栁?????!????~??lt;/FONT>??鯢??????????http://mvfin.cn
