### ISSUE TITLE
小程序页面疑似css加载失败导致页面错乱

### ISSUE THREAD

**Issue by ggaier** [redengineer/redmini#1348]
## Issue类型
bug

## 问题模块
小程序容器(Android)
 
## 所属的服务商
粗门

## 平台
Android

## 小红书版本信息
v8.45.0
 
## 基础库版本
v3.95.0

## 用户ID 
563437358

## 发生问题的时间 
2024-07-19 08:15:26 至 2024-07-19 10:15:26

## 问题描述
我们的小红书小程序有用户打开页面后，页面错乱，所有内容都是竖向排列。

## 期望结果
查找到问题原因，寻找解决办法，看看我们如何解决

## 重现步骤和复现问题的最小demo Github链接
因为这个是偶现问题，难以复现。用户手机我们也无法获取，没有办法提供demo。希望能后台查一下日志，看看什么问题

**Comment by hhuwc** [comment]
用户uid: 5657933db8c8b42750097d66

**Comment by hhuwc** [comment]
华为p50pro 鸿蒙系统

<img width="528" alt="image" src="https://github.com/user-attachments/assets/2f14c530-9a1f-4fed-919d-ba7ebb3b99a8">
<img width="528" alt="image" src="https://github.com/user-attachments/assets/f35b9912-9f4d-4870-9ec9-322d18cd97af">

**Comment by hhuwc** [comment]
未复现问题，建议用户更新app后体验
