### ISSUE TITLE
期望能从小程序跳转到小红书官方薯店

### ISSUE THREAD

**Issue by jencho2017** [redengineer/redmini#1349]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
大咖说

## 平台
IOS, Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.98.1

## 发生问题的时间 
2024-07-19 15:12:27 至 2024-07-19 15:12:27

## 问题描述
目前无法从自研的小程序跳转到在小红书开的官方店铺。

## 期望结果
期望能从自研的小程序大咖说讲师团跳转到新开的我司的官方小羌镍芴英揠睨軔衰傑书店铺。

## 重现步骤和复现问题的最小demo Github链接
需求，无需复现

**Comment by leeligang1027** [comment]
暂不支持，请关注开放平台文档中心！
