### ISSUE TITLE
能否把其他小程序平台的代码，转到小红书小程序平台进行投放？

### ISSUE THREAD

**Issue by Hubmeat** [redengineer/redmini#135]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
- 如果已经使用第三方开源框架（如 taro, uni 等）开发的话，可以基于原有的项目， 通过配置小红书平台插件，来快速过渡到小程序平台（要注意一些基础能力的兼容性问题），具体可以参考： https://miniapp.xiaohongshu.com/docs/ide/frameworkdevelop


- 如果是原生小程序的代码，可以使用小红书转换工具，将代码语法转换成小红书小程序语法来快速过渡到小红书平台。具体可以参考：https://miniapp.xiaohongshu.com/docs/ide/moveTool

**Comment by mayunpeng12580** [comment]
<Button
          openType='getPhoneNumber'
          type='primary'
          onGetPhoneNumber={this.handleGetPhoneNumberAfter}
         
        >
获取手机号回调失败

**Comment by mayunpeng12580** [comment]
<Button
openType='getPhoneNumber'
type='primary'
onGetPhoneNumber={this.handleGetPhoneNumberAfter}

    >

手机号回调事件不生效   taro打包得

**Comment by ArwayQu** [comment]
@Hubmeat 请问使用uniapp3开发的小程序目前支持编译为小红书小程序吗？目前看到文档只提供了uniapp2的方法
