### ISSUE TITLE
商品同步-生活服务 接口报错 

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#1351]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
麦西盟

## 平台
IOS, Android

## 小红书版本信息
8.44
 
## 基础库版本
v3.94.0

## 发生问题的时间 
2024-07-01 00:00:00 至 2024-07-19 17:35:05

## 问题描述
接口:
https://miniapp.xiaohongshu.com/api/rmp/mp/deal/poi/product/upsert

返回内容:
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;syntax error, expect {, actual [, pos 1, line 1, column 2[]&quot;,&quot;code&quot;:500001}

## 期望结果
处理 syntax error, expect {, actual [, pos 1, line 1, column 2[] 错误.

## 重现步骤和复现问题的最小demo Github链接
调用 https://miniapp.xiaohongshu.com/api/rmp/mp/deal/poi/product/upsert 接口即可

**Comment by Tokysky** [comment]
可能是输入的body json解析错误，请提供一下具体的请求参数

**Comment by anaian** [comment]
{"out_product_id":"xhsproduct_658","name":"集运服务","short_title":"集运服务","desc":"集运服务-141362","path":"\/pages\/index","top_image":"https:\/\/www.maxmcargo.com\/sites\/default\/files\/mxmcore\/wei_xin_tu_pian_20191022142934_1.jpg","category_id":"5a310e143f7d1712823ba202","biz_create_time":"1721982444","biz_update_time":"1721982444","skus":[{"out_sku_id":"658","name":"集运服务-141362","sku_image":"https:\/\/www.maxmcargo.com\/sites\/default\/files\/mxmcore\/wei_xin_tu_pian_20191022142934_1.jpg","origin_price":"113925","sale_price":"113925","status":"1"}],"ext":[],"product_type":2,"settle_type":1,"poi_id_list":["66389bd93c228b00011a84a8"]}

**Comment by anaian** [comment]
POST /api/rmp/mp/deal/poi/product/upsert?appid=xxx&access_token=xxx HTTP/1.0
Content-Type: application/json
User-Agent: Drupal (+http://drupal.org/)
Host: miniapp.xiaohongshu.com
Content-Length: 669

**Comment by anaian** [comment]
返回数据:

{"data":null,"success":false,"msg":"syntax error, expect {, actual [, pos 1, line 1, column 2[]","code":500001}

**Comment by Tokysky** [comment]
ext参数是Map对象类型，不是列表，所以应该是{}，而不是[]
https://miniapp.xiaohongshu.com/docs?path=/docs/api-backend/post-api-rmp-mp-deal-poi-product-upsert

**Comment by anaian** [comment]
好的, 可以了
