### ISSUE TITLE
小程序关店订单无法处理

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#1352]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
8.44

## 运营场景描述
小程序关店订单无法处理 

## 发生问题的时间 
2024-07-19 17:39:43 至 2024-07-19 17:39:43

## 期望结果
小程序满足关店条件，顺利关店。

## 业务基础信息（选填）
订单号：E20240407101954001900011
【APP_ID】:  62e76e08b066b800014d26f8

调用接口是结算成功的
参数{
&quot;out_order_id&quot;: &quot;E20240407101954001900011&quot;,
&quot;out_settle_id&quot;: &quot;202404260021213952210019&quot;,
&quot;out_after_sales_order_ids&quot;: [
	&quot;202404260021213952210019&quot;
    ],
&quot;after_settle&quot;: 1
}
result&#x3D;{&quot;code&quot;:200,&quot;data&quot;:{&quot;code&quot;:0,&quot;data&quot;:{&quot;out_settle_id&quot;:&quot;202404260021213952210019&quot;,&quot;settle_id&quot;:&quot;RS202406160001609973&quot;,&quot;settle_info&quot;:{&quot;cps_infos&quot;:[],&quot;commission_amount&quot;:540,&quot;settle_product_amount&quot;:10800,&quot;commission_info&quot;:{&quot;red&quot;:378,&quot;service_provider&quot;:162},&quot;cps_commission_amount&quot;:0},&quot;settle_status&quot;:&quot;SUCCESS&quot;,&quot;settle_time&quot;:1718531473},&quot;msg&quot;:&quot;success&quot;,&quot;success&quot;:true},&quot;message&quot;:&quot;successful&quot;,&quot;statusCode&quot;:&quot;01@@3131@010200&quot;,&quot;success&quot;:true}

**Comment by Tokysky** [comment]
已解决
