### ISSUE TITLE
旅行社专业号开通担保支付能力

### ISSUE THREAD

**Issue by xiaodingluaipao** [redengineer/redmini#1353]
## Issue类型
feature

## 所属的服务商
荟集生活

## 这个功能解决的问题
我们想做一个不通过服务商的, 旅行社资质的交易型小程序, 目前通过文档已经完成, 法人认证,开通交易能力,还在本地生活商家管理平台完成了绑卡, *但没有开通门店的入口*, 对接接口方面*没有同步本地生活商品接口的能力,也没有担保支付的能力*, 通过文档我们不知道要怎样去解决问题了, 麻烦指教一下, 我们要怎么去开通担保支付能力, 有没有解决方案

**Comment by ohaq-hue** [comment]
已经开通了担保交易，无需认领门店
