### ISSUE TITLE
uniapp Vue2打包成小红书小程序

### ISSUE THREAD

**Issue by woshiqianduangongchengshi** [redengineer/redmini#1358]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
屿见厦门

## 平台
IDE

## 小红书开发者工具版本
2.0.17

## 基础库版本
v3.99.0

## 用户ID
5db8d1050000000001001af9

## 发生问题的时间
2024-07-24 11:02:31 至 2024-07-24 11:02:31

## 问题描述
vue create -p dcloudio/uni-preset-vue uni-app-xhs
使用官网文档打包出来的小红书小程序是模板的
不包含已开发的相关代码，怎么做才能把当前代码打包成小红书小程序，并且可以发布和开发用

## 期望结果
将当前项目代码打包成小红书小程序，并且可以开发编译和发布版本

## 重现步骤和复现问题的最小demo Github链接
npm install -g @vue/cli@4
vue create -p dcloudio/uni-preset-vue uni-app-xhs
npm run dev:mp-xhs

**Comment by jzhmcoo1** [comment]
使用开发者工具导入生成的 dist 目录

**Comment by woshiqianduangongchengshi** [comment]
![微信截图_20240724111705](https://github.com/user-attachments/assets/70a0e30c-fa01-4c94-b6a3-286aa8bcc677)
打开是这样的，跟我当前项目代码不同

**Comment by woshiqianduangongchengshi** [comment]
> 使用开发者工具导入生成的dist目录
打开是这样的，我当前项目代码不同
![image](https://github.com/user-attachments/assets/de80e17f-03ab-4ac6-9568-e03600936e7b)
