### ISSUE TITLE
订单列表页点击跳转报错【页面不存在】

### ISSUE THREAD

**Issue by cdl345805335** [redengineer/redmini#1363]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
侠侣亲子

## 平台
IOS

## 小红书版本信息
15
 
## 基础库版本
v3.99.1

## 用户ID 
5b67d0424b523800013cd5d0

## 发生问题的时间 
2024-07-27 16:52:14 至 2024-07-27 16:52:14

## 问题描述
订单列表页点击调整报【页面不存在】
手机型号：iphone 15
跳转时，看着并没有跳转到我们小程序

## 期望结果
确认下点击订单详情页的链接访问出错的是不是我们小程序返回的链接问题

## 重现步骤和复现问题的最小demo Github链接
小红书用户ID：5b67d0424b523800013cd5d0
订单号：Peb734005876781205111
手机型号：iphone 15
订单详情页，点击该订单报页面不存在错误

**Comment by cdl345805335** [comment]
发生时间修改
2024-07-27 16:00:00 至 2024-07-27 16:35:00

**Comment by xutm** [comment]
发起日志回捞了，麻烦打开下 APP
