### ISSUE TITLE
商品同步-生活服务-接口报错:msg: 网络异常请稍后再试 code: 5

### ISSUE THREAD

**Issue by 17612850365** [redengineer/redmini#1364]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
自有团队

## 平台
IOS, Android

## 小红书版本信息
8.42.0
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-07-28 22:47:14 至 2024-07-28 22:47:14

## 问题描述
生活服务商品同步报错，错误原因提示不明确

## 期望结果
提交成功，或者详细提示错误信息。

## 重现步骤和复现问题的最小demo Github链接
API：https://miniapp.xiaohongshu.com/api/rmp/mp/deal/poi/product/upsert
提交数据：{
    "out_product_id": "R1o1Mg==",
    "name": "广州长隆野生动物世界",
    "short_title": "广州长隆野生动物世界",
    "desc": "空中缆车俯瞰动物,特色小火车穿越五大洲,看动物大家族",
    "path": "/pages/park-detail/index?type=note&scenicCode=GZ52&scenicName=%E5%B9%BF%E5%B7%9E%E9%95%BF%E9%9A%86%E9%87%8E%E7%94%9F%E5%8A%A8%E7%89%A9%E4%B8%96%E7%95%8C",
    "top_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
    "category_id": "65e5b275c525f200015c677c",
    "biz_create_time": 1722177810,
    "biz_update_time": 1722177810,
    "skus": [
        {
            "out_sku_id": "GZ52_CATE_0031572520100462",
            "name": "特惠门票-2大1小家庭票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 94500,
            "sale_price": 94500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100461",
            "name": "特惠门票-1大1小亲子票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 59500,
            "sale_price": 59500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100460",
            "name": "特惠门票-双人票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 70000,
            "sale_price": 70000
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100455",
            "name": "特惠门票-标准票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 35000,
            "sale_price": 35000
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100456",
            "name": "特惠门票-儿童票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 24500,
            "sale_price": 24500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100458",
            "name": "特惠门票-青少年票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 28000,
            "sale_price": 28000
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100413",
            "name": "特惠门票-中高考生三人欢聚票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 73500,
            "sale_price": 73500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100457",
            "name": "特惠门票-长者票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 24500,
            "sale_price": 24500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100459",
            "name": "特惠门票-优待票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 24500,
            "sale_price": 24500
        },
        {
            "out_sku_id": "GZ52_CATE_0031572520100454",
            "name": "特惠门票-工行联名卡权益票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 35000,
            "sale_price": 35000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00167",
            "name": "套票-动物世界+广州大马戏16:30场普通座标准票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 69500,
            "sale_price": 69500
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00125",
            "name": "套票-动物世界+广州大马戏16:30场普通座儿童票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 56000,
            "sale_price": 56000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00124",
            "name": "套票-动物世界+广州大马戏16:30场普通座青少年票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 64000,
            "sale_price": 64000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00168",
            "name": "套票-动物世界+广州大马戏16:30场普通座优待票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 56000,
            "sale_price": 56000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00039",
            "name": "套票-动物世界+广州大马戏19:30场普通座标准票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 78000,
            "sale_price": 78000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00183",
            "name": "套票-动物世界+广州大马戏19:30场普通座儿童票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 56000,
            "sale_price": 56000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00180",
            "name": "套票-动物世界+广州大马戏19:30场普通座青少年票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 64000,
            "sale_price": 64000
        },
        {
            "out_sku_id": "GZ52_CATE_003154252AH00186",
            "name": "套票-动物世界+广州大马戏19:30场普通座优待票",
            "sku_image": "https://0img.chimelong.com/backend-file/2024/01/17/111437_f7a2106651324b69a5cea2cf39bffba6.png",
            "origin_price": 56000,
            "sale_price": 56000
        }
    ],
    "product_type": 1,
    "settle_type": 1
}

**Comment by Tokysky** [comment]
您好，单次上传的sku过多导致后台请求超时了，可以尝试拆分成多次请求
