### ISSUE TITLE
在网页端用xhs.miniProgram.postMessage向小程序发送数据，电脑编译会执行bindmessage，但手机端不执行bindmessage

### ISSUE THREAD

**Issue by yuguihunsha** [redengineer/redmini#1365]
## Issue类型
bug

## 问题模块
小程序容器(Android)
 
## 平台
Android

## 小红书版本信息
8.46.0
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-07-29 09:34:48 至 2024-07-29 09:34:48

## 问题描述
在网页端用xhs.miniProgram.postMessage向小程序发送数据，电脑编译会执行bindmessage，但手机端不执行bindmessage，手机端小程序无法接收网页传过去的数据。

## 期望结果
对于bindmessage数据接收功能，在文档中进行详细说明以及提供案例代码。

## 重现步骤和复现问题的最小demo Github链接
/entry/component/component
在于归婚纱小程序中，点击婚纱页面，此网页用xhs.miniProgram.postMessage向小程序传递了数据，小程序的bindmessage未执行。

**Comment by jzhmcoo1** [comment]
先用下 3.8.0 版本，是迁移的一个 bug，后续发版后更新最新版在官方文档上
