### ISSUE TITLE
web-view组件，真机调试和开发者工具有差异。

### ISSUE THREAD

**Issue by FengXinKai** [redengineer/redmini#1366]
<img width="303" alt="84e2cc1920224400f91063231a0df41" src="https://github.com/user-attachments/assets/86a75107-e70c-449a-91d4-af6eaf65b05e">
![cf4a71cb2dd7b4bf7523586a3ce63a0](https://github.com/user-attachments/assets/83ff47cb-f934-4d6d-aaf3-d4a435e73079)
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
奇陌

## 平台
Android, IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.96.2

## 发生问题的时间 
2024-07-29 17:45:29 至 2024-07-29 17:45:29

## 问题描述
web-view组件，真机调试和开发者工具有差异。

## 期望结果
请帮我解决这种情况。

## 重现步骤和复现问题的最小demo Github链接
  &lt;web-view src&#x3D;&quot;https://kimocloud.com/gameDemo/&quot; bindmessage&#x3D;&quot;&quot;&gt;&lt;/web-view&gt;

**Comment by FengXinKai** [comment]
![cf4a71cb2dd7b4bf7523586a3ce63a0](https://github.com/user-attachments/assets/68b10376-17fb-4376-ae9c-897dfa499978)

**Comment by jzhmcoo1** [comment]
![CleanShot 2024-07-29 at 18 05 51@2x](https://github.com/user-attachments/assets/acf64e03-3732-41e9-9733-1a6d6f9f1690)
我这边开发者工具与你真机效果类似，可以发一下你的开发者工具版本号么

**Comment by FengXinKai** [comment]
2.0.17

**Comment by FengXinKai** [comment]
> ![CleanShot 2024-07-29在18：05 51@2x](https://private-user-images.githubusercontent.com/55695299/353004401-acf64e03-3732-41e9-9733-1a6d6f9f1690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTI0OTUsIm5iZiI6MTcyMjI1MjE5NSwicGF0aCI6Ii81NTY5NTI5OS8zNTMwMDQ0MDEtYWNmNjRlMDMtMzczMi00MWU5LTk3MzMtMWE2ZDZmOWYxNjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDExMjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4OGNmYzIwMGIxYWY2OTI1OTZjY2Y1YjllZTA2ZmU2MmE0YjQwNWVhZjQ3ZjFjYzgyOGQ4ZTg3NjI0ZDcwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GwId82hQ9oO_1C-bfd-Zr656yZHKsQCVnPoxGHKJlXE)我这边开发者工具与你真机效果类似，可以发一下你的开发者工具版本号么

如果我想在这个web-view上面在展示一下其他的东西怎么做 ？

**Comment by jzhmcoo1** [comment]
> 如果我想在这个web-view上面在展示一下其他的东西怎么做？

这个不行的吧，你可以调研下友商的效果

**Comment by jzhmcoo1** [comment]
有差异是因为真机上用的是原生组件，IDE 是用 iframe 模拟的，所以你这边可以写层级更高的覆盖在它上面，后面我们修复下 IDE 上的效果
