### ISSUE TITLE
本地生活商家管理平台，没有商家首页、商品管理、订单管理等菜单

### ISSUE THREAD

**Issue by wangsheng2012** [redengineer/redmini#1368]
## Issue类型
operator

## 问题模块
自研小程序商品售卖

## 所属的服务商
宋城旅游

## 小红书版本信息
1

## 运营场景描述
自研小程序商品售卖 

## 发生问题的时间 
2024-07-29 20:42:26 至 2024-07-29 20:42:26

## 期望结果
期望本地生活商家管理平台，有商家首页、商品管理、订单管理等菜单

**Comment by ohaq-hue** [comment]
暂不支持
