### ISSUE TITLE
xhs-ci上传时需要支持机器人账号 开发者需要有后台登录权限切版本

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#1372]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
领克

## 平台
IDE

## 小红书版本信息
7.8.8
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-01 16:57:57 至 2024-08-01 16:57:57

## 问题描述
用ci上传的时候，显示的体验版本会到其他人的账号下

## 期望结果
希望支持统一的机器人账号，另外希望尽快支持开发者登录后台切换体验版（或者有其他途径可以切换）

## 重现步骤和复现问题的最小demo Github链接
见群聊

**Comment by ohaq-hue** [comment]
1、ci上传时用新的开发者账号可以避免这个问题
2、感谢建议，开发者登陆后台切换暂时还不支持
