### ISSUE TITLE
授权信息返回异常

### ISSUE THREAD

**Issue by Avenmemety** [redengineer/redmini#1373]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
Android

## 小红书版本信息
8.40.0
 
## 基础库版本
v3.92.0

## 发生问题的时间 
2024-08-02 10:00:00 至 2024-08-02 12:00:00

## 问题描述
记录到授权返回的信息异常导致无法获取用户信息

## 期望结果
授权后能正常拿到用户信息

## 重现步骤和复现问题的最小demo Github链接
sentry捕获到的错误，目前未复现。记录到的授权信息是：
{&quot;_stop&quot;:false,&quot;_end&quot;:false,&quot;defaultPrevented&quot;:false,&quot;button&quot;:0,&quot;timeStamp&quot;:1722564782083,&quot;type&quot;:&quot;getphonenumber&quot;,&quot;mpEvent&quot;:{&quot;type&quot;:&quot;getphonenumber&quot;,&quot;timeStamp&quot;:1722564782077,&quot;target&quot;:{&quot;dataset&quot;:{&quot;channel&quot;:&quot;&quot;,&quot;shareType&quot;:&quot;normal&quot;,&quot;sid&quot;:&quot;_EF&quot;},&quot;id&quot;:&quot;_EF&quot;,&quot;offsetTop&quot;:446,&quot;offsetLeft&quot;:290},&quot;currentTarget&quot;:{&quot;dataset&quot;:{&quot;channel&quot;:&quot;&quot;,&quot;shareType&quot;:&quot;normal&quot;,&quot;sid&quot;:&quot;_EF&quot;},&quot;id&quot;:&quot;_EF&quot;,&quot;offsetTop&quot;:446,&quot;offsetLeft&quot;:290},&quot;detail&quot;:{&quot;errMsg&quot;:&quot;getPhoneNumber:ok&quot;},&quot;touches&quot;:[],&quot;changedTouches&quot;:[]},&quot;bubbles&quot;:true,&quot;cancelable&quot;:true,&quot;detail&quot;:{&quot;errMsg&quot;:&quot;getPhoneNumber:ok&quot;},&quot;touches&quot;:[],&quot;changedTouches&quot;:[],&quot;_vts&quot;:1722564782083}

显示“getPhoneNumber:ok”。但是没有iv和encryptedData信息。导致无法获取用户信息

小程序appid：6551791d0fa73d005807ef73
入口地址：{&quot;path&quot;:&quot;pages/presaleIndex/index&quot;,&quot;query&quot;:{&quot;dsmatrix_key&quot;:&quot;distribution_red_goods&quot;,&quot;ds_token&quot;:&quot;v2_8db66412f2de60b16dd840c7a763b079&quot;,&quot;goodsNum&quot;:&quot;126138346790178816005&quot;,&quot;n&quot;:&quot;72341945&quot;,&quot;live_coupon_claim_status&quot;:&quot;2&quot;,&quot;source&quot;:&quot;local_life_note&quot;,&quot;sourceFrom&quot;:&quot;buyable_goods_note&quot;,&quot;note_track_id&quot;:&quot;&quot;,&quot;video_feed_type&quot;:&quot;note_related_notes&quot;,&quot;apm_key&quot;:&quot;52075BED-3EF8-40BD-A42A-2B9F55C3C57D&quot;,&quot;page_key&quot;:&quot;28&quot;,&quot;open_url&quot;:&quot;/miniapp/qrcode?background_transparent&#x3D;true&amp;disableNativeLoading&#x3D;yes&amp;fullscreen&#x3D;true&amp;i&#x3D;6551791d0fa73d005807ef73&amp;type&#x3D;1&amp;sharer_userid&#x3D;5fe81d750000000001005e43&amp;p&#x3D;pages%2FpresaleIndex%2Findex%3Fdsmatrix_key%3Ddistribution_red_goods%26ds_token%3Dv2_8db66412f2de60b16dd840c7a763b079%26goodsNum%3D126138346790178816005%26n%3D72341945%26live_coupon_claim_status%3D2%26source%3Dlocal_life_note%26sourceFrom%3Dbuyable_goods_note%26note_track_id%3D%26video_feed_type%3Dnote_related_notes%26apm_key%3D52075BED-3EF8-40BD-A42A-2B9F55C3C57D&quot;,&quot;launch_from&quot;:&quot;captain&quot;,&quot;web_id&quot;:&quot;&quot;}}

**Comment by xutm** [comment]
给一下 userid

**Comment by Avenmemety** [comment]
openId可以吗？
openId：d31a1ccab44c79cb5b5969192bd3ea7b48b8fb737dc02d48c688420b8c579816
appId： 6653f57733828a0001beff01
发生时间：08-04 14:32

**Comment by xutm** [comment]
麻烦重新打开下手机，看下你的离线日志

**Comment by Avenmemety** [comment]
> 麻烦重新打开下手机，看下你的离线日志

我自己没复现，都是找的线上记录下来的，你需要什么信息呢？

**Comment by xutm** [comment]
> > 麻烦重新打开下手机，看下你的离线日志
> 
> 我自己没复现，都是找的线上记录下来的，你需要什么信息呢？

你只需要重新启动下小红书app，就行，我这边发起了离线任务，捞下你的日志，我再看看

**Comment by Avenmemety** [comment]
> > > 麻烦重新打开下手机，看下你的离线日志
> > 
> > 
> > 我自己没复现，都是找的线上记录下来的，你需要什么信息呢？
> 
> 你只需要重新启动下小红书app，就行，我这边发起了离线任务，捞下你的日志，我再看看

是重启小程序吧？
我在11:01第一次进入了小红书 appid为【6653f57733828a0001beff01】的小程序，并操作了授权用户信息

**Comment by xutm** [comment]
> > > > 麻烦重新打开下手机，看下你的离线日志
> > > 
> > > 
> > > 我自己没复现，都是找的线上记录下来的，你需要什么信息呢？
> > 
> > 
> > 你只需要重新启动下小红书app，就行，我这边发起了离线任务，捞下你的日志，我再看看
> 
> 是重启小程序吧？ 我在11:01第一次进入了小红书 appid为【6653f57733828a0001beff01】的小程序，并操作了授权用户信息

重启小红书 app

**Comment by Avenmemety** [comment]
> > > > > 麻烦重新打开下手机，看下你的离线日志
> > > > 
> > > > 
> > > > 我自己没复现，都是找的线上记录下来的，你需要什么信息呢？
> > > 
> > > 
> > > 你只需要重新启动下小红书app，就行，我这边发起了离线任务，捞下你的日志，我再看看
> > 
> > 
> > 是重启小程序吧？ 我在11:01第一次进入了小红书 appid为【6653f57733828a0001beff01】的小程序，并操作了授权用户信息
> 
> 重启小红书 app

18:30 已杀掉小红书APP进程并重新打开
