### ISSUE TITLE
对接中，下单提示“网络异常，请稍后重试”

### ISSUE THREAD

**Issue by wangsheng2012** [redengineer/redmini#1375]
## Issue类型
feature

## 这个功能解决的问题
对接中，下单提示“网络异常，请稍后重试”，请求数据：{&quot;price_info&quot;:{&quot;order_price&quot;:10},&quot;open_id&quot;:&quot;2f8fc88de914e7f1504a7969e52bd711be3e94cb34126a3369b138b09953f78a&quot;,&quot;out_order_id&quot;:&quot;123456789&quot;,&quot;product_infos&quot;:[{&quot;out_sku_id&quot;:&quot;123456789&quot;,&quot;num&quot;:&quot;1&quot;,&quot;out_product_id&quot;:&quot;111&quot;,&quot;real_price&quot;:&quot;10&quot;,&quot;sale_price&quot;:&quot;10&quot;}],&quot;biz_create_time&quot;:1722652391}，接口地址：https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert

**Comment by Tokysky** [comment]
哈喽，失败的原因是path字段必填，
可以先参考文档，把必填的字段都填上哈https://miniapp.xiaohongshu.com/docs?path=/docs/api-backend/post-api-rmp-mp-deal-order-upsert
后面我们也会优化错误描述
