### ISSUE TITLE
商品数据异常，请确定是担保支付的商品

### ISSUE THREAD

**Issue by wangsheng2012** [redengineer/redmini#1376]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
宋城旅游

## 平台
IDE

## 小红书版本信息
1
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-03 14:37:11 至 2024-08-03 14:37:11

## 问题描述
下单提示：商品数据异常，请确定是担保支付的商品。
请求地址和数据https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert ，数据：{
  &quot;out_order_id&quot;: &quot;2024080300001&quot;,
  &quot;open_id&quot;: &quot;2f8fc88de914e7f1504a7969e52bd711be3e94cb34126a3369b138b09953f78a&quot;,
  &quot;path&quot;: &quot;111&quot;,
  &quot;biz_create_time&quot;: 0,
  &quot;biz_update_time&quot;: 0,
  &quot;order_expired_time&quot;: 0,
  &quot;product_infos&quot;: [
    {
      &quot;out_product_id&quot;: &quot;111&quot;,
      &quot;out_sku_id&quot;: &quot;123456789&quot;,
      &quot;num&quot;: 1,
      &quot;sale_price&quot;: 10,
      &quot;real_price&quot;: 10
    }
  ],
  &quot;price_info&quot;: {
    &quot;order_price&quot;: 10
  }
}

## 期望结果
https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/api-backend/post-api-rmp-token自研小程序的文档中，没找找到关于商品设置担保支付的商品参数？

## 重现步骤和复现问题的最小demo Github链接
https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert ，数据：{
  &quot;out_order_id&quot;: &quot;2024080300001&quot;,
  &quot;open_id&quot;: &quot;2f8fc88de914e7f1504a7969e52bd711be3e94cb34126a3369b138b09953f78a&quot;,
  &quot;path&quot;: &quot;111&quot;,
  &quot;biz_create_time&quot;: 0,

**Comment by leeligang1027** [comment]
请调用接口 https://miniapp.xiaohongshu.com/docs?path=/docs/api-backend/post-api-rmp-mp-deal-poi-product-upsert 同步商品
