### ISSUE TITLE
一加8、华为mate20在打开webview的时候是否存在加载两次的情况

### ISSUE THREAD

**Issue by tanchidahuilang** [redengineer/redmini#138]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
小程序 ua
Dalvik/2.1.0 (Linux; U; Android 11; IN2010 Build/RP1A.201005.001) Resolution/1080*2400 Version/7.47.0 Build/7470116 Device/(OnePlus;IN2010) discover/7.47.0 xhsminiapp/3.28.1
webview ua
Mozilla/5.0 (Linux; Android 11; IN2010 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Safari/537.36 Build/7470116 discover/7.47.0 xhsminiapp/3.28.1
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
卸载后重新下载小红书app，搜索原始原素，点击店铺，点击商品，点击立即购买进入下单
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
这块在特殊安卓机型下首次打开webview容器的时候会不会存在加载两次的可能
我们这边查了kibana当时的请求情况
发现跳转的时候加载了两次相同的url
https://cashier.youzan.com/pay/wsctrade_buy?kdt_id=99546167&book_key=9ca73931-cdd3-4425-be9a-2a821c13f99e&logger={%22user%22:{%22uuid%22:%22gDrqzb0alHM1yUj1657349011574%22,%22ftime%22:1657349011574,%22li%22:15632635651,%22m%22:%2213216265361%22},%22context%22:{%22appId%22:%22620a0f9f96206e0001ffc6d2%22,%22weapp_version%22:%221.3.8%22,%22slg%22:%22%22}}&timestamp=1658115728164&mpVersion=1.3.8&login_ticket=4cc7786d2cd34967b5d4d14d329265a5
最后一个参数login_ticket是一次性的，第二次使用就会拿不到登录态了
同样的多端小程序代码 我们去微信、支付宝反复测试执行就是正常的

**Comment by taiyiandr** [comment]
你们是否进行了web-view 静态资源预加载，对应的预加载配置是什么？

**Comment by tanchidahuilang** [comment]
try {
        // eslint-disable-next-line no-undef
        xhs.prefetch({
          // eslint-disable-next-line @youzan/domain/forbid-hardcode-domain-name
          url: `https://cashier.youzan.com/pay/wsctrade_buy_prefetch?kdt_id=${this.ctx.data.kdtId}`,
          complete: (res) => {
            console.log('xhs.prefetch complete', res);
          },
        });
      } catch (e) {
        console.error('此版本不支持xhs.prefetch功能');
      }

**Comment by taiyiandr** [comment]
> try { // eslint-disable-next-line no-undef xhs.prefetch({ // eslint-disable-next-line @youzan/domain/forbid-hardcode-domain-name url: `https://cashier.youzan.com/pay/wsctrade_buy_prefetch?kdt_id=${this.ctx.data.kdtId}`, complete: (res) => { console.log('xhs.prefetch complete', res); }, }); } catch (e) { console.error('此版本不支持xhs.prefetch功能'); }

静态资源预载，不应有一次性的字段。请联系对应开发同学进行链路整改

**Comment by tanchidahuilang** [comment]
query上加的kdtId就是我们这边的店铺id，是在node层用来处理一些逻辑的，最终返回的页面及页面加载的静态资源是一致的
而且问题场景是单个店铺，理论上不会存在不一样的url
且这套流程只有在部分特殊安卓机上出现问题，其他的都跑的通
所以不太能理解为啥会导致所提出场景的问题

我们这边可以先尝试去掉后 试下问题是否还能复现
