### ISSUE TITLE
登录按钮的getphonenumber方法无法进入回调中

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#139]
## 系统环境(必填[多选]) +
- [ x ] IOS +
- [ ] Android +
- [ x ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ x ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ x ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.48

## 重现步骤 和 复现问题的最小demo Github链接 +
一个问题在开发者工具中button弹不出手机号授权 也无任何报错
![image](https://user-images.githubusercontent.com/49746060/180208361-0f5d1cbc-4ccd-4440-bda5-8df0ec72f4f8.png)
![image](https://user-images.githubusercontent.com/49746060/180208383-df0d7bc4-2a88-4b56-8c01-ca9925b9ce81.png)
在预览二维码中 登录按钮的getphonenumber方法无法进入回调中 无任何反应
## 期望结果 和 实际结果(必填) +
希望能正常授权手机号
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
是原生小程序吗？还是 taro 框架？

**Comment by Hubmeat** [comment]
先不用，我们先排查下

**Comment by Hubmeat** [comment]
您好，开发者，@tarojs/plugin-platform-xhs <= 0.0.4 版本存在兼容问题，
可以安装 > 0.0.4 版本。

< 0.0.4 版本临时解决方案：
[pwd]:node_modules/@tarojs/plugin-platform-xhs/dist/index.js

code: 8
```js
// button 添加下面的代码
    Button: {
        'data-channel': '',
        bindGetPhoneNumber: '',
        bindGetUserInfo: '',
        bindOpenSetting: '',
        bindContact: '',
        bindChooseAddress: '',
        bindChooseInvoiceTitle: '',
        bindLogin: ''
    }
```

已 PR 到 taro 插件组，等待 taro 发版后，可以更新插件修复。
