### ISSUE TITLE
在真机上rpx和微信小程序表现不一致

### ISSUE THREAD

**Issue by badKid1109** [redengineer/redmini#1390]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
宝尊

## 平台
Android

## 小红书版本信息
8.47.0
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-08-06 16:12:27 至 2024-08-06 16:12:27

## 问题描述
看了微信小程序和小红书小程序的关于css的说明，应该是表现一致的，但同一个代码通过uniapp编译不同的端后，样式不一致。例如.item {
        line-height: rpx(20);
        border: 1px solid #bbb;
      } 在华为P70上视觉效果差很多

## 期望结果
微信小程序和小红书小程序表现一致

## 重现步骤和复现问题的最小demo Github链接
.item {
        line-height: rpx(20);
        border: 1px solid #bbb;
      }

**Comment by hhuwc** [comment]
请提供下uniapp编译到小红书小程序后的css代码，并且提供下华为p70 的截图

**Comment by badKid1109** [comment]
<img width="195" alt="1" src="https://github.com/user-attachments/assets/23ffe279-9b60-44b5-8a2f-c3847a4e463f">
<img width="237" alt="2" src="https://github.com/user-attachments/assets/6125c8b4-3d81-48d0-8bac-4d5a89755492">
同一个手机

**Comment by badKid1109** [comment]
微信小程序：    font-size: 28rpx;
    font-weight: 500;
    line-height: 40rpx;
    margin-top: 40rpx;
    margin-left: 20rpx;
    padding: 20rpx 40rpx;
    letter-spacing: 2px;
    color: #1D1D1D;
    border: 4rpx solid #bbb;
    小红书小程序
        border: 1
px
 solid #bbb;
    color: #1d1d1d;
    
    font-size: 3.73333vw;
    font-weight: 500;
    letter-spacing: 2px;
    line-height: 5.33333vw;
    margin-left: 2.66667
vw
;
    margin-top: 5.33333
vw
;
    padding: 2.66667
vw
 5.33333
vw
;
    --ide-font-size: 28rpx;
    --ide-line-height: 40rpx;
    --ide-margin-left: 20rpx;
    --ide-margin-top: 40rpx;
    --ide-padding: 20rpx 40rpx;

**Comment by badKid1109** [comment]
微信小程序
{
    font-size: 28rpx;
    font-weight: 500;
    line-height: 40rpx;
    margin-top: 40rpx;
    margin-left: 20rpx;
    padding: 20rpx 40rpx;
    letter-spacing: 2px;
    color: #1D1D1D;
    border: 4rpx solid #bbb;
}
小红书小程序
{
    border: 1px；
    solid #bbb;
    color: #1d1d1d;
    font-family: PingFangSC,PingFangSC-Medium;
    font-size: 3.73333vw;
    font-weight: 500;
    letter-spacing: 2px;
    line-height: 5.33333vw;
    margin-left: 2.66667vw;
    margin-top: 5.33333vw;
    padding: 2.66667vw 5.33333vw;
    --ide-font-size: 28rpx;
    --ide-line-height: 40rpx;
    --ide-margin-left: 20rpx;
    --ide-margin-top: 40rpx;
    --ide-padding: 20rpx 40rpx;
}

**Comment by hhuwc** [comment]
border 样式不一样 有什么条件编译嘛？

**Comment by badKid1109** [comment]
> border 样式不一样 有什么条件编译嘛？

不好意思，border都是border: 4rpx solid #bbb;，刚才测试改了下写死1px样式差不多。，代码就一套，左右边距也有区别的，小红书都换行了

**Comment by hhuwc** [comment]
回复这是正常现象，原因是平台rpx 实现方式会产生细微偏差

在 412px 屏幕上，1rpx = 412px / 750 = 0.5493px，80rpx理论上应该渲染出 80 * 0.5493 = 43.944px

微信：实际只渲染出43px
小红书：渲染出44px

正是这些差异累计导致样式的偏差
