### ISSUE TITLE
mac系统升级小红书开发工具后，出现无法创建新项目

### ISSUE THREAD

**Issue by skyhotspur** [redengineer/redmini#1396]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
宋城旅游

## 平台
IDE

## 小红书开发者工具版本
2.0.18

## 基础库版本
v3.101.0

## 发生问题的时间
2024-08-07 14:08:18 至 2024-08-07 16:08:18

## 问题描述
Mac Studio Apple M2 Ultra mac os 系统版本：14.6 (23G80)

最初安装的IDE版本是2.0.17，今天根据提示升级到v2.0.18后, 创建新项目始终无法成功，一直提示：创建项目失败:ENOENT: no such file or directory, stat &#x27;/var/folders/gm/f0ct89495gs_4prr3wyc5tj40000gn/T/xhs-miniprogram&#x27;

这也很尴尬，我选择的都是当前用户的目录，也不会涉及到root用户的目录层级

## 期望结果
可以正常完成新项目的创建

## 重现步骤和复现问题的最小demo Github链接
1、打开小红书开发者工具，根据升级提示，从2.0.17完成升级到2.0.18，根据流程进行了重新打开，版本也正常升级到了2.0.18

2、出现一个二维码要求登录页面，通过小红书扫码完成登录。

3、创建新项目，填写符合要求的项目名称，和选择项目目录后，以及输入APPID后，点击“新建” ，提示：创建项目失败:ENOENT: no such file or directory, stat &#x27;/var/folders/gm/f0ct89495gs_4prr3wyc5tj40000gn/T/xhs-miniprogram&#x27;

**Comment by skyhotspur** [comment]
各种卸载重装都试过，万能的重启电脑大法都试过了，都不行

创建新项目操作截图：
![3](https://github.com/user-attachments/assets/6fb28547-f655-41be-9666-dfc35aace10e)

![002](https://github.com/user-attachments/assets/4f1f51a0-2731-4c0c-a7c2-3b0128c2170f)

**Comment by mmmml-zhao** [comment]
找到你截图提示的地址，把里面的文件复制一份出来就可以了。
<img width="325" alt="image" src="https://github.com/user-attachments/assets/ad8668ab-d5e7-43e4-ac0d-e72eb1801528">

**Comment by yujon** [comment]
问题收到，会发个bugfix版本修复

**Comment by skyhotspur** [comment]
> 找到你截图提示的地址，把里面的文件复制一份出来就可以了。 <img alt="image" width="325" src="https://private-user-images.githubusercontent.com/25151442/355748571-ad8668ab-d5e7-43e4-ac0d-e72eb1801528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTQzOTIsIm5iZiI6MTcyMzE5NDA5MiwicGF0aCI6Ii8yNTE1MTQ0Mi8zNTU3NDg1NzEtYWQ4NjY4YWItZDVlNy00M2U0LWFjMGQtZTcyZWIxODAxNTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYmQ0NmRmYzY4NjEyMWI1ZGUyOWYxNTk4MWU2NzRiZjYxZjZmNTA0YzJkZTU1MmYxNWRiY2VjMGFmMTQ2ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cN3LgUOT9QiMJvUPeahkbYIK7QOybrh9K3n1sxWyZU">

@mmmml-zhao 这个路径本身就不存在，即使我本地用权限创建了这个目录，创建项目还是会报错，报文件读写权限问题

![WX20240809-170503](https://github.com/user-attachments/assets/4456bdc7-a17f-4ab5-bc32-4f55369bbbb3)
