### ISSUE TITLE
预览模式，真机第一次扫码显示的不是最新的小程序代码，需第二次扫码才可以正常显示

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#14]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.22.2
## 期望结果 和 实际结果(必填)
希望每次扫码出来的小程序都是最新的代码

**Comment by Edge00** [comment]
我这边用 IDE 1.59.23-beta.22，iOS 平台 v7.36 的客户端，第一次预览符合预期，修改内容后再点击预览，客户端能够正确显示变更的部分，请问你这边是必现吗？
