### ISSUE TITLE
requestOrderPayment 调用成功 无法进入支付宝支付

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#140]
## 系统环境(必填[多选]) +
- [ x ] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ x ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ x ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ x ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.48
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/49746060/180399675-5c212994-75de-44a8-9df0-9b0e730463af.png)
调用此requestOrderPayment API 成功后 进入下面页面 无法进行点击等任何操作
![image](https://user-images.githubusercontent.com/49746060/180399864-c270ebb7-9235-455f-aadc-812332244af5.png)

## 期望结果 和 实际结果(必填) +
希望直接能跳支付宝支付
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
1.手机安装了支付宝APP吗？
2.弹框请求跳转支付宝，是不是点了拒绝？

**Comment by collincheng** [comment]
@AngryBrotherXiang 无弹框提示 手机安装了支付宝App

https://user-images.githubusercontent.com/49746060/180401343-e743ae2a-3ec9-48ba-9f1c-c2ce8b8c6cde.mp4

**Comment by AngryBrotherXiang** [comment]
这个用的是支付宝间接支付，iOS 7.50版本开始支持，7.50版本以下，请用支付宝直接支付！
