### ISSUE TITLE
input获取焦点之后键盘弹起样式错乱

### ISSUE THREAD

**Issue by zhouhaipeng** [redengineer/redmini#1400]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
惜食魔法袋

## 平台
IOS, Android

## 小红书版本信息
8.64
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-08 10:23:05 至 2024-08-08 10:23:05

## 问题描述
input获取焦点之后键盘弹起样式错乱，设置adjust-position的值为true或false没有任何变化

## 期望结果
input获取焦点之后键盘弹起样式不错乱，希望可以解决，目前微信，支付宝，抖音小程序都可正常

## 重现步骤和复现问题的最小demo Github链接
随便一个input或者textarea都会引起这个问题，问题图片我会贴在评论处，图片内容依次是小红书安卓端，小红书ios端，微信小程序，支付宝小程序，我已经提了好几个issue，严重影响开发效率，希望可以得到回复，谢谢。

![xhsandroid](https://github.com/user-attachments/assets/6424b6b6-035a-457f-99c1-cf81b01371cf)
![xhsios](https://github.com/user-attachments/assets/6d356aab-c252-4766-816a-4a0927074338)
![wx](https://github.com/user-attachments/assets/969c52c6-e414-4c5e-b1a6-e7030e935748)
![alipay](https://github.com/user-attachments/assets/720feef8-d954-4cad-aba0-2b057b921b53)

**Comment by jzhmcoo1** [comment]
adjust-position需要等同层输入组件上线后才能支持

**Comment by zhouhaipeng** [comment]
> adjust-position需要等同层输入组件上线后才能支持
如果上线之后我这个问题可以解决吗？希望可以验证一下啊，谢谢

**Comment by zhouhaipeng** [comment]
这个问题并没有解决，为什么要关闭呢

**Comment by Hubmeat** [comment]
> 这个问题并没有解决，为什么要关闭呢

您好，这个属性是同层组件的属性，麻烦重新提一个新的需求：
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/177674d4-11b0-4a3a-9cb7-11c4967b5c0b">

标题可以写「期望支持 input 同层渲染组件」，才能排期支持
