### ISSUE TITLE
猫眼小程序授权登录获取openid大量报错

### ISSUE THREAD

**Issue by OmMaBaMiHong** [redengineer/redmini#1402]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
猫眼

## 平台
IOS, Android

## 小红书版本信息
8.30
 
## 基础库版本
v3.101.0

## 发生问题的时间 
2024-08-07 16:52:11 至 2024-08-08 17:44:11

## 问题描述
获取openid接口大量报错：
接口：https://miniapp.xiaohongshu.com/api/rmp/session
入参出参case：
params:{access_token&#x3D;305597bcc2974b5db049d66c346f2126, code&#x3D;77d472508c97439693a70330457480c3, appid&#x3D;62c65ac8b7945e0001577f34}, resultJson:{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;应用访问令牌不匹配&quot;,&quot;code&quot;:410101}

## 期望结果
返回正常结果中有openid

## 重现步骤和复现问题的最小demo Github链接
小红书，猫眼电影，点击店铺，登录猫眼小程序授权登录发生报错，，影响时间1小时左右2024-08-07 16:52:12 至 2024-08-07 17:44:38

**Comment by OmMaBaMiHong** [comment]
发生该问题原因是什么？

**Comment by Tokysky** [comment]
哈喽，经过日志排查失败原因分2个阶段。
第一个阶段是从16:50开始，因为一个服务商大量操作商品导致请求量太大，触发了商品侧的限流，导致请求失败（从日志上看62c65ac8b7945e0001577f34当时是在上传商品）
第二个阶段token 305597bcc2974b5db049d66c346f2126生成时间是16点，过期时间大约是17:00，过期之后再使用就会返回应用访问令牌不匹配
