### ISSUE TITLE
滑动自定义弹窗的时候，底部页面跟随滑动

### ISSUE THREAD

**Issue by zhouhaipeng** [redengineer/redmini#1409]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
惜食魔法袋

## 平台
Android

## 小红书版本信息
8.64
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-08-09 09:36:36 至 2024-08-09 09:36:36

## 问题描述
滑动自定义弹窗的时候，弹窗内的内容不滑动，底部页面跟随滑动

## 期望结果
滑动自定义弹窗的时候，弹窗内的内容要滑动，底部页面滑不滑动无所谓

## 重现步骤和复现问题的最小demo Github链接
滑动自定义弹窗的时候，弹窗内的内容要滑动，底部页面滑不滑动无所谓，只有底部页面在最上方的时候，滑动自定义弹窗才会有这种现象，具体表现见下方视频

https://github.com/user-attachments/assets/83c5af59-f613-43c4-8b08-927c909db43e

**Comment by xutm** [comment]
xhs?.setBodyStyle({
        style: "overflow: hidden;",
      });

**Comment by zhouhaipeng** [comment]
> xhs?.setBodyStyle({ style: "overflow: hidden;", });

可以了，谢谢
