### ISSUE TITLE
小红书小程序是否支持 new Date();的使用

### ISSUE THREAD

**Issue by blackbird12138** [redengineer/redmini#1410]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
容量互娱

## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.101.0

## 发生问题的时间 
2024-08-09 10:40:19 至 2024-08-09 10:40:19

## 问题描述
    ,-[[36;1;4md:\小程序项目\mini-app-xhs\components\collectPopup\collectPopup.js[0m:88:1]
 [2m88[0m |         let isXjcApp &#x3D; xhs.getStorageSync(&#x27;isXjcApp&#x27;);
 [2m89[0m |         let sence &#x3D;  app.globalData.appScene;
 [2m90[0m |         let tempXinshou &#x3D; 1;
 [2m91[0m |         let nowDate &#x3D; new Date();
    : [31;1m                           ^^^^[0m

## 期望结果
小红书小程序是不支持new Date();语法吗？

## 重现步骤和复现问题的最小demo Github链接
    ,-[[36;1;4md:\小程序项目\mini-app-xhs\components\collectPopup\collectPopup.js[0m:88:1]
 [2m88[0m |         let isXjcApp &#x3D; xhs.getStorageSync(&#x27;isXjcApp&#x27;);
 [2m89[0m |         let sence &#x3D;  app.globalData.appScene;
 [2m90[0m |         let tempXinshou &#x3D; 1;
 [2m91[0m |         let nowDate &#x3D; new Date();
    : [31;1m                           ^^^^[0m

**Comment by Hubmeat** [comment]
支持的，遇到什么问题了？

**Comment by hhuwc** [comment]
ide 什么版本

**Comment by hhuwc** [comment]
发现了 ，你的这个等于号 前后有特殊空格字符，删除就好了，编辑器应该有提示

**Comment by blackbird12138** [comment]
> 发现了 ，你的这个等于号 前后有特殊空格字符，删除就好了，编辑器应该有提示

哦哦 还真是 谢谢已解决

**Comment by hhuwc** [comment]
done
