### ISSUE TITLE
模拟器 checkbox 失效

### ISSUE THREAD

**Issue by yangyonghong** [redengineer/redmini#1412]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
秀动

## 平台
IDE

## 小红书开发者工具版本
2.0.18

## 基础库版本
v3.100.0

## 发生问题的时间
2024-08-09 14:53:29 至 2024-08-09 14:53:29

## 问题描述
使用IDE模拟器 checkbox点击无效，真机正常。

## 期望结果
使用IDE模拟器 checkbox能正常使用

## 重现步骤和复现问题的最小demo Github链接
使用checkbox组件，在模拟器上运行，点击组件，无选中状态

**Comment by yujon** [comment]
感觉反馈，我们排期修复

**Comment by yangyonghong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
