### ISSUE TITLE
input设置value原始值，在输入汉字不对

### ISSUE THREAD

**Issue by zhouhaipeng** [redengineer/redmini#1413]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
惜食魔法袋

## 平台
Android, IDE

## 小红书版本信息
8.64
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-08-09 16:20:22 至 2024-08-09 16:20:22

## 问题描述
input设置value原始值，在输入汉字不对

## 期望结果
input设置value原始值，在输入汉字显示正常

## 重现步骤和复现问题的最小demo Github链接
给input组件设置默认值value&#x3D;&quot;{{xx}}&quot;之后输入汉字不正确，具体表现如下视频

https://github.com/user-attachments/assets/b5dc945a-f95b-4a3f-8980-0fa4eb1ae6d2

**Comment by jzhmcoo1** [comment]
输入型组件已经在 bugfix 了，预计 8.50 上线

**Comment by mmmml-zhao** [comment]
> 输入型组件已经在 bugfix 了，预计 8.50 上线



请问这个问题 bugfix 好了吗？
ide里，输入中文貌似还是有问题，只有最后一个字母在输入法里，按数字键选择文字会直接把数字追加到字符串末尾。
```html
<input style="border: 1px solid red;" value="{{valueTest}}" bindinput="changeValueTest"></input>
```
```js
{
 data: {
    valueTest: ''
  },
  methods:{
    changeValueTest(e){
      console.log(e)
      this.setData({
        valueTest: e.detail.value
      })
    }
  }
}

```
https://github.com/user-attachments/assets/12d2f0a2-1b85-4f97-84f9-b8c48e9c1e66

**Comment by jzhmcoo1** [comment]
> 请问这个问题 bugfix 好了吗？

修复了，都跟版 850 上线，基础库是 3.102.0，目前还未发布

**Comment by zhouhaipeng** [comment]
这个也没有修复呢？为什么都close了呢

**Comment by Hubmeat** [comment]
> 都跟版 850 上线，基础库是 3.102.0，目前还未发布

850 版本已支持，对应基础库是 3.102.0，可以发布后再验证下，如果还有问题，可以在重新打开该问题
