### ISSUE TITLE
运行后bug

### ISSUE THREAD

**Issue by blackbird12138** [redengineer/redmini#1415]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
容量互娱

## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.101.0

## 发生问题的时间 
2024-08-09 16:43:22 至 2024-08-09 16:43:22

## 问题描述
load page module has uri error: missing route resource, route: pages/fx_xjc/fx_xjc
70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2 [service/package_route_asset_missing]
v @ 70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2
70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2 URIError: load page module has uri error: missing route resource, route: components/shareBtn/shareBtn
很多路径报这个错

## 期望结果
解决当前问题 还有xhs:for语法 为什么 item in 3 会出现17个？

## 重现步骤和复现问题的最小demo Github链接
load page module has uri error: missing route resource, route: pages/fx_xjc/fx_xjc
70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2 [service/package_route_asset_missing]
v @ 70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2
70f798f5-73c1-4cf6-9b05-8d657a8ea18b:2 URIError: load page module has uri error: missing route resource, route: components/shareBtn/shareBtn
很多路径报这个错

**Comment by hhuwc** [comment]
item in 3 是vue的语法
小程序是 xhs:for 、xhs:for-item、 xhs:for-index 、xhs:key  配合使用的

**Comment by blackbird12138** [comment]
> item in 3 是vue的语法

路径这个是什么问题啊？

**Comment by blackbird12138** [comment]
![image](https://github.com/user-attachments/assets/09d0a3a6-688e-4706-8aa0-c9669270b21b)

**Comment by blackbird12138** [comment]
我看咱们的文档说 wx:for item从0开始 xhs:for  item是从1开始 那之前的数组第一项 不是循环不到了吗？

**Comment by hhuwc** [comment]
组件找不到 建议更新到我们最新的ide, 看看组件格式路径配置是否正确，ide会有检验

**Comment by blackbird12138** [comment]
> 组件找不到 建议更新到我们最新的ide, 看看组件格式路径配置是否正确，ide会有检验

嗯 是的 我用基础库2.0构架编译就没这个路径的问题了  。我上述的问题可以解释一下吗？ wxfor 和 xhs:for的那个

**Comment by hhuwc** [comment]
`<view xhs:for="{{2}}">
  {{item}}
</view>`

表现跟微信确实有差异，然而不管是微信和小红书 都不建议直接遍历 字符串，数字，应该遍历数组

**Comment by hhuwc** [comment]
另外开启2.0 架构请将ide 更新到 2.0.18 版本及以上

**Comment by blackbird12138** [comment]
> 另外开启2.0 架构请将ide 更新到 2.0.18 版本及以上

他说2.0.17是最新了

**Comment by blackbird12138** [comment]
> 另外开启2.0 架构请将ide 更新到 2.0.18 版本及以上

好像不太对 开2.0架构后 我的 页面都不出来了，1.0页面是出来的 只是路径报错

**Comment by blackbird12138** [comment]
> > 另外开启2.0 架构请将ide 更新到 2.0.18 版本及以上
> 
> 好像不太对 开2.0架构后 我的 页面都不出来了，1.0页面是出来的 只是路径报错

mp-service.js:1 逻辑层错误： Error: 
        Miniapp Container Startup Fail, missing renderer~

**Comment by Hubmeat** [comment]
您好，这个问题现在解决了吗？

**Comment by hhuwc** [comment]
请问使用的IDE 版本是多少呢？

**Comment by hhuwc** [comment]
请将IDE 右上角 详情 -> 本地设置 截图贴一下
