### ISSUE TITLE
急急急、mac版本xhs.mpide-2.0.18没有担保支付方法，windows版本xhs.mpide-2.0.17没有担保支付方法

### ISSUE THREAD

**Issue by wangsheng2012** [redengineer/redmini#1416]
## Issue类型
feature

## 所属的服务商
宋城旅游

## 这个功能解决的问题
急急急，mac 最新版本xhs.mpide-2.0.18没有担保支付方法，windows最新版本xhs.mpide-2.0.17没有担保支付方法，开发文档：https://miniapp.xiaohongshu.com/docs?path&#x3D;/docs/api/requestGuaranteeOrderPayment

**Comment by leeligang1027** [comment]
暂不支持，请关注开放平台文档中心！
