### ISSUE TITLE
变量名 存在 `void`时，该字段将失效

### ISSUE THREAD

**Issue by mmmml-zhao** [redengineer/redmini#1418]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
德比

## 平台
IDE

## 小红书版本信息
2.0.20
 
## 基础库版本
v3.84.1

## 发生问题的时间 
2024-08-12 09:47:24 至 2024-08-12 09:47:24

## 问题描述
当变量名存在void（例如 voidText,voidIcon）时，该字段在xhsml里无法访问，对应处的逻辑无法执行。

## 期望结果
不能用的话，文档上体现一下哪些关键字在变量名内不给用吧。

## 重现步骤和复现问题的最小demo Github链接
在js文件 data内声明 变量 voidText: &quot;voidText&quot;, xhsml内使用voidText

**Comment by hhuwc** [comment]
收到，我们后续修复一下这个bug
