### ISSUE TITLE
input maxlength 设置为-1时无法输入

### ISSUE THREAD

**Issue by mmmml-zhao** [redengineer/redmini#1419]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
德比

## 平台
IDE

## 小红书版本信息
2.0.20
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-08-12 13:55:34 至 2024-08-12 13:55:34

## 问题描述
给input设置 maxlength 后，input 无法输入

## 期望结果
按官方文档描述即可。

## 重现步骤和复现问题的最小demo Github链接
```html
   <input placeholder="占位文字" maxlength="{{-1}}" placeholder-style="color: #3333334D;" />

```

**Comment by jzhmcoo1** [comment]
什么业务场景下，需要设置为 -1，期望是什么表现

**Comment by mmmml-zhao** [comment]
> 什么业务场景下，需要设置为 -1，期望是什么表现

<img width="860" alt="image" src="https://github.com/user-attachments/assets/0eab9755-8e95-4c11-b071-bab27a4d5b82">

正在将微信小程序原生代码写的的组件库搬到小红书，这里 maxlength默认设置的-1，不限制输入长度。

**Comment by jzhmcoo1** [comment]
好的收到，这个 bug 我们排期修复下

**Comment by Hubmeat** [comment]
> 3.102.x 基础库版本已支持
