### ISSUE TITLE
小红书私信卡片跳转商品白屏

### ISSUE THREAD

**Issue by Wang-Xijie** [redengineer/redmini#142]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.48.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如： +
 +
## 期望结果 和 实际结果(必填) +
问题描述：私信发送商品卡片，点击卡片跳转白屏
appid：621f7d3573f8b60001da143a
手机机型：iphone12
小红书版本号 7.48.1 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
目前发现仅 iphone12 最新版本出现这个问题,怀疑新版本适配问题

**Comment by haojiasheng** [comment]
补充下：
appuid：5fc273d4000000000101e278

商家一直重试都不行




https://user-images.githubusercontent.com/33249100/180600880-0b2bf2fe-7139-453a-a549-b3317ac6d73c.mp4

**Comment by Hubmeat** [comment]
可以给一下问题发生的详细时间段

**Comment by Hubmeat** [comment]
发生的时间是 2022-07-26 17:50:00 - 2022-07-26 17:52:00 是吗？

**Comment by Hubmeat** [comment]
目前通过 748， 749 多台 ios 设备未复现这个问题，私信、店铺入口均可正常打开小程序。

723 的日志已经失效，可以和用户做如下确认：

1、尝试重启、升级新版本 app, 看问题是否可以解决
2、如果依然存在私信入口白屏的情况，可以再次录屏，补充在这个 Issue 下，我们可协助按照最新日志进行排查
