### ISSUE TITLE
有input的页面，点击input外的区域会自动获取焦点

### ISSUE THREAD

**Issue by zhouhaipeng** [redengineer/redmini#1420]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
惜食魔法袋

## 平台
Android

## 小红书版本信息
8.48
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-12 17:14:21 至 2024-08-12 17:14:21

## 问题描述
有input的页面，点击input外的区域会自动获取焦点，点击vConsole也会获取焦点

## 期望结果
有input的页面，点击input外的区域不会自动获取焦点，点击vConsole也不会获取焦点

## 重现步骤和复现问题的最小demo Github链接
具体表现看下方视频，只有android会有这种情况，点击其他区域之后会先获得焦点，然后迅速失去焦点

https://github.com/user-attachments/assets/28018b54-5d44-47f6-8f9d-9a3a2ff37bac

**Comment by jzhmcoo1** [comment]
如何访问你们的小程序？我们看下

**Comment by zhouhaipeng** [comment]
> 如何访问你们的小程序？我们看下

还没上线，需要提供小红书号，把你 添加到体验者

**Comment by jzhmcoo1** [comment]
小红书号 3584471543

麻烦给一个二维码

**Comment by zhouhaipeng** [comment]
> 小红书号 3584471543
> 
> 麻烦给一个二维码

![WechatIMG15](https://github.com/user-attachments/assets/28bc2c16-865b-4613-ab7a-3b2e86879ead)

**Comment by jzhmcoo1** [comment]
focus 属性设置为 false 试试呢

**Comment by zhouhaipeng** [comment]
> focus 属性设置为 false 试试呢

可以了，谢谢

**Comment by jzhmcoo1** [comment]
好的
