### ISSUE TITLE
商家无法解绑目前的服务商（订单已履约完毕）

### ISSUE THREAD

**Issue by qiuqiu1203** [redengineer/redmini#1421]
## Issue类型
operator

## 问题模块
小程序解绑服务商

## 所属的服务商
直客通

## 小红书版本信息
4347

## 运营场景描述
解绑商家对目前服务商的授权，商家需要重新授权给新的服务商 

## 用户ID 
5b58069611be107f2668f90d

## 发生问题的时间 
2024-07-01 00:00:00 至 2024-08-12 11:29:13

## 期望结果
解绑商家对目前服务商的授权，商家需要重新授权给新的服务商

## 业务基础信息（选填）
小程序APPID：62f0cc994440da0013ca148b

**Comment by leeligang1027** [comment]
已处理 可以进行授权
