### ISSUE TITLE
onPullDownRefresh不触发

### ISSUE THREAD

**Issue by cafugiggs** [redengineer/redmini#1423]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
叁见

## 平台
IDE, IOS, Android

## 小红书版本信息
8.48
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-13 16:40:52 至 2024-08-13 16:40:52

## 问题描述
page中配置了enablePullDownRefresh为true
但onPullDownRefresh未触发

## 期望结果
page中配置了enablePullDownRefresh为true
onPullDownRefresh触发

## 重现步骤和复现问题的最小demo Github链接
1. json中配置enablePullDownRefresh为true
2. js中加入onPullDownRefresh方法

**Comment by Hubmeat** [comment]
您好，目前没有复现这个问题
