### ISSUE TITLE
开发者工具分享功能不可用

### ISSUE THREAD

**Issue by lljj-x** [redengineer/redmini#1426]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
Klook

## 平台
IDE

## 小红书开发者工具版本
2.0.17

## 基础库版本
v3.100.0

## 发生问题的时间
2024-08-13 17:08:32 至 2024-08-13 17:08:32

## 问题描述
在开发者工具点击右上角分享报错，导致无法弹窗分享功能和执行相关回调

## 期望结果
开发者工具点击右上角能够正常分享和调试

## 重现步骤和复现问题的最小demo Github链接
1. 打开小程序
2. 点击右上角分享
3. 无法弹窗分享菜单，控制台报错
<img width="962" alt="image" src="https://github.com/user-attachments/assets/0d7b03fd-f39b-4dd8-9ef1-c67936ede208">

**Comment by ohaq-hue** [comment]
目前ide不支持分享到微信群组、朋友圈等能力，需要排期支持
