### ISSUE TITLE
小程序生命周期触发两次

### ISSUE THREAD

**Issue by WangHaoBZ** [redengineer/redmini#1427]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
宝尊

## 平台
IOS, Android

## 小红书版本信息
8.48
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-13 19:00:57 至 2024-08-13 19:00:57

## 问题描述
在真机上的log上面看到上生命周期onload，onshow，onready触发两次，导致其他例如登录方法都会被触发两次。还有切换app，onhide，onshow都会有两次触发

## 期望结果
onload，onshow，onready等生命周期正常触发

## 重现步骤和复现问题的最小demo Github链接
无
![6c0e61d2-8665-4618-a123-4b8b06a82da4](https://github.com/user-attachments/assets/1a08d4da-4251-43f8-9760-039c21caa5ee)

**Comment by WangHaoBZ** [comment]
是通过uniapp转的小红书小程序

**Comment by Hubmeat** [comment]
您好，使用的是什么版本的架构？1.0 还是 2.0

**Comment by Hubmeat** [comment]
该问题能确认下是 vconsole 打印了多次，还是 生命周期执行了多次呢？
可以通过在单一页面上，输出计数器，确认下。

**Comment by WangHaoBZ** [comment]
> 该问题能确认下是 vconsole 打印了多次，还是 生命周期执行了多次呢？ 可以通过在单一页面上，输出计数器，确认下。

用的1.0的，看了下打印计数器，是vconsole打印了两次，那问题不是很大。

**Comment by WangHaoBZ** [comment]
.
