### ISSUE TITLE
微信小程序和小红书小程序样式有差异

### ISSUE THREAD

**Issue by WangHaoBZ** [redengineer/redmini#1429]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
宝尊

## 平台
Android

## 小红书版本信息
8.48.0
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-08-14 10:40:50 至 2024-08-14 10:40:50

## 问题描述
一套代码，通过uniapp编译到微信小程序和小红书小程序后，在安卓(华为P70)表现的样式差异有点大，ios差异不大。表现差不多。但也有差异

## 期望结果
麻烦看看有没有什么办法让小红书小程序和微信小程序表现一致

## 重现步骤和复现问题的最小demo Github链接
原始代码 .item {
        font-family: PingFangSC, PingFangSC-Medium;
        font-size: 28rpx;
        font-weight: 500;
        line-height: 40rpx;
        margin-top: 40rpx;
        margin-left: 20rpx;
        padding: 20rpx 40rpx;
        letter-spacing: 4rpx;
        color: #1D1D1D;
        border: 4rpx solid #bbb;
      }
编译到微信小程序代码：font-family: PingFangSC, PingFangSC-Medium;
    font-size: 28rpx;
    font-weight: 500;
    line-height: 40rpx;
    margin-top: 40rpx;
    margin-left: 20rpx;
    padding: 20rpx 40rpx;
    letter-spacing: 4rpx;
    color: #1D1D1D;
    border: 4rpx solid #bbb;
}
编译到小红书小程序代码：
border: 0.53333vw solid #bbb;
    color: #1d1d1d;
    font-family: PingFangSC,PingFangSC-Medium;
    font-size: 3.73333vw;
    font-weight: 500;
    letter-spacing: .53333vw;
    line-height: 5.33333vw;
    margin-left: 2.66667vw;
    margin-top: 5.33333vw;
    padding: 2.66667vw 5.33333vw;
    --ide-border: 4rpx solid #bbb;
    --ide-font-size: 28rpx;
    --ide-letter-spacing: 4rpx;
    --ide-line-height: 40rpx;
    --ide-margin-left: 20rpx;
    --ide-margin-top: 40rpx;
    --ide-padding: 20rpx 40rpx;
安卓对比图
![970499720521386b295fabe6ae27b009_compress](https://github.com/user-attachments/assets/9e4f7f41-269b-44f6-a188-2e4233e21be9)
ios对比图
![dfaa5289ab8f11abc534667c76c2392f_compress](https://github.com/user-attachments/assets/c4d79625-ddae-4773-a050-66a00861001c)

**Comment by hhuwc** [comment]
同 #1390 

小程序上线了没？上线后，请给一下appid

**Comment by hhuwc** [comment]
这个问题可以咨询下微信，看着是 微信在p70 上样式跟 ios 不一致
