### ISSUE TITLE
 this.selectComponent 方法获取子组件实例对象

### ISSUE THREAD

**Issue by mmmml-zhao** [redengineer/redmini#1431]
## Issue类型
feature

## 所属的服务商
德比

## 这个功能解决的问题
解决组件间的通信。
请问  `this.selectComponent`这个api能在代码中使用吗？
我在代码里试了下，可以获取到组件，但是文档里写着暂不支持，所以有点担心使用后会有bug。
<img width="829" alt="image" src="https://github.com/user-attachments/assets/e71ee58f-9778-43d4-8160-182a9e7a3968">
<img width="907" alt="image" src="https://github.com/user-attachments/assets/bea0d0ab-e199-4c4f-b853-1f0fbdffa1c3">

https://miniapp.xiaohongshu.com/docs?path=/docs/guide/componentEvent

**Comment by hhuwc** [comment]
支持的，文档内容有误，我们更新下
