### ISSUE TITLE
模拟器UA没有Iphone和Android等关键字，无法判断是移动端

### ISSUE THREAD

**Issue by lusoftware** [redengineer/redmini#1433]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
淘票票

## 平台
IDE

## 小红书开发者工具版本
2.0.20

## 基础库版本
v3.102.1

## 发生问题的时间
2024-08-15 10:19:12 至 2024-08-15 10:19:12

## 问题描述
模拟器user-agent没有iPhone和Android等标识，无法判断是移动端口
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) @xhs/mp-ide/2.0.20 Chrome/116.0.5845.228 Electron/26.4.0 Safari/537.36 discover/2.0.20 xhsminiapp/latest

## 期望结果
与微信小程序一致，包含iPhone、Android等标识
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1 wechatdevtools/1.06.2405020 MicroMessenger/8.0.5 webview/

## 重现步骤和复现问题的最小demo Github链接
任意项目请求

**Comment by yujon** [comment]
用的是模拟器新架构么，新架构问题已知，已修复待发布。旧模拟器架构正常

**Comment by lusoftware** [comment]
最新的2.0.20，应该是新架构吧，那我close了
