### ISSUE TITLE
调用api/rmp/qrcode/unlimited生产的二维码，扫码后生成二维码的入参scene在小程序什么地方能获取？

### ISSUE THREAD

**Issue by fuiiiiiii** [redengineer/redmini#1447]
## Issue类型
bug

## 问题模块
小程序服务(文档平台)
 
## 所属的服务商
领克

## 平台
IOS, Android, IDE

## 小红书版本信息
8.49.1
 
## 基础库版本
v3.99.1

## 发生问题的时间 
2024-08-22 08:52:29 至 2024-08-22 08:52:29

## 问题描述
https://miniapp.xiaohongshu.com/api/rmp/qrcode/unlimited接口生成的二维码，其中的scene在小程序中如何获取？文档没有找到相关说明，因为二维码只能打开生成环境，不允许在线上验证

## 期望结果
相关人员给出获取方式，文档没有写清楚

## 重现步骤和复现问题的最小demo Github链接
1.调用https://miniapp.xiaohongshu.com/api/rmp/qrcode/unlimited（获取不限制的小程序二维码），body中scene传某个值
2.扫描1中生成的二维码打开小程序，如何获取到二维码中的scene值？

**Comment by xutm** [comment]
onLaunch query.sence
