### ISSUE TITLE
在没有appid的情况下能够给开发者一个临时的appid

### ISSUE THREAD

**Issue by bruce940910** [redengineer/redmini#1448]
## Issue类型
feature

## 这个功能解决的问题
在没有认证入住平台前，希望能让开发者能够有权限编辑分配的临时appid, 可以让开发者进行功能验证，简单体验IDE的功能，具体可以参考微信小程序给没有开发容器的个人开发者提供的临时容器，微信小程序的代码片段功能

**Comment by ohaq-hue** [comment]
暂时不支持该能力
