### ISSUE TITLE
input输入框输入内容被清空，无法使用

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#1449]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
百居易

## 平台
IOS

## 小红书版本信息
8.50
 
## 基础库版本
v3.93.2

## 发生问题的时间 
2024-08-23 14:58:20 至 2024-08-23 14:58:20

## 问题描述
input输入框输入内容被清空，confirm-type设置为search输入法右下角按钮也没有变成搜索字样，目前处于完全不可用状态，我在本地开发者工具测试了最新的3.102.3基础库，问题依旧存在，直接无法输入了

https://github.com/user-attachments/assets/eecdcb20-2ad5-4418-82f1-73f98b2657d8

## 期望结果
input输入框可以正常使用

## 重现步骤和复现问题的最小demo Github链接
自己打开输入框试试就知道了

**Comment by jzhmcoo1** [comment]
Hello，请问你们的使用方式是什么样的
input 目前在传入 value 的绑定的时候，需要在 bindinput 下同步 setData 使用
