### ISSUE TITLE
小程序申清切换担保支付，商品已同步到小红书，但仍提示商品收款方式和商品类型同步小红书

### ISSUE THREAD

**Issue by 350050183** [redengineer/redmini#1453]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
广州三毛信息科技有限公司

## 平台
IOS, Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.104.0

## 用户ID 
22222

## 发生问题的时间 
2024-08-27 14:55:20 至 2024-08-27 14:55:20

## 问题描述
专业号后台一小程序一交易能力一切换成担保支付一确认一弹窗提示“请联系技术服务商将商品收款方式和商品类型同步至小红书”。小程序ID：6602796538d1a400440b2688

## 期望结果
自开发如何解决商品收款方式和商品类型同步问题，需在27号提交切换担保交易审核。

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by YuYongzhi** [comment]
@350050183 这个问题是如何解决的？
