### ISSUE TITLE
设置navigationStyle为default的dsl原生页面，跳转到webview h5页面后返回，页面顶部被截断

### ISSUE THREAD

**Issue by zhubeniii** [redengineer/redmini#1455]
![IMG_0351](https://github.com/user-attachments/assets/00c61b54-323c-4252-ae87-99532acaba45)
![IMG_0352](https://github.com/user-attachments/assets/02bf049d-3636-48e5-9136-2f48b599163e)
## Issue类型
bug

## 问题模块
小程序容器(Android)
 
## 所属的服务商
阿里影业

## 平台
Android

## 小红书版本信息
8.50.0
 
## 基础库版本
v3.104.0

## 发生问题的时间 
2024-08-27 15:13:20 至 2024-08-27 15:13:20

## 问题描述
设置navigationStyle为default的dsl原生页面，跳转到webview h5页面后返回，页面顶部被截断。看起来像是跳转后返回，dsl原生页面被视为设置了navigationStyle为custom，但页面导航栏仍存在，看起来就是被截断，且无法滚动上去。

## 期望结果
页面顶部不要被截断，正常展示导航栏和完整页面。

## 重现步骤和复现问题的最小demo Github链接
设置navigationStyle为default的dsl原生页面，跳转到webview h5页面后返回。

**Comment by taiyiandr** [comment]
跟8.54版本修复。预计全量时间在9月20左右。
