### ISSUE TITLE
商品同步-生活服务 接口报错

### ISSUE THREAD

**Issue by xinhui01** [redengineer/redmini#1459]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
广州三毛信息科技有限公司

## 平台
IOS, Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.104.0

## 发生问题的时间 
2024-08-27 17:44:31 至 2024-08-27 17:48:18

## 问题描述
appid:6602796538d1a400440b2688
参数
{
	&quot;out_product_id&quot;: &quot;255&quot;,
	&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何&quot;,
	&quot;short_title&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何&quot;,
	&quot;desc&quot;: &quot;精品小团 | 敦煌文化 | 丝路文明&quot;,
	&quot;path&quot;: &quot; /package/product/pages/detail/detail2?id&#x3D;255&quot;,
	&quot;top_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
	&quot;category_id&quot;: &quot;6522996c363e0d00012e3bda&quot;,
	&quot;biz_create_time&quot;: 1724750864,
	&quot;biz_update_time&quot;: 1724750864,
	&quot;skus&quot;: [
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12029&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何上午场9:30-【拼团】讲解（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 18800,
			&quot;sale_price&quot;: 16800,
			&quot;status&quot;: 1
		},
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12030&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何上午场9:30-【私家团】讲解1-3人（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 70000,
			&quot;sale_price&quot;: 68000,
			&quot;status&quot;: 1
		},
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12031&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何上午场9:30-【私家团】讲解4-6人（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 90000,
			&quot;sale_price&quot;: 88000,
			&quot;status&quot;: 1
		},
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12032&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何下午场14:00-【拼团】讲解（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 18800,
			&quot;sale_price&quot;: 16800,
			&quot;status&quot;: 1
		},
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12033&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何下午场14:00-【私家团】讲解1-3人（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 70000,
			&quot;sale_price&quot;: 68000,
			&quot;status&quot;: 1
		},
		{
			&quot;out_sku_id&quot;: &quot;tour2_sale_12034&quot;,
			&quot;name&quot;: &quot;敦煌市博物馆 | 华戎交汇，盛世几何下午场14:00-【私家团】讲解4-6人（不含票）&quot;,
			&quot;sku_image&quot;: &quot;https://images.sanmaoyou.com/img/new_images/2024-08/7e77035811fdbf569ac4a7fbd3d654eb.jpg&quot;,
			&quot;origin_price&quot;: 90000,
			&quot;sale_price&quot;: 88000,
			&quot;status&quot;: 1
		}
	],
	&quot;product_type&quot;: 1,
	&quot;settle_type&quot;: 1
}
返回结果
{
	&quot;data&quot;: null,
	&quot;success&quot;: false,
	&quot;msg&quot;: &quot;系统异常，请稍后重试&quot;,
	&quot;code&quot;: 2
}

## 期望结果
同步成功,可以成功切换到担保支付

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by uudui** [comment]
已经线下通过群方式解决

**Comment by YuYongzhi** [comment]
> 已经线下通过群方式解决

具体是如何解决的？是需要小红书配置，还是需要自己开发问题？
