### ISSUE TITLE
showToast 在安卓下提示两次

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#146]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ x ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ x ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ x ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.48
## 重现步骤 和 复现问题的最小demo Github链接 +
showToast 在安卓下提示两次
![image](https://user-images.githubusercontent.com/49746060/180979679-6d399e01-63b4-43b8-af1a-1a72eaafb6f3.png)

https://user-images.githubusercontent.com/49746060/180979871-42c2f1be-8a78-4b9c-806e-62bf0369779c.mp4

## 期望结果 和 实际结果(必填) +
只提示一次
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
两个 toast 的样式并不相同，将 success 回调内的 toast 调用先删除试试看。

**Comment by collincheng** [comment]
@Hubmeat 确实是安卓复制的API的自带了提示 但这个问题还是要IOS和安卓表现一致 且其他渠道的小程序复制不自带提示

**Comment by Hubmeat** [comment]
好的，我和端侧同学同步下，你们先兼容

**Comment by collincheng** [comment]
@Hubmeat 这个关了吧 现在知识ide上没有展示 真机表现正常
