### ISSUE TITLE
申请小游戏自开发权限，游戏名称《动物夜市》，微信小游戏流水过亿

### ISSUE THREAD

**Issue by Bigz256** [redengineer/redmini#1467]
## Issue类型
feature

## 所属的服务商
长沙天创文化传播有限公司

## 这个功能解决的问题
申请小游戏自开发权限，游戏名称《动物夜市》，微信小游戏流水过亿

**Comment by ohaq-hue** [comment]
暂不支持，可关注后续平台类目开放情况
