### ISSUE TITLE
小程序提审核时被退回

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1468]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
上海卡里司马科技有限公司

## 平台
IDE

## 小红书版本信息
8.0.52
 
## 基础库版本
v3.105.0

## 发生问题的时间 
2024-09-04 09:17:00 至 2024-09-04 09:17:00

## 问题描述
小程序在提交代码审核后，被退回，退回原因是“白屏”。但我从手机上看小程序，是可以打开以及正常浏览的，并没有白屏

## 期望结果
需要审核通过，并让我可以正常发布小程序上线

## 重现步骤和复现问题的最小demo Github链接
具体见截图

**Comment by Murphy3389** [comment]
<img width="765" alt="image" src="https://github.com/user-attachments/assets/e463515c-a39c-4017-b73b-af17413afa24">

**Comment by Murphy3389** [comment]
小程序appID：66208da77a8b91004ade0ad8
auditRuleUrl："https://miniapp.xiaohongshu.com/docs/operation/appAuditDeployRule"

**Comment by Murphy3389** [comment]
![image](https://github.com/user-attachments/assets/75b9de0e-0e07-4a72-87c2-4ac444815f0a)
我手机上都可以正常浏览，为什么审核的人说小程序白屏？需要解决

**Comment by yujon** [comment]
我们排查下

**Comment by Murphy3389** [comment]
好的，还需要我提供什么么？大概什么时间会有结果
@yujon

**Comment by yujon** [comment]
> 好的，还需要我提供什么么？大概什么时间会有结果 @yujon

已修复，请重新提审一下

**Comment by Murphy3389** [comment]
好的
