### ISSUE TITLE
scroll-view组件的scroll-with-animation scroll-left 不能同时使用

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#147]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/181411497-c18b9198-33c7-469e-8148-2acc4226036b.png)
![image](https://user-images.githubusercontent.com/63334662/181411541-45b1c3b4-fb93-41c0-a98d-866327364f5b.png)
添加scroll-with-animation 属性后 再设置scroll-left值 会导致无法再滑动回左侧
## 期望结果 和 实际结果(必填) +
scroll-with-animation scroll-left 属性能正常使用
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
![image](https://user-images.githubusercontent.com/63334662/181412126-a4adbd28-13e4-4824-b5fc-835d8fa81707.png)

**Comment by Hubmeat** [comment]
麻烦提供下这个场景的原生小程序代码片段吧（需要原生小程序的，包含示例就可以了）

**Comment by echooys** [comment]
> 麻烦提供下这个场景的原生小程序代码片段吧（需要原生小程序的，包含示例就可以了）

`<view class="index">
  <scroll-view 
    class="scroll-view" 
    show-scrollbar="{{false}}" 
    scroll-left="{{scrollLeft}}" 
    scroll-x 
    scroll-with-animation
    enable-flex> 
    <view class="item" bindtap="itemClick">1</view>
    <view class="item" bindtap="itemClick">2</view>
    <view class="item" bindtap="itemClick">3</view>
    <view class="item" bindtap="itemClick">4</view>
    <view class="item" bindtap="itemClick">5</view>
    <view class="item" bindtap="itemClick">6</view>
    <view class="item" bindtap="itemClick">7</view>
    <view class="item" bindtap="itemClick">8</view>
    <view class="item" bindtap="itemClick">9</view>
    <view class="item" bindtap="itemClick">0</view>
    <view class="item" bindtap="itemClick">2</view>
    <view class="item" bindtap="itemClick">343</view>
    <view class="item" bindtap="itemClick">4343</view>
    <view class="item" bindtap="itemClick">555</view>
    <view class="item" bindtap="itemClick">666</view>
  </scroll-view>
</view>`



`Page({
  data: {
    scrollLeft:0
  },
  itemClick(e){
    this.setData({
      scrollLeft:e.target.offsetLeft
    })
  }
})
`




`.index{
  width:100vw;
  height:100vh;
  overflow: hidden;
}
.scroll-view{
  width: 100%;
  height:40px;
  background-color:#e12160;
}
.item{
  width:320px;
  height:40px;
  box-sizing: border-box;
  padding:0 40px;
  color:#000;
  border-left:5px solid blue;
}`


https://user-images.githubusercontent.com/63334662/181426702-58564405-eb6f-411b-a249-105c989ee6ab.mp4

**Comment by Hubmeat** [comment]
您好，感谢反馈，这个问题 751 版本会进修复
