### ISSUE TITLE
uniapp的代码转小红书小程序，IDE模拟器和真机调试都正常，但是预览和体验版均无法正常运行。

### ISSUE THREAD

**Issue by antonySee** [redengineer/redmini#1477]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
uniapp

## 平台
IDE

## 小红书版本信息
v8.52
 
## 基础库版本
v3.104.0

## 发生问题的时间 
2024-09-04 16:27:16 至 2024-09-05 16:27:16

## 问题描述
uniapp的代码转小红书小程序，IDE模拟器和真机调试都正常，但是预览和体验版均无法正常运行。哪怕是基础的switchTab也无法跳转，我加了complete回掉但是没有任何打印。在打印中看到很多警告，有些是组件找不到，有些是路由问题，但是警告不是报错，而且这些在模拟器中都正常。版本是vue2+cli

## 期望结果
在真机预览中可以有更详细的错误报告。

## 重现步骤和复现问题的最小demo Github链接
可编译为微信小程序的uniapp工程编译为小红书小程序

https://gitee.com/antonyseex/demo-uni-xhs

**Comment by hhuwc** [comment]
你好请提供下 @dcloudio/uni-mp-xhs 插件版本，以及IDE 详情设置的截图

**Comment by antonySee** [comment]
> 你好请提供下 @dcloudio/uni-mp-xhs 插件版本，以及IDE 详情设置的截图

![image](https://github.com/user-attachments/assets/bb1911d7-0e94-4b52-835d-c0ff5c965da5)
![image](https://github.com/user-attachments/assets/1e57b979-148a-4468-b50c-c86d5d770593)
![image](https://github.com/user-attachments/assets/b86a74b0-0328-489f-8db5-606e2d06223b)

**Comment by hhuwc** [comment]
2.0.2-3061820230117002 所有插件都升级到这个版本

**Comment by hhuwc** [comment]
`{
  "name": "uni-app-xhs",
  "version": "0.1.0",
  "private": true,
  "scripts": {},
  "dependencies": {
    "@dcloudio/uni-app": "^2.0.2-3061820230117002",
    "@dcloudio/uni-app-plus": "^2.0.2-3061820230117002",
    "@dcloudio/uni-h5": "^2.0.2-3061820230117002",
    "@dcloudio/uni-i18n": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-360": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-alipay": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-baidu": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-jd": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-kuaishou": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-lark": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-qq": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-toutiao": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-vue": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-weixin": "^2.0.2-3061820230117002",
    "@dcloudio/uni-mp-xhs": "^2.0.2-3061820230117002",
    "@dcloudio/uni-quickapp-native": "^2.0.2-3061820230117002",
    "@dcloudio/uni-quickapp-webview": "^2.0.2-3061820230117002",
    "@dcloudio/uni-stacktracey": "^2.0.2-3061820230117002",
    "@dcloudio/uni-stat": "^2.0.2-3061820230117002",
    "@vue/shared": "^3.0.0",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.0.4",
    "@dcloudio/uni-automator": "^2.0.2-3061820230117002",
    "@dcloudio/uni-cli-i18n": "^2.0.2-3061820230117002",
    "@dcloudio/uni-cli-shared": "^2.0.2-3061820230117002",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-migration": "^2.0.2-3061820230117002",
    "@dcloudio/uni-template-compiler": "^2.0.2-3061820230117002",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.2-3061820230117002",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.2-3061820230117002",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.2-3061820230117002",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.2-3061820230117002",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.2-3061820230117002",
    "@vue/cli-plugin-babel": "~4.5.18",
    "@vue/cli-service": "~4.5.18",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "sass": "^1.49.8",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "Android >= 4.4",
    "ios >= 9"
  ],
  "uni-app": {
    "scripts": {}
  }
}
`

**Comment by antonySee** [comment]
> `{ "name": "uni-app-xhs", "version": "0.1.0", "private": true, "scripts": {}, "dependencies": { "@dcloudio/uni-app": "^2.0.2-3061820230117002", "@dcloudio/uni-app-plus": "^2.0.2-3061820230117002", "@dcloudio/uni-h5": "^2.0.2-3061820230117002", "@dcloudio/uni-i18n": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-360": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-alipay": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-baidu": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-jd": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-kuaishou": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-lark": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-qq": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-toutiao": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-vue": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-weixin": "^2.0.2-3061820230117002", "@dcloudio/uni-mp-xhs": "^2.0.2-3061820230117002", "@dcloudio/uni-quickapp-native": "^2.0.2-3061820230117002", "@dcloudio/uni-quickapp-webview": "^2.0.2-3061820230117002", "@dcloudio/uni-stacktracey": "^2.0.2-3061820230117002", "@dcloudio/uni-stat": "^2.0.2-3061820230117002", "@vue/shared": "^3.0.0", "core-js": "^3.6.5", "flyio": "^0.6.2", "vue": "^2.6.11", "vuex": "^3.2.0" }, "devDependencies": { "@dcloudio/types": "^3.0.4", "@dcloudio/uni-automator": "^2.0.2-3061820230117002", "@dcloudio/uni-cli-i18n": "^2.0.2-3061820230117002", "@dcloudio/uni-cli-shared": "^2.0.2-3061820230117002", "@dcloudio/uni-helper-json": "*", "@dcloudio/uni-migration": "^2.0.2-3061820230117002", "@dcloudio/uni-template-compiler": "^2.0.2-3061820230117002", "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.2-3061820230117002", "@dcloudio/vue-cli-plugin-uni": "^2.0.2-3061820230117002", "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.2-3061820230117002", "@dcloudio/webpack-uni-mp-loader": "^2.0.2-3061820230117002", "@dcloudio/webpack-uni-pages-loader": "^2.0.2-3061820230117002", "@vue/cli-plugin-babel": "~4.5.18", "@vue/cli-service": "~4.5.18", "babel-plugin-import": "^1.11.0", "cross-env": "^7.0.2", "jest": "^25.4.0", "mini-types": "*", "miniprogram-api-typings": "*", "postcss-comment": "^2.0.0", "sass": "^1.49.8", "sass-loader": "^8.0.2", "vue-template-compiler": "^2.6.11" }, "browserslist": [ "Android >= 4.4", "ios >= 9" ], "uni-app": { "scripts": {} } } `

我真实项目的版本是：2.0.2-4020420240722001，这个版本是否也可以呢？但是这个版本使用下来，也是同样的问题

**Comment by hhuwc** [comment]
IDE 更新到 2.0.20 关闭使用新版编译器 或者 使用新版模拟器，试试

**Comment by antonySee** [comment]
> IDE 更新到 2.0.20 关闭使用新版编译器 或者 使用新版模拟器，试试

以上方法都试过了 都不行 你可以下载我示例工程试试看呢

**Comment by hhuwc** [comment]
我这边使用 2.0.2-3061820230117002 是可以的

**Comment by antonySee** [comment]
> 我这边是可以的

奇了怪了，难道是因为小程序没有审核？或者是资料没有完善？或者小红书app是最新版本？我是ios最新，小红书版本也是最新，ide也是最新

**Comment by hhuwc** [comment]
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/dc7300c4-7169-49ba-b75a-ab060a992fd3">
试试我说的呢，
1: 插件版本全部调整为， 2.0.2-3061820230117002 

2: 关闭使用新版编译器 和 使用新版模拟器

**Comment by hhuwc** [comment]
小红书版本目前最新的是 8.51 或者 8.52 检查下是不是

**Comment by antonySee** [comment]
![image](https://github.com/user-attachments/assets/6d1ad97f-870a-42e6-83a7-72056b71cd84)


> <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/20037388/365014171-dc7300c4-7169-49ba-b75a-ab060a992fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTA4ODgsIm5iZiI6MTcyNTU5MDU4OCwicGF0aCI6Ii8yMDAzNzM4OC8zNjUwMTQxNzEtZGM3MzAwYzQtNzE2OS00OWJhLWI3NWEtYWIwNjBhOTkyZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMWE4YjM3MjcwNWY4ZjFmMDFiOGZkOTRkMGVhMWVmNDJlODQyMzg0OGY1MWIzZjc5MTdkNDI5OWJhOGVkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p5wFwQAea5k4oEVPs4rcrEAInHWsXofzBQ-gddEtGnE"> 试试我说的呢， 1: 插件版本全部调整为， 2.0.2-3061820230117002
> 2: 关闭使用新版编译器 和 使用新版模拟器
直接报错了

**Comment by antonySee** [comment]
![c16302674ad6fe0375a00b96774a33b](https://github.com/user-attachments/assets/54557f24-825c-40d4-8adf-876ea34b8600)
真机预览控制台这个报错是原因吗

**Comment by antonySee** [comment]
是不是因为我在项目根目录加了个配置的原因？
![image](https://github.com/user-attachments/assets/8ff91d38-2b16-48e5-8c30-4214ed3bb30a)
但是这个如果不加，编译出来就报这个错误
![image](https://github.com/user-attachments/assets/84332145-575d-4b80-85b5-3ef472ebb925)
 哎 真的累了啊

**Comment by antonySee** [comment]
我试了下加的vue.config.js去掉 真机预览就可以了 但是模拟器就不行了 这个咋解决啊

**Comment by antonySee** [comment]
把模拟器新架构这个选项关掉就好了 我去 
原来到底 就是因为我加的那个配置文件的问题 看来还是不能随便乱加啊

**Comment by bfc846958672** [comment]
> 把模拟器新架构这个选项关掉就好了 我去 原来到底 就是因为我加的那个配置文件的问题 看来还是不能随便乱加啊

可以调整一下上面的插件，补充一下 typeof window !== undefined 的判断
```
const webpack = require('webpack')  
module.exports = {  
    configureWebpack: {  
        plugins: [  
            new webpack.BannerPlugin({  
                banner: ` if (typeof window !== undefined && !window.navigator) { window.navigator =  { userAgent: '' } };`,  
                raw: true,  
                entryOnly: true,  
                test: /vendor\.js$/  
            }),  
        ]  
    }  
}  
```

**Comment by Superhusky** [comment]
问下解决了吗？ 我也有一模一样的问题
