### ISSUE TITLE
小红书小程序开通交易能力无法使用

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#1478]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
东拼西凑

## 平台
Android

## 小红书版本信息
8.51
 
## 基础库版本
v3.100.0

## 发生问题的时间 
2024-09-05 17:45:44 至 2024-09-05 17:45:44

## 问题描述
小红书小程序已开通交易能力,但无法调起支付界面

## 期望结果
开通交易能力后可以正常拉起支付界面

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by anaian** [comment]
![微信图片_20240905174928](https://github.com/user-attachments/assets/eb9d3b1d-97ce-46c6-9527-bfbc92036f16)

**Comment by anaian** [comment]
使用新api可以支付 xhs.requestGuaranteeOrderPayment

**Comment by zane418** [comment]
@anaian 新的API xhs.requestGuaranteeOrderPayment不是指担保支付吗？好像只有支付宝呀。想要微信支付的怎么办
