### ISSUE TITLE
页面右滑返回上一页范围太大了，导致页面中间右滑误触

### ISSUE THREAD

**Issue by fuiiiiiii** [redengineer/redmini#1482]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
8.52
 
## 基础库版本
v3.105.0

## 发生问题的时间 
2024-09-06 16:00:17 至 2024-09-06 16:00:17

## 问题描述
页面中间有滑块，在右滑时候触发框架的上一页，必须手指在滑块上停留一会再滑动，体验不是很好，其他小程序右滑返回的区间在页面边边，没有那么大范围

## 期望结果
官方能够调整优化下，并给反馈

## 重现步骤和复现问题的最小demo Github链接
页面中间右滑

**Comment by fuiiiiiii** [comment]
安卓 正常  IOS 整个页面都能右滑返回

**Comment by leeligang1027** [comment]
目前为平台规范，产品侧进行调研后进行迭代，请关注开放平台文档中心！

**Comment by youngchao** [comment]
还没解决啊
