### ISSUE TITLE
小程序deekink跳转小红书的app

### ISSUE THREAD

**Issue by ZheGeUsernameKeYiMe** [redengineer/redmini#1498]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
北京童影嘉映教育科技有限公司

## 平台
Android, IOS

## 小红书版本信息
8.53
 
## 基础库版本
v3.106.1

## 发生问题的时间 
2024-09-13 11:27:46 至 2024-09-13 11:27:46

## 问题描述
在小程序中通过deekink跳转小红书的app打开某个用户的列表页，提示“无跳转权限，请申请”，这个如何申请

## 期望结果
如何deekink跳转小红书的app，可打开怎么授权

## 重现步骤和复现问题的最小demo Github链接
在小程序中通过deekink跳转小红书的app打开某个用户的列表页，提示“无跳转权限，请申请”，这个如何申请

**Comment by Hubmeat** [comment]
用的什么方式跳转的？

**Comment by ZheGeUsernameKeYiMe** [comment]
goXhs: function (e) {
    console.log('goXhs')
    let url = e.currentTarget.dataset.url
    xhs.openXhsDeeplink({
      link: url,
      success: function (res) {
        console.log(res)
      },
      complete: function (res) {
        console.log(res)
      }
    })
  },

**Comment by Hubmeat** [comment]
openXhsDeeplink 为内部 api，一般不对外开放，如果需要用的话，可以由你们运营人员和小红书接入人员联系申请开通

**Comment by ZheGeUsernameKeYiMe** [comment]
好的谢谢

**Comment by LiuJin1203** [comment]
@ZheGeUsernameKeYiMe  您好，麻烦问一下, openXhsDeeplink API最后可以正常使用么？
