### ISSUE TITLE
xhs.requestOrderPayment 传入H5中间页是否支持引入web-view sdk 实现与小程序交互？

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#15]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书版本：v7.37.3

## 重现步骤 和 复现问题的最小demo Github链接
使用  xhs.requestOrderPayment API 配置支付h5中间页引入 web-view sdk ，无法唤起小程序页面。
![image](https://user-images.githubusercontent.com/11973539/167805907-10e74cfc-8e43-474b-a3da-95f12ce171c3.png)

## 期望结果 和 实际结果(必填)
使用  xhs.requestOrderPayment API 配置支付h5中间页支付引入 web-view sdk 实现与小程序交互，正常唤起小程序页面。

**Comment by xutm** [comment]
支持的，通过 location.url = 'xhsdiscover://'，就可以了。

https://miniapp.xiaohongshu.com/third/api-3rd-doc/rmpDeal

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/11706751/167809949-493ac158-be2f-47b6-90ea-118ef67a18f6.png">

**Comment by dandelion-Chen** [comment]
> 支持的，通过 location.url = 'xhsdiscover://'，就可以了。
> 
> https://miniapp.xiaohongshu.com/third/api-3rd-doc/rmpDeal
> 
> <img alt="image" width="1051" src="https://user-images.githubusercontent.com/11706751/167809949-493ac158-be2f-47b6-90ea-118ef67a18f6.png">

支付中间页使用 location.url = 'xhsdiscover://' 回到小红书APP 是不是行不通呢？ 在手机浏览器是可以正常唤起小红书的（如视频1），但小程序中唤起支付中间页触发并不生效（如视频2）

https://user-images.githubusercontent.com/11973539/167988077-4a5e5896-1cc8-47f7-aebf-7e409d2fe408.mp4


https://user-images.githubusercontent.com/11973539/167988209-f6217e8c-6226-4fe1-af88-746c27274449.mp4

**Comment by xutm** [comment]
> https://miniapp.xiaohongshu.com/third/api-3rd-doc/rmpDeal

交易流程图的第 19 步，关注下

「安卓微信、支付宝和 iOS 支付宝支付可直接跳回小红书小程序，
iOS 微信支付会打开浏览器，跳转到开发者 H5 支付结果页，需要开发者使用“location.url = 'xhsdiscover://'” 方式跳回小红书」

跳转回小红书，开发者仅需要关注 iOS 微信支付场景。

**Comment by xutm** [comment]
> > 支持的，通过 location.url = 'xhsdiscover://'，就可以了。
> > https://miniapp.xiaohongshu.com/third/api-3rd-doc/rmpDeal
> > <img alt="image" width="1051" src="https://user-images.githubusercontent.com/11706751/167809949-493ac158-be2f-47b6-90ea-118ef67a18f6.png">
> 
> 支付中间页使用 location.url = 'xhsdiscover://' 回到小红书APP 是不是行不通呢？ 在手机浏览器是可以正常唤起小红书的（如视频1），但小程序中唤起支付中间页触发并不生效（如视频2）
> 
>  1652326981198673.mp4 
>  1652326988255724.mp4

交易流程图的第 19 步，关注下
「安卓微信、支付宝和 i0s 支付宝支付可直接跳回小红书小程序
ios 微信支付会打开浏览器，跳转到开发者 H5 支付结果页，需要开发者使用"location.url="'xhsdiscover://" 方式跳回小红书」

跳转回小红书，开发者仅需要关注 ios 微信支付场景。

**Comment by xutm** [comment]
交易流程中，第 12 步打开开发者 h5 页面，用的是独立的 web-view 容器，没有提供 js-sdk。
