### ISSUE TITLE
支付拉起速度太慢

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#1500]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
麦西盟

## 平台
IOS, Android

## 小红书版本信息
8.53
 
## 基础库版本
v3.106.1

## 发生问题的时间 
2024-09-18 11:32:16 至 2024-09-18 11:32:16

## 问题描述
小红书支付拉起速度太慢. 原因是提交产品同步后,不能立即提交产品同步. 中间有时间差. 会提示 未知系统异常
对于订单金额不固定的产品很不友好.

## 期望结果
能缩短时间差.或者没有时间差

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by leeligang1027** [comment]
请等待商品同步成功后，再进行支付调用，后续平台将补充流程图做详细说明，请关注开放平台文档中心！
