### ISSUE TITLE
门店首图审核通过后 外网一直未更新

### ISSUE THREAD

**Issue by YRJX** [redengineer/redmini#1502]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
订单来了

## 小红书版本信息
v8.53

## 运营场景描述
小红书店铺 门店首图 

## 用户ID 
5f532d1600000000010065e5

## 发生问题的时间 
2024-09-01 00:00:00 至 2024-09-18 12:41:32

## 期望结果
替换掉门前的门店首图，更换成目前后台上传审核的图片

**Comment by leeligang1027** [comment]
提供具体问题截图 以及门店poi
