### ISSUE TITLE
使用cli上传代码，appid和上传代码秘钥都是对的，但无法上传

### ISSUE THREAD

**Issue by ljy423897608** [redengineer/redmini#1516]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
领克

## 平台
Android

## 小红书版本信息
8.42
 
## 基础库版本
v3.96.2

## 发生问题的时间 
2024-09-24 09:04:50 至 2024-09-24 09:04:50

## 问题描述
使用cli上传代码，appid和上传代码秘钥都是对的，但是报错：Error: code：-240375，msg: 获取对应账号信息失败

## 期望结果
能够使用cli发布小程序

## 重现步骤和复现问题的最小demo Github链接
const setApp &#x3D; async() &#x3D;&gt; {
await xmc.setAppConfig({
appId,
config: {
token
}
})
}

// 代码上传
const upload &#x3D; async() &#x3D;&gt; {
await xmc.upload({
project: {
projectPath: distPath,
},
version: &quot;0.0.5&quot;,
desc: &quot;预约试驾&quot;
});
}

**Comment by yujon** [comment]
确认下项目内project.config.json的appid和配置的appid一致么

**Comment by ljy423897608** [comment]
> 确认下项目内project.config.json的appid和配置的appid一致么

是对的。有的店端的小程序，至少有一个开发者，就可以通过cli上传。如果小程序一个开发者都没有，即使appid和上传小程序秘钥是对的，跟项目代码的配置也是一致，也不能通过cli上传成功。是这样的限制吗？

**Comment by yujon** [comment]
> > 确认下项目内project.config.json的appid和配置的appid一致么
> 
> 是对的。有的店端的小程序，至少有一个开发者，就可以通过cli上传。如果小程序一个开发者都没有，即使appid和上传小程序秘钥是对的，跟项目代码的配置也是一致，也不能通过cli上传成功。是这样的限制吗？

是的，目前需要获取最新开发者的信息。这个是个优化点，目前待排期支持

**Comment by thisLkk** [comment]
为什么appid与token都是正确的。上传时报cli token不匹配？
