### ISSUE TITLE
xhs.request 在ios手机接收不到header请求头的数据

### ISSUE THREAD

**Issue by 1061393172** [redengineer/redmini#1524]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
自开发

## 平台
IOS

## 小红书版本信息
8.54.1
 
## 基础库版本
v3.57.3

## 发生问题的时间 
2024-09-26 15:31:41 至 2024-09-26 15:31:41

## 问题描述
我在使用xhs.request API，ios手机向后端发送请求，后端那边接受不到请求头的数据，但是安卓手机可以

## 期望结果
获取到header请求头的数据

## 重现步骤和复现问题的最小demo Github链接
https://github.com/1061393172/xhsDemo

**Comment by hhuwc** [comment]
手机版本是多少？

**Comment by 1061393172** [comment]
17.6.1 和 17.3.1

**Comment by hhuwc** [comment]
app 版本是多少？具体是哪个请求头 没有接收到呢？

**Comment by 1061393172** [comment]
app版本号是8.54.1， 在后端的服务器上，获取不到HttpRequest的Header。实际上在前端的请求时有携带的。这种情况对于安卓手机没有影响，但IOS IPhone却不行。

**Comment by 1061393172** [comment]
我翻看了一下你们的issues，在 1071 这个issues中好像也是一样的问题

**Comment by hhuwc** [comment]
使用自定义请求头时，非标准字段 请使用 x-开头 ，另外header里面一定要是字符串，不能是其他类型

`
{
 x-login-id: '1234'
}
`

**Comment by 1061393172** [comment]
您好，我们已经排查出来了，原因是我们的header请求头的loginId传的是int类型，所以是接收不到，但是为什么安卓是没问题的，ios就有问题呢？而且微信小程序那边是没有这个问题的

**Comment by hhuwc** [comment]
ios miss 了这个case
