### ISSUE TITLE
已解除与服务商的授权但是依旧显示还在授权 没有域名与推送板块

### ISSUE THREAD

**Issue by linyyj** [redengineer/redmini#1528]
## Issue类型
operator

## 问题模块
小程序授权已解除 但依

## 所属的服务商
路客云

## 小红书版本信息
v8.54.1

## 运营场景描述
已解除与服务商的授权但是依旧显示还在授权 没有域名与推送板块 

## 发生问题的时间 
2024-09-26 16:49:33 至 2024-09-26 16:49:33

## 期望结果
希望恢复原本小程序的版块

**Comment by leeligang1027** [comment]
请提供具体小程序信息

**Comment by linyyj** [comment]
![星怡](https://github.com/user-attachments/assets/18c53e81-bac7-4a69-bdd0-e921d30acd9b)

**Comment by leeligang1027** [comment]
未成功解除授权，请调用https://miniapp.xiaohongshu.com/docs?path=/third/api-3rd/post-api-rmp-tp-auth-cancel进行解除
