### ISSUE TITLE
审核信息提示语简陋（没有图片等），无法自查定位问题

### ISSUE THREAD

**Issue by shixiaohu2206** [redengineer/redmini#1535]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
淘票票

## 平台
IOS, Android

## 小红书版本信息
2.1.3
 
## 基础库版本
v3.107.2

## 发生问题的时间 
2024-09-29 16:18:28 至 2024-09-29 16:18:28

## 问题描述
审核信息提示语简陋（没有图片等），无法自查定位问题

## 期望结果
可以提供拒绝审核的详细原因，供自查

## 重现步骤和复现问题的最小demo Github链接
https://github.com/shixiaohu2206/xhs-miniapp-demo

**Comment by leeligang1027** [comment]
需求收到后续迭代！
