### ISSUE TITLE
商家与服务商运营解除合同，希望解除授权

### ISSUE THREAD

**Issue by MirroCh** [redengineer/redmini#1541]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
微盟

## 小红书版本信息
v8.55.2

## 运营场景描述
希望解除与微盟授权小程序，商家要自建小程序 

## 用户ID 
6036813e0000000001003592

## 发生问题的时间 
2024-10-07 15:22:45 至 2024-10-07 15:22:45

## 期望结果
希望解除与微盟授权，商家要自建小程序

**Comment by leeligang1027** [comment]
https://miniapp.xiaohongshu.com/docs?path=/third/api-3rd/post-api-rmp-tp-auth-cancel 调用解绑接口自行解绑
