### ISSUE TITLE
通过小红书客服工作台发送的小程序商品链接提示商品过期不存在

### ISSUE THREAD

**Issue by HoiChing-F** [redengineer/redmini#1561]
## Issue类型
operator

## 问题模块
小红书小程序商品页分享

## 所属的服务商
三毛游

## 小红书版本信息
8.55.2

## 运营场景描述
通过小红书客服工作台发送的商品链接提示商品过期不存在，实际在小程序店铺是可以正常打开的，另外昨天已发送的链接打开也是正常的。
小红书客服工作台版本：V1.1.50 

## 发生问题的时间 
2024-10-11 14:14:29 至 2024-10-11 14:14:29

## 期望结果
商品链接打开后可正常显示

## 业务基础信息（选填）
小程序ID 6602796538d1a400440b2688

**Comment by leeligang1027** [comment]
已回滚，重试即可！
