### ISSUE TITLE
shareChat分享图片Android显示为小红书logo

### ISSUE THREAD

**Issue by WangHaoBZ** [redengineer/redmini#1563]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
宝尊

## 平台
Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.105.1

## 发生问题的时间 
2024-10-11 18:28:41 至 2024-10-11 18:28:41

## 问题描述
链接为有中文的链接，在ios端encode后正常显示，但在Android，一直显示为小红书的logo。

## 期望结果
安卓能够正常显示图片

## 重现步骤和复现问题的最小demo Github链接
 onShareChat() {
    return {
      title:  this.shareTitle,
      path: &#x60;subPackages/pdp/pages/pdp/index?code&#x3D;${this.code}&#x60;,
      imageUrl: (this.shareImgUrl),
    };
  },链接微信转发

**Comment by Hubmeat** [comment]
以同步业务方修复方案和相关限制
