### ISSUE TITLE
小红书小程序在支付成功产生订单后，从小红书app的购物车中找到的订单，状态还是待付款，想知道原因是什么

### ISSUE THREAD

**Issue by Murphy3389** [redengineer/redmini#1569]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
上海卡里司马科技有限公司

## 平台
IOS, Android

## 小红书版本信息
8.52
 
## 基础库版本
v3.108.1

## 发生问题的时间 
2024-10-14 09:43:09 至 2024-10-14 09:43:09

## 问题描述
小红书小程序在支付成功产生订单后，从小红书app的购物车中找到的订单，状态还是待付款，想知道原因是什么

## 期望结果
小红书app购物车的订单状态需要和小程序的订单状态一致

## 重现步骤和复现问题的最小demo Github链接
详见截图

**Comment by Murphy3389** [comment]
<img width="682" alt="image" src="https://github.com/user-attachments/assets/4aeed982-b60e-4f10-bbcc-14b96c5a4951">

订单号：412410140918125024
左边图片为小程序内的订单状态，为订单成功，也就是付款成功已出票
右边图片为小红书app购物车的订单信息，为待支付状态
小程序的状态是对的，而app不对

**Comment by leeligang1027** [comment]
当前订单状态为待支付，未正确同步订单状态至小红书平台！请调用https://miniapp.xiaohongshu.com/docs?path=/docs/api-backend/post-api-rmp-mp-deal-order-sync_status 同步订单状态
