### ISSUE TITLE
小红书担保支付拉不起

### ISSUE THREAD

**Issue by caolin6167** [redengineer/redmini#1593]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
消失的轨迹

## 平台
Android

## 小红书版本信息
v8.57
 
## 基础库版本
v3.108.1

## 用户ID 
2622793882

## 发生问题的时间 
2024-10-18 14:23:31 至 2024-10-18 14:23:31

## 问题描述
用cocos打的微信小游戏包，导入到小红书开发者工具上用oppo安装小红书app扫码测试，登录可以调通，测试支付拉不起，已确认参数没问题，支付方法：xhs.requestGuaranteeOrderPayment，appid：66e63f0d7d0cb50001b629f8

## 期望结果
期望可以正常拉起支付

## 重现步骤和复现问题的最小demo Github链接
https://miniapp.xiaohongshu.com/docs?path&amp;#x3D;/docs/api/requestGuaranteeOrderPayment
xhs.requestGuaranteeOrderPayment({
orderInfo: {
payToken:response.data.payToken,
orderId:response.data.order_id,
},
success: function (res) {
console.log(&#x27;res:&#x27;+res);
callback({&#x27;errorCode&#x27;: &#x27;0&#x27;, &#x27;errorMessage&#x27;: &#x27;支付成功&#x27;});
},
fail: function (res) {
console.log(res);
callback({&#x27;errorCode&#x27;: res.errCode, &#x27;errorMessage&#x27;: &#x27;错误代码:&#x27; + res.errMsg});
},
complete: function (res) {
console.log(res);
}
});

**Comment by xutm** [comment]
8.60 支持小游戏
