### ISSUE TITLE
自定义组件 options 字段冲突

### ISSUE THREAD

**Issue by zwz661216** [redengineer/redmini#16]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
基础库：3.22.3
## 重现步骤 和 复现问题的最小demo Github链接
组件 在this上挂载options与框架内部options冲突导致报错
![image](https://user-images.githubusercontent.com/90956697/168002052-a1057d93-6bf0-4238-884f-5a7fe6628f87.png)

```
Component({
  properties: {
    list: {type:null},
   },
  observers:{
    list(opt){
      if(Array.isArray(opt)){
        console.log(this.options)
        this.options = opt
        
        this.setData({
          col:opt
        })
      }
    }
  }, 
  data:{
    col:[]
  }
})
```
## 期望结果 和 实际结果(必填)
this.options 不要与框架内部字段冲突

**Comment by Hubmeat** [comment]
this.options 是一个框架内部维护的字段，表示小程序组件配置。

业务 options 的注入方式是什么呢？

**Comment by zwz661216** [comment]
> 



> this.options 是一个框架内部维护的字段，表示小程序组件配置。
> 
> 业务 options 的注入方式是什么呢？
直接设置 this.options = xxx
