### ISSUE TITLE
升级IDE 2.2.0 版本后swiper高度丢失

### ISSUE THREAD

**Issue by hhuwc** [redengineer/redmini#1641]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
太目

## 平台
IDE

## 小红书开发者工具版本
2.2.0

## 基础库版本
v3.110.1

## 发生问题的时间
2024-11-05 10:32:10 至 2024-11-05 10:32:10

## 问题描述
升级IDE 2.2.0 版本后swiper高度丢失

## 期望结果
swiper组件高度正常

## 重现步骤和复现问题的最小demo Github链接
![企业微信截图_17307736581579](https://github.com/user-attachments/assets/0ff27471-fb57-48ab-a54d-9e7469a4d4b5)
![企业微信截图_17307736856845](https://github.com/user-attachments/assets/8abbeb34-4dd7-4af8-9600-fb5c704341b5)
![企业微信截图_17307737414196](https://github.com/user-attachments/assets/fbbcbea6-e77b-4c4a-a3a4-ba1cd967e4fd)
![企业微信截图_17307735956499](https://github.com/user-attachments/assets/562e4c1e-46fc-4e3b-a787-485156058360)
![企业微信截图_17307736255430](https://github.com/user-attachments/assets/8866d94e-256d-47ac-a1d4-3804a23bd719)

**Comment by yufengkz** [comment]
升级工具报错

**Comment by yujon** [comment]
切换使用最新版本基础库是否正常

**Comment by yufengkz** [comment]
不正常
