### ISSUE TITLE
mac与windows ide编译产物不一致

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#1645]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
迪奥

## 平台
IDE

## 小红书开发者工具版本
2.2.0

## 基础库版本
v3.38.0

## 发生问题的时间
2024-11-12 14:33:06 至 2024-11-12 14:33:06

## 问题描述
我们使用的taro react  在某个页面使用了原生组件  这个原生组件在windows的ide上面编译出来是正常的   但是在mac的ide上面编译出来不对   还是原来的原生组件名   并没有替换成真实的组件

## 期望结果
mac产出与window产出一致

## 重现步骤和复现问题的最小demo Github链接
编译

**Comment by hhuwc** [comment]
windows mac 和 IDE 都使用的是同一个版本嘛？原生组件叫什么名字呢？

**Comment by dc980806** [comment]
> windows mac 和 IDE 都使用的是同一个版本嘛？原生组件叫什么名字呢？

windows： 2.0.17   mac: 2.2.0    原生组件名为native-webview   然后通过app.json全局注册

**Comment by hhuwc** [comment]
native-webview ? 小红书小程序只有 web-view

**Comment by dc980806** [comment]
> native-webview ? 小红书小程序只有 web-view

我们用的是taro react里面的taro与原生混合   
https://taro-docs.jd.com/docs/hybrid
微信百度京东都是正常的  mac版小红书ide不正常
<img width="887" alt="image" src="https://github.com/user-attachments/assets/529707db-0a5d-43bf-903e-8ca66919a265">
<img width="908" alt="image" src="https://github.com/user-attachments/assets/ae23f44d-43a2-4747-8189-218cf69526dd">
<img width="898" alt="image" src="https://github.com/user-attachments/assets/47e2fc21-66b9-4388-8859-1633e7a7422a">

**Comment by hhuwc** [comment]
okay 我们看下taro 插件的问题
