### ISSUE TITLE
taro最新框架，转成小红书小程序提示：Template undefined is not found in base.xhsml 一直白屏无法加载页面

### ISSUE THREAD

**Issue by xixihhhh** [redengineer/redmini#1657]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
小红书

## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.111.4

## 发生问题的时间 
2024-11-24 20:35:28 至 2024-11-24 20:35:28

## 问题描述
Template undefined is not found in base.xhsml 一直白屏无法加载页面

## 期望结果
Template undefined is not found in base.xhsml 一直白屏无法加载页面

## 重现步骤和复现问题的最小demo Github链接
Template undefined is not found in base.xhsml 一直白屏无法加载页面

**Comment by xixihhhh** [comment]
taro 框架

**Comment by xixihhhh** [comment]
转小红书小程序提示Template undefined is not found in base.xhsml

https://github.com/xixihhhh/taro-4.0.7-xhs

clone代码，跑dev:xhs，然后页面白屏无法正常预览，使用官方的初始化代码，什么都没加，1.2.1版本的小红书插件

**Comment by hhuwc** [comment]
taro目前仅支持到3.x 版本有问题可以给taro 官方提issue
