### ISSUE TITLE
安卓下的setTabBarItem API 调用后导致tabbar图片消失 且 tabbar的icon有切掉一部分

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#166]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ x ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ x ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ x ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.49
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="550" alt="image" src="https://user-images.githubusercontent.com/49746060/181895688-d68ce264-3569-4c1a-bbd8-668f9f4912e2.png">
<img width="583" alt="Snipaste_2022-07-30_16-24-14" src="https://user-images.githubusercontent.com/49746060/181896472-7f6a8c56-6c80-4e72-9376-12c3fecfad37.png">
安卓下的setTabBarItem API 调用后导致tabbar图片消失
icon切掉一部分
<img width="436" alt="2B3E2752-251D-41FE-8FE4-EBD3EDB4DFA1" src="https://user-images.githubusercontent.com/49746060/181897633-695c3d3e-4421-4fd0-97db-218075769aa7.png">
ios表现正常
<img width="475" alt="Snipaste_2022-07-30_16-30-30" src="https://user-images.githubusercontent.com/49746060/181899248-d5ce4d5b-8763-4c97-91de-97970055aaa2.png">

 +
## 期望结果 和 实际结果(必填) +
希望安卓能正常调用且icon不要被截掉
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
辛苦将 小红书号 317940352 加一下这个小程序的预览权限哈

**Comment by taiyiandr** [comment]
7.51版本修复
