### ISSUE TITLE
安卓下无法做到页面沉浸式

### ISSUE THREAD

**Issue by collincheng** [redengineer/redmini#167]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ x ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ x ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ x ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.49+
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/49746060/181900559-5cb4b6fa-61ee-4602-88b1-f18889dea10a.png)
<img width="508" alt="image" src="https://user-images.githubusercontent.com/49746060/181901274-cc0d6a83-1564-4148-bd73-a213f87e881e.png">

ios表现正常
![IMG_6B9399806C62-1](https://user-images.githubusercontent.com/49746060/181901811-70482b9b-55e0-467d-83ec-4d54f4a72f5c.jpeg)

## 期望结果 和 实际结果(必填) +
能正常显示去除白块
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
可以提供下 taro 产物的 app.json 吗

**Comment by collincheng** [comment]
{
    "pages": [
        "pages/startIndex/index",
        "pages/index/index",
        "pages/customIndex/index",
        "pages/storeIndex/index",
        "pages/storeCustomIndex/index",
        "pages/storeDetail/index",
        "pages/presaleSelectStore/index",
        "pages/orderConfirm/index",
        "pages/pay/index",
        "pages/payContainer/index",
        "pages/orderDetail/index",
        "pages/refundApply/index",
        "pages/refundDetail/index",
        "pages/refundHelp/index",
        "pages/personalCenter/index",
        "pages/orderList/index",
        "pages/login/index",
        "pages/shopImpression/index",
        "pages/refundList/index",
        "pages/agreement/index",
        "pages/noPage/index",
        "pages/roomTypeList/index",
        "pages/presaleIndex/index",
        "pages/presaleList/index",
        "pages/presaleRoomType/index",
        "pages/presaleDetail/index",
        "pages/presaleOrderConfirm/index",
        "pages/presaleOrderSubmit/index",
        "pages/presaleLog/index",
        "pages/presaleMoreList/index",
        "pages/presaleOrderDetail/index",
        "pages/presaleAppointmentOrderDetail/index",
        "pages/baiduWebView/index",
        "pages/webview/index",
        "pages/offShelf/index",
        "pages/personalDefault/index",
        "pages/cityList/index",
        "pages/storeList/index",
        "pages/calendarRoomDetails/index",
        "pages/roomCalendar/index",
        "pages/presaleCalendar/index",
        "pages/swanLogin/index"
    ],
    "window": {
        "backgroundTextStyle": "light",
        "navigationBarBackgroundColor": "#fff",
        "navigationBarTitleText": "页面",
        "navigationBarTextStyle": "black"
    },
    "tabBar": {
        "color": "#bbbbbb",
        "selectedColor": "#2E2E2E",
        "list": [
            {
                "pagePath": "pages/index/index",
                "text": "首页",
                "iconPath": "native/tabbar/index_default.png",
                "selectedIconPath": "native/tabbar/index_theme1.png"
            },
            {
                "pagePath": "pages/shopImpression/index",
                "text": "门店印象",
                "iconPath": "native/tabbar/impression_default.png",
                "selectedIconPath": "native/tabbar/impression_theme1.png"
            },
            {
                "pagePath": "pages/personalCenter/index",
                "text": "个人中心",
                "iconPath": "native/tabbar/center_default.png",
                "selectedIconPath": "native/tabbar/center_theme1.png"
            }
        ]
    },
    "permission": {
        "scope.userLocation": {
            "desc": "你的位置信息将用于小程序为您定位当前城市"
        }
    },
    "animation": {
        "duration": 0,
        "delay": 50
    }
}
@Hubmeat

**Comment by Hubmeat** [comment]
给下 appid 把

**Comment by taiyiandr** [comment]
如果是预览版的话请提供一下二维码，以及把小红书号：317940352，添加一下权限。

**Comment by taiyiandr** [comment]
Android 7.52 fix
