### ISSUE TITLE
直播异常

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#169]
---
name: 直播异常
about: 直播出现点击购买无反应、app出现闪退现象、点击进入页面白屏
title: ''
labels: ''
assignees: ''

---
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

https://user-images.githubusercontent.com/33249100/182280270-5ede3a2f-aa2d-4181-95d0-412f953cfefe.mov
出现问题手机号：17701801426
![wecom-temp-f160369ea8dfaf5d73a725eb4763f93e](https://user-images.githubusercontent.com/33249100/182280383-6f16344f-c472-42d4-93ce-592fdde6bc68.jpg)
![wecom-temp-4b8573aa2324050293aedf73a27da2a5](https://user-images.githubusercontent.com/33249100/182280394-64fdf217-8020-4040-8802-ccc3be6ebd77.jpg)

更多信息可以在对接群里咨询，我给拉进商家群
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
确认Android也有这个白屏问题吗？
