### ISSUE TITLE
page disableScroll  设置无效 scroll-view ios弹性效果导致页面卡住

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#171]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
`{
    "navigationBarTitleText": "demo",
    "disableScroll":true
}
`

`
<view class="page">
<view class="tabbar">
  <scroll-view scroll-x class="tabbar-scroll" enable-flex>
    <view class="item">1</view>
    <view class="item">2</view>
    <view class="item">3</view>
    <view class="item">4</view>
    <view class="item">5</view>
    <view class="item">6</view>
    <view class="item">7</view>
    <view class="item">8</view>
    <view class="item">9</view>
    <view class="item">10</view>
    <view class="item">11</view>
  </scroll-view>
</view>
<view class="wrapper">
  <scroll-view scroll-y class="wrapper-scroll" bindscrolltolower="bindScrollToLower" lower-threshold="200">
    <view xhs:for="{{list}}" class="item">
      {{index}}: {{item}}
    </view>
  </scroll-view>
</view>
<view class="footer">
  footer
</view>
</view>
`

`
.page{
  width:100%;
  height:100vh;
  display: flex;
  flex-direction: column;
}
.tabbar{
  width:100%;
  height:50px;
  background-color: #ccc;
}
.tabbar .item{
  height:50px;
  min-width:120px;
  text-align: center;
  line-height: 50px;
  font-size: 24px;
  color:#fff;
}

.wrapper{
  width:100%;
  flex:1;
  overflow: hidden;
}
.wrapper .wrapper-scroll{
  width:100%;
  height:100%;
}
.wrapper-scroll .item{
  width:100%;
  height:120px;
  background-color: #e12160;
  margin-bottom: 20px;
  font-size: 40px;
  text-align: center;
  line-height: 120px;
  color:#fff;
}

.footer{
  width:100%;
  height:55px;
  text-align: center;
  line-height: 55px;
  font-size: 32px;
  color:#fff;
  background-color: #000;
}
`

`
Page({
  data: {
    page:1,
    size:10,
    list:[]
  },
  onReady(){
    const list = []
    for(let i = 0;i < this.data.size;i++){
      list.push(i*this.data.page)
    }
    this.setData({list})
  },
  bindScrollToLower(){
    this.data.page +=1;
    const list = this.data.list
    for(let i = 0;i < this.data.size;i++){
      list.push(i*this.data.page)
    }
    this.setData({list})
  },
  itemClick(e){
    this.setData({
    })
  }
})

`

https://user-images.githubusercontent.com/63334662/182554375-3a41fca3-42a0-4ea6-ba56-72c597f631de.mp4

## 期望结果 和 实际结果(必填) +
disableScroll可以禁止页面弹性效果，scroll-view 正常滑动
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
看视频内是 ios 的过渡滚动效果，disableScroll  目前在小红书这边控制的是外层 root 容器的 overflow 属性

**Comment by Hubmeat** [comment]
> > 看视频内是 ios 的过渡滚动效果，disableScroll 目前在小红书这边控制的是外层 root 容器的 overflow 属性
> 
> 我们期望的是disableScroll可以禁用掉ios的滚动弹性效果，scroll-view 的也是 快速滑动会导致scroll-view bindscrolltolower等属性达不到预期的效果，就像整个scroll-view卡住了一样

嗯，我们先解决  disableScroll 不符合期望的问题，如果解决后 scroll-view 还有你说的问题，可以在提新的 issue 进行跟进。
我们内部在排查中，有结论在 issue 内会进行同步

**Comment by echooys** [comment]
> > > 看视频内是 ios 的过渡滚动效果，disableScroll 目前在小红书这边控制的是外层 root 容器的 overflow 属性
> > 
> > 
> > 我们期望的是disableScroll可以禁用掉ios的滚动弹性效果，scroll-view 的也是 快速滑动会导致scroll-view bindscrolltolower等属性达不到预期的效果，就像整个scroll-view卡住了一样
> 
> 嗯，我们先解决 disableScroll 不符合期望的问题，如果解决后 scroll-view 还有你说的问题，可以在提新的 issue 进行跟进。 我们内部在排查中，有结论在 issue 内会进行同步

好的，谢谢

**Comment by AngryBrotherXiang** [comment]
iOS 7.51 fix disableScroll 设置无效 问题
