### ISSUE TITLE
swiper circular 属性滑动预期效果不符

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#172]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
轮播图添加了circular属性左右轮播把中间所有的swiper-item滚动一遍，看起来感觉是页面在乱跳了，
https://user-images.githubusercontent.com/63334662/182557134-fea44e1c-e9fe-41a9-bf9d-fd861da21496.mp4

## 期望结果 和 实际结果(必填) +
第一个右滑滚动至最后一个或者最后一个左滑至第一个 不应该吧吧所有item都滚动一边
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
滚动逻辑和上面的 tab 组件是否做了逻辑绑定？比如 swiper change 事件 和 tab 针对 swiper index 的索引控制权导致组件产生这个现象

**Comment by echooys** [comment]
https://user-images.githubusercontent.com/63334662/182566055-b2c0c82c-f787-482f-9b8f-713acb8204e0.mp4

`
Page({
  data: {
    current:0
  },
  onChange(e){
    if(e.detail.source){
      this.setData({current:e.detail.current})
    }
  }
})

`

`
<view class="page">
<swiper current="{{current}}" circular bindchange="onChange" autoplay>
          <swiper-item>
            <view class="swiper-item red"></view>
          </swiper-item>
          <swiper-item>
            <view class="swiper-item blue"></view>
          </swiper-item>
          <swiper-item>
            <view class="swiper-item blueviolet"></view>
          </swiper-item>
          <swiper-item>
            <view class="swiper-item chartreuse"></view>
          </swiper-item>
      </swiper>
</view>
`

`
.page{
  width:100%;
  height:100vh;
  display: flex;
  flex-direction: column;
}
.swiper-item{
  width:100vw;
  height:300px;
}
.swiper-item.red{
  background-color: red;
}
.swiper-item.blue{
  background-color: blue;
}
.swiper-item.blueviolet{
  background-color: blueviolet;
}
.swiper-item.chartreuse{
  background-color: chartreuse;
}
`

**Comment by echooys** [comment]
> 滚动逻辑和上面的 tab 组件是否做了逻辑绑定？比如 swiper change 事件 和 tab 针对 swiper index 的索引控制权导致组件产生这个现象

我用原生写了demo 没有任何绑定也是一样的= =

**Comment by echooys** [comment]
> 滚动逻辑和上面的 tab 组件是否做了逻辑绑定？比如 swiper change 事件 和 tab 针对 swiper index 的索引控制权导致组件产生这个现象

应该说只要控制current 就会有这个问题

**Comment by Hubmeat** [comment]
好的，我们先排查下

**Comment by Hubmeat** [comment]
你好，感谢反馈，这个问题在 752 版本会进行修复

**Comment by echooys** [comment]
> 你好，感谢反馈，这个问题在 752 版本会进行修复

你好，这个还有问题，如果通过改变current 从第一个变成最后一个，从最后一个变成第一个还是会把所有都滚动一遍

**Comment by Hubmeat** [comment]
麻烦提供下代码片段吧

**Comment by echooys** [comment]
> 麻烦提供下代码片段吧


https://user-images.githubusercontent.com/63334662/187146318-5484ad84-4dcd-48c0-bf51-79c709083091.mp4



`
Page({
    data:{
        background:['red','blue','green','orange'],
        current:0
    },
    handleFirst(){
        this.setData({current:0})
    },
    handleLast(){
        this.setData({current:3})
    }
})
`

`
<view>
  <swiper current="{{current}}" circular >
      <block xhs:for="{{background}}" xhs:key="*this">
        <swiper-item>
          <view class="swiper-item {{item}}">{{index}}</view>
         </swiper-item>
      </block>
  </swiper>
  <button bindtap="handleFirst">去第一页</button>
  <button bindtap="handleLast">去最后一页</button>
</view>
`

`
.swiper-item{
    width:100%;
    height:200px;
    font-size: 40px;
    text-align: center;
    line-height: 200px;
    color:#fff;
}
.red{
    background-color: red;
}
.blue{
    background-color: blue;
}
.green{
    background-color: green;
}
.orange{
    background-color: orange;
}
`
