### ISSUE TITLE
taro  onShareChat接口不支持

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#173]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
onShareChat接口taro不支持

## 期望结果 和 实际结果(必填) +
onShareChat Taro的兼容方案
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
能看下你的用法吗？

**Comment by Hubmeat** [comment]
@tarojs/plugin-platform-xhs v0.0.5   是否有同样的问题呢

**Comment by echooys** [comment]
> 能看下你的用法吗？

没办法用啊，
![image](https://user-images.githubusercontent.com/63334662/182575854-390528c9-2c22-4ba2-86ee-af25e1fa4936.png)
taro 只提供了这两个api ，我们是用的函数组件

**Comment by echooys** [comment]
> @tarojs/plugin-platform-xhs v0.0.5 是否有同样的问题呢

onShareChat是小红书 独有的api

**Comment by Hubmeat** [comment]
> > @tarojs/plugin-platform-xhs v0.0.5 是否有同样的问题呢
> 
> onShareChat是小红书 独有的api

  可以尝试在 button 组件下添加下面的代码试试
  ```html
    <button open-type="share" data-share-type="shareChat">唤起分享</button>
  ```

**Comment by echooys** [comment]
> > > @tarojs/plugin-platform-xhs v0.0.5 是否有同样的问题呢
> > 
> > 
> > onShareChat是小红书 独有的api
> 
> 可以尝试在 button 组件下添加下面的代码试试
> 
> ```
>   <button open-type="share" data-share-type="shareChat">唤起分享</button>
> ```

唤起了去哪配置
![image](https://user-images.githubusercontent.com/63334662/182577603-c43ed75f-7793-4ecf-8c66-0cc85bb17185.png)
对应属性呢。

**Comment by echooys** [comment]
> 

试了一下 识别不了data-share-type 还是分享到站内的

**Comment by Hubmeat** [comment]
嗯，taro 不支持 onShareChat 还需要官方兼容下。我们先排查下再给你结论。现在第三方框架的适配支持没有足够人力跟进，只能 case by case 去跟进。

**Comment by echooys** [comment]
> 

好的，谢谢

**Comment by Hubmeat** [comment]
```js
const Index = { ... }
class Outer extends Component {
  onShareAppMessage(res) {
    if (res.from === 'button') {
      // 来自页面内转发按钮
      console.log(res.target)
    }
    return {
      title: '自定义转发标题',
      path: '/page/user?id=123'
    }
  }
  
  onShareTimeline() {
    console.log('onShareTimeline')
    return {}
  }

  render(): ReactNode {
    return <Index />
  }
}

page.config.ts 可开启：
  enableShareAppMessage: true,
  enableShareTimeline: true

```

**Comment by Hubmeat** [comment]
> > 
> 
> 好的，谢谢

上面给到了朋友圈，站内分享 ，taro 的用法。

onShareChat 这个 taro 这边暂不支持配置，支持到 taro 需要一些时间，建议先不要在 taro 场景里使用 onShareChat, 
我这边和 taro 再沟通下，有结论会继续在这个 issue 下同步

**Comment by Hubmeat** [comment]
onShareChat 可以这样兼容：

```js

const Index = { ... }
class Outer extends Component {
  onShareAppMessage(res) {
    if (res.from === 'button') {
      // 来自页面内转发按钮
      console.log(res.target)
    }
    return {
      title: '自定义转发标题',
      path: '/page/user?id=123'
    }
  }
  
  onShareTimeline() {
    console.log('onShareTimeline')
    return {}
  }
  
  onShareChat() {
     return {
         title: "test",
         path: '/path/test?a=1&b=2'
      }
  }

  render(): ReactNode {
    return <Index />
  }
}
本地先按照如下方式兼容：
小红书插件修改： node_modules/@tarojs/plugin-platform-xhs/dist/runtime.js
```
// 修改 hostConfig 如下：
export const hostConfig = {
    initNativeApi,
    getPathIndex(indexOfNode) {
        return `${indexOfNode}`;
    },
    getMiniLifecycle (config) {
        const methods = config.page[5]
        if (methods.indexOf('onShareChat') === -1) {
          methods.push('onShareChat')
        }
        return config
    }
};
```

**Comment by Hubmeat** [comment]
> NervJS/taro-plugin-platform-xhs#7

taro-plugin-platform-xhs@0.0.6  已发布

**Comment by Hubmeat** [comment]
button 的使用方式可以关注下这个 MR @echooys :

https://github.com/NervJS/taro-plugin-platform-xhs/pull/9/files
