### ISSUE TITLE
get 请求json文件 返回接口安卓 ios 不一致

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#174]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/182783484-8bd2f880-6c89-49db-a5f3-d42aa23eadf8.png)
<img width="632" alt="image" src="https://user-images.githubusercontent.com/63334662/182783756-e5d40b8a-0cba-40ae-92ab-de17ab33fd3c.png">

同一个接口 ios和模拟器返回的是数据 安卓返回的会被JSON.stringify转换
## 期望结果 和 实际结果(必填) +
返回接口保持一致
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
请求有传dataType参数吗？

**Comment by echooys** [comment]
> 

dataType? 你说的content-type吗？

**Comment by taiyiandr** [comment]
https://miniapp.xiaohongshu.com/docs/api/request

可以提供一下预览二维码吗？以及把小红书号317940352加一下权限。

**Comment by taiyiandr** [comment]
Android 7.51版本修复
