### ISSUE TITLE
showShareMenu api无响应

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#175]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/182997046-420f9aa0-8e74-4f5f-8206-c565abd2d223.png)
![image](https://user-images.githubusercontent.com/63334662/182997074-6e315d6d-f7cf-467e-be3a-ef5b040ae2e2.png)
点击无响应
## 期望结果 和 实际结果(必填) +
showShareMenu 正确响应
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
可以提供下代码片段么

**Comment by Hubmeat** [comment]
加上回调看是否有响应呢

```js

    xhs?.showShareMenu({
      success: res => {
        this.updateApiData('success', res)
      },
      fail: res => {
        this.updateApiData('fail', res)
      },
      complete: res => {
      
      },
    })
```

**Comment by Hubmeat** [comment]
如果要实现分享，可以通过控制 Page 函数内的 api 来控制分享入口，可以参考下：
https://miniapp.xiaohongshu.com/docs/guide/openTransmit

**Comment by echooys** [comment]
> 

回调会响应 但不会显示分享按钮

**Comment by Hubmeat** [comment]
这样试试呢：

```js
showShareMenu({ shareTypes: ['normal', 'wx_moments', 'wx_friends'] })
```

**Comment by echooys** [comment]
> 这样试试呢：
> 
> ```js
> showShareMenu({ shareTypes: ['normal', 'wx_moments', 'wx_friends'] })
> ```

没有效果
