### ISSUE TITLE
创建服务商账户，提示“系统异常” 

### ISSUE THREAD

**Issue by axeon** [redengineer/redmini#177]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
按照文档“准备->创建服务商”章节填入创建服务商信息，点击“确认创建”按钮后，提示“系统异常”
![微信图片_20220805135902](https://user-images.githubusercontent.com/10541706/183011447-dfdd5068-5382-4a63-a544-cfa04b9c2666.jpg)

 +
## 期望结果 和 实际结果(必填) +
期望正确创建服务商账号，实际提示“系统异常”。 
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by abandonedkid** [comment]
报错是因为请求超时了
创建失败的真实原因是IP白名单里不要有\n，可以先填写一个IP使创建成功，之后再更改IP白名单

**Comment by axeon** [comment]
IP白名单已经改为只有一个，并确认没有\n，依旧提示“系统异常”。
帮忙再看一下原因。

**Comment by abandonedkid** [comment]
> IP白名单已经改为只有一个，并确认没有\n，依旧提示“系统异常”。 帮忙再看一下原因。

这次是【小程序业务域名】不要加上协议

**Comment by axeon** [comment]
已经解决，谢谢！

**Comment by axeon** [comment]
已经解决，谢谢！
