### ISSUE TITLE
是否支持vue3？（uni-app）

### ISSUE THREAD

**Issue by ThisIsBritta** [redengineer/redmini#179]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 我们希望在我们原有的uni-app vue3项目快速迁移到小红书上，维护一份代码，现在我直接在vue3的项目里面增加@dcloudio/uni-mp-xhs编译小红书，运行的时候就出现报错，不清楚是否支持vue3+
<img width="667" alt="image" src="https://user-images.githubusercontent.com/29575851/183375167-9273e003-9695-49fa-9143-a6c947d137b8.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/29575851/183375332-f19b8d11-c071-41de-8ded-55104aa462d5.png">

 
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 希望能够支持Vue3+
 如果支持，在旧的uni-app项目里面该如何配置 xhs的打包。+
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Edge00** [comment]
小红书小程序只支持小红书制定的语言（xhsml / css / js / json），uni-app 的模式是用 Vue 编译写，最终 uni-app 会编译成小红书小程序支持的语言。
建议用 uni-app 创建一个空项目来测试和迁移已有小程序。
