### ISSUE TITLE
video组件 controls: true 时没有静音按钮

### ISSUE THREAD

**Issue by qhhuang** [redengineer/redmini#18]
## 系统环境(必填)
- [x] IOS
- [X] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [X] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.22.3
## 重现步骤 和 复现问题的最小demo Github链接
video组件 controls: true 时没有静音按钮
## 期望结果 和 实际结果(必填)
video组件 controls: true 时控制栏上有静音按钮

**Comment by handsome025** [comment]
##cart.xhsml
<import src="./unit-shop-cart.xhsml" />
<view><template is="unit-title"></template></view>

##cart.js
onTapCart(e){console.log(3333)}

##unit-shop-cart.xhsml
<template name="unit-shop-cart">
    <view catchtap="onTapCart">
    加购
    </view>
</template>

**Comment by maolovecoding** [comment]
controls: true控制栏就是不会有静音按钮的
