### ISSUE TITLE
华为P40 pro 手机扫开发工具预览码和登录码扫不上 

### ISSUE THREAD

**Issue by banxian250** [redengineer/redmini#182]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 

https://user-images.githubusercontent.com/31688968/183831206-b93e4b7e-eded-4de3-a4ea-5bf4bb3abd59.mp4

开放工具的 登陆吗 和 预览码 华为 p40 pro怎么扫都扫不上 把码截图 用相册识别就可以。麻烦看看是什么问题
 +
## 期望结果 和 实际结果(必填) +
正常快速扫上码 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by xutm** [comment]
暂时不能复现，先关闭吧
