### ISSUE TITLE
已经在管理台开了开发者权限，但是现实还是没有权限，无法上传代码

### ISSUE THREAD

**Issue by ThisIsBritta** [redengineer/redmini#185]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/29575851/183865544-6b9cb582-e6b7-423e-908d-a3cf9c0ca1ae.png">

+
## 期望结果 和 实际结果(必填) +
能够上传代码，现在无法上传代码，并且打开开发者工具也会报错，报同样的错+
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by xutm** [comment]
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/11706751/183868794-7727b916-4f41-48db-a116-65151e47d39a.png">

根据图中的操作，看下接口对应的权限是否有，如果没有的话，说明权限的确没加上

**Comment by ThisIsBritta** [comment]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/29575851/183870250-358e84b9-79ca-40da-8916-dbeaff667ebd.png">

提示应用失效

**Comment by ThisIsBritta** [comment]
> <img alt="image" width="1514" src="https://user-images.githubusercontent.com/11706751/183868794-7727b916-4f41-48db-a116-65151e47d39a.png">
> 
> 根据图中的操作，看下接口对应的权限是否有，如果没有的话，说明权限的确没加上

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/29575851/183870448-9fc4d488-f796-46ce-bc95-60dc0d416451.png">

提示应用失效，需要我提供什么信息吗？
