### ISSUE TITLE
自定义导航栏，ios手机号授权弹窗关闭 顶部闪烁

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#188]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
`
<view>
    <image class="image" src="https://tse1-mm.cn.bing.net/th/id/OIP-C.n0_p3rYRuofABd3XudbZnAHaEo?pid=ImgDet&rs=1" mode="widthFix" />
    <input type="number" placeholder="测试number" class="input" max-length="11" />
    <button open-type="getPhoneNumber" bindgetphonenumber="bindgetphonenumber">获取手机号</button>
</view>
`
`
Page({
    bindgetphonenumber(e){
        console.log(e);
    }
})
`

https://user-images.githubusercontent.com/63334662/184054706-1ffb8ecf-991f-48ae-b90a-f4cf9fa122c4.mp4

 +
## 期望结果 和 实际结果(必填) +
ios 不闪烁
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
7.53 fix，预计8月22发布到App Store
