### ISSUE TITLE
input bindinput 返回字符串无效

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#189]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/184061428-8111f8db-10ea-43c3-b366-d1082742d598.png)
`
<view>
    <image class="image" src="https://tse1-mm.cn.bing.net/th/id/OIP-C.n0_p3rYRuofABd3XudbZnAHaEo?pid=ImgDet&rs=1" mode="widthFix" />
    <input type="text" placeholder="测试number" class="input" max-length="11" bindinput="bindInput" />
</view>
`

`
Page({
    data:{
        value:''
    },
    bindInput(e){
        const value = e.detail.value;
        // this.setData({value:value.replace(/[^0-9]/g, '')})
        return value.replace(/11/g, '2')
    }
})
`

https://user-images.githubusercontent.com/63334662/184061607-701126cc-0a9c-4f68-a993-e0fa05e3d983.mp4

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
非问题：
.限制输入长度，需要开发者设置maxLength
2.type设置number是数字键盘，用户可以手动切换键盘类型
