### ISSUE TITLE
xhs.downloadFile 成功回调的返回值跟文档不一致，缺少 tempFilePath 与  statusCode

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#19]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v7.37.3

## 重现步骤 和 复现问题的最小demo Github链接
使用 xhs.downloadFile API，查看成功回调的参数与文档内容不一致，缺少
`xhs.downloadFile({
        url: url, 
        success: (res: any) => {
            console.log(res);
        },
        fail:( error: any ) => {
            console.log(error, 'downloadFile fail');
        }
    });`
![teO29jDOsh](https://user-images.githubusercontent.com/11973539/168208605-007ba867-9231-454c-bc0b-32491fe438aa.png)
![pthbXAyoSA](https://user-images.githubusercontent.com/11973539/168208638-670d3f41-fe5a-4cd5-84c6-ec9c5359bc99.png)

## 期望结果 和 实际结果(必填)
按照文档正常返回

**Comment by pengweinan123** [comment]
问题已修复，和文档统一，添加statusCode回调参数，若开发者不传filePath，成功回调里会返回tempFilePath。
