### ISSUE TITLE
inpuy type=number  ios无效

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#190]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

`
<view>
    <image class="image" src="https://tse1-mm.cn.bing.net/th/id/OIP-C.n0_p3rYRuofABd3XudbZnAHaEo?pid=ImgDet&rs=1" mode="widthFix" />
    <input type="number" placeholder="测试number" class="input" max-length="11" />
    <button open-type="getPhoneNumber" bindgetphonenumber="bindgetphonenumber">获取手机号</button>
</view>
`
![22651660184534_ pic](https://user-images.githubusercontent.com/63334662/184062132-03a80159-1a9e-4372-b952-64998ca735b2.jpg)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
![wecom-temp-77369-56743154d065515ffc2171858e6ae864](https://user-images.githubusercontent.com/16516984/184077752-e5410c6b-7a9e-4100-acbd-83947f87616c.jpg)
input type=number是生效的，点击左下角可以切换输入法类型

**Comment by echooys** [comment]
好的，谢谢，就是说ios 弹出数字键盘 需要用户手动切输入法才行吧
