### ISSUE TITLE
input 聚焦时无法更新value值

### ISSUE THREAD

**Issue by xf079** [redengineer/redmini#191]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
`
<view>
    <image class="image" src="https://tse1-mm.cn.bing.net/th/id/OIP-C.n0_p3rYRuofABd3XudbZnAHaEo?pid=ImgDet&rs=1" mode="widthFix" />
    <input type="text" value="{{value}}" placeholder="测试number" class="input" max-length="11" bindinput="bindInput" />
</view>
`

`
Page({
    data:{
        value:''
    },
    bindInput(e){
        console.log(e);
        const value = e.detail.value;
        this.setData({value:value+'000'})
    }
})
`

https://user-images.githubusercontent.com/63334662/184065815-fa06b284-4b40-41b2-8928-5d38e04dfecb.mp4

 +
## 期望结果 和 实际结果(必填) +
聚焦时可以正常更新value值
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
非问题：
.限制输入长度，需要开发者设置maxLength
2.type设置number是数字键盘，用户可以手动切换键盘类型

**Comment by Edge00** [comment]
> 非问题：
.限制输入长度，需要开发者设置maxLength
2.type设置number是数字键盘，用户可以手动切换键盘类型

如果还有疑问可以 reopen

**Comment by echooys** [comment]
> > 非问题：
> > .限制输入长度，需要开发者设置maxLength
> > 2.type设置number是数字键盘，用户可以手动切换键盘类型
> 
> 如果还有疑问可以 reopen

这个issues 不是什么输入长度数字键盘，上面demo 已经贴了，现在input的值在聚焦状态是不受控的

**Comment by Edge00** [comment]
我看了 iOS 是 OK 的，只有 Android 有这个问题是吗？

**Comment by echooys** [comment]
> 我测试了下 iOS 是 OK 的，Android 可以复现，只有 Android 有这个问题是吗？

都有

**Comment by echooys** [comment]
> 我测试了下 iOS 是 OK 的，Android 可以复现，只有 Android 有这个问题是吗？

还有 两个input在在input1聚焦时让input1的focus = false 让input2的focus = true 也无效

**Comment by Edge00** [comment]
> input 聚焦时无法更新value值

问题已经定位，但是 ios 我们没能复现，方便提供一个 ios 的录屏吗？

**Comment by Edge00** [comment]
> 还有 两个input在在input1聚焦时让input1的focus = false 让input2的focus = true 也无效

我这里尝试双端都是 OK 的，麻烦提供下最小复现工程

**Comment by echooys** [comment]
> > input 聚焦时无法更新value值
> 
> 问题已经定位，但是 ios 我们没能复现，方便提供一个 ios 的录屏吗？

![b364cf0dbb838fca16932be3fc5aa94](https://user-images.githubusercontent.com/63334662/187174343-1b3fcd96-5772-4d2d-b31a-8056b3bfbdeb.jpg)

https://user-images.githubusercontent.com/63334662/187174357-40f35ff2-5049-401b-a3b5-19b46ada429c.mp4

**Comment by echooys** [comment]
> 

`
import {  Input,  View } from '@tarojs/components'
import { useImmer } from 'use-immer'
import './index.scss'

const Test = () => {
  const [ state, updateState ] = useImmer({
    desc: new Array(6).fill({ value: '', cursor:0, focus:false }),
  });
  const handleInput = (index, e) => {
    const { cursor, value, keyCode } = e.detail;
    const nextIndex = index+1;
    const regex = /[^\u4e00-\u9fa5a-zA-Z0-9,.!\-_！，。 ]/g;
    const _newValue = value.replace(regex, '').substr(0, 23);
    if (cursor >= 23 && _newValue.length >= 23){
      if (index < 5){
        const _desc = state.desc.map((item, _i)=>({
          ...item,
          cursor:item.value.length,
          focus:nextIndex === _i
        }));
        updateState(draft=>{
          draft.desc = _desc;
        });
      }
      updateState(draft=>{
        draft.desc.splice(index, 1, { ...draft.desc[index], value:_newValue });
      });
    } else if (value === '' && keyCode === 8){
      if (index > 0){
        const _desc = state.desc.map((item, _i)=>({
          ...item,
          value:index === _i ? '':item.value,
          cursor:item.value.length,
          focus:index-1 === _i
        }));
        updateState(draft=>{
          draft.desc = _desc;
        });
      }
    } else {
      updateState(draft=>{
        draft.desc.splice(index, 1, { value:_newValue, cursor:value.length, focus:true });
      });
    }
  };

  const handleConfirm = (index:number)=>{
    const nextIndex = index+1;
    if (index < 5){
      const _desc = state.desc.map((item, _i)=>({
        ...item,
        cursor:item.value.length,
        focus:nextIndex === _i
      }));
      updateState(draft=>{
        draft.desc = _desc;
      });
    }
  };

  return (
    <View className='page-container'>
      {(state.desc || []).map((item, index) => {
        return (
          <Input
            key={index}
            type='text'
            value={item.value}
            focus={item.focus}
            className='input'
            cursor={item.cursor}
            onInput={e => handleInput(index, e)}
            onConfirm={()=>handleConfirm(index)}
            maxlength={140}
            max-length={140}
            confirm-type='next'
          />
        );
      })}
    </View>
  )
}

export default Test

`

**Comment by Edge00** [comment]
```html
<view>
  <input type="text" value="{{value}}" placeholder="测试number" class="input" bindinput="bindInput" />
</view>
```
```js
Page({
  data: {
    value: '',
  },
  bindInput(e){
    console.log(e)
    const value = e.detail.value
    this.setData({
      value: value + '000',
    })
  }
})
```

https://user-images.githubusercontent.com/23715779/187178737-7d36d122-0306-40f7-a517-9c27700a8855.mov

**Comment by Edge00** [comment]
请提供最小复现工程

**Comment by echooys** [comment]
https://user-images.githubusercontent.com/63334662/187187354-af0a68aa-c922-4707-bd4d-c4760105efc5.mp4

![image](https://user-images.githubusercontent.com/63334662/187187377-0ac94952-b01f-4c97-84c5-9768f1e1d359.png)

**Comment by Edge00** [comment]
@echooys  setData 不生效的问题已经定位并修复，focus 的问题麻烦提供下 taro 组件代码吧

**Comment by Edge00** [comment]
这个 case 可以吗？
```jsx
import { View, Input, Button } from '@tarojs/components'
import { useState } from 'react'

const Test = () => {

  const [focus, setFocus] = useState({
    focus1: true,
    focus2: false,
  })

  const changeFocus = () => {
    setFocus({
      focus1: false,
      focus2: true,
    })
  }

  return (
    <View>
      <Input focus={focus.focus1} placeholder='test1' />
      <Input focus={focus.focus2} placeholder='test2' />
      <Button onClick={changeFocus}>聚焦第二个</Button>
    </View>
  )
}

export default Test
```

**Comment by echooys** [comment]
> 这个 case 可以吗？
> 
> ```js
> import { View, Input, Button } from '@tarojs/components'
> import { useState } from 'react'
> 
> const Test = () => {
> 
>   const [focus, setFocus] = useState({
>     focus1: true,
>     focus2: false,
>   })
> 
>   const changeFocus = () => {
>     setFocus({
>       focus1: false,
>       focus2: true,
>     })
>   }
> 
>   return (
>     <View>
>       <Input focus={focus.focus1} placeholder='test1' />
>       <Input focus={focus.focus2} placeholder='test2' />
>       <Button onClick={changeFocus}>聚焦第二个</Button>
>     </View>
>   )
> }
> 
> export default Test
> ```

不是这种的 demo我群里发你了
