### ISSUE TITLE
小红书消息异常  错误码410403

### ISSUE THREAD

**Issue by Wang-Xijie** [redengineer/redmini#192]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +无
 +无
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：小红书消息异常+
 +[小红书] 客服消息发送失败. request:{"content":"选取您喜欢的领取方式\n[礼物]微商城主页(会员享好礼）\n①3包咖百味价值39.9元，领券购买19.9元\n②高山拿铁咖啡+半塘拿铁价值35.9元，领券购买15.9元\n\n[礼物]实付满35元送价值29.9元的咖百味随机两袋。\n\n点击下方微信商城链接，按照自己选择的方式~\nhttps://shop90886329.m.youzan.com/v2/feature/6CCdNxGULw","msg_type":"text","openid":"61ad6463216eab9934730fb808905ad3f75af8fdc3b757d434dac2dbcfe099fc"}, response:{"code":410403,"msg":"客服发送异常","success":false} 
## 期望结果 和 实际结果(必填) +
消息正常发送 + 接收消息
 +实际报错 410403
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by abandonedkid** [comment]
回复文案存在引流行为
