### ISSUE TITLE
webview配置业务域名后，一直302，从浏览器访问正常

### ISSUE THREAD

**Issue by 15732631053** [redengineer/redmini#193]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
* [x]  IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
* [x] 小程序开发者工具(IDE) +
* [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
* [x]   其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
小程序版本库:v3.33.0
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![小程序ide抓包现象](https://wechatapppro-1252524126.cdn.xiaoeknow.com/appAKLWLitn7978/image/b_u_5b2225aa46488_oGKN7IvA/l6pvc78c065c.png?imageView2/2/w/200/q/60)
小程序业务域名:
h5.inside.xiaoeknow.com;apppchqltpt3482.h5.inside.xiaoeknow.com;appnpz8l6ru1746.h5.inside.xiaoeknow.com

webview地址:https://appnpz8l6ru1746.h5.inside.xiaoeknow.com/p/course/video/v_62344a2ee4b01f97f0ba55fa

ide抓包一直302，但是从浏览器上可以访问成功
 +
## 期望结果 和 实际结果(必填) +
能够正常加载webview地址（https://appnpz8l6ru1746.h5.inside.xiaoeknow.com/p/course/video/v_62344a2ee4b01f97f0ba55fa）
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
在通过pc访问的时候，会经历一次302，然后加载页面，但是在小程序嵌这个webview时，在业务域名已配置的情况，一直302

**Comment by Hubmeat** [comment]
IDE 上在配置栏中，开启「不校验 http 链接」功能了吗？

**Comment by 15732631053** [comment]
> IDE 上在配置栏中，开启「不校验 http 链接」功能了吗？

没有开启「不校验 http 链接」，DE最新版：1.59.24没找到这个开关

**Comment by ThisIsBritta** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/29575851/184606603-fdcf4bcb-9077-4f5b-acf9-fae0b6c6ce82.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/29575851/184606734-ae524075-5a58-4d25-ae6c-63b7b5743a79.png">
没有看到这些配置的按钮

**Comment by Hubmeat** [comment]
抓包对比下正常情况下的请求和 IDE 请求的 header, 看是不是缺少了 referer 这类字段导致 302.

如果是 header 导致可能要服务后端看下请求头的差异和服务器拦截限制
