### ISSUE TITLE
movable-view 滑动卡顿

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#194]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
`
<view class="page">
    <movable-area class="wrap">
      <movable-view direction="all" x="{{200}}" y="{{200}}" damping="{{200}}" class="content">
        <view class="content-btn">拖动按钮</view>
      </movable-view>
    </movable-area>
</view>
`

`
.page{
    width:100vw;
    height:100vh;
}
.page .wrap{
    width:100%;
    height:100%;
    background-color: beige;
}

.content{
    width: 80px;
    height: 80px;
    pointer-events: auto;
    background-color: red;
}
`

https://user-images.githubusercontent.com/63334662/184567053-18311cf0-2dbd-4c7f-bcac-e3af17149bc5.mp4

滑动过快没反应，只能慢慢的拖动

 +
## 期望结果 和 实际结果(必填) +
正常拖拽无卡顿
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
是要实现什么功能呢，最新版本的话，可以考虑使用 sjs 来实现拖拽：

https://miniapp.xiaohongshu.com/docs/frame/sjsIntro

**Comment by echooys** [comment]
> 是要实现什么功能呢，最新版本的话，可以考虑使用 sjs 来实现拖拽：
> 
> https://miniapp.xiaohongshu.com/docs/frame/sjsIntro

taro 没办法用sjs语法呀

**Comment by echooys** [comment]
> 是要实现什么功能呢，最新版本的话，可以考虑使用 sjs 来实现拖拽：
> 
> https://miniapp.xiaohongshu.com/docs/frame/sjsIntro

是一个浮动在页面的客服按钮，可以随意拖拽，现在 movable-view 实现的 很卡，只能慢慢得拖动，稍微快点就卡在那

**Comment by Hubmeat** [comment]
好的了解，你提供下代码片段我们这边排查下， taro 这边不支持 sjs 的问题近期会再推进下。

**Comment by echooys** [comment]
> 好的了解，你提供下代码片段我们这边排查下， taro 这边不支持 sjs 的问题近期会再推进下。

上面重现步骤里就有基础的代码 都会卡顿

**Comment by Hubmeat** [comment]
IDE 上可能因为模拟手势冲突导致的问题，可以在真机上试试应该没这个问题。

**Comment by echooys** [comment]
> 

真机也是一样

**Comment by Hubmeat** [comment]
您好，这个问题预计在 754 RC 版本 fix
