### ISSUE TITLE
previewImage 显示页码

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#195]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

![601660530560_ pic](https://user-images.githubusercontent.com/63334662/184567548-cff2bf13-74c0-4aa4-a20f-956335e46147.jpg)

previewImage 是否可以添加页码显示
 +
## 期望结果 和 实际结果(必填) +
previewImage 添加页面 当前索引 总数
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
微信内，你们有这个需求吗？

**Comment by echooys** [comment]
> 
有的，微信有页码显示

**Comment by taiyiandr** [comment]
Android 7.53 版本提供
