### ISSUE TITLE
swiper 设置circular previous-margin next-margin 时与预期效果不符

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#196]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/184572046-40375ce6-350e-4fad-8f30-830dc3314844.png)

设置了previous-margin 当前current 是第一个时 没有露出最后一个 一部分，只有往右滑动了一次才会显示出来
![image](https://user-images.githubusercontent.com/63334662/184572189-65ec5e00-4766-46df-a203-6ced1ce04765.png)
<img width="473" alt="image" src="https://user-images.githubusercontent.com/63334662/184572505-ffa35924-3efa-4d3a-935e-4ac3077b2235.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/63334662/184572369-b0bb7f74-0840-4ffe-b251-8050fa92139c.png">

 +
## 期望结果 和 实际结果(必填) +
默认就可以显示出最后一项的一部分
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Edge00** [comment]
@echooys  该问题在基础库 v3.34.1 版本已修复，请切换到 v3.34.1 版本验证
