### ISSUE TITLE
scroll-view ios 惯性滚动时无法更新scroll-(x|y)、scroll-into-view 的值

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#197]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

https://user-images.githubusercontent.com/63334662/184572974-49b5a8b9-61fa-44e8-8295-acb30dd68de9.mp4

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Edge00** [comment]
该问题在基础库 v3.34.1 版本已修复，请切换到 v3.34.1 版本验证

**Comment by Edge00** [comment]
这个问题还有吗，有的话麻烦补充下提供代码片段吧
