### ISSUE TITLE
线上环境，部分机型input输入的内容无法被获取到。

### ISSUE THREAD

**Issue by csxian2012** [redengineer/redmini#20]
## 系统环境(必填)
- [ √ ] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [ √ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.18.1
## 重现步骤 和 复现问题的最小demo Github链接
IDE无法重现，表现正常。仅部分真机异常。
## 期望结果 和 实际结果(必填)
使用uni框架，input输入内容，提交时检查是否为空。
期望结果：input有值时提交成功。
实际结果：线上部分机型始终为空，校验始终无法通过。

**Comment by xutm** [comment]
出问题的 iOS 机器的 系统版本号，也同步下吧

**Comment by csxian2012** [comment]
> 出问题的 iOS 机器的 系统版本号，也同步下吧

IOS13.1 会出现此问题，App侧反馈已发布hot fix，待客户反馈
