### ISSUE TITLE
getMenuButtonBoundingClientRect位置信息返回错误

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#200]
---
name: getMenuButtonBoundingClientRect位置信息返回错误
about: 商品详情的返回按钮位置根据getMenuButtonBoundingClientRect获取的信息进行布局，现在这个api返回了错误的位置信息，导致我们的商详返回按钮位置错乱
title: ''
labels: ''
assignees: ''

---
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 、v7.48.1
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
1. 苹果12，小红书App版本v7.48.1
2. 打开【白狮美瞳集合店】小程序
3. 进入商详
![wecom-temp-f0fae082ba68dbfa85bf2fcd3210e2cd](https://user-images.githubusercontent.com/33249100/184628713-3410671e-a9dd-4dfd-adbe-c37c0e7ee079.jpg)
 

## 期望结果 和 实际结果(必填) +
getMenuButtonBoundingClientRect返回位置信息正确
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
正常getMenuButtonBoundingClientRect位置信息返回：
![origin_img_v2_2ad2ba9a-d749-495a-adb5-0fc1377f3e3g](https://user-images.githubusercontent.com/33249100/184628542-2bd0667c-d34b-4569-867b-5118a16c9b42.jpg)

展示有问题时拿到的胶囊位置信息：
![origin_img_v2_db8bce95-0e6f-4409-a22d-8f3a37b04deg](https://user-images.githubusercontent.com/33249100/184628584-3d22a143-bae9-4274-b2fc-60d647b4d8ea.jpg)

**Comment by AngryBrotherXiang** [comment]
iOS 7.53 fix

**Comment by echooys** [comment]
> iOS 7.53 fix

安卓也有同样的问题，模拟器也是

**Comment by Hubmeat** [comment]
可以提供下 demo 嘛

**Comment by echooys** [comment]
> 可以提供下 demo 嘛

![image](https://user-images.githubusercontent.com/63334662/186888091-2a2f5f89-9132-4e83-901c-079b83b9549d.png)
![image](https://user-images.githubusercontent.com/63334662/186888125-82640fae-7d2d-4730-b687-2ebc4bc75c60.png)

**Comment by jonsen-liu** [comment]
top怎么都不可能是600+

**Comment by jonsen-liu** [comment]
> 可以提供下 demo 嘛

这个问题大概什么时候好？
![BFE26B43-E893-4455-AE70-0837B1069CE0](https://user-images.githubusercontent.com/26186472/187817677-ae3b1717-cabf-4891-b53e-ec88979f023a.png)

**Comment by jonsen-liu** [comment]
5天过去了，还是没结果么？
