### ISSUE TITLE
页面跳转时白屏较明显

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#204]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
页面跳转时白屏较明显，无法从代码层面优化，顾客体验不好，求问小程序端如何改善
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
你好，请问能否提供录屏，具体case能列举一下吗？

**Comment by echooys** [comment]
> 你好，请问能否提供录屏，具体case能列举一下吗？

https://user-images.githubusercontent.com/63334662/185062710-67349385-6d13-49c0-b039-1568cdacfa19.mp4

页面跳转是 大概有1s左右的白屏 下一个页面才渲染出来

**Comment by Hubmeat** [comment]
这个只能通过性能优化来解决了，初渲染 taro 有大量的节点进行传输，在节点未处理结束到达渲染层之前，页面没有内容的。

我们先内部拉群聊下吧

**Comment by echooys** [comment]
> 这个只能通过性能优化来解决了，初渲染 taro 有大量的节点进行传输，在节点未处理结束到达渲染层之前，页面没有内容的。 即 taro 场景下，页面一开始是没有内容的，所以页面是白色。 等 taro 处理结束后，才开始通知框架进行绘制。 taro 是否有什么优化或预加载策略？

taro 的预加载只能针对异步数据预加载，但目前节点渲染慢的情况没有好的办法

**Comment by Hubmeat** [comment]
长期需要看下 taro demo 结合小红书场景的优化策略，需要用 taro 的 demo 进行优化排查。

短期方案，可以考虑将部分页面切换为原生实现，这些 loading 动画一开始就会 run 在渲染层（和微信一样）。
