### ISSUE TITLE
openDocument 打开PDF时，用户没有相关pdf软件时显示空白

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#205]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
openDocument 打开PDF时，用户没有相关pdf软件时显示空白
 +
## 期望结果 和 实际结果(必填) +
正常打开pdf 预览跟用户有没有相关软件无关
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by echooys** [comment]
`
<view class="page">
    <view bindtap="handleDownLoad">下载发票</view>
</view>
`

`
Page({
    handleDownLoad(){
        xhs.downloadFile({
            url: 'https://www-pre.baiwang.com/fp/d?d=78384372C3EBD6323C50912119383DE7C7FCAF9E05A86B09DA1B0DF6587CBCB8',
            header: {
              'Content-Type': 'application/pdf'
            },
            success({ statusCode, tempFilePath: filePath, errMsg }) {
              if (Number(statusCode) == 200) {
                xhs.showToast({
                  title: '发票下载成功',
                  icon: 'success',
                  duration: 1500,
                  complete(){
                    xhs.openDocument({
                        filePath,
                        fileType: 'pdf'
                    });
                  }
                });
              } else {
                xhs.showToast({
                  title: errMsg,
                  icon: 'none',
                  duration: 1500
                });
              }
            },
            complete(){
            }
          })
    }
})
`

https://user-images.githubusercontent.com/63334662/185532019-9de19d93-6ae1-4566-b584-c306648922db.mp4

**Comment by pengweinan123** [comment]
问题预计755版本修复，目前只支持下载链接带有文件格式(.pdf/.doc等)
eg：https://www-pre.baiwang.com/fp/d?d=78384372C3EBD6323C50912119383DE7C7FCAF9E05A86B09DA1B0DF6587CBCB8.pdf
