### ISSUE TITLE
请问对接小红书有java的sdk包可以用吗

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#207]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

 +
## 期望结果 和 实际结果(必填) +
请问对接小红书有java的sdk包可以用吗
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
你好，如果是以小程序的方式接入，则不需要sdk，与业界标准的小程序开发模式相同。
https://miniapp.xiaohongshu.com/docs/guide/miniIntroduce

**Comment by xuwenjie0505** [comment]
https://miniapp.xiaohongshu.com/third/api-3rd/post-api-rmp-tp-auth-apps-qrcode-unlimited
 也应该会用到第三方api这部分接口的，这部分接口有sdk吗

**Comment by xuwenjie0505** [comment]
请问目前小红书是所有接口都没有sdk提供是吗

**Comment by taiyiandr** [comment]
> 请问目前小红书是所有接口都没有sdk提供是吗

嗯，服务端还是面向restful接口对接，不考虑针对特定语言提供sdk。
