### ISSUE TITLE
授权流程的推送ticket授权事件问题

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#209]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
你好，我这边正在开发小红书api，我这边的服务商ID=62ecc606a44cb400012a7507，我看了这个接口文档https://miniapp.xiaohongshu.com/third/api-3rd-doc/pushTicket，服务商创建后，小红书会每隔 10 分钟以 POST 请求向 授权事件接收 URL 发送 ticket 消息。但是我这边观察了并没有收到授权事件请求，麻烦帮忙看看没有收到授权事件请求的原因，如果是哪里配置问题麻烦告知下，谢谢了。

 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by abandonedkid** [comment]
最近一次10:14:14发送过ticket，HTTP请求是POST，response status是405，请先检查下你们的接口是否支持POST

**Comment by xuwenjie0505** [comment]
你好，我这边试了postman测试post方式是正常的呢，可以麻烦你再帮忙看看吗
![image](https://user-images.githubusercontent.com/111478514/185852226-a8ce8d78-6eb6-451b-8330-b0378ef17277.png)

**Comment by abandonedkid** [comment]
> 你好，我这边试了postman测试post方式是正常的呢，可以麻烦你再帮忙看看吗 ![image](https://user-images.githubusercontent.com/111478514/185852226-a8ce8d78-6eb6-451b-8330-b0378ef17277.png)

你这个 URL 是【消息事件接收 URL】，ticket 推送的【授权事件接收 URL】，你的【授权事件接收 URL】是不支持 POST 的
