### ISSUE TITLE
微盟Picker组件相关异常问题

### ISSUE THREAD

**Issue by csxian2012** [redengineer/redmini#21]
## 系统环境(必填)
- [√] IOS
- [√] Android
- [√] IDE

## 问题模块(必填)
- [ ] 审核
- [√] API & 组件 & 框架
- [√] IDE
- [√] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
APP：7.38.1，基础库：default

## 期望结果 和 实际结果(必填)
期望结果：
可以正常选择选项，默认正常选中当前时间；

实际结果：
iOS：picker再次点击，显示NaN；
Android：picker未默认选中当前日期；

**Comment by Hubmeat** [comment]
未复现，提供下业务流程最小 demo

**Comment by csxian2012** [comment]
已更换新版小程序组件库，该问题不做处理了。
