### ISSUE TITLE
@tarojs/plugin-platform-xhs 插件问题与需求整理

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#210]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
**1.scroll-view 内存在swiper组件时触发警告**
![image](https://user-images.githubusercontent.com/63334662/185836690-59480b50-b8d0-4ebc-bfa8-3fa71fd5f3f9.png)

**2.view组件手势事件无法使用**
![image](https://user-images.githubusercontent.com/63334662/185837152-dd72da14-2570-467e-9c05-b3b65b172f25.png)
给插件添加了view相关手势事件会与swiper事件冲突，导致swiper手势无效

**3.组件属性事件缺失需添加**
![image](https://user-images.githubusercontent.com/63334662/185836921-3fc0e24b-9010-42b6-852f-3ea4300cc379.png)

**4.配置文件冲突是否可以更改project.config.json 为project.xhs.json**

**5.scroll-view需添加enable-flex属性**

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
好的，这个提供下 swiper 嵌套 scroll-view 的 demo 吧，我们内部排查下

**Comment by Edge00** [comment]
开发框架（React / Vue / Vue3）使用的哪个？

**Comment by echooys** [comment]
> 开发框架（React / Vue / Vue3）使用的哪个？

react

**Comment by Edge00** [comment]
问题 2 和 问题 3 麻烦提供下更详细的 demo 吧，目前提供的没有相关逻辑
<img width="981" alt="image" src="https://user-images.githubusercontent.com/23715779/186063740-2bcf9208-7d54-4408-a32f-d266aba4a51e.png">

**Comment by Edge00** [comment]
`@tarojs/plugin-platform-xhs@1.0.0` 已发布，修复了问题 3 和问题4，问题 1 会在下一个基础库版本修复

**Comment by Edge00** [comment]
@echooys  我在 IDE 中试过了，基础课版本小于 3.35.0 稳定复现，大于 3.35.0 没有出现 warning，麻烦再验证下

**Comment by echooys** [comment]
> @echooys 我在 IDE 中试过了，基础库版本小于 3.35.0 稳定复现，大于 3.35.0 没有出现 warning，麻烦再验证下

需求5什么时候发版呢~，发了我在测试一下吧不然还是要每次改插件
