### ISSUE TITLE
引导商家在小红书APP上授权失败问题

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#212]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
授权报错截图：![lQDPJxaetTfYE_rNCSTNBDiweAE0DPwzGCADBRfifAChAA_1080_2340](https://user-images.githubusercontent.com/111478514/186324691-fbad4bca-9f04-4527-ad71-e5e3fe8d3ccd.jpg)
授权二维码链接：https://admin.zowoyoo.com/xhs/getQRCode-png.jsp?saasId=84826
 +
## 期望结果 和 实际结果(必填) +
你好，我这边在对接小红书，对接到了小程序引导授权，但是授权后提示了授权回调地址无效，我检查了这边的回调地址是正常的，这个是回调地址：https://xhs-open-stag.zowoyoo.com/openapi/app/auth/get_app_auth_code ；麻烦帮忙看看授权失败具体是什么原因呢，服务商id=62ecc606a44cb400012a7507，小程序id=62e8c26d65ba04000150223c
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by abandonedkid** [comment]
看下你们的【授权页域名】配置，与你的回调页地址域名不一致
