### ISSUE TITLE
xhs.chooseImage  API在ios 真机上选择图片后3个回调均不执行

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#213]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 领克 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.52 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
3个回调均不执行
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/31440366/186370191-6039c569-8641-4364-8278-a115909ffe77.png">

 +
## 期望结果 和 实际结果(必填) +
回调及参数正常执行 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by AngryBrotherXiang** [comment]
未复现，麻烦发下提供出错demo

**Comment by jianchaoWang4515** [comment]
> 未复现，麻烦发下提供出错demo

1. 是我回调里uni.toast 没执行
2. chooseImage 成功回调的图片地址路径ios端<image />标签无法加载
