### ISSUE TITLE
taro react  循环渲染swiper-item，当数组长度为1时无法渲染

### ISSUE THREAD

**Issue by xf079** [redengineer/redmini#215]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/63334662/187143936-c03446ba-d554-4ccd-bcc8-958550e78606.png)

images 长度为1时 swiper-item没渲染，2个以上才能正常渲染，没有任何报错

但是编译到其他平台又是正常的，不确定问题出在那里

## 期望结果 和 实际结果(必填) +

可以正常渲染1个swiper-item

## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
麻烦提供下 demo 吧

**Comment by echooys** [comment]
> 麻烦提供下 demo 吧

`
    <Swiper circular>
      <SwiperItem>
        <View className='item'>
          <Image src='https://m.dior.cn/couture/ecommerce/media/catalog/product/cache/1/cover_image_mobile_1/715x773/17f82f742ffe127f42dca9de82fb58b1/t/S/1645731911_B1133PMTCY_D301_E01_GHC.jpg' />
        </View>
      </SwiperItem>
    </Swiper>
`

排查到问题了，加了circular 属性  只有一个swiperItem就无法渲染
