### ISSUE TITLE
TextArea换行输入异常

### ISSUE THREAD

**Issue by csxian2012** [redengineer/redmini#22]
## 系统环境(必填)
- [√] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [√] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
App：7.38.1 基础库：default

## 期望结果 和 实际结果(必填)
期望结果：换到第二行输入。
实际结果：IOS，换行输入时，换行后又回到了第一行，无法定位到第二行

**Comment by xutm** [comment]
可以录个屏吗？

**Comment by xutm** [comment]
无法复现，暂时关闭
