### ISSUE TITLE
开发者工具 真机预览  IOS扫码后提示 小程序服务异常

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#226]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.53(7530209)
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by jonsen-liu** [comment]
![lADPJxRxSs9Fkb7NBQDNAlA_592_1280](https://user-images.githubusercontent.com/26186472/187615500-acb28687-f75d-4868-ae4e-11adb29de8fa.jpg)

**Comment by AngryBrotherXiang** [comment]
这是通用报错，麻烦发下小程序的appId，和扫码异常时userId，userId在小红书APP - 我 - 右上角分享icon - 弹出来的分享面板左下角 复制链接，，把复制链接的结果发出来。

**Comment by jonsen-liu** [comment]
> 这是通用报错，麻烦发下小程序的appId，和扫码异常时userId，userId在小红书APP - 我 - 右上角分享icon - 弹出来的分享面板左下角 复制链接，，把复制链接的结果发出来。

小程序appid  62e8c26d65ba04000150223c
userId  https://www.xiaohongshu.com/user/profile/615833350000000002027a53?xhsshare=CopyLink&appuid=615833350000000002027a53&apptime=1661942349

**Comment by AngryBrotherXiang** [comment]
出错的具体时间呢，最好精确到分钟？

**Comment by jonsen-liu** [comment]
> 出错的具体时间呢，最好精确到分钟？

今天  12 点 02 分 50秒左右
