### ISSUE TITLE
IOS 真机预览  request 请求返回 异常，安卓正常

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#227]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.54.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by jonsen-liu** [comment]
![image](https://user-images.githubusercontent.com/26186472/187661189-768743e4-0343-40c4-ada8-f1ce55eb9468.png)

**Comment by AngryBrotherXiang** [comment]
由于系统限制，不同平台对于证书要求的严格程度不同。
https://developers.weixin.qq.com/community/develop/doc/000eec1dab0a40b7baba9135d56800?highLine=%2520err_ssl_version_or_cipher_mismatch

https://developers.weixin.qq.com/community/develop/article/doc/0000ec596949589e14f8641785bc13

**Comment by jonsen-liu** [comment]
> 由于系统限制，不同平台对于证书要求的严格程度不同。 https://developers.weixin.qq.com/community/develop/doc/000eec1dab0a40b7baba9135d56800?highLine=%2520err_ssl_version_or_cipher_mismatch
> 
> https://developers.weixin.qq.com/community/develop/article/doc/0000ec596949589e14f8641785bc13

但是   微信小程序/字节小程序/百度小程序/支付宝小程序   都正常哦
![image](https://user-images.githubusercontent.com/26186472/187825599-d19006db-860b-4fd4-9e9d-4dd25e4204dc.png)
