### ISSUE TITLE
Android手机，部分第三方登录的账号，获取用户信息错误

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#228]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.53 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
部分第三方登录的账号，点击获取用户信息时，返回的数据和用户信息不符

## 期望结果 和 实际结果(必填) +
可以返回用户的正确信息

## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
后端接口已全量修复
