### ISSUE TITLE
推送了商品但是在小红书订购页面没有展示出来

### ISSUE THREAD

**Issue by anzzz999** [redengineer/redmini#231]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.53.0 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![6f5d84f532af0def4215927dc90f1b6](https://user-images.githubusercontent.com/50934953/188038974-309fa8dd-9bef-4547-8414-482cfdd2a60e.jpg)
 +
## 期望结果 和 实际结果(必填) +
实际结果：无展示商品
期望结果： 展示对应商品

 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
这个商户推送了商品但是没有展示出来。我查商品都是上线状态。
小程序id：62c59d7bb7945e0001577ee8
小红书名称：黄鹿山云栖别居民宿
商品id:
1546777696280948738
1546777630429229058
1546777735215525890
1546777469801005058
1546777553833996290

**Comment by wdvxdr** [comment]
数据已修正
