### ISSUE TITLE
开发工具调用getLocation和chooseImage报错

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#233]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 领克
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 开发工具 1.59.29+
调试基础库 3.34.3
## 重现步骤 和 复现问题的最小demo Github链接 +
1.开发工具先调用authorize进行授权，在调用getLocation直接报错（真机同样报错）
![image](https://user-images.githubusercontent.com/18606361/188068035-69bb4630-9356-4391-ac68-aadec61a4ab5.png)
2.开发工具调用chooseImage方法不能打开本地文件夹，出现选择的不知道是哪里的图片，也直接报错了
![image](https://user-images.githubusercontent.com/18606361/188068274-a11802bb-bed0-4901-84d7-cce503dbe2f6.png)
![image](https://user-images.githubusercontent.com/18606361/188068313-43126e53-f8c4-4ff5-ac18-f51b47112bd0.png)

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
已和issue提出者确认，真机双端定位功能正常。IDE问题

**Comment by fanqidong** [comment]
@taiyiandr  IDE无法调用getLocation方法 真机可以， 这个问题不处理了吗？

**Comment by taiyiandr** [comment]
> @taiyiandr IDE无法调用getLocation方法 真机可以， 这个问题不处理了吗？

IDE 问题后面会由对应的同学跟进处理
