### ISSUE TITLE
小红书小程序授权绑定失败，提示：”不支持授权给自己“

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#237]
---
about: 小红书小程序授权绑定失败，提示：”不支持授权给自己“
title: ''
labels: ''
assignees: ''

---
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [x] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.53
 
## 重现步骤 和 复现问题的最小demo Github链接 +
appid：61696cf8c52bb0000110bad2

https://b.yzcdn.cn/public_files/320a221a269bbc01bea5ca1564a8fbce.jpg

 +
## 期望结果 和 实际结果(必填) +
正常授权绑定
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
是因为服务商主体和专业号主体是同一个导致吗？

**Comment by wdvxdr** [comment]
相同专业号userId无法进行授权，与报错提示一致“应用不能授权自己”
