### ISSUE TITLE
修改订单存在问题

### ISSUE THREAD

**Issue by anzzz999** [redengineer/redmini#238]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
麻烦帮忙看看这个out_order_id 1557690254497390593 订单的 real_price 是否为0，我这边修改数据传real_price过去，接口返回调用成功，但是我查了一下这个订单的real_price还是0。

修改成功的请求
"Cat-Msg-Id":["karen-ac14e2ea.37943-461767-1347562","openapiminiapp-ac14afdb.0045467-461767-10652"],
"Request-Id":["8eea4f284ca748f89f6871cc36a2ec6d"]

修改后查询出来还是0
![image](https://user-images.githubusercontent.com/50934953/188397075-bb82a20a-1f7f-4389-8949-f9acd73c3fb5.png)

 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
可能存在缓存问题

**Comment by wdvxdr** [comment]
订单提交后，仅待支付状态能修改订单信息，其他状态仅支持状态流转，不支持信息（包括价格）修改
订单状态机见 https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-mp-deal-order-sync_status
