### ISSUE TITLE
非 Tab 页无法通过右上角胶囊按钮分享

### ISSUE THREAD

**Issue by dxp-dan** [redengineer/redmini#24]
胶囊分享按钮 弹出分享给朋友是灰色的

**Comment by dxp-dan** [comment]
问一下胶囊分享按钮 弹出 分享给朋友按钮的禁用规则是什么

**Comment by xutm** [comment]
https://miniapp.xiaohongshu.com/docs/frame/Page#onShareAppMessage-Object-object

页面下面需要配置 `onShareAppMessage `，才可以
