### ISSUE TITLE
getMenuButtonBoundingClientRect 位置信息 开发者工具和真机表现不一致

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#244]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by jonsen-liu** [comment]
![image](https://user-images.githubusercontent.com/26186472/188767417-f40be27b-19d2-41f6-ab15-fdfb7a2cf375.png)

**Comment by Hubmeat** [comment]
您好，由于策略调整，IDE 目前处于维护状态，IDE 相关问题都得不到优先支持，排在最低优。后续修复会在 issue 同步，给您这边开发带来麻烦，抱歉。
