### ISSUE TITLE
xhs.stopPullDownRefresh 方法会报未捕获异常

### ISSUE THREAD

**Issue by liangqingfengfeng** [redengineer/redmini#25]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.23.0
## 重现步骤 和 复现问题的最小demo Github链接
`
onPullDownRefresh(from) {
   wx.stopPullDownRefresh();
 },
`
<img width="911" alt="image" src="https://user-images.githubusercontent.com/52652101/168720545-06f7e20e-6646-4bad-9413-ec507f2f20b8.png">

## 期望结果 和 实际结果(必填)
不出现未捕获异常

**Comment by xutm** [comment]
IDE 1.59.26 已修复，建议下载最新版
