### ISSUE TITLE
交易组件订单-获取订单信息接口调用失败问题

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#251]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
调用订单-获取订单信息接口https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/get，返回该错误{"data":null,"success":false,"msg":"内部系统异常","code":500001}，请求的body为{"out_order_id":"697274045","open_id":"6180a2d69dd8b58fb393f64abae469d77aff076285f5dbbb6977d03a390a2129"}，开发的小程序id=62e8c26d65ba04000150223c，麻烦帮忙看看这个异常报错，谢谢
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by wdvxdr** [comment]
该订单目前已完成，5XX异常考虑是内部服务超时。
若复现请再次联系
