### ISSUE TITLE
支付域名配置问题

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#252]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
文档提示在专业号平台->店铺->域名与推送配置支付中间页链接的域名，但是我登录了专业号平台并没有看到这个选项，麻烦帮忙看看，小程序id=62e8c26d65ba04000150223c
![image](https://user-images.githubusercontent.com/111478514/189295632-28482276-19b2-40c9-b6ac-18ab6657cd7c.png)

 +

**Comment by xutm** [comment]
服务商，需要通过接口进行设置

**Comment by xuwenjie0505** [comment]
可以麻烦您说下文档哪个地方有介绍是通过哪个接口设置的呢，我看文档没有看到呢

**Comment by xuwenjie0505** [comment]
@xutm 您好，麻烦帮忙指引下服务商如何通过接口进行支付中间页链接的域名配置的，谢谢了
