### ISSUE TITLE
Taro动态设置maxHeight发现失效

### ISSUE THREAD

**Issue by WeiJietao** [redengineer/redmini#26]
## 系统环境(必填)
- [X] IOS
- [X] Android
- [X] IDE

## 问题模块(必填)
- [ ] 审核
- [X] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)

1.59.23-beta.22

## 期望结果 和 实际结果(必填)

style动态设置maxHeight发现失效，改为height则生效。（下方"查看更多详情"变为"点击收起"，证明状态值expandBtnStatus是正常变化的）

![截屏2022-05-17 下午4 07 22](https://user-images.githubusercontent.com/18640419/168767276-0f2d46eb-1bf0-49fc-80b6-cb7e5a913f70.png)

![截屏2022-05-17 下午4 30 38](https://user-images.githubusercontent.com/18640419/168767288-e331918c-cf02-4f95-b53b-72be0026e19d.png)

**Comment by Hubmeat** [comment]
style: 'max-height'  可以解决问题
