### ISSUE TITLE
properties接收了一个对象，对象里面的函数会丢失

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#266]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
IDE版本版本: 3.36.2 其实一直没有这个功能
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

[xhs_demo 2.zip](https://github.com/redengineer/redmini/files/9573830/xhs_demo.2.zip)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
JSON.stringfy导致丢失了

**Comment by coshinehcl** [comment]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/90542393/190369840-322a2761-63d2-471e-88e6-498623db1e43.png">

**Comment by Hubmeat** [comment]
提供下复现 demo 吧

**Comment by coshinehcl** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/90542393/190939748-7efd8303-9b62-4427-b998-f9257213a1ab.png">
有提供的

**Comment by coshinehcl** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/90542393/192479312-2cfc7528-c6c6-4073-a186-23163d4ffe07.png">

**Comment by coshinehcl** [comment]
这个优先级比较高，麻烦优先处理下

**Comment by Hubmeat** [comment]
你好开发者，小红书小程序不支持在 data 中透传 function ，可以考虑下使用其他的策略实现互调

**Comment by coshinehcl** [comment]
好的

**Comment by coshinehcl** [comment]
感谢
