### ISSUE TITLE
组件如果使用了template和behavior，且behavior使用了setData修改了视图的变量，this会不对

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#268]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
IDE版本库：v3.36.2 
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
[xhs_demo 2.zip](https://github.com/redengineer/redmini/files/9573871/xhs_demo.2.zip)
<img width="718" alt="image" src="https://user-images.githubusercontent.com/90542393/190368152-9d76aff4-24d1-4c9d-85d6-e73e11ff8300.png">

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by coshinehcl** [comment]
我今天测试下来是这样子：template是延后渲染的
<view xhs:if="{{isShow}}">
   <template is="default"></template> // 这个时候的template里面的事件执行的this会乱掉
</view>

**Comment by coshinehcl** [comment]
我今天测试下来是这样子
```xml
<view xhs:if="{{isShow}}">
 <!--这个时候template里面绑定的事件的this会乱掉，也就是isShow延后渲染就会带来这个问题-->
  <template is="default"></template>
</view>
```

**Comment by Hubmeat** [comment]
麻烦提供下可复现的代码包吧

**Comment by coshinehcl** [comment]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/90542393/190939693-fff19d7a-5dee-4068-8928-5c25cb0648de.png">
有提供的

**Comment by Hubmeat** [comment]
您好，这个问题在跟进中，目前定位和 behavior 无关，是因为 xhs:if 指令导致引用实例错乱引发，目前建议先避免在 template 外层包裹 xhs:if 指令，后续修复后我们会在 issue 下进行同步，时间暂未确定。
