### ISSUE TITLE
observers，触发更新时，this.data不能同步获取到props上的其他值

### ISSUE THREAD

**Issue by csxian2012** [redengineer/redmini#27]
## 系统环境(必填)
- [√] IOS
- [√] Android
- [√] IDE

## 问题模块(必填)
- [ ] 审核
- [√] API & 组件 & 框架
- [√] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
App：7.38，基础库3.23
## 重现步骤 和 复现问题的最小demo Github链接
[observers.zip](https://github.com/redengineer/redmini/files/8706830/observers.zip)
## 期望结果 和 实际结果(必填)
期望：observers，触发更新时，this.data可以获取到props上的其他值
实际结果：this.data不能同步获取到props上的其他值

**Comment by Hubmeat** [comment]
您好，这个兼容将在小红书 7.42, 基础库 >= 3.24.1 版本修复，预计发布时间 5月25日。到时可以关注下
