### ISSUE TITLE
订单结算失败

### ISSUE THREAD

**Issue by anzzz999** [redengineer/redmini#270]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
订单和售后单正常推送，订单状态为已完成（7），售后单状态为 拒绝退款（3） ，但是结算时报 订单或者售后单数据未同步
商户小程序id 62b93ea4a5d04b00012b6486
订单id 1566818534274199554
售后单id 1566822577620172801

麻烦帮忙看看是什么原因结算失败，谢谢

 +
## 期望结果 和 实际结果(必填) +

期望正常结算
 +

**Comment by wdvxdr** [comment]
请确认下，售后单是否成功同步

**Comment by anzzz999** [comment]
> 请确认下，售后单是否成功同步

售后单同步成功，能通过接口查询的到，金额正确，状态为拒绝退款。结算时报 订单或者售后单数据未同步。麻烦帮忙看一下是什么原因结算不了

结算时的参数：
{
    "out_order_id":"1566818534274199554",
    "out_after_sales_order_ids":[
        "1566822577620172801"
    ],
    "out_settle_id":"1566818568666660865",
    "after_settle":0
}

**Comment by wdvxdr** [comment]
售后失败的售后单无需在结算时同步过来，后面考虑在结算的时候过滤掉售后失败的售后单
先去掉该售后单，再尝试结算一下
