### ISSUE TITLE
小程序历史用户，发布新版本后，再次进入小程序后会偶发出现旧版数据、样式错乱、白屏等问题

### ISSUE THREAD

**Issue by viclee25** [redengineer/redmini#274]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [x] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.55.1 +（ios环境）
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
复现前提：
用户之前有进入过小程序，在发版之后再次进入小程序后，会出现显示旧版数据、样式错乱、白屏等问题
需要反复多次退出进入小程序才能正常
示例：https://locals-house-prod.oss-cn-shenzhen.aliyuncs.com//localhomeqy/demo/1663247959473408.mp4
 +
## 期望结果 和 实际结果(必填) +
每次更新后正常加载，不出现白屏、样式错乱等问题。
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
感觉应该是缓存机制的问题，我们小程序是taro写的，不知道是否与该架构有关

**Comment by taiyiandr** [comment]
Android 7.64 fix

**Comment by mocerliu** [comment]
2023年12月12日 09点43分 仍会出现以上问题， 看起来像是onshow或者app 的onready（如果他有的话）出现了问题， 安卓上切换app模拟onhide||onshow之后可以解决白屏问题， 这个issue在我们个人开发者这边其实很难描述清楚，很难在本地debugger，很难界定出错的逻辑有没有进入到本地源码的js逻辑中，在目前的调试中，尝试用UpdateManager配合做了更新新版本来解决缓存和白屏问题，但是无效。
