### ISSUE TITLE
小红书专业号主页商品排序接口bug

### ISSUE THREAD

**Issue by Wang-Xijie** [redengineer/redmini#275]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +无
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
调用商品排序接口报错，is_apply 为0的时候，也需要商品不为空
[小红书] baseRequest 调用小红书接口结束. response:{"code":400001,"msg":"参数不合法","success":false}，postUrl:https://miniapp.xiaohongshu.com/api/rmp/tp/display/home_page_item_tab?appid=623bea5915587a00014d302f&auth_access_token=92e4b4c7681147498effdc20f0cf8f83, request:{"is_apply":0}
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
实际结果。当选择不排序时，不添加商品报错
期望结果：当选择不排序时，商品可不填写

 +

**Comment by wdvxdr** [comment]
已修复
