### ISSUE TITLE
小红书下载文件api报错，但是看不出来具体错误

### ISSUE THREAD

**Issue by ggaier** [redengineer/redmini#278]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
V3.24.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
直接在小红书开发工具的console里执行`xhs.downloadFile({url: "https://c-ssl.duitang.com/uploads/item/202009/23/20200923185609_rQUdj.jpeg"})`，就会报错
 +
## 期望结果 和 实际结果(必填) +
期望结果能够完整的下载一个文件+
 +

**Comment by xutm** [comment]
只有 IDE 存在问题吗？

**Comment by ggaier** [comment]
> 只有 IDE 存在问题吗？
是的，只在IDE上下载图片会失败。

我是M1芯片, 12.5.1版本的系统；

IDE信息： 
> 版本: 1.59.29
> 提交: b1abbb66ea2c6c351ea762d310e29c17afa6f114
> 日期: 2022-08-22T11:21:41.908Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Darwin x64 21.6.0
