### ISSUE TITLE
button组件hover-class属性无效

### ISSUE THREAD

**Issue by Suntgr** [redengineer/redmini#28]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
基础库:3.23.0 
APP:1.59.23-beta.19 

## 重现步骤 和 复现问题的最小demo Github链接
点击button组件,没有自定义的点击效果；

[hover-class.zip](https://github.com/redengineer/redmini/files/8708522/hover-class.zip)

## 期望结果 和 实际结果(必填)
可以自定义hover-class

**Comment by Hubmeat** [comment]
您好，感谢你的提问。 这个 issue 修复将在小红书 7.42，基础库 >= 3.24.1 版本修复，预计发布时间 5月25日。到时可以使用官网最新的 IDE 测试下。
