### ISSUE TITLE
Android 7.55.0版本， xhs.uploadFile方法没有产生预期效果

### ISSUE THREAD

**Issue by ggaier** [redengineer/redmini#280]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.55.0 +
 
## 重现步骤 和 复现问题的最小demo Github链接 +
1. 使用`xhs.downloadFile({url: "https://c-ssl.duitang.com/uploads/item/202009/23/20200923185609_rQUdj.jpeg"})`下载文件。
2. 下载完成后，`xhs.uploadFile(tempFilePath, {uploadUrl, filepath, name ...})`
3. 在Android手机7.55版本上，该方法回调成功，但是实际上文件并没有上传成功， 服务端该文件并不存在。
4. 在iOS7.57.1版本上，该方法是执行成功了的。
5. 在小红书小程序开发工具上，首先是下载方法报错，所以没有观察到后续结果 [参考链接](https://github.com/redengineer/redmini/issues/278)

## 期望结果 和 实际结果(必填) +
 1. 文件上传能够成功
 2. 开发工具上能给出清晰的错误提示

**Comment by taiyiandr** [comment]
请提供下预览二维码，将小红书号 317940352 加一下预览权限。并说明如何操作复现，谢谢。

**Comment by taiyiandr** [comment]
> 请提供下预览二维码，将小红书号 317940352 加一下预览权限。并说明如何操作复现，谢谢。

本地测试上传下载均无问题，需要提供更多信息哈。

**Comment by ggaier** [comment]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/8504095/192773636-af319818-99a3-4e3c-a188-b3d7251eff8c.png">
测试流程：
1. 订单页面有一个【跳转到测试页面】按钮。
2. 测试页面点击按钮会执行上传逻辑。
3. 在上传成功后，会打印最后的上传地址。
代码如下：
```javascript
Page({
  onTestButtonClicked() {
    console.log(`onTestButtonClicked`);
    xhs.downloadFile({
      url: "https://c-ssl.duitang.com/uploads/item/201602/26/20160226125736_2Pefd.jpeg",
      fail: result => {
        console.log(`download file error: ${result.errMsg}`);
      },
      success: result => __awaiter(this, void 0, void 0, function* () {
        console.log(`download file done: ${result.tempFilePath}`);
        xhs.uploadFile({
          url: "",
          filePath: result.tempFilePath,
          header: {},
          formData: {
            "OSSAccessKeyId": "",
            "Signature": "",
            "key": "",
            "policy": "eyJleHBpcmF0aW9uIjoiMjAyMi0wOS0yOFQxMDo0Nzo0Ny40NjdaIiwiY29uZGl0aW9ucyI6W3sia2V5IjoidXBsb2FkLzAxODM3ODdlLTBhMTktZWU4My1lNTZiLWEwNzdhNGEzNGU1MC8wMTgzODNiMS0yMjI4LTZjYTUtNmRmNy1hNGNiM2FiNjUyODEifSx7IkNvbnRlbnQtVHlwZSI6ImltYWdlL2pwZWcifSx7Ingtb3NzLWNvbnRlbnQtdHlwZSI6ImltYWdlL2pwZWcifV19",
            "x-oss-content-type": "image/jpeg"
          },
          name: 'file',
          timeout: 10000,

          success() {
            console.log(`object url:...`);
          },

          fail(err) {
            console.log(`upload file failed: ${JSON.stringify(err)}`);
          }

        });
      })
    });
  }

});
```

**Comment by ggaier** [comment]
> <img alt="image" width="220" src="https://user-images.githubusercontent.com/8504095/192773636-af319818-99a3-4e3c-a188-b3d7251eff8c.png">
> 
> 测试流程：
> 1. 订单页面有一个【跳转到测试页面】按钮。
> 2. 测试页面点击按钮会执行上传逻辑。
> 3. 在上传成功后，会打印最后的上传地址。
> 
> 伪代码如下：
> 
> ```js
> Page({
>   onTestButtonClicked() {
>     console.log(`onTestButtonClicked`);
>     xhs.downloadFile({
>       url: "https://c-ssl.duitang.com/uploads/item/201602/26/20160226125736_2Pefd.jpeg",
>       fail: result => {
>         console.log(`download file error: ${result.errMsg}`);
>       },
>       success: result => __awaiter(this, void 0, void 0, function* () {
>         console.log(`download file done: ${result.tempFilePath}`);
>         xhs.uploadFile({
>           url: "",
>           filePath: result.tempFilePath,
>           header: {},
>           formData: {
>             "OSSAccessKeyId": "",
>             "Signature": "",
>             "key": "",
>             "policy": "eyJleHBpcmF0aW9uIjoiMjAyMi0wOS0yOFQxMDo0Nzo0Ny40NjdaIiwiY29uZGl0aW9ucyI6W3sia2V5IjoidXBsb2FkLzAxODM3ODdlLTBhMTktZWU4My1lNTZiLWEwNzdhNGEzNGU1MC8wMTgzODNiMS0yMjI4LTZjYTUtNmRmNy1hNGNiM2FiNjUyODEifSx7IkNvbnRlbnQtVHlwZSI6ImltYWdlL2pwZWcifSx7Ingtb3NzLWNvbnRlbnQtdHlwZSI6ImltYWdlL2pwZWcifV19",
>             "x-oss-content-type": "image/jpeg"
>           },
>           name: 'file',
>           timeout: 10000,
> 
>           success() {
>             console.log(`object url:...`);
>           },
> 
>           fail(err) {
>             console.log(`upload file failed: ${JSON.stringify(err)}`);
>           }
>         });
>       })
>     });
>   }
> });
> ```

执行完成后，访问打印的`object url`, 发现图片并没有变成对应[上传的图片](https://c-ssl.duitang.com/uploads/item/201602/26/20160226125736_2Pefd.jpeg)。

**Comment by taiyiandr** [comment]
xhs.uploadFile API，Android 7.56版本将form表单中的file字段放到了最后，修复了之前存在的问题。
