### ISSUE TITLE
调用 request api时，response Headers内缺少自定义参数

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#29]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.20.4
## 重现步骤 和 复现问题的最小demo Github链接
在Response Headers 里添加一些自定义参
数，在IDE的network显示正确，但api返回结果里， IDE显示为undefined，真机上显示默认的参数，缺少自定义添加的参数。
## 期望结果 和 实际结果(必填)
可以正常返回所有参数。

### 期望结果

![wecom-temp-70e443cb61272979d0fbcfa6870da950](https://user-images.githubusercontent.com/11706751/169467583-c306cadf-a6b9-4509-9fb8-bfa5e9cc5499.jpg)

### 实际结果

![wecom-temp-0347eddf9ef3626c88770d47c876b632](https://user-images.githubusercontent.com/11706751/169467422-dac87ddd-98cf-4d43-baa4-72a61cc09252.jpg)

### charles 抓包可以看到 response header
![wecom-temp-3379d5b0d7d3332f5d3f56d9d0f62913](https://user-images.githubusercontent.com/11706751/169467734-734dfcf0-598a-46b3-92eb-955e368b4c2d.jpg)

**Comment by qq280605311** [comment]
x-request-code

**Comment by Yaxian** [comment]
@qq280605311  可以提供一个测试的 api 吗，我们测试一下 header

**Comment by xutm** [comment]
IDE 1.59.26 已修复，建议下载最新版
