### ISSUE TITLE
商品新增skus.origin_price为0报错

### ISSUE THREAD

**Issue by toufuChew** [redengineer/redmini#3]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
基础库版本
## 期望结果 和 实际结果(必填)
实际结果：https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/upsert 参数报错 {"data":null,"success":false,"msg":"参数错误：invalid skus.origin_price","code":400001}
期望结果：正常返回
## 补充(猜测可能的原因是什么，你有啥想法，选填)
可能是我传的sku有的带了 origin_price 是 0，如果不能为0，有什么办法能解决？

**Comment by wdvxdr** [comment]
origin_price 不能为0，若包含零元的赠品，改赠品可以不用同步到小红书侧
