### ISSUE TITLE
使用uni-app，IOS使用input组件设置 confirm-type="search"  无效，点击右下角按钮未触发confirm事件

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#30]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v7.38.1

## 重现步骤 和 复现问题的最小demo Github链接
```js
<template>
	<view class="content">
		<input class="weui-input" type="text" confirm-type="search" placeholder="输入123自动收起键盘" @confirm="onConfirm"/>
	</view>
</template>

<script lang="ts">
    import Vue from 'vue';
	export default Vue.extend({
		data() {
			return {
				title: 'Hello'
			}
		},
		
		methods: {
			onConfirm (){
				console.log('onConfirm----------------');
			}
		}
	});
</script>
```
使用input组件，设置 confirm-type="search"，键盘调起右下角按钮未设置为“搜索”文案，点击按钮没有触发confirm事件。
![origin_img_v2_0c41ec91-f0db-4fd3-bcea-7af80b82b2bh](https://user-images.githubusercontent.com/11973539/169000379-a971afa6-4ce6-44aa-92f8-615cf296c0de.jpg)

## 期望结果 和 实际结果(必填)
api 文档 ：https://miniapp.xiaohongshu.com/docs/component/input
期望结果：
与文档描述的一致，实现按钮文案为“搜索”，点击触发 bindconfirm 事件
![image](https://user-images.githubusercontent.com/11973539/169001127-cf99717c-4ee2-4c43-b24b-bc6844c9a1dd.png)
![image](https://user-images.githubusercontent.com/11973539/169001207-9ed79b04-532d-47f5-b937-0ecd3b33f0ca.png)

**Comment by dandelion-Chen** [comment]
> 原生 Input 组件还未上线，暂不支持该功能，预计 7.40 后进行支持。

预计这个版本啥时候全量发布呢

**Comment by xutm** [comment]
> > 原生 Input 组件还未上线，暂不支持该功能，预计 7.40 后进行支持。
> 
> 预计这个版本啥时候全量发布呢

5.25 号 全量
