### ISSUE TITLE
xhs.canIUse不能正常使用

### ISSUE THREAD

**Issue by 15116li** [redengineer/redmini#31]
## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v.7.38.0.4b634c5

## 重现步骤 和 复现问题的最小demo Github链接
xhs.canIUse('openLocation')返回为true，但是目前客户端版本并没有支持openLocation，导致报xhs.openLocation is not a function错

## 期望结果 和 实际结果(必填)
期望xhs.canIUse正常工作，返回正确的值。

**Comment by xutm** [comment]
openLocation 是在 基础库 3.23.0，native 版本 7.40 才支持的。

你目前使用的 native 包看起来是不支持的。
