### ISSUE TITLE
开发者者工具 Elements 菜单不显示页面结构

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#310]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by jonsen-liu** [comment]
![1ADE2E20-1C04-4dc3-8CBF-6B03D3A7765D](https://user-images.githubusercontent.com/26186472/192255589-d9fa3c96-a6d2-4413-9848-d39e0462e6d6.png)

**Comment by yinpeng633** [comment]
一样的问题，

**Comment by 0924sofia** [comment]
一样的问题，这个有结果了吗？而且我的项目一直处于初始化状态

**Comment by 0924sofia** [comment]
同样遇到这个问题了，请问现在有解决办法了吗？

**Comment by xutm** [comment]
ok，下周我们高优解决

**Comment by 0924sofia** [comment]
> 同样遇到这个问题了，请问现在有解决办法了吗？

现在偶发性，底部控制台可以出现页面结构。加油 (ง •̀_•́)ง

**Comment by 0924sofia** [comment]
> ok，下周我们高优解决

现在偶发性，底部控制台可以出现页面结构。加油 (ง •̀_•́)ง
