### ISSUE TITLE
6110a48a000000000100078c   有院民宿

### ISSUE THREAD

**Issue by msc123456789** [redengineer/redmini#317]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [x] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7571(7571003)
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
问题描述：商家那边所有订单都已经是结算完成的状态，目前还是无法操作解绑

**Comment by fyjr1997** [comment]
号店关系没恢复的问题，在找相关团队的技术解决了。也在群里回复过了

**Comment by msc123456789** [comment]
好的收到

**Comment by msc123456789** [comment]
请问这个技术团队那边可以解决嘛,客户比较急

**Comment by fyjr1997** [comment]
这个已经解决好了，还有问题么?
