### ISSUE TITLE
开发者工具devtool无法正常使用

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#32]
## 系统环境(必填)
- [ ] IOS
- [X] MACOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [X] IDE
- [ ] 客户端
- [ ] 管理后台

## 开发者工具版本和macos系统版本(必填)
![image](https://user-images.githubusercontent.com/31440366/169458301-08fb5a90-72a5-4650-b3f5-7bdd574ac6e9.png)
![image](https://user-images.githubusercontent.com/31440366/169458635-3ce45bb6-0c0b-4f32-802a-4c9bcbb4537d.png)

## 重现步骤 和 复现问题的最小demo Github链接
- 使用开发者工具正常创建默认工程，devtool中elements、console等工具无法正常使用，界面显示也不正常
![image](https://user-images.githubusercontent.com/31440366/169458717-f7220774-a2ff-4ffa-880d-b74334169f0f.png)
![image](https://user-images.githubusercontent.com/31440366/169458840-79512832-a756-48e7-aed1-a0da3882ccab.png)
![image](https://user-images.githubusercontent.com/31440366/169472737-720393f7-b9b1-4968-8390-598df7b4bcae.png)

## 期望结果 和 实际结果(必填)
期望可devtool可正常使用

**Comment by Yaxian** [comment]
关闭小红书小程序 所有进程，然后重启小红书小程序

**Comment by jianchaoWang4515** [comment]
> 关闭小红书小程序 所有进程，然后重启小红书小程序

uni-app更新文件热更新后就又无法使用了，必须重启开发者工具

**Comment by Yaxian** [comment]
@jianchaoWang4515 
麻烦打开 IDE 的控制台，
```
$('webview#devtool-webview').src
```
看看 端口是否被占用了
