### ISSUE TITLE
setClipboardData没办法hideToast默认有的toast提示

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#320]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
IDE版本：3.36.2
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
**这边有提供demo**
[xhs_demo 4 3.zip](https://github.com/redengineer/redmini/files/9664029/xhs_demo.4.3.zip)

<img width="871" alt="image" src="https://user-images.githubusercontent.com/90542393/192756958-1e5b710a-722b-4621-b9d3-0925c15d59c3.png">

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by coshinehcl** [comment]
这个优先级比较高，麻烦优先处理下，感谢

**Comment by AngryBrotherXiang** [comment]
7.60 fix

**Comment by coshinehcl** [comment]
好的，感谢。修复效果是我们可以hideToast吗

**Comment by coshinehcl** [comment]
@AngryBrotherXiang

**Comment by AngryBrotherXiang** [comment]
> 好，谢谢。修复效果是我们可以隐藏吐司吗？

7.60 fix后，开发者可以调用hideToast隐藏
