### ISSUE TITLE
ios 支付宝支付，未安装支付宝提示安装支付宝，点击取消安装，回到小程序onShow不执行

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#328]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 + 
- [ ] DIOR + 
- [ ] longchamp + 
- [ ] 领克 + 
- [ ] 猫眼 + 
- [ ] 自我游 + 
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![51664526871_ pic](https://user-images.githubusercontent.com/63334662/193229432-ff17ff6f-39d9-4f3c-9664-0efb0fe3e1ae.jpg)

点击取消回到小程序，onShow不执行
 +
## 期望结果 和 实际结果(必填) +
onShow正常执行
 +

**Comment by AngryBrotherXiang** [comment]
7.61 fix
