### ISSUE TITLE
uni-popup报错

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#329]
> ## 系统环境(必填[多选]) +
> * [x]  IOS +
> * [x]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [ ]  小程序Api +
> * [x]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
> 
> 
> ## 基础库版本或小红书APP版本(必填) +
> v7.57.1 + +
> 
> ## 重现步骤 和 复现问题的最小demo Github链接 +
> 
![uni-popup](https://user-images.githubusercontent.com/18606361/193238967-168e23c0-5990-408d-b220-077dcbd4e369.jpg)

> 
> ## 期望结果 和 实际结果(必填) +
> 用uniapp开发，使用uni-popup弹出框点击弹框任意地方会提示事件信息不存在然后自动关闭弹框，弹框没有任何dom和事件
> 
> ## 补充(猜测可能的原因是什么，你有啥想法，选填) +
> 和蒙层关闭事件无关 且不会触发弹框的change事件

**Comment by jonsen-liu** [comment]
兄弟，你也是用uniapp开发小红书小程序？能加个微信学习请教下不？
