### ISSUE TITLE
商品新增接口异常

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#338]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
调用商品新增接口https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/upsert 报了异常，异常报错如下
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AccessDeny</title><link rel="stylesheet" href="https://imgcache.qq.com/qcloud/security/static/404style.css"></head><body><div class="conent"><div class="accessDenySvg"><img src="https://imgcache.qq.com/qcloud/security/static/imgs/attackIntercept.svg" alt=""></div><h1 class="err">很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的策略阻断</h1></div></body></html>

小程序id=62e8c26d65ba04000150223c，麻烦帮忙看看这个问题

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by wdvxdr** [comment]
麻烦提供下详细的请求信息，并确认下当前网络环境，是否挂了代理之类的
