### ISSUE TITLE
touchmove 事件触摸点信息不正确

### ISSUE THREAD

**Issue by liangqingfengfeng** [redengineer/redmini#34]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.23.1
## 重现步骤 和 复现问题的最小demo Github链接
`
<scroll-view scroll-x="true" scroll-y="true" bindtouchmove="touchmove"></scroll-view>
`
// js
`
touchmove(e) {
  console.log('touchs', e.touchs);
}
`
双指滑动屏幕，e.touchs长度一直为1，触点信息只捕获到1个
## 期望结果 和 实际结果(必填)
期望能捕获到正确的触点信息，e.touchs为触点的个数

**Comment by xutm** [comment]
真机调试未复现该问题，暂时关闭
