### ISSUE TITLE
授权给服务商的小程序支付域名问题

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#341]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
appId：630751a77be693000175e435，小程序名称：智我优出游攻略；这个小程序已经授权给了服务商，服务商id=62ecc606a44cb400012a7507，服务商的开发小程序id=62e8c26d65ba04000150223c，服务商的开发小程序已经配置了支付域名了，而且支付正常，但是授权给服务商的小程序支付不正常，支付提示支付host域名不合法，麻烦帮忙看看
![企业微信截图_16653970753392](https://user-images.githubusercontent.com/111478514/194847116-e4423ab2-8617-4bf1-9b61-7b72b51fdb56.png)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by wdvxdr** [comment]
需要配置的服务商域名，不是开发小程序
https://miniapp.xiaohongshu.com/third/api-3rd-doc/createThrid

**Comment by xuwenjie0505** [comment]
![image](https://user-images.githubusercontent.com/111478514/195757885-113957c5-1489-4304-b204-28354f63c074.png)
@wdvxdr 您好，服务商这里能配置域名的地方我都配置上支付域名了，请问具体是需要配置在哪个地方呢？可以麻烦帮忙截个图看看吗
