### ISSUE TITLE
不能使用 Component 构造器构造页面吗？

### ISSUE THREAD

**Issue by frojan** [redengineer/redmini#344]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
基础库版本 3.36.0+
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/6687233/195053849-4856f476-8148-466d-ab1b-b5e1f9589626.png)

## 期望结果 和 实际结果(必填) +
期望：正常输出
实际：未执行
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
文档上写了支持，但是实际不支持吗？

**Comment by xutm** [comment]
目前还不支持。长期规划，也不会支持。建议做下兼容
