### ISSUE TITLE
提示找不到ext.json，是taro插件导出的，自开发小程序，不需要配置ext.json吧

### ISSUE THREAD

**Issue by yinpeng633** [redengineer/redmini#345]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
基础库版本：3.36.2 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/4269654/195236446-6d12e64f-8158-4735-87f9-b1e8234fc277.png">

 +
## 期望结果 和 实际结果(必填) +
不提示这个错误 +
 +

**Comment by 0924sofia** [comment]
> 您好开发者, 我们已收到你的问题, 已通知开发团队进行处理！ 如您未阅读我们的开发文档，可先参阅开发文档 [小红书问题处置流程](https://miniapp.xiaohongshu.com/docs/guide/exceptionPerformanceWhiteScreen) ✨ 感谢您的提问！✨

你好，请问这个问题需要怎么解决？导入一个微信原生小程序，也出现这个问题提示了
![image](https://user-images.githubusercontent.com/50742189/195776362-2054ed6c-95df-44d4-a0ac-d0b7593ab231.png)

**Comment by xutm** [comment]
自开发小程序不需要导入 ext.json
