### ISSUE TITLE
小红书app商品笔记添加商品失败，后台通过商品id查找不到，帮忙看下原因

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#346]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
APPID：632d4f1dcc5a860001831423
商品ID：1419707950141
 
<img width="540" alt="iShot_2022-10-12_10 36 59" src="https://user-images.githubusercontent.com/90542393/195236932-02ef21a4-81ac-4940-8644-73ebc53eceaf.png">

**商家着急，辛苦优先处理下，谢谢**

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by fyjr1997** [comment]
提供一下挂不了的操作截图

以及到底是商品笔记还是评论区组件？

**Comment by coshinehcl** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/90542393/195304584-d8ccc475-cdc4-4659-ac3a-f25afc0f6f02.png">
<img width="520" alt="wecom-temp-77431-622a7cb68dd3b40647354c43b697620e" src="https://user-images.githubusercontent.com/90542393/195304648-ee3e5aba-a492-4464-b4a7-834857ccf712.png">
是：评论区组件
@fyjr1997

**Comment by fyjr1997** [comment]
<img width="408" alt="截屏2022-10-13 下午1 11 08" src="https://user-images.githubusercontent.com/109206057/195510929-5ace2c69-9c24-4367-943b-55458389ac52.png">
我试了下都是好的。。是不是上面的报备品牌没有选

**Comment by coshinehcl** [comment]
OK。这边确认已经好了。谢谢
