### ISSUE TITLE
安卓手机，预览出来的码接口报错，但是用真机调试的码测试就没问题。

### ISSUE THREAD

**Issue by luochenwang** [redengineer/redmini#347]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [x] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.58.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
使用安卓手机 扫预览出来的码，有一个接口报错，但是真机调试出来的码接口就正常。ios都正常
 +
## 期望结果 和 实际结果(必填) +
安卓手机预览 接口不会报错
 +

**Comment by taiyiandr** [comment]
方便提供下预览二维码吗，并且将小红书号 317940352 加一下预览权限。并说明如何操作复现，谢谢。

**Comment by luochenwang** [comment]
> 方便提供下预览二维码吗，并且将小红书号 317940352 加一下预览权限。并说明如何操作复现，谢谢。

轮播第一个图片 然后点击立即申领，到下单页面。会提示商品找不到。ios就没问题

**Comment by luochenwang** [comment]
> 方便提供下预览二维码吗，并且将小红书号 317940352 加一下预览权限。并说明如何操作复现，谢谢。

已添加 
<img width="313" alt="WeChatbcdb5c90c551fd6c878643c56cf5bd54" src="https://user-images.githubusercontent.com/16608338/195295031-558fd6a6-0bb4-491b-8902-2b473257ac0e.png">

**Comment by taiyiandr** [comment]
业务方已自行解决：get请求参数放url中。
