### ISSUE TITLE
input组件placeholder-style 无效

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#35]
## 系统环境(必填)
- [X] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [X] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书 v7.39
## 重现步骤 和 复现问题的最小demo Github链接
设置placeholder-style 和 placeholder-class 模拟器正常 在app上无效

**Comment by dandelion-Chen** [comment]
遇到同款问题，设置了style的width属性时，placeholder-style 在app无效。 下面代码中如果把  style="width: 100%;"  去掉就placeholderStyle就起作用。 有点迷惑，麻烦官方帮忙看下。
```js
<template>
	<view class="content">
		<input style="width: 100%;" :placeholder-style="placeholderStyle" type="text" confirm-type="search" placeholder="输入123自动收起键盘" @confirm="onConfirm"/>
	</view>
</template>

<script lang="ts">
    import Vue from 'vue';
	export default Vue.extend({
		data() {
			return {
				title: 'Hello',
				placeholderStyle: 'color: #F44447'
			}
		},
		
		methods: {
			onConfirm (){
				console.log('onConfirm----------------');
			}
		}
	});
</script>
```

**Comment by Hubmeat** [comment]
你好，请问双端的 input placeholder style 都不生效嘛？

**Comment by dandelion-Chen** [comment]
> 你好，请问双端的 input placeholder style 都不生效嘛？



> 你好，请问双端的 input placeholder style 都不生效嘛？
目前在安卓手机上看到

**Comment by dandelion-Chen** [comment]
> 你好，请问双端的 input placeholder style 都不生效嘛？

目前在安卓手机上没有看到

**Comment by jianchaoWang4515** [comment]
> 你好，请问双端的 input placeholder style 都不生效嘛？

这个问题有修复吗
