### ISSUE TITLE
自定义组件props的值，第二次传入的值一样的话，组件内部observers无法监听到

### ISSUE THREAD

**Issue by Suntgr** [redengineer/redmini#356]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [x] 小程序Api +
- [x] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
复现很简单，就是对自定义组件的props值，多次传入重复的值，组件内部observers无法监听到
 +
## 期望结果 和 实际结果(必填) +
observers可以监听到props每次传入的值，就算一样，也触发observers

**Comment by Hubmeat** [comment]
目前小红书小程序这边，如果 props 值未变化，observer 则不会触发。

**Comment by Suntgr** [comment]
@Hubmeat props的observer 不触发可以理解，但是observers应该是每次外界setDate都需要触发的啊，不论值相等不。这个场景很多啊；先传一个初始值，组件内部更变更，然后组件外部想给重置成初始值，这下就不行了。
