### ISSUE TITLE
form 无法收集native表单

### ISSUE THREAD

**Issue by 15116li** [redengineer/redmini#36]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v7.39.0.ec72b79

## 期望结果 和 实际结果(必填)
form提交可以收集用户输入的表单数据

**Comment by Hubmeat** [comment]
你好，这个问题提供下最小 demo
