### ISSUE TITLE
分享出来的卡片在安卓机子上，没有背景图，到对方手机上看也没有背景图

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#362]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="795" alt="image" src="https://user-images.githubusercontent.com/90542393/195540180-188581f8-6c4e-4fe7-850e-5b12c9d1a95e.png">

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by taiyiandr** [comment]
本地未复现，请将小红书号 317940352 加一下预览权限

**Comment by coshinehcl** [comment]
@taiyiandr 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/90542393/197673811-1b4de3cb-38f1-4372-86e5-dd2ed0f087cd.png">

**Comment by coshinehcl** [comment]
@taiyiandr 大佬帮忙看下

**Comment by taiyiandr** [comment]
> @taiyiandr <img alt="image" width="188" src="https://user-images.githubusercontent.com/90542393/197673811-1b4de3cb-38f1-4372-86e5-dd2ed0f087cd.png">

发送和接收双方都没有复现。
你们那边现在还是必现吗，相关机型都是什么呢？
