### ISSUE TITLE
iphone8偶现组件不调用ready生命周期的情况

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#367]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 
## 基础库版本或小红书APP版本(必填) 
v7.59.1
 
## 重现步骤 和 复现问题的最小demo Github链接 +

iphone8偶现组件不调用ready生命周期的情况

通过抓包发现，出现白屏时，都是没有调用ready生命周期

https://user-images.githubusercontent.com/33249100/195795422-5d093073-8daf-47cd-9371-0e6f667d9d64.mp4

## 期望结果 和 实际结果(必填) 
正常调用生命周期

**Comment by Hubmeat** [comment]
ready 是指 page 的 onReady 事件吗？麻烦小红书用户 id 提供下吧

**Comment by haojiasheng** [comment]
> ready 是指 page 的 onReady 事件吗？麻烦小红书用户 id 提供下吧

ready 是指 Component 的 ready 事件
用户id：5dd143250000000001005c94

**Comment by AngryBrotherXiang** [comment]
不是生命周期onReady事件没触发，是内存不足时webkit内核崩溃了，导致白屏
