### ISSUE TITLE
新注册小红书账号进入小程序，点击按钮授权 getUserInfo 一直提示是 “getUserInfo:fail auth deny”

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#37]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书版本：v7.39

## 重现步骤 和 复现问题的最小demo Github链接
新注册小红书用户进到小程序，点击按钮 getUserInfo  授权，弹窗没弹出来。 操作了几次，都是失败回调都是拒绝，等到用户点击了设置页面（什么都没有操作），再回到小程序就可以弹出授权窗口了。录屏如下：

https://user-images.githubusercontent.com/11973539/170397790-66056624-4bee-4316-96b5-3f0bc4f07d56.mp4

## 期望结果 和 实际结果(必填)
点击按钮能正常唤起用户信息授权弹窗。

**Comment by dandelion-Chen** [comment]
> 其他状态未知，我们都按照拒绝来判断，现在直接返回未知错误，估计是后端接口问题，新账号，建议绑定手机号

使用微信登录的用户不一定会去绑定手机号。 不绑定手机号就会出现用户信息授权拿不到的情况吗？

**Comment by AngryBrotherXiang** [comment]
742fix，弹出授权框

**Comment by dandelion-Chen** [comment]
> 742fix，弹出授权框

是版本7.4.2会fix吗，预计什么时候全量呢

**Comment by xutm** [comment]
6.7 号已经全量

**Comment by dandelion-Chen** [comment]
> 6.7 号已经全量

在小红书7.44.x版本仍存在，请问有人帮忙看嘛？
