### ISSUE TITLE
安卓环境，调用updateManager方法异常，出现反复不断触发updateManager.onUpdateReady

### ISSUE THREAD

**Issue by viclee25** [redengineer/redmini#373]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
在安卓环境下，调用updateManager方法异常，出现反复不断触发updateManager.onUpdateReady
代码书写与文档示例代码完全一致
<img width="734" alt="image" src="https://user-images.githubusercontent.com/29431453/196164865-362171ff-f014-4e20-b534-f8a62f40ac45.png">
[复现录屏：https://locals-house-prod.oss-cn-shenzhen.aliyuncs.com//localhomeqy/mp4/0.mp4](https://locals-house-prod.oss-cn-shenzhen.aliyuncs.com//localhomeqy/mp4/0.mp4)
手机型号：小米12
 +
## 期望结果 和 实际结果(必填) +
期望API表现正常，仅首次触发updateManager.onUpdateReady
 +

**Comment by taiyiandr** [comment]
7.45.1版本，小红书还未支持updateManager相关api

**Comment by taiyiandr** [comment]
7.64 fix
