### ISSUE TITLE
最新版本打开小程序速度有明显降低

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#374]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.59.1
## 重现步骤 和 复现问题的最小demo Github链接 +
在相同网络环境、同一个手机、同一个小程序情况下，新老版本打开小程序速度有明显差异
新版本打开速度：3秒内
老版本打开速度：5-6秒

视频太大了，传不上来，视频可以去“小红书有赞技术对接”群查看

## 期望结果 和 实际结果(必填) +
保持老版本打开速度

**Comment by Hubmeat** [comment]
双端都是吗？还是只有某个平台

**Comment by taiyiandr** [comment]
最新反馈7.59.1及前后版本速度正常，无明显降低
