### ISSUE TITLE
订单结算提示：当前订单数据状态错误，不可结算

### ISSUE THREAD

**Issue by huijunliu** [redengineer/redmini#379]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
发起结算报错，请求参数：{"afterSettle":0,"appid":"616d1d3e53d0ba0001db1529","outAfterSalesOrderIds":["1001030252553"],"outOrderId":"308491386000735","outSettleId":"308491386000735"}
响应参数：{"globalTicket":"9698-1666248002.284-saas-w1-1038-61635331948","processResult":true,"responseVo":{"code":420308,"msg":"当前订单数据状态错误，不可结算","success":false},"returnCode":"420308","returnMsg":"当前订单数据状态错误，不可结算","successForMornitor":true,"timestamp":"1666248002431"}

 +
## 期望结果 和 实际结果(必填) +
订单能正常结算，且请给出结算报错的原因。
 +

**Comment by wdvxdr** [comment]
测试商户，已沟通
