### ISSUE TITLE
1.59.24 开发者工具登录点击一直转 loading

### ISSUE THREAD

**Issue by zhangguangyi** [redengineer/redmini#38]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [✅ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ✅] IDE
- [ ] 客户端
- [ ] 管理后台

## 重现步骤 和 复现问题的最小demo Github链接
<img width="295" alt="image" src="https://user-images.githubusercontent.com/26796197/170489323-3a5f1a60-4b10-421f-a5c4-feebac3d830e.png">

**Comment by zhangguangyi** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/26796197/170489239-47a18dc1-0bc5-4525-97cb-6f8ce787bf90.png">

**Comment by xutm** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/11706751/171083066-0ec02f66-9899-46a8-8cde-7cd678c3f590.png">

「切换开发者工具」确认下里面的接口请求是否正常
