### ISSUE TITLE
支付api调用回调错误

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#383]
> ## 系统环境(必填[多选]) +
> * [x]  IOS +
> * [x]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [x]  小程序Api +
> * [ ]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
> 
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
1.调动xhs.requestOrderPayment这个支付的api，弹出选择支付方式的弹框，关闭弹框不触发任何回调
2.选择任意支付方式，取消支付，返回小红书时触发success回调和complete，但是根本不能分辨是否是取消支付
3.似乎在还没返回app的时候回调就已经执行了

ps:下图是进入支付宝app支付  然后取消支付回到app看到的回调
<img width="414" alt="requestOrderPayment" src="https://user-images.githubusercontent.com/18606361/197494229-1512e706-eb9a-44fa-862c-ac06c360391d.png">

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by shiminJ** [comment]
取消选择支付方式弹框应该是缓存了，后面尝试有返回失败回调了

**Comment by AngryBrotherXiang** [comment]
小红书的支付用的是H5跳转微信、支付宝，框架侧实际上是感知不到支付结果的。
调用xhs.requestOrderPayment，若参数出问题了，会直接回调，其他情况，都需要开发者手动去查询订单的状态
