### ISSUE TITLE
xhs.followOfficialAccount已关注情况下不会触发success、fail、complete

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#385]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.61

## 重现步骤 和 复现问题的最小demo Github链接 +
已关注情况下调用followOfficialAccount，只会弹出toast"已关注"，但是不会调用sucess。

看文档是会调用sucess，并且状态值为1
![image](https://user-images.githubusercontent.com/33249100/197517775-ff8037cf-2f5f-431a-8290-ff7cf97c93d0.png)

## 期望结果 和 实际结果(必填) +
会调用sucess，且状态值为1
 +

**Comment by AngryBrotherXiang** [comment]
跟 #381 重复了
