### ISSUE TITLE
直播打开商详较慢

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#386]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.59.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
uid：5ee77e4d0000000001000a23
从直播场景打开商品详情，速度较慢
https://user-images.githubusercontent.com/33249100/197518380-525d4488-e145-4f09-a2aa-4ad8367e7881.mp4

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +

**Comment by taiyiandr** [comment]
最新反馈7.59.1及前后版本速度无明显降低
