### ISSUE TITLE
ios 设备上，Request Header 的 'Accept-Language' 被修改了？

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#39]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v7.40

## 重现步骤 和 复现问题的最小demo Github链接
在iOS设备上，请求header设置 'Accept-Language': 'zh_CN'， 但服务端接收到的是zh-Hans-CN。开发者工具与安卓APP都是正常的。
![image](https://user-images.githubusercontent.com/11973539/170670385-08b81b0a-1571-42fc-b0f9-0d001869c3eb.png)
![image](https://user-images.githubusercontent.com/11973539/170670712-9f61d0c4-900b-4883-a2c8-716c8adcdd46.png)

## 期望结果 和 实际结果(必填)
不修改请求header 的 Accept-Language，发到服务端仍然为 'Accept-Language': 'zh_CN'

**Comment by xutm** [comment]
小红书网络库问题，742 修复，预计 6.8 号发版
