### ISSUE TITLE
PickerView + PickerViewColumn自定义多列选择器，频繁操作后onchange回调异常

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#391]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v3.35.2 

## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/35423514/199009324-a2ad2d84-c340-411a-b5c7-5b47a35860ef.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/35423514/199142373-4db7a911-9f9c-4e8a-b656-bd03a7176a27.png">

https://user-images.githubusercontent.com/35423514/199009220-0a55dd7b-3fc9-49e5-aa84-601391c823c6.mp4

频繁操作数据后， 操作第二列第三列 onchange回调event.detail.column始终返回为0

## 期望结果 和 实际结果(必填) +
正常返回当前操作列 +
 +

**Comment by Hubmeat** [comment]
尝试原生小程序复现下，给下代码吧。没有其他服务商反馈过这个问题

**Comment by Hubmeat** [comment]
无法复现，麻烦给个原生可以复现的 demo 把。
