### ISSUE TITLE
[服务端] 订单-获取订单信息 接口出现内部系统异常

### ISSUE THREAD

**Issue by BrighterAmmo** [redengineer/redmini#394]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
新建一笔订单，返回了订单的信息
![image](https://user-images.githubusercontent.com/38214419/199657215-b21fb1e9-2b09-42e3-919e-5a452834e191.png)

获取订单信息的时候，出现了内部系统异常
![image](https://user-images.githubusercontent.com/38214419/199657313-8a5f5a06-e158-4327-87b8-24e857d7bb94.png)

## 期望结果 和 实际结果(必填) +
正常展示订单信息

**Comment by wdvxdr** [comment]
out_product_id、out_sku_id 相同导致内部系统无法处理层级结构
测试数据还是尽量符合真实数据结构
