### ISSUE TITLE
取消支付的回调返回不同

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#395]
> ## 系统环境(必填[多选]) +
> * [x]  IOS +
> * [x]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [x]  小程序Api +
> * [ ]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
调用requestOrderPayment弹出支付框，取消支付时回调ios和安卓返回不同
<img width="563" alt="安卓报错" src="https://user-images.githubusercontent.com/18606361/199676547-40465f50-ac27-4a9f-b874-24385ee69ec1.png">
<img width="448" alt="ios报错" src="https://user-images.githubusercontent.com/18606361/199676567-39489b29-1197-4113-a89e-7874722035fb.png">

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by AngryBrotherXiang** [comment]
iOS 7.64版本对齐
