### ISSUE TITLE
Taro3.4.8项目IDE报错can't not using self component, componentPath: custom-wrapper

### ISSUE THREAD

**Issue by WeiJietao** [redengineer/redmini#4]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [X] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [X] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)

IDE 1.59.23-beta.15

## 期望结果 和 实际结果(必填)

运行 Taro 项目报错"[RUNTIME Render ERROR] startMiniContainer has error happen Error: can't not using self component, componentPath: custom-wrapper, please reload page"（会导致页面无法显示），还有形如"getEagletDeviceInfo fail: 方法不支持"的报错（不会导致页面无法显示）。

尝试去掉 dist 目录下的 custom-wrapper 组件及其引用，可以正常显示页面，但页面一多，对该组件的引用也变多，要手动去掉引用代码实在不方便，麻烦兼容一下。

![截屏2022-05-06 下午4 38 51](https://user-images.githubusercontent.com/18640419/167099462-a92c3d88-b792-4248-9cd1-295f901f21e2.png)

![截屏2022-05-06 下午4 39 13](https://user-images.githubusercontent.com/18640419/167099472-80c82661-0e30-4425-bb23-e457044e7250.png)

**Comment by xutm** [comment]
1. "[RUNTIME Render ERROR] startMiniContainer has error happen Error: can't not using self component, componentPath: custom-wrapper, please reload page"（会导致页面无法显示）

这个错误是因为 IDE 版本较老。建议暂时使用如下版本。今天我们会出正式版。

IOS: https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/b64a43f4-a810-4d72-aba2-d60db98c6740/xhs-mpide-1.59.23-beta.22.dmg

WINDOW: https://picasso-1251524319.cos.ap-shanghai.myqcloud.com/electron-app-updater-cli/67197136-7159-4014-88b5-65e0d71a7a63/xhs-mpide-1.59.23-beta.22.exe

2. "getEagletDeviceInfo fail: 方法不支持"的报错（不会导致页面无法显示）
这个错误的确不影响页面展示，我们最新版基础库也会进行修复
