### ISSUE TITLE
IDE默认创建的工程webview无法正常使用

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#400]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
IDE 1.60.0  +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
使用 小红书开发工具 1.60.0 版
工程管理新建工程
打开工程,打开 webview 页面 +
 +
## 期望结果 和 实际结果(必填) +
期望结果:
能正常跑默认工程示例.能显示webview页面
实际结果:
IDE上无显示 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
可能是报错引起的,有两个错误,打开工程就有
code: -1
errMsg: "pageRenderLifeCycleStatus fail: 方法不支持xxx"
code: -1
errMsg: "reportPerformance fail: 方法不支持xxx"

**Comment by motopia** [comment]
怎么解决的，我也碰到了

**Comment by anaian** [comment]
在手机上可以显示,不知道什么情况
示例的网页打不开,自己弄一个可以打开的就行
