### ISSUE TITLE
小红书体验版扫码，IOS可以扫码进入小程序，安卓不行

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#404]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
小程序appid：630751a77be693000175e435
小程序名称：智我优出游攻略
体验版二维码：
![image](https://user-images.githubusercontent.com/111478514/200244539-1117bbe7-da48-4787-a1d6-b9b6fb8abcef.png)
报错截图：
![lADPJxuMTB3FOCjNCWDNBDg_1080_2400](https://user-images.githubusercontent.com/111478514/200244612-e067c4b8-c1d1-4c7d-b1b2-5095b9c310d8.jpg)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by taiyiandr** [comment]
请把小红书号【317940352】添加一下体验版访问权限呢。

**Comment by taiyiandr** [comment]
客户端侧：iOS安全问题，Android符合预期。

**Comment by taiyiandr** [comment]
预计7.65fix
