### ISSUE TITLE
小红书服务端订单-新增/修改接口返回获取佣金率设置失败

### ISSUE THREAD

**Issue by JXLau** [redengineer/redmini#408]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [x] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +

## 重现步骤 和 复现问题的最小demo Github链接 +

调用订单-新增/修改接口 https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert 的时候，接口返回了这个错误

```json
{"data":null,"success":false,"msg":"获取佣金率设置失败","code":420114}
```

小程序id: 635bbddccbe21a0001367a19

 +

## 期望结果 和 实际结果(必填) +
创建后应返回正常数据

```json
{
  "data": {
    "out_order_id": "string",
    "order_id": "string",
    "final_price": 0,
    "pay_token": "string",
    "expired_time": 0
  },
  "success": true,
  "msg": "success",
  "code": 0
}
```

 +

**Comment by wdvxdr** [comment]
需要运营设置支付权限，运营反馈已回复
