### ISSUE TITLE
xhs.miniProgram.navigateTo在模拟器中可正常跳转，使用预览功能在app中无法正常跳转

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#41]
## 系统环境(必填)
- [X] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [X] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书V7.40

**Comment by xutm** [comment]
你用的 jssdk 的版本是多少？

**Comment by xutm** [comment]
请使用 3.4.2 jssdk 版本
