### ISSUE TITLE
需要提供下载远程字体xhs.loadFontFace的api 

### ISSUE THREAD

**Issue by handsome025** [redengineer/redmini#42]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 期望结果 和 实际结果(必填)
提供类似支付宝或者微信下载字体的api  loadFontFace

**Comment by coshinehcl** [comment]
同问，官方demo里面的下载字体是不支持的，这个需求什么时候能提供
