### ISSUE TITLE
小红书url link接口获取的link失效问题

### ISSUE THREAD

**Issue by xning1001** [redengineer/redmini#429]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [x] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
小红书获取url link接口地址：https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-url
curl:
curl -X POST \
  'https://miniapp.xiaohongshu.com/api/rmp/url?access_token=d66f0d5682974816bdce0e47db965f31&appid=62abfee2dc4969000146520e' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 30d8f565-91a3-48e9-90ad-0912ab650d63' \
  -H 'cache-control: no-cache' \
  -d '{
  "page_url": "pages/order/list/index"
}'
问题：调用接口获取到的pageUrl跳转pages/order/list/index失效，最开始可以跳转成功，后面就不行了
## 期望结果 和 实际结果(必填) +
根据接口要求，expire_interval不传时生成的pageUrl默认应该是365天有效，想知道为什么生成的url会失效和如何生成一个长时间有效的url link

**Comment by wdvxdr** [comment]
问题已定位，本周内修复。可以先指定过期时间

**Comment by xning1001** [comment]
> 问题已定位，本周内修复。可以先指定过期时间

好的，感谢
