### ISSUE TITLE
设置页面分享图时没有显示图片

### ISSUE THREAD

**Issue by JXLau** [redengineer/redmini#433]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
配置页面 onShareAppMessage 时使用网络图片分享后，图片不显示，不设计分享图时，能正常显示logo

小程序ID：635bbddccbe21a0001367a19

设置分享内容的图片链接：https://f01.32hike.com/image/2019/11/06/58dcbe61796d54757d218c2c06c63160.jpg

![image](https://user-images.githubusercontent.com/30074374/203030365-56501d01-dc99-4547-b4dd-aae61d4f14bc.png)

 +

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by Hubmeat** [comment]
退出 App 重新进入是否可以加载呢？ 部分图片可能因为网络原因没加载出来

**Comment by Hubmeat** [comment]
hi， 你好开发者，我们找端侧同学协助排查了下，并不是一个必现问题，你本地可以稳定复现吗？

另外，再站内分享时，可以关注下这个区域的产品图片是否加载正常：
![df793799-056b-46de-a346-616674233f3e](https://user-images.githubusercontent.com/25141100/208398903-caabca07-37a9-4df1-af43-3c732a31b5b8.jpg)

**Comment by JXLau** [comment]
已解决，是我们的CDN域名的访问限制问题，谢谢

**Comment by Hubmeat** [comment]
好的
