### ISSUE TITLE
swipe组件不受控

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#435]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.62.2 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
swipe传入了current属性，swiper-item设置了item-id，但是每次重新打开都是展示第一个swiper-item的内容。
 +
## 期望结果 和 实际结果(必填) +
传入current后，第一次打开会展示对应的swiper-item +
 +

**Comment by LaoChen1994** [comment]
这个问题修好了吗，现在好像还是会复现

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LaoChen1994** [comment]
如果current对应的是下面swiper-item的item-id的话 建议修改swiper文档，现在current里面写的是对应swiper-item划块的index
