### ISSUE TITLE
小红书无法获取用户手机号，和用户信息

### ISSUE THREAD

**Issue by huyun1743518169** [redengineer/redmini#439]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [x] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.62.0 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
一，获取用户信息
html

			<button
			   open-type="getUserInfo"
			   bindgetuserinfo="getUserInfo"
			   class="QuickLogin"
			 >
			   <image
			     src="/static/image/xhs.png"
			     mode="aspectFill"
			   ></image>
			   <text>快捷登录</text>
			 </button>
			 
js
	// 获取用户信息
	getuserinfo(e){
		// 无法调起授权弹窗，事件不触发
		console.log(e);
	},

二，获取用户手机

html，
	
           <button
              open-type="getPhoneNumber"
              bindgetphonenumber="getPhoneNumber"
              class="QuickLogin"
            >
              <image
                src="/static/image/xhs.png"
                mode="aspectFill"
              ></image>
              <text>快捷登录</text>
            </button>
			

js
 async getPhoneNumber(e) {
      if (_this.Read) {
        uni.showLoading({
          title: _this.Language.Hint_9,
          mask: true,
        });
        uni.setStorageSync("lastLoginType", "xhs");

        xhs.login({
          async success(res) {
            let OpenID = await _this.$API.Universal.GetUserInfo({
              encData: e.detail.encryptedData,
              iv: e.detail.iv,
              code: res.code,
            });
            console.log(OpenID);
          },
        });
      } else {
        uni.showToast({
          position: "bottom",
          title: _this.Language.Hint_10,
          icon: "none",
          mask: true,
        });
      }
    },

## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +期望结果，与文档一致，1. 能正常通过button来调起授权个人信息弹窗，2. 手机号授权弹窗点击允许后回调指定事件返回相关信息

**Comment by huyun1743518169** [comment]
文档已阅读，麻烦亲可以自己稍微试一下这两个方法，或者推送一个实现效果的小程序给我们

**Comment by taiyiandr** [comment]
请提供一下预览二维码和复现方式，并把小红书号【317940352】添加一下访问权限。谢谢

**Comment by huyun1743518169** [comment]
小红书号【317940352】已添加为体验者，小红书扫码即可进入



代码示例一：为dom
&nbsp;<!-- 获取用户信息按钮--s --&gt;
			 <button
			&nbsp; &nbsp; open-type="getUserInfo"
			&nbsp; &nbsp; bindgetuserinfo="getUserInfo"
			&nbsp; &nbsp; class="QuickLogin"
			&nbsp; &gt;
			&nbsp; &nbsp; <text&gt;open-type为getUserInfo</text&gt;
			&nbsp; </button&gt;
			 <!-- 获取用户信息按钮--e --&gt;
			<!-- 获取手机号--s --&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<button
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; open-type="getPhoneNumber"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bindgetphonenumber="getPhoneNumber"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; class="QuickLogin"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <text&gt;open-type为getPhoneNumber</text&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </button&gt;
			<!-- 获取手机号--e --&gt;



代码示例二，为js中的回调方法


&nbsp;// 获取电话
	&nbsp; getPhoneNumber(e){
		&nbsp; console.log(e);
		&nbsp; let title='getPhoneNumber'+e;
		&nbsp; uni.showToast({
		&nbsp; &nbsp; duration: 2000,
		&nbsp; &nbsp; position: "bottom",
		&nbsp; &nbsp; title:title,
		&nbsp; &nbsp; icon: "none",
		&nbsp; &nbsp; mask: true,
		&nbsp; });
	&nbsp; },
	&nbsp; // 获取用户信息
	&nbsp; getUserInfo(e){
		&nbsp; console.log(e);
		&nbsp; let title='getUserInfo'+e;
		&nbsp; uni.showToast({
		&nbsp; &nbsp; duration: 2000,
		&nbsp; &nbsp; position: "bottom",
		&nbsp; &nbsp; title:title,
		&nbsp; &nbsp; icon: "none",
		&nbsp; &nbsp; mask: true,
		&nbsp; });
	&nbsp; },





问题描述，昨天获取用户信息方法无弹窗，授权手机弹窗正常弹出，均无回调。今天获取用户信息方法可正常弹出，但无回调信息，授权手机方法无响应。无回调。getPhoneNumber与getUserInfo方法未触发，置于uniapp中methods中或与methods方法同级均不触发。


运行环境：---uniapp+vue2，vue-cli执行npm run dev:mp-xhs编译运行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
请提供一下预览二维码和复现方式，并把小红书号【317940352】添加一下访问权限。谢谢

**Comment by taiyiandr** [comment]
> 

请问下，扫哪个码？

**Comment by Hubmeat** [comment]
给下 uni 编译的 dist 产物目录，我们协助你这边排查下

**Comment by huyun1743518169** [comment]
好的，这个是uni编译的dist-》dev-》里面的mp-xhs压缩文件夹，是编译之后的代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月28日(星期一) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
给下 uni 编译的 dist 产物目录，我们协助你这边排查下

**Comment by huyun1743518169** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
给下 uni 编译的 dist 产物目录，我们协助你这边排查下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

mp-xhs.zip (4.65M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5a37336248be8dc9bcced80515320a190104565455030805485451070b1f0c0e50041e5a03065c1b5753570301000e01035100073338385b151a4b0a401c425f15370e&t=exs_ftn_download&code=e73b3286

**Comment by huyun1743518169** [comment]
好的，请稍等，我们的体验版测试正在进行其他的功能测试，测试完成会尽快告知，体验版二维码依旧是






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
请提供一下预览二维码呢

**Comment by taiyiandr** [comment]
你好，我们这边看不到您提供的二维码图片。如果你们是邮件回复的，可以尝试将二维码作为附件上传。

**Comment by huyun1743518169** [comment]
上周有相应的调试方法，目前我们已经屏蔽了相关方法，因测试正在测试主要功能中，可能需要明天才能把方法放开，二维码已附件，用户之前也已添加为体验者，如果方便的话，可以加
微信：huyun18879099906，以便于及时的沟通
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
你好，我们这边看不到您提供的二维码图片。如果你们是邮件回复的，可以尝试将二维码作为附件上传。

**Comment by Hubmeat** [comment]
这个包是业务大包，能针对  open-type 给个单独的最小 demo 吗？麻烦提供 uni 未编译的包吧

**Comment by huyun1743518169** [comment]
最小包在附件里，请新建文件夹解压，配置用配套的，直接解压即可，不用另外npm install


uniapp未编译代码
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] 小红书无法获取用户手机号，和用户信息 (Issue #439)





 
这个包是业务大包，能针对  open-type 给个单独的最小 demo 吗？麻烦提供 uni 未编译的包吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

demo.rar (88.79M, 2022年12月29日 14:51 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5c36356137684acfb8cfde0645360b1a0053035351025c544c005705531b0d505302180006540d18505454505405015754520555633e3951045b5a4f11574b355c&t=exs_ftn_download&code=a65ac695

**Comment by taiyiandr** [comment]
uniapp写法问题，开发者已自行解决。
@getphonenumber="LOGIN_XHS"

**Comment by huyun1743518169** [comment]
首次授权获取的数据解密后是乱码，二次授权是正常解密
