### ISSUE TITLE
POI管理更新门店商品关系不起作用

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#441]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
小程序appid=appId=635dd82e99158d0001fafb10，小红书poi_id=1513678987052769129，调用POI管理-更新门店-商品关系接口已成功，用POI管理-获取POI下的商品列表接口也查询到数据，返回的数据为：{"data":{"list":[{"out_product_id":"60173985"}]},"success":true,"msg":"success","code":0} 
但是进入这个门店没有显示POI商品出来，麻烦看看
![lADPJxRxUILgK1TNCSTNBDg_1080_2340](https://user-images.githubusercontent.com/111478514/203719510-deecbe69-caac-4df8-ae5f-77b0d4d6d436.jpg)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by fyjr1997** [comment]
商品类目传错了，POI只展示类目是民宿/酒店-套餐和民宿/酒店-日历房的商品
