### ISSUE TITLE
小红书小程序安卓环境正常使用，IOS系统无法打开，一片空白

### ISSUE THREAD

**Issue by huyun1743518169** [redengineer/redmini#443]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.6.5 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
ios系统扫码一片空白，安卓手机可正常打开
 +
## 期望结果 和 实际结果(必填) +
ios系统也正常打开小红书小程序
正常加载出资源 +
 +

## 补充(猜测可能的原因是什么，你有啥想法，选填) +
安卓机正常使用，ios无法正常使用，猜测原因
1，平台兼容性问题
2，部分样式与方法不兼容ios ---依托与小红书，小红书生态环境。概率不大
3，页面报错----安卓正常使用，无报错，非逻辑bug

**Comment by AngryBrotherXiang** [comment]
iOS 7.65有问题，需要升级到7.65.1
