### ISSUE TITLE
利用ext.json实现自定义小程序首页不生效

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#447]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
提交代码时，我在ext.json里的entryPagePath字段放了自定义的小程序首页路径，但是小红书程序不生效，我这边测试过抖音小程序是生效的，就是ext.json的entryPagePath可以覆盖app.json的entryPagePath，但是小红书小程序不行，麻烦帮忙看看是否可以升级支持覆盖这个字段
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by xutm** [comment]
entryPagePath 小红书小程序 目前不支持

**Comment by xuwenjie0505** [comment]
那后面有没支持这个字段的计划呢？或者小红书小程序有没别的办法服务商是相同的代码模板情况下，可以实现不同商家自定义不同的首页路径呢

**Comment by xutm** [comment]
目前没有指定页面的话，会默认读取 pages 里面的 第一个页面。可以用次方案替代 entryPagePath。

**Comment by xuwenjie0505** [comment]
我试过ext.json里面传了pages，pages里面第一个放了小程序的首页路径，也无法实现切换首页路径的功能，麻烦帮忙确认下，谢谢
