### ISSUE TITLE
如何获取对应小程序用户的openId

### ISSUE THREAD

**Issue by anzzz999** [redengineer/redmini#448]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [x] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

1. 目前因为之前openId没有记录，导致现在推送不了订单状态，
麻烦帮忙查一下这个小程序这两单的openId，谢谢

 小程序id
62d530a568507d0001443f58

 订单编号
1550412069051383810
1550332946977849346

2. 然后有可以自查的接口吗，如何可以自查到openId

 +
## 期望结果 和 实际结果(必填) +
期望结果： 1. 能把这两个订单的openId查出来    2.有方法可以查到订单对应的openId
 +

**Comment by xutm** [comment]
只能通过登录流程获取 openid

**Comment by anzzz999** [comment]
> 只能通过登录流程获取 openid

能辛苦帮忙查询一下吗，因为是客户的openId，我们这边也没办法强制客户登录去拿这两个openId。。

**Comment by anzzz999** [comment]
> 只能通过登录流程获取 openid

或者说是否可以通过IDE去拿到这个openId呢
