### ISSUE TITLE
xhs.getExtConfig获取到的extConfig都是空的

### ISSUE THREAD

**Issue by WeiJietao** [redengineer/redmini#45]
## 系统环境(必填)
- [ ] IOS
- [X] Android
- [X] IDE

## 问题模块(必填)
- [ ] 审核
- [X] API & 组件 & 框架
- [X] IDE
- [X] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)

IDE 1.59.24
基础库 3.26.0
Android v.7.41.0.8750ffc

## 重现步骤 和 复现问题的最小demo Github链接

xhs.getExtConfig获取到的extConfig是空的，截图上面为ext.json内容，下面为xhs.getExtConfig success输出结果。

extAppid：62974fd8d64cf40001079ce8。

![截屏2022-06-07 上午11 33 07](https://user-images.githubusercontent.com/18640419/172298102-c5e01a46-5655-431e-aa73-b43431ac2f9a.png)

---

最新调查结果：

1. iOS上，`xhs.getExtConfigSync()`可以获取到extAppid，而`xhs.getExtConfig()`的success、fail、complete均没有接收到内容，Android上两个api均可正常调用；
2. Android上`xhs.getExtConfig()` success中返回的extConfig为JSON字符串（IDE上是Object），需要自己用`JSON.parse()`转换。

Android和iOS xhs.getExtConfig success、fail、complete输出对比：

Android：

![WechatIMG58](https://user-images.githubusercontent.com/18640419/173299236-b732d4e5-e0d6-4d54-9a9b-109bad7f626f.jpeg)

iOS：

![WechatIMG60](https://user-images.githubusercontent.com/18640419/173299188-0bcfc1aa-82f5-470b-8bb8-e8fd052c3b01.jpeg)

## 期望结果 和 实际结果(必填)

正常获取ext信息。

**Comment by taiyiandr** [comment]
同一个二维码，iOS正常吗？

**Comment by AngryBrotherXiang** [comment]
iOS 7.44版本修复xhs.getExtConfig()问题，在这之前，iOS只能使用xhs.getExtConfigSync()方法

**Comment by taiyiandr** [comment]
> 

Android 同样，7.44版本修复xhs.getExtConfig()问题。此版本之前，也只能使用xhs.getExtConfigSync()方法。

**Comment by Hubmeat** [comment]
744 RC 版本修复
