### ISSUE TITLE
商户笔记关联商品时，显示价格与传入价格不一致

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#450]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.5.6 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/118496055/204459324-1d105377-69d7-474f-bd9c-39672ef7b6ae.png)
![67b1f2aa-7ecc-4fd5-a92c-5b413bb0e452](https://user-images.githubusercontent.com/118496055/204459413-003818e8-277c-4f04-9694-2eed3071dde0.jpg)
商户在微盟后台创建并同步过去的商品价格为191元，但是笔记关联商品时价格显示61元，帮忙查一下。商户反馈不止该一个商品，可能需要统一修复一下
appid:6324297f22f7940001ef36b9
商品id:1397470140110
 +
## 期望结果 和 实际结果(必填) +
价格显示正常，且其他商品以及商户都显示正常+
 +

**Comment by Matthew-1996** [comment]
商品笔记关联商品时，价格展示当前SPU下价格最低的SKU的价格
