### ISSUE TITLE
小程序上传文件api没有包含文件流

### ISSUE THREAD

**Issue by wangting1234567** [redengineer/redmini#452]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
https://miniapp.xiaohongshu.com/docs/api/uploadFile 
我们根据文档使用了小程序的api，上传了图片，但是在到达我们服务端的时候没有接收到文件。
该后端接口原先是给微信小程序用上传文件用的，可以正常使用，但是小红书小程序上传时无法在后端转换成 StandardMultipartHttpServletRequest
![image](https://user-images.githubusercontent.com/119400770/208834632-1840b8f6-f163-4d7f-9f49-4c5d423f3062.png)
![image](https://user-images.githubusercontent.com/119400770/208834649-513c9ea4-4d08-4eb5-9244-7bc07192cd46.png)
![lQLPJxbrF8pxA1PNAQzNA3awdHpGAWVk3g0Dgj4Y1QBhAA_886_268 png_620x10000q90](https://user-images.githubusercontent.com/119400770/204477788-27c348a0-4792-41d1-90dc-fac44baf7b43.jpg)

我们尝试自己写死一个boundry，但是仍然无法满足文件上传的条件
 +
## 期望结果 和 实际结果(必填) +
不知道能不能给出一些改进的建议
 +

**Comment by xutm** [comment]
IDE 不支持

**Comment by BrighterAmmo** [comment]
> IDE 不支持

我们不是在ide上调的，我们直接扫码测试的

**Comment by xutm** [comment]
> > IDE 不支持
> 
> 我们不是在ide上调的，我们直接扫码测试的

是指真机调试吗？

**Comment by BrighterAmmo** [comment]
> > > IDE 不支持
> > 
> > 
> > 我们不是在ide上调的，我们直接扫码测试的
> 
> 是指真机调试吗？

真机调试的时候会说网络不行，我们用的预览模式

**Comment by xutm** [comment]
是 IOS 还是 Android？

**Comment by BrighterAmmo** [comment]
> 是 IOS 还是 Android？

都是这样

**Comment by BrighterAmmo** [comment]
真机调试的时候加载失败这个有什么办法吗

**Comment by taiyiandr** [comment]
请提供预览二维码，描述一下复现路径，并把小红书号【317940352】添加一下访问权限。谢谢

**Comment by BrighterAmmo** [comment]
ok，已经在准备了

**Comment by BrighterAmmo** [comment]
我们的上传图片的场景在订单支付成功后，发起售后时会上传售后凭证，这时会调用小红书的上传文件api
权限和预览码还要等一下。

**Comment by BrighterAmmo** [comment]
![image](https://user-images.githubusercontent.com/38214419/208631381-46b469fc-44db-4ab5-aca9-5777cc6200cf.png)
点击全部订单到订单列表
![image](https://user-images.githubusercontent.com/38214419/208631395-6d1134cb-613f-44d0-9684-eba124531b6a.png)
待发货的订单申请售后
![image](https://user-images.githubusercontent.com/38214419/208631410-ad2890b6-c3f0-45e9-9e7b-ae60543ffd95.png)
在上传凭证时会发起文件上传
![image](https://user-images.githubusercontent.com/38214419/208631424-b00e2d65-1dc5-400a-9276-59783ed312ff.png)

**Comment by BrighterAmmo** [comment]
> 请提供预览二维码，描述一下复现路径，并把小红书号【317940352】添加一下访问权限。谢谢

哈喽，这是预览码，权限我们也已经开通了，可以试一下了  
![image](https://user-images.githubusercontent.com/38214419/208638210-3c62589b-b519-4a12-b928-d7c50397e767.png)

**Comment by BrighterAmmo** [comment]
可以先授权注册一下然后点下fang方的全部 进入商品列表，滑到这个商品，选择 XS的支付一下，麻烦你了
![image](https://user-images.githubusercontent.com/38214419/208639473-4d276f38-63ec-48b5-94e0-afedd0056f1e.png)
![image](https://user-images.githubusercontent.com/38214419/208639586-07d714ec-1d46-47dc-96d4-a7a56d816ded.png)

**Comment by BrighterAmmo** [comment]
支付应该是一毛钱，成功之后发起退款可以上传图片，我们这边可以退款的。

**Comment by BrighterAmmo** [comment]
支付应该是一毛钱，成功之后发起退款可以上传图片，我们这边可以退款的。

**Comment by taiyiandr** [comment]
这个商品显示已经无货，另外的商品点击继续支付 提示订单尚未同步（从我的-全部订单进去支付也一样）

**Comment by BrighterAmmo** [comment]
不好意思，这个库存昨天被人改了。确实有些商品没有同步过去，改用这个商品吧
![image](https://user-images.githubusercontent.com/38214419/208798823-1a0972ba-110d-4d9a-b04f-1dea2a851900.png)
![image](https://user-images.githubusercontent.com/38214419/208798893-a9e20cc7-9258-4914-9621-9ce70e13f386.png)
![image](https://user-images.githubusercontent.com/38214419/208799023-9a13fb63-7b2e-4ae6-8145-a35d52c55483.png)

**Comment by taiyiandr** [comment]
uploadFile API 在其他场景下没问题。且在上面的场景中，当业务代码不传【"Content-Type":"multipart/form-data;boundary=-------------------------289417865703883381658994"】参数时，即可上传成功，返回如下内容（resourcePath下载的图片与上传的相符）。你们确认下呢？

{"errorCode":"0","msg":"success","msgInfo":"","data":{"resultMap":{"1":[{"recordId":2790,"classificationId":0,"resourceStorageType":1,"resourceExtensionType":1,"resourceExtensionName":".image","resourceName":"image","resourceActualName":"03a22367-62f2-4128-9892-9b2ee13721c7.image","resourcePath":"https://mpsit40.ibaiqiu.com/img/resourceBank/levis/levis_xhs_store/03a22367-62f2-4128-9892-9b2ee13721c7.image","resourceCoverId":null,"resourceCoverPath":"","summary":"","size":661278,"width":1080,"height":1296,"duration":null,"attributeJson":"","md5Hashcode":"ddebe53c2350b247030a58de4c7066b3","wxAppId":"","wxMediaId":"","qnHashcode":"","shopCode":"levis_xhs_store","tenantCode":"levis","delFlg":0,"createTime":"2022-12-21 11:22:45","createUser":"","updateTime":"2022-12-21 11:22:45","updateUser":""}]}},"traceId":"102711a75f8b497a"}

**Comment by BrighterAmmo** [comment]
收到

**Comment by BrighterAmmo** [comment]
可以拿到了，谢谢支持
