### ISSUE TITLE
视频全屏 安卓ios表现不一致

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#454]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v3.37.0 

## 重现步骤 和 复现问题的最小demo Github链接 +
一个竖屏视频点击全屏按钮 ，安卓全屏下变成横屏，ios为竖屏
 
## 期望结果 和 实际结果(必填) +
 都是竖屏

**Comment by taiyiandr** [comment]
目前小红书还没有自定义渲染层内核，无法获取视频相关参数。
可以先在业务代码上实现竖屏全屏逻辑。
