### ISSUE TITLE
web-view的h5执行postMessage在真机上面没有反应，在ide是好的

### ISSUE THREAD

**Issue by coshinehcl** [redengineer/redmini#456]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.65
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
你们自己测试下
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by Hubmeat** [comment]
android / ios 都有这个问题吗

**Comment by coshinehcl** [comment]
是的

**Comment by Matthew-1996** [comment]
排查中，预计跟版770

**Comment by coshinehcl** [comment]
这个还有问题。这边测试下来。e.detail.data 是string类型。而不是object。需要你们JSON.parse下

**Comment by coshinehcl** [comment]
> 这个还有问题。这边测试下来。e.detail.data 是string类型。而不是object。需要你们JSON.parse下



> 排查中，预计跟版770

还有问题

**Comment by xutm** [comment]
789 会修复，月底上线
