### ISSUE TITLE
xhs.request  状态码非200时返回结果非JSON格式时报错 无法拿到状态码

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#46]
![image](https://user-images.githubusercontent.com/31440366/172550040-3f627e53-a9ce-4d95-acbc-312a970120bd.png)
![image](https://user-images.githubusercontent.com/31440366/172550094-a80de633-90f0-43d7-8582-82eb14038e5b.png)
![image](https://user-images.githubusercontent.com/31440366/172550138-7390eb5f-cc30-48d5-bd0e-b51c6f78ac97.png)

**Comment by xutm** [comment]
真机上的效果也是一样的吗？

**Comment by Yaxian** [comment]
不指定 datatype，返回结果默认按 json 处理。
如果指定了 datatype 是json，你们后端返回的得是 json 格式
