### ISSUE TITLE
app.json全局配置失效

### ISSUE THREAD

**Issue by yintingwen** [redengineer/redmini#47]
## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
v7.42.0.0309f18
## 重现步骤 和 复现问题的最小demo Github链接
在app.json中配置了 navigationBarBackgroundColor/navigationBarTextStyle 为白底黑字，而其他页面中没有单独设置
但是在真机预览中，所有页面的头部条都成为了默认的黑底白字，全局设置未生效，模拟器中显示正常
![Snipaste_2022-06-08_17-29-16](https://user-images.githubusercontent.com/52306105/172583126-c16538fd-a770-4f96-967e-10127d252c28.png)
![3006442c5267dd8af3ff3c75eba469fe](https://user-images.githubusercontent.com/52306105/172583570-7e9295dd-e344-4768-b6ea-35805d5ad5e0.jpg)

## 期望结果 和 实际结果(必填)
全局配置真机生效

**Comment by xutm** [comment]
安卓将于744fix
