### ISSUE TITLE
小红书专业号的订购模块商品数量错误

### ISSUE THREAD

**Issue by hurongguang** [redengineer/redmini#470]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [x] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
小红书首页的订购模块只展示5个商品，实际上有6个商品
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by fyjr1997** [comment]
检查商品类目

**Comment by hurongguang** [comment]
都是这个 627a33edff16300001314989 类目（户行服务-民宿/酒店-套餐）,一共六个商品，只展示了五个

**Comment by hurongguang** [comment]
appId: 6396e40ea9f15f00012064ba
