### ISSUE TITLE
小程序中同步了的订单在app的订单中无法显示详情

### ISSUE THREAD

**Issue by BrighterAmmo** [redengineer/redmini#471]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
调用小程序的订单相关的api将订单信息同步给小红书后，能够使用api查询到订单详情
![image](https://user-images.githubusercontent.com/38214419/207753738-ea0b08d0-c93c-41be-ad46-106430195ccc.png)
但是在app的订单列表中详情没有显示
![image](https://user-images.githubusercontent.com/38214419/207754565-df54aac9-87d3-42c7-ba64-dd473a4a3c09.png)

https://user-images.githubusercontent.com/38214419/207754654-ba91f929-6215-4ebc-a003-5512efcbcb80.mp4

## 期望结果 和 实际结果(必填) +
期望可以正常跳转到小程序的订单详情

**Comment by BrighterAmmo** [comment]
订单号是 HS186261059904298852

**Comment by Matthew-1996** [comment]
优先看一下，订单路径（path）传的是不是有问题

**Comment by Matthew-1996** [comment]
https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-mp-deal-order-get
