### ISSUE TITLE
video 期望支持显示音量键

### ISSUE THREAD

**Issue by xf079** [redengineer/redmini#472]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
video 没有显示音量键的api
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by Hubmeat** [comment]
截图看下期望什么效果

**Comment by echooys** [comment]
> 截图看下期望什么效果

![image](https://user-images.githubusercontent.com/63334662/207807250-e881df56-c3a4-459c-af15-fe2eb47e1a69.png)
这样有控制视频声音的

**Comment by Hubmeat** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/25141100/207808012-ec5dd54c-4530-4828-b844-b37add6f95fc.png">
这个功能是有的, 你检查下配置呢

**Comment by echooys** [comment]
> <img alt="image" width="706" src="https://user-images.githubusercontent.com/25141100/207808012-ec5dd54c-4530-4828-b844-b37add6f95fc.png">
> 
> 这个功能是有的, 你检查下配置呢

但是文档里确实没有啊

**Comment by Hubmeat** [comment]
OK ,  看了下微信这边可以通过 show-mute-btn 支持静音，小红书在下个版本做同步支持

**Comment by echooys** [comment]
> OK , 看了下微信这边可以通过 show-mute-btn 支持静音，小红书在下个版本做同步支持

好的，谢谢
