### ISSUE TITLE
小红书绑定手机号的组件无法点击

### ISSUE THREAD

**Issue by BrighterAmmo** [redengineer/redmini#485]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
如图所示，弹框里面的立即绑定无法点击
![lQLPJv9o300VFsTNAhHM9LAUtzFWc_m3VwOnctG7gFoA_244_529 png_620x10000q90](https://user-images.githubusercontent.com/38214419/209766345-418b13db-719e-463e-a943-01a710bfc017.jpg)

## 期望结果 和 实际结果(必填) +
能够点击绑定手机号

**Comment by taiyiandr** [comment]
你好，确认Android也存在此问题吗？

**Comment by BrighterAmmo** [comment]
你好，是的，上午的时候有这个问题

**Comment by taiyiandr** [comment]
请在Android上再复现并提供录屏，同时给一下使用的小红书号呢？

**Comment by xfg520** [comment]
> 请在Android上再复现并提供录屏，同时给一下使用的小红书号呢？

你好 能不能解答下我提出的问题呢

**Comment by taiyiandr** [comment]
> > 请在Android上再复现并提供录屏，同时给一下使用的小红书号呢？
> 
> 你好 能不能解答下我提出的问题呢

你好，我这边是Android开发哈

**Comment by xfg520** [comment]
> > > 请在Android上再复现并提供录屏，同时给一下使用的小红书号呢？
> > 
> > 
> > 你好 能不能解答下我提出的问题呢
> 
> 你好，我这边是Android开发哈

好的！那你能不能找个人解决下484的问题呢

**Comment by taiyiandr** [comment]
> > > > 请在Android上再复现并提供录屏，同时给一下使用的小红书号呢？
> > > 
> > > 
> > > 你好 能不能解答下我提出的问题呢
> > 
> > 
> > 你好，我这边是Android开发哈
> 
> 好的！那你能不能找个人解决下484的问题呢

已经有相关同学在解决了哈
