### ISSUE TITLE
xhs.getSystemInfoSync返回值不正确

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#49]
name | about | title | labels | assignees
-- | -- | -- | -- | --
xhs.getSystemInfoSync返回值不正确 | 最新APP版本API getSystemInfoSync函数字段windowHeight返回值始终为0，老版本就没问题 |   |   |  

## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小程序APP版本：7.43.0

## 期望结果 和 实际结果(必填)
希望返回正确可使用窗口高度

## 重现步骤
小红书小程序出现空白
多个账号和网络切换都是空白
小程序名称：安娜Con-「美瞳集合店」
![image](https://user-images.githubusercontent.com/33249100/173350481-726fbd1e-153c-4efc-9dae-cbd9f48d34fc.png)

红色线框出部分不应该出现空白

![Ekp32YIBQU](https://user-images.githubusercontent.com/33249100/173351033-1463d789-ba0e-420f-ae8a-6ce1e658a05f.png)

**Comment by AngryBrotherXiang** [comment]
开发者在小程序页面创建之前调用，这时候windowHeight实际上还没算出来，建议在onload之后调用
