### ISSUE TITLE
hideShareMenu()不起作用

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#490]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="691" alt="image" src="https://user-images.githubusercontent.com/35423514/209895195-daf08619-e17a-4fd4-ae72-68cc0a76dfb6.png">
无法关闭分享

 +
## 期望结果 和 实际结果(必填) +
可以正常关闭分享
 +

**Comment by Hubmeat** [comment]
你好，这是 taro 的用法吧。能给下 taro 的最小 demo 吗？ 我们这边看下什么原因。

**Comment by dc980806** [comment]
[demo.zip](https://github.com/redengineer/redmini/files/10317464/demo.zip)

**Comment by Hubmeat** [comment]
demo 中的使用案例不对，正确调用方式为：

/**
 * @enum { normal } - 站内分享
 * @enum { wxFriends } - 微信好友
 * @enum { wxMoments } - 微信朋友圈
 */
export enum ShareType {
  normal = 'normal',
  wxFriends = 'wx_friends',
  wxMoments = 'wx_moments',
}

```js
    Taro.hideShareMenu({ shareTypes: 'normal, wx_friends, wx_moments' })
```

可以参考：https://miniapp.xiaohongshu.com/docs/guide/openShare
