### ISSUE TITLE
小程序accessToken每到凌晨3点5分，后台接口都报 应用访问令牌不匹配

### ISSUE THREAD

**Issue by yinpeng633** [redengineer/redmini#491]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 如题，12月29号凌晨2点55分新获取的accessToken 在3点05分之前还正常，05分后就报应用访问令牌不匹配，+
 accessToken是同一个，缓存在redis，确定在2点55分只获取了一次+
## 期望结果 和 实际结果(必填) +
调用接口正常 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
是不是商品新增/修改接口有 限流，超过特定qps就报”应用访问令牌不匹配“

**Comment by wdvxdr** [comment]
https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-token
"生成新的 access_token，如果上一个生成的 access_token 有效时间大于 5 分钟，上一个 access_token 的有效期会缩短至 5 分钟。"
你们在02:55 03:00 请求了两次 /api/rmp/token 接口

**Comment by yinpeng633** [comment]
@wdvxdr ”你们在02:55 03:00 请求了两次 /api/rmp/token 接口“，最早怀疑是并发问题获取了两次，但是看了下日志2:55分 只调用了一下/api/rmp/token接口
