### ISSUE TITLE
开通小红书cps分佣权限后无法设置买样

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#493]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
开通小红书cps分佣权限后无法设置买样，提示：“获取spu 638efe919db9d90001767b14信息失败,请稍后重试”
看商品送审信息没问题的。
![企业微信截图_d5bf729f-1d3f-4297-b2bb-683a0c4446cc](https://user-images.githubusercontent.com/33249100/210035320-26d23c04-bb85-4885-8705-391813f29041.png)

出现问题的小程序appid：635b8b22a14d0d0001c3ff5e
 +
## 期望结果 和 实际结果(必填) +
可以正常设置买样 +
 +

**Comment by Matthew-1996** [comment]
原因：商品未过审；处理：已人工审核通过
