### ISSUE TITLE
用户点私信链接进小程序显示 No message available

### ISSUE THREAD

**Issue by yinpeng633** [redengineer/redmini#495]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
小程序基础库版本 3.36.2，用户小红书App版本未知+
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
<img width="627" alt="image" src="https://user-images.githubusercontent.com/4269654/210698586-6671d2c5-0e53-4a9d-8d9e-b7ea90c2c809.png">
 +
 +
## 期望结果 和 实际结果(必填) +
正常从私信链接进入小程序 +
 +

**Comment by xutm** [comment]
是哪个小程序？

**Comment by yinpeng633** [comment]
> 

花筑民宿，是个别用户才有这个问题，大部分都能正常进入

**Comment by fanqidong** [comment]
@xutm 你好 最近在开发小红书小程序 发现小红书IDE不太好用 审查元素Element 经常出不来，只显示一个根标签 严重影响了调试 希望能改进一下这个问题，盼回复
![image](https://user-images.githubusercontent.com/33058804/210925856-622187be-c390-4b43-9ab3-f7a06165209c.png)

**Comment by xutm** [comment]
> @xutm 你好 最近在开发小红书小程序 发现小红书IDE不太好用 审查元素Element 经常出不来，只显示一个根标签 严重影响了调试 希望能改进一下这个问题，盼回复 ![image](https://user-images.githubusercontent.com/33058804/210925856-622187be-c390-4b43-9ab3-f7a06165209c.png)

是 二跳场景吗？
