### ISSUE TITLE
POST请求，content-type使用application/x-www-form-urlencoded会导致参数错误

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#5]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [x] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
基础库版本 3.21.2
## 重现步骤 和 复现问题的最小demo Github链接
```js
  xhs.request({
    url: 'example.php', // 仅为示例，并非真实的接口地址
    method: 'POST',
    data: {
      x: '123',
      y: 456,
      z: '7b9',
    },
    header: {
      'content-type': 'application/x-www-form-urlencoded',
    },
    success(res) {
      console.log(res.data);
    },
  });
```
<img width="342" alt="DX-20220506@2x" src="https://user-images.githubusercontent.com/16522613/167124082-10155a14-1a74-4e71-a7ba-a293aa4959d5.png">

## 期望结果 和 实际结果(必填)
正常显示 传入的参数

**Comment by xutm** [comment]
IDE 网络面板展示 bug，不影响实际功能

**Comment by xutm** [comment]
IDE 1.59.24 fixed
