### ISSUE TITLE
业务域名配置报错

### ISSUE THREAD

**Issue by yukari521** [redengineer/redmini#500]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [ ] IDE +
- [x] 其它

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 
![E886B607-1C0D-4E0F-8566-C70EF035D3A1](https://user-images.githubusercontent.com/26429674/210952937-772439ae-7ddc-4124-86a8-41e2a7c997fa.jpeg)

![D22C7768-3A7E-46AF-B267-4209D79F33E1](https://user-images.githubusercontent.com/26429674/210952916-9fc5dce9-05d7-43de-a483-47c3d70629d3.jpeg)

小程序后台添加业务域名接口报错，如上图，接口地址：https://pro.xiaohongshu.com/api/eros/mp/red/mp/apps/6396a85dbeef0d00019effe1/config/web-view

校验文件已上传：https://pubswap.sendinfo.com.cn/493b4730.txt，可以访问。
 +
## 期望结果 和 实际结果(必填) +
能够正常配置业务域名
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
。。。

**Comment by wdvxdr** [comment]
Invalid mime type "text/plain; charset=utf-8,gbk"
修改成 text/plain;charset=UTF-8 试一下

**Comment by yukari521** [comment]
> Invalid mime type "text/plain; charset=utf-8,gbk"
> 修改成 text/plain;charset=UTF-8 试一下

这是需要手动请求接口去配置业务域名吗？没明白什么意思，能够说明这个问题原因是什么吗？另外，如果是接口问题应该是平台来修复解决。

**Comment by wdvxdr** [comment]
意思是修改下你们根目录文件返回的charset
