### ISSUE TITLE
uniapp项目移植打包后报错

### ISSUE THREAD

**Issue by Hankbeast** [redengineer/redmini#501]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
按照小红书的文档新建uniapp项目，选择模版后将原uniapp项目(HBuilderX创建，不支持打包到小红书)移植至新项目 +
 +
## 期望结果 和 实际结果(必填) +
npm run build:xhs打包后在IDE打开，报错"逻辑层初始化加载错误，请优先处理: ReferenceError: pleaseSetTranspileDependencies is not defined"，pages.json的tabbar正常加载 +
 +

**Comment by xutm** [comment]
https://blog.csdn.net/weixin_40548203/article/details/128563946

试试这个呢？
