### ISSUE TITLE
小程序商品-请求sku下架接口并返回成功，但sku并没有被下架

### ISSUE THREAD

**Issue by Zonev** [redengineer/redmini#505]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
+ 复现步骤：
post请求:https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/sku/batch_offline
body:
{"out_sku_ids":["1611312924951785474","1611312924955979778","1611312924955979779","1611312924955979780","1611312924955979781","1611312924955979782","1611312924955979783","1611312924955979784"]}
出参:
{"code":0,"msg":"success","success":true}

## 期望结果 和 实际结果(必填) +
+ 期望结果：下架入参内的 SKU
+ 实际结果：入参内的 SKU 没有被下架
![image](https://user-images.githubusercontent.com/33475810/211289812-da0b4735-e1ce-4d4a-a760-a623ff70bf14.png)

**Comment by wdvxdr** [comment]
日志看，下架之后又通过商品同步接口，把商品状态置为1了。再确认一下下架流程呢
