### ISSUE TITLE
开发者工具不显示DOM结构、重启IDE也不生效 严重影响调试

### ISSUE THREAD

**Issue by fanqidong** [redengineer/redmini#506]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v3.37.0 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：
![image](https://user-images.githubusercontent.com/33058804/211234016-2af9d5ce-2634-41c0-ad19-31d024c2fa60.png)

## 期望结果 和 实际结果(必填) +
正常加载DOM +
 +

**Comment by xutm** [comment]
是页面二跳场景吗？

**Comment by fanqidong** [comment]
运行一段时间或者打开一两个就会不显示 Elements那一栏，直接显示空白，根本无法调试页面样式。

**Comment by xutm** [comment]
ok，是 windows 还是 mac？

**Comment by yanyunwu** [comment]
@fanqidong 你好，针对目前的小红书ide请采用真机调试的方案，具体为点击真机调试，然后打包完成会生成二维码，在小红书app扫码即可调试，此时在idm会弹出一个调试的窗口，在这个窗口可以查看调试信息，dom结构等等。不要使用ide中的调试工具

**Comment by jswbiubiu** [comment]
> @fanqidong 你好，针对目前的小红书ide请采用真机调试的方案，具体为点击真机调试，然后打包完成会生成二维码，在小红书app扫码即可调试，此时在idm会弹出一个调试的窗口，在这个窗口可以查看调试信息，dom结构等等。不要使用ide中的调试工具
这下好了  真机调试也坏了
