### ISSUE TITLE
jssdk 3.4.2找不到previewImage等方法

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#51]
![image](https://user-images.githubusercontent.com/31440366/173570092-32823b25-956f-4a34-b54d-50e093a6bae5.png)
![image](https://user-images.githubusercontent.com/31440366/173570146-b5d856db-626a-411e-ad15-c30d44b0f9d4.png)

**Comment by xutm** [comment]
IDE 暂不支持，请在真机上验证
