### ISSUE TITLE
小红书服务端订单-新增/修改接口返回提示获取佣金率设置失败 

### ISSUE THREAD

**Issue by huang-shen** [redengineer/redmini#510]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [x] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
appId:637728b449d1490001569235
调用订单-新增/修改接口 https://miniapp.xiaohongshu.com/api/rmp/mp/deal/order/upsert 的时候，接口返回了这个错误.
```java
{
    "data": null,
    "success": false,
    "msg": "获取佣金率设置失败",
    "code": 420114
}
```

 +
## 期望结果 和 实际结果(必填) +
创建订单后应出现正确返回内容
```java
{
    "data": {
        "out_order_id": "string",
        "order_id": "string",
        "final_price": 0,
        "pay_token": "string",
        "expired_time": 0
    },
    "success": true,
    "msg": "success",
    "code": 0
}

```

**Comment by Matthew-1996** [comment]
https://oa.xiaohongshu.com/h5/terms/ZXXY20220407006/-1

**Comment by Matthew-1996** [comment]
需要提交保证金后，才可开通支付能力。（创建小程序时品牌已阅读并签署合作协议，协议中有保证金下线打款流程和账户）
请确认一下是否提交保证金。若已提交可以出示一下打款票据。

如仍有相关问题，建议通过销售沟通小程序运营团队

**Comment by huang-shen** [comment]
想问下打款票据应该向谁提供？

**Comment by huang-shen** [comment]
![img_v2_88cd2069-26a7-44f7-99e7-9681512da5cg](https://user-images.githubusercontent.com/53030164/216264582-6eb17c99-ece4-4bb4-b862-3ba068732d05.jpg)
