### ISSUE TITLE
uniapp打包到小红书后切换页面报错，且页面在第二次进入时无法正常加载

### ISSUE THREAD

**Issue by Hankbeast** [redengineer/redmini#511]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
uniapp项目打包到小红书小程序，所有页面在进入（或切换）时会报错，错误信息为Cannot destructure property 'appId' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined +
此外，除了tabbar中的页面，其他所有页面除了首次进入可以正常渲染之外，再次进入均无法渲染出现白屏（tabbar仍然存在），不确定是否和第一条的错误有关 +
 +
工程项目和project.config.json中均有正确的appid +
 +

**Comment by xutm** [comment]
建议先自查一下。不行的话，可以提供下，最小 demo

**Comment by xutm** [comment]
能提供一个最小 demo 吗？

**Comment by Hankbeast** [comment]
> 能提供一个最小 demo 吗？

[mp-xhs.zip](https://github.com/redengineer/redmini/files/10529450/mp-xhs.zip)
这是用uniapp打包后的代码

**Comment by fanqidong** [comment]
真机扫码调试遇到同样的报错 Cannot destructure property 'appId' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

**Comment by yanyunwu** [comment]
你这个demo业务逻辑太多了，且是打包后的，很难排查，最好是提供一个精简的demo，另外可以录一下屏
