### ISSUE TITLE
uni.request 和xhs.request  请求返回相同结果，ios和安卓执行不同的回调

### ISSUE THREAD

**Issue by jianchaoWang4515** [redengineer/redmini#52]
![wecom-temp-df07fc9dd21e15c93f8d5554fa8d3872](https://user-images.githubusercontent.com/31440366/173712868-93b294fd-3e74-44a5-84f5-c1f872417f73.jpg)

当返回以上结果时：
 1. uni.request  安卓只会执行complete而不会执行fail回调  ios会执行fai回调 两端导致不一致
 2. xhs.request会执行success回调 而ios会执行fail回调

**Comment by xutm** [comment]
期望的结果，也给一下吧
