### ISSUE TITLE
商品-新增/修改 接口调成功- 服务号下方未展示商品

### ISSUE THREAD

**Issue by huang-shen** [redengineer/redmini#527]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 +  调用商品-新增/修改 商品同步成功 在服务号下方未看到有商品展示
![img_v2_d07b0494-855e-4250-b394-d67538d2cd7g](https://user-images.githubusercontent.com/53030164/215442551-6b4c425a-fdc0-411e-b5e2-1ec1e5672ba8.png)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
![img_v2_c513d591-806f-40a1-a5e8-86bf4440ac7g](https://user-images.githubusercontent.com/53030164/215442507-d49a8d13-8427-45ab-8dc2-bba16409cb87.jpg)

**Comment by Matthew-1996** [comment]
1、主页管理打开“店铺”按钮，就会有商品页tab。操作详见：【小程序入口-账号主页入口】https://doc.weixin.qq.com/doc/w3_AfkApwYEAGgU8ZpKwVUQaayRvOFle?scode=ANAAyQcbAAg0n1D1UiAfkApwYEAGg
2、商品-新增/修改仅影响商品库，不影响主页的商品页tab展示。主页的商品页tab编辑详见：https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-display-home_page_item_tab
