### ISSUE TITLE
image组件设置style样式height为auto之后预览时高度为0

### ISSUE THREAD

**Issue by jswbiubiu** [redengineer/redmini#528]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
基础库3.37.0
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如： 小demo 分别为html  css  和page页面  
https://pic.imgdb.cn/item/63d8debde90d1c0098b4fec7.png
https://pic.imgdb.cn/item/63d8debde90d1c0098b4fedf.png
https://pic.imgdb.cn/item/63d8debde90d1c0098b4fef1.png
 +
## 期望结果 和 实际结果(必填) +
设置属性 height为auto时能够正常加载出图片 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
从图中可以看出image设置样式height: auto;无效 图片直接不显示！！！

**Comment by Hubmeat** [comment]
图片使用 background-image 进行展示，需手动设置高度，auto 内没有元素高度为0 哈

**Comment by jswbiubiu** [comment]
重点不是需手动设置高度，auto 内没有元素高度为0 哈

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jswbiubiu** [comment]
主要是内部组件image  的图片即使不设置height  那么它的高度也应该默认为它图片的本身高度才对啊  可是项目中使用时  它却展示不出来呢

**Comment by jswbiubiu** [comment]
我uniapp项目中使用场景是这样的  前端使用得是富文本 mp-html 组件来渲染 以下内容 然后小红书ide显示的**只有设置了height为绝对单位的才能展示** ，  而**微信、字节小程序是正常的**三张图片都能正常比例展示的

<mp-html
           :copy-link="false"
           @linktap="clickLink"
          :content="desc"
          error-img="xxx.png"
        ></mp-html>

样式css： 
.detail-desc-box {
    ._img,
    img,
    image {
      max-width: 100%;
      height: auto;
    }
  }

desc内容
<p>
    <a href="/appoint/appointProduct?groupId=33990&amp;yyCustId=6297191" target="_self" title="预约链接33">预约链接33</a>    <br />
</p>
<p>
          <img class="raw-image" data-ratio="1.5096953" data-w="722" data-src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" title="温德姆_01.jpg" src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" lazy="loaded" style="font-size:16px;text-align:center;" /><br />
          <img class="raw-image" data-ratio="1.5096953" data-w="722" data-src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" title="温德姆_02.jpg" src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" lazy="loaded" style="font-size:16px;text-align:center;height:400px;" /><br />
        <img class="raw-image" data-ratio="1.5096953" data-w="722" data-src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" title="温德姆_03.jpg" src="https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png" lazy="loaded" style="font-size:16px;text-align:center;height:auto;" /><br />
</p>

**Comment by jswbiubiu** [comment]
请问下小红书的开发人员是跑路了吗？ 没有回复了？

**Comment by Hubmeat** [comment]
你这边提供下可以复现 image 问题的小红书语法的 demo 吧，之前目前内部测试下来 image 组件表现正常的。uni、mp-html 等第三方包实现有差异，我们先排除 Image 组件本身的问题

**Comment by jswbiubiu** [comment]
我上面已经发的很清楚了 就是image组件的问题  您可以在小红书ide上测试  写一个image  用css来控制
![image](https://user-images.githubusercontent.com/90231104/219546937-e09d787b-ee6f-4670-9004-6355466756e1.png)
![image](https://user-images.githubusercontent.com/90231104/219546998-e1cfcce2-60ea-4000-a2ce-e7166a83faaa.png)
看这里  只有img3 设置了写死的height： 100px  才有高度显示，

**Comment by jswbiubiu** [comment]
随便用一张图来测试  在微信、头条小程序上都是可以正常展示高度的 （都设置了max-weight: 100%，height: auto情况下） 唯独小红书的高度被吞了

**Comment by jswbiubiu** [comment]
> 你这边提供下可以复现 image 问题的小红书语法的 demo 吧，之前目前内部测试下来 image 组件表现正常的。uni、mp-html 等第三方包实现有差异，我们先排除 Image 组件本身的问题

麻烦您再确认下  用小红书ide来模拟我上面的例子  如果你设置height为auto图片能正常显示那就牛逼close咯

**Comment by Hubmeat** [comment]
好的，我们先排查下，最新版尽快修复，后续会同步版本更新时间

**Comment by jswbiubiu** [comment]
辛苦了大佬  小红书ide的命运掌握在你们手里了哈哈

**Comment by yanyunwu** [comment]
正在修复

**Comment by yanyunwu** [comment]
在不，微信和百度都是设置auto后图片不显示啊，你可以再详细一点吗

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jswbiubiu** [comment]
我都试过了&nbsp; 微信、头条、小程序&nbsp; 只要图片本身有宽高xx（px单位）默认height: auto; 能正常显示的&nbsp;&nbsp;
（tips：不过官方这么晚才给出答复&nbsp; 这个问题已经早用别的方法代替解决了&nbsp; 挺差评的~谢谢）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redengineer/redmini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redengineer/redmini] image组件设置style样式height为auto之后预览时高度为0 (Issue #528)





 
在不，微信和百度都是设置auto后图片不显示啊，你可以再详细一点吗

**Comment by yanyunwu** [comment]
不是，你再去微信试一下，我们发现微信设置auto也是图片不显示

**Comment by yanyunwu** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/73828319/226238515-c266093d-e5d2-4493-91ac-53e592f51d9a.png">
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/73828319/226238553-7ea91bd0-b731-484f-b6c1-6277660ad865.png">

**Comment by yanyunwu** [comment]
有图有真相

**Comment by yanyunwu** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/73828319/226238692-92cc4d69-af45-406e-8011-e15069ea6b49.png">
什么都不加默认是显示的，图片默认值是320 X 255，设置auto就是0，都是这样的呀

**Comment by jswbiubiu** [comment]
好的吧  No problem

**Comment by fanqidong** [comment]
@jswbiubiu  你好 遇到同样的问题 也是用mp-html 图片不显示 你是如何解决这个问题的？

**Comment by jswbiubiu** [comment]
> 


          <rich-text :nodes="content" />
          
          
          <mp-html :content="content"></mp-html>
