### ISSUE TITLE
ide开发工具 element、network体验差

### ISSUE THREAD

**Issue by jswbiubiu** [redengineer/redmini#529]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
基础库3.37.0
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
第一次打开开发工具时  element元素菜单还能点击查看  跳转页面之后 即无法访问了

**Comment by jswbiubiu** [comment]
network 就是  选择ajax请求列表  展示了

**Comment by jswbiubiu** [comment]
network 就是 选择ajax请求列表 展示了与其不相关的例如图片、...等其他非xhr请求

**Comment by jswbiubiu** [comment]
第一次打开 https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1855.png
点击跳转路由后 https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1863.png
network https://pic.imgdb.cn/item/63d8e254e90d1c0098bd1875.png

**Comment by xutm** [comment]
好，我们看下

**Comment by jswbiubiu** [comment]
好的&nbsp; 辛苦了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月31日(星期二) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [redengineer/redmini] ide开发工具 element、network体验差 (Issue #529)





 
好，我们看下

**Comment by jswbiubiu** [comment]
别光看呀大佬  已经大半年了  去年7-8月份  使用ide的时候就体验很难受了  至今为此没有任何改变  开发者都快吐槽dead了

**Comment by fanqidong** [comment]
复议 确实是没有小程序开发ide和抖音开发ide好用 很多功能都不支持 编译一次预览代码 几分钟  就离谱

**Comment by anaian** [comment]
感觉就是KPI的产物,要不行了

**Comment by xutm** [comment]
Elements 跳转消息问题，已经修复了，还在 beta 阶段，晚点发 release 版本

**Comment by JacquesYW** [comment]
能比小红书开发工具差的,也就只能拉qq的开发工具出来遛一遛了

**Comment by JacquesYW** [comment]
element能渲染出来..都看运气...

**Comment by xutm** [comment]
1.61.0 已经修复
