### ISSUE TITLE
IOS真机上调用saveImageToPhotosAlbum方法下载图片报错: 图片路径为空

### ISSUE THREAD

**Issue by Silious** [redengineer/redmini#53]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
APP: v7.42.1(7421003)
## 期望结果 和 实际结果(必填)
期望结果：下载成功
实际结果：报错信息：
····
message:
          "savelmageToPhotosAlbum fail: call function: 'savel
          mageToPhotosAlbum',图片路径为空°
          stack:
          "@in@n@inJ@Inb@ln@\ngeneratorResume@(native
          code inn@ina@n@lnPromise@(native codeInt@n
          @IndeQueue@\ne@"
···

## 补充(猜测可能的原因是什么，你有啥想法，选填)
实际是传了图片链接的

**Comment by AngryBrotherXiang** [comment]
麻烦给下图片链接，或者复现场景二维码，图片未找到会回调 图片路径为空

**Comment by Silious** [comment]
> 麻烦给下图片链接，或者复现场景二维码，图片未找到会回调 图片路径为空

https://image-c-dev.weimobwmc.com/watermark/qa-merchant-setting/cebe1d99574dc02bcb5c9d4b8b60f4a9.png

**Comment by AngryBrotherXiang** [comment]
> 
savelmageToPhotosAlbum不支持网络路径

**Comment by Silious** [comment]
> 
是先调用getImageInfo再调用saveImageToPhotosAlbum的，代码如下：
`
xhs.getImageInfo({
  src: 'https://image-c-dev.weimobwmc.com/watermark/qa-merchant-setting/cebe1d99574dc02bcb5c9d4b8b60f4a9.png',
  success (res) {
  xhs.saveImageToPhotosAlbum({filePath:res.path})
  }
})
`

**Comment by Silious** [comment]
> 

@AngryBrotherXiang
