### ISSUE TITLE
微盟-商户第三方客服系统无法正常打开

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#537]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.73.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
app搜索JNBY进入官方店铺首页，右下角点击客服
下为录屏：
https://user-images.githubusercontent.com/118496055/217160790-7fbb2a4c-13b4-41d8-b041-c5c65f523174.mp4
第三方客服(七鱼）链接：
https://jnby.ioutu.cn/weimo/customerService/index.html

 +
## 期望结果 和 实际结果(必填) +
支持正常打开客服功能 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
是否是目前的域名被做了限制，是否有什么解决方案

**Comment by Matthew-1996** [comment]
请自查 appid 有没有问题
