### ISSUE TITLE
微盟-商户第三方客服系统异常

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#539]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.73.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
第三方客服系统打开异常，此前排查因未加白导致无法访问，现已开白，但ios进入后显示白屏，andriod进入显示无法打开页面 +
 复现路径：app搜JNBY->进入店铺->点击首页右下角客服+

以下为ios录屏
https://user-images.githubusercontent.com/118496055/217704412-b41e9a92-9b99-4b5b-a708-92ee4e9c4797.mp4

我方排查如下：
![排查1](https://user-images.githubusercontent.com/118496055/217704362-23c711ea-5dbb-4997-82da-8090d49939e1.jpg)
![排查2](https://user-images.githubusercontent.com/118496055/217704378-7369050c-f0ba-4034-bde0-db8c73e3de8f.jpg)
我方抓到这个第三方的地址上有接口报错，Traceid: ffa4bc597f634eaf95c690a46d325000，应该是被这个请求拦掉了  导致的白屏
![排查3](https://user-images.githubusercontent.com/118496055/217704393-27284d24-174f-4d72-9186-f47de945ff6a.png)

## 期望结果 和 实际结果(必填) +
正常加载出资源，辛苦定位一下是需要贵方优化还是第三方优化+
 +

**Comment by xutm** [comment]
把你们后台添加的域名白名单list，截图看看

**Comment by mmeng1996** [comment]
![企业微信截图_16764470502321](https://user-images.githubusercontent.com/118496055/218969229-9c1bccf1-85bf-4329-9370-fa91183da207.png)
这个是我们添加的域名白名单，辛苦看看

**Comment by mmeng1996** [comment]
白名单已添加完了，但是还是显示白屏。辛苦帮忙再加急查一下
<img width="925" alt="企业微信截图_16768746136950" src="https://user-images.githubusercontent.com/118496055/220070865-5f133cb9-9313-4703-811f-890c58d7f63a.png">

**Comment by xuwenbo22** [comment]
具体需要将哪些域名添加，111111139.qiyukf.com这个域名下的链接有很多的，且可能少了一个 都不知道

**Comment by xuwenbo22** [comment]
按照常规逻辑，既然小红书测给111111139.qiyukf.com这个域名加白，不拦截了，那应该这个域名下的链接访问也不被拦截。。如果要罗列出来所有链接，这个难度有点大
