### ISSUE TITLE
小红书小程序一键搬家路径报错

### ISSUE THREAD

**Issue by liuqingqing95** [redengineer/redmini#54]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [x] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
2.20.2
## 重现步骤 和 复现问题的最小demo Github链接
选择微信小程序，进行导入
![afdc014163e166ff25ab9357bcd6f60](https://user-images.githubusercontent.com/20039379/173766326-0931f5a7-1518-4b9a-a345-a79c1911d70b.png)

## 期望结果 和 实际结果(必填)
文件路径存在问题
![image](https://user-images.githubusercontent.com/20039379/173766511-f91417db-1164-4402-bd66-b66f7b81d970.png)

## 补充(猜测可能的原因是什么，你有啥想法，选填)
貌似小红书必须使用相对路径？
![image](https://user-images.githubusercontent.com/20039379/173766812-bb871404-3aea-431a-8e3e-3e0222d10ab3.png)

**Comment by liuqingqing95** [comment]
这个报错麻烦看看吧，不清楚在哪配置比较好 
![Uploading 1655278214751.png…]()

**Comment by liuqingqing95** [comment]
这个报错麻烦看看吧，不清楚需要在哪配置
![1655278214751](https://user-images.githubusercontent.com/20039379/173769595-70370081-8af2-4b0a-9545-a18dbdc892d3.png)

**Comment by xutm** [comment]
目前搬家工具，支持暂缓，后续跟进会在这里同步
