### ISSUE TITLE
页面生命周期onshow调用时机不正确

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#540]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.72.2 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
页面生命周期onshow在支付切出app时会被触发

具体可见有赞测试小程序【张小辫儿 - 小程序测试】，进入小程序后找个商品进行支付，在支付还未切回就会触发onShow
 +
## 期望结果 和 实际结果(必填) +
等到支付完成之后回到小程序页面才会触发onshow +
 +

**Comment by xutm** [comment]
iOS 777 修复
