### ISSUE TITLE
IDE展示功能问题

### ISSUE THREAD

**Issue by Riki-WangJJ** [redengineer/redmini#55]
## 系统环境(必填)

- [ ] IDE  
版本: 1.59.26
提交: f18b35c170b2e22772660d35ccdbc28f4107e2fd
日期: 2022-05-30T07:58:07.926Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 21.5.0

IDE顶部功能区域 未展示

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/31041245/174007069-413fe1ee-2723-487d-a376-ce653113607f.png">

**Comment by xutm** [comment]
把截图补充进来吧
