### ISSUE TITLE
跨设备相同用户获取到OpenId不同

### ISSUE THREAD

**Issue by huang-shen** [redengineer/redmini#550]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/53030164/219635328-e81ae0fc-9d92-425c-bdb5-5447f420b4b6.png">
登录接口文档提示获取到的openid 在小程序内是唯一的实际测试 发现统一手机号用户更换手机登录产生不同openid
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
根据用户手机设备生成相同的openid

**Comment by wdvxdr** [comment]
理论不会出现以上问题，可以提供详细信息再进一步排查
