### ISSUE TITLE
服务商创建报错，url校验失败

### ISSUE THREAD

**Issue by theeAbc** [redengineer/redmini#554]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
服务商创建页面消息时间接收urlhttps://domain/open/xhs/messageNotify/$APPID$ 
点击“确认创建”后，报错，报错信息“https://domain/open/xhs/messageNotify/$APPID$ 未返回 echostr 参数内容”
## 期望结果 和 实际结果(必填) +
正常加载出资源 +服务商创建成功
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
echo校验失败，校验失败原因未知，其他路径也是同一个域名，但是不报错

**Comment by Matthew-1996** [comment]
判断是url错误，建议自查。

**Comment by theeAbc** [comment]
url对应接口返回信息有误，不符合echo校验规则，已解决问题

**Comment by xgs87762GH** [comment]
怎么解决的？
