### ISSUE TITLE
服务商创建相关问题

### ISSUE THREAD

**Issue by theeAbc** [redengineer/redmini#556]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
第一个问题：创建服务商时的授权事件url以及消息接收事件url这两个是api中的回调接口地址吗？比如ticket推送。如果是的话想请问echo验证走的是get请求，我这边通过事件接口需要获取post请求，并且传的是json格式参数。如果我这边要发布生产环境，重新创建服务商，那我这怎么兼容get请求的echo验证和post请求的消息和授权接收？
第二个问题：我这边在url校验完成后点击创建服务商，报小程序业务域名校验请求失败，填写的两个对外的公网测试域名是testwap.lotsmall.cn和testtradewap.lotsmall.cn，两个域名的根目录下都上传了校验文件，麻烦看看日志定位下校验失败的原因
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 + 服务商创建成功
 +

**Comment by wdvxdr** [comment]
# 问题一见 https://miniapp.xiaohongshu.com/third/api-3rd-doc/createThrid，授权事件url以及消息接收事件url不是一个地址，只是有相同的校验方式；目前需要改路径同事支持GET POST请求
# txt 文件格式 修改成 text/plain;charset=UTF-8

**Comment by theeAbc** [comment]
第一个问题可能是我描述不清楚，我问的不是授权事件url和消息接收事件url是不是同一个，我的问题是授权以及消息事件echo校验的url和后续创建完服务商后，我这边要接收小红书的授权推送以及消息推送的接口url是不是同一个？如果是同一个，我怎么兼容echo校验是get请求url拼接参数传参，授权和消息事件是json body传参？
第二个问题，我传送的文件就是从服务商创建页面的校验文件链接下载的，编码格式就是utf-8，这个还需要我这边修改吗？

**Comment by theeAbc** [comment]
> * 问题一见 https://miniapp.xiaohongshu.com/third/api-3rd-doc/createThrid   ，授权事件url以及消息接收事件url不是一个地址，只是有相同的校验方式；目前需要改路径同事支持GET POST请求
> * txt 文件格式 修改成 text/plain;charset=UTF-8




> * 问题一见 https://miniapp.xiaohongshu.com/third/api-3rd-doc/createThrid   ，授权事件url以及消息接收事件url不是一个地址，只是有相同的校验方式；目前需要改路径同事支持GET POST请求
> * txt 文件格式 修改成 text/plain;charset=UTF-8

第一个问题可能是我描述不清楚，我问的不是授权事件url和消息接收事件url是不是同一个，我的问题是授权以及消息事件echo校验的url和后续创建完服务商后，我这边要接收小红书的授权推送以及消息推送的接口url是不是同一个？如果是同一个，我怎么兼容echo校验是get请求url拼接参数传参，授权和消息事件是json body传参？
第二个问题，我传送的文件就是从服务商创建页面的校验文件链接下载的，编码格式就是utf-8，这个还需要我这边修改吗？
