### ISSUE TITLE
小红书APP原生小程序页面跳转H5页面异常，提示ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by malanll** [redengineer/redmini#56]
## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE
Android&IOS

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台
客户端
## 基础库版本或小红书APP版本(必填)
小红书APP版本v.7.37.4.861ad9c

## 期望结果 和 实际结果(必填)
期望结果：小红书小程序原生页面跳转h5页面正常
实际结果：跳转不成功提示ERR_BLOCKED_BY_RESPONSE
<img width="323" alt="image" src="https://user-images.githubusercontent.com/107608649/174010547-2b4dbef1-2043-400f-a88c-699853966c34.png">

**Comment by xutm** [comment]
跳转 h5 页面相关 代码贴一下。H5 页面的 xhsml 也粘贴下

**Comment by xutm** [comment]
手机型号

**Comment by malanll** [comment]
xhsml:<web-view src="{{ url }}" class="web-view-coupon-list"></web-view>
url部分：
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/107608649/174014995-29baf09f-95c9-4fcd-891b-9279ecd74e7d.png">
手机型号：Mi 11

**Comment by malanll** [comment]
确认已加白名单

**Comment by malanll** [comment]
因为前两天跳转还是正常的，所以小红书这边是不是最近升级做了什么修改。调研了一下，我们项目的安全策略不能随便放开。希望小红书这边支持一下

**Comment by xutm** [comment]
建议你们后端通过 ua 做下过滤吧，目前 iframe 的实现方式，的确会存在这类限制
