### ISSUE TITLE
安卓手机调用 uploadFile 上传图片失败

### ISSUE THREAD

**Issue by zwtzwx** [redengineer/redmini#564]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
## 基础库版本或小红书APP版本(必填) +
v7.75.0 +
## 重现步骤 和 复现问题的最小demo Github链接 +
我是用Taro框架打包的，打包出来后微信小程序测试没问题，小红书小程序用 iphone 测试没问题，使用 Android 测试的时候服务端获取不到文件流，以下是 Android 和 Iphone 上传的接口参数和简单示例代码，可以看出安卓对应的文件key不一样。
* Android
<img width="433" alt="WechatIMG102" src="https://user-images.githubusercontent.com/23564486/220856641-b626eb84-a7c1-4407-b5a0-a78f3da9ab4e.png">
* Iphone
<img width="570" alt="WechatIMG101" src="https://user-images.githubusercontent.com/23564486/220856426-b8f322f1-5be7-4040-885f-a127027905df.png">

```
Taro.chooseImage({
      count: 1,
      success(res) {
        const temp = res.tempFilePaths[0]
        Taro.uploadFile({
          url: 'xxxxxxxxx/upload/image',
          filePath: temp,
          name: 'image',
          header: {},
        });
      },
})
```
## 期望结果 和 实际结果(必填) +
能正确获取到文件流

**Comment by taiyiandr** [comment]
你好，该问题本地已经修复，期望能和你们确认一下，请问需要在哪个群联系对应的开发同学？

**Comment by zwtzwx** [comment]
你好，我还没有加入开发群，麻烦提供下群号，我申请加入一下，谢谢！

**Comment by taiyiandr** [comment]
7.80 fixed
