### ISSUE TITLE
安卓系统 修改 pages 顺序导致无法打开 entryPagePath 

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#568]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.76.0 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
安卓 entryPagePath 设置无效.
经过我们测试安卓实际是按照 tabBar 的第一个页面打开.
然后我们提交了一个新版本,修改了 pages 页面的顺序,同时去掉了 entryPagePath 设置, 然后无法打开.
经过测试发现,需要清空小红书APP在安卓手机上的数据然后就可以打开了.
但是只能打开其中一个版本.
清空数据先访问任意一个版本,都没法再访问另一个版本了.
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
安卓小程序运行环境有问题

**Comment by xutm** [comment]
暂不支持 entryPagePath
