### ISSUE TITLE
使用mvp-demo时编译报错

### ISSUE THREAD

**Issue by liuqingqing95** [redengineer/redmini#57]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 重现步骤 和 复现问题的最小demo Github链接
index.html中定义了window.xhs但是页面没有这个xhs这个对象
![e9b004c00474ce82e234babad1fb59d](https://user-images.githubusercontent.com/20039379/174016354-78e66ed4-7687-4e31-ab7a-ef0dbf068e3d.png)

**Comment by Hubmeat** [comment]
IDE 的版本是最新的嘛？可以尝试刷新或切换基础版本到最新版试试

**Comment by liuqingqing95** [comment]
是新下载的，page/component/pages/scroll-view/scroll-view这个页面没有xhs，也报错了

**Comment by Hubmeat** [comment]
可以检查下 ide 打开的打开路径。

1.59.24 版本无法复现这个问题

**Comment by liuqingqing95** [comment]
怎么检查呢？我是文件->打开文件夹  然后编译这样操作的

**Comment by liuqingqing95** [comment]
尝试 工程管理 > 导入 居然可以了

**Comment by liuqingqing95** [comment]
尝试 工程管理 > 导入 居然可以了

**Comment by liuqingqing95** [comment]
不太明白这些报错要怎么处理，经常出现
![image](https://user-images.githubusercontent.com/20039379/174213577-2af5b1ed-fe8c-4760-ba10-6edf21f34ca8.png)

**Comment by Hubmeat** [comment]
体验版小程序的白名单列表可能已经过期，可以把配置中的 whiteList 删除。具体可以参考：webviewhttps://miniapp.xiaohongshu.com/docs/component/web-view

**Comment by liuqingqing95** [comment]
![image](https://user-images.githubusercontent.com/20039379/174248017-0d603b3a-0be1-41a4-8ebc-f259dba66ab6.png)

麻烦看看为何onAppShow没有 scene场景值
![image](https://user-images.githubusercontent.com/20039379/174247897-f70124c4-8e72-4de8-9b20-f66d8ba2c5de.png)

**Comment by liuqingqing95** [comment]
@Hubmeat

**Comment by liuqingqing95** [comment]
还有referrerInfo 
微信小程序的onAppShow是[提供](https://developers.weixin.qq.com/miniprogram/dev/api/base/app/app-event/wx.onAppShow.html#%E8%BF%94%E5%9B%9E%E6%9C%89%E6%95%88%20referrerInfo%20%E7%9A%84%E5%9C%BA%E6%99%AF)了的，但是目前没有在小红书文档上看到
![image](https://user-images.githubusercontent.com/20039379/174248786-62be4238-0d14-4ae2-8e2f-339e3d4ee121.png)
![image](https://user-images.githubusercontent.com/20039379/174248948-61b1fb53-c936-40f3-b861-64206a8cef0a.png)

**Comment by Hubmeat** [comment]
onAppShow 未拿到 referrerInfo 的问题，另外提一个 issue 把，这个作为 mvp 编译问题的 issue , 默认关闭了。

**Comment by liuqingqing95** [comment]
那场景值呢？也单独提一个issue?
