### ISSUE TITLE
关于结算请求和查询结算开发过程中的问题

### ISSUE THREAD

**Issue by cloudandrews** [redengineer/redmini#571]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
1.如果订单全额退款了 是否需要发起结算请求 +
2.如果结算失败，是否支持重试结算，重试的时候是否需要更换out_settle_id +
3.结算请求、查询结算的QPS是多少，是否支持我批量去调用  +
4.结算请求一般过后多久能处理完 +
 +

**Comment by wdvxdr** [comment]
1.全额退款也需要结算
2.结算接口有幂等，重试不需要更换id
3.QPS请控制在100以内
4.通常不会出现pending，延时为网络延时
