### ISSUE TITLE
input组件样式异常

### ISSUE THREAD

**Issue by 15116li** [redengineer/redmini#58]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
iPhone 11 软件版本15.5

## 重现步骤 和 复现问题的最小demo Github链接
input组件，输入value，value贴着左边框，没有padding

## 期望结果 和 实际结果(必填)
期望显示正常

**Comment by xutm** [comment]
input 代码片段给一下吧

**Comment by 15116li** [comment]
<input 
        type="text" 
        placeholder="xxxxxxx"
        value="{{value}}"
      />

**Comment by 15116li** [comment]
<input 
        type="text" 
        placeholder="xxxxxxx"
        value="{{value}}"
      />

**Comment by 15116li** [comment]
` <input 
    type="text" 
    placeholder="xxxxxxx"
    value="{{value}}"
  />`

**Comment by Hubmeat** [comment]
可以补齐下双端的差异，看是否对齐
比如 android 未加 padding 但真机上有默认 paading 值，ios 则必须手动设置 padding 值。
这样端侧同学方便排查。

业务上暂时根据平台来做下兼容处理把

**Comment by 15116li** [comment]
ios 手动设置 padding 值 是没有用的，不起效果，android是正常的，现在无法根据平台来做兼容处理
