### ISSUE TITLE
订单没有运费 下单提示运费错误

### ISSUE THREAD

**Issue by huang-shen** [redengineer/redmini#589]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
订单同步接口 电子票 没有运费响应提示 请求失败参数错误：invalid price_info.freight_price
https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-mp-deal-order-upsert
  ```
{
    "biz_create_time": 1678270181,
    "biz_update_time": 1678270182,
    "open_id": "91d6d0b1453aa575c0454786bcd9a45d48ef956cf081e116e64eab967da7dbc0",
    "order_expired_time": 1678270781,
    "out_order_id": "CY2310361082856",
    "path": "/package-order/pages/order-detail/order-detail?orderOID=64085ee5e6f4f400019e56f8",
    "price_info": {
        "freight_price": 0,
        "order_price": 19200
    },
    "product_infos": [
        {
            "num": 1,
            "out_product_id": "640808cbdeddea00013cbbfb",
            "out_sku_id": "640808cbdeddea00013cbc10",
            "real_price": 19200,
            "sale_price": 19200
        }
    ]
}
 ```
+
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by Matthew-1996** [comment]
背景是由于订单中商品价格0元的问题，造成了很多结算的bad case，所以我们把订单新增修改接口中，与价格有关的参数全加了0元的校验。

如果没有运费，请调整成，直接不传运费字段
