### ISSUE TITLE
小红书新版本升级以后新样式未加载

### ISSUE THREAD

**Issue by mingzitainanle** [redengineer/redmini#596]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.77
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![f888dd2e9aa5b5e1e01281853f0e18a](https://user-images.githubusercontent.com/30645049/224890792-05d9bd8c-7527-41f7-8b14-b769e217f54e.jpg)
+
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
![b3a94a9a3cdf03d8fc358eebbc363c2](https://user-images.githubusercontent.com/30645049/224890878-be8ac89c-80b8-4115-b039-0a87ecbf2d0b.jpg)

**Comment by Matthew-1996** [comment]
android已修复，iOS修复在781版本
