### ISSUE TITLE
xhsml 中标签的 catchtap 的值不支持表达式

### ISSUE THREAD

**Issue by liangqingfengfeng** [redengineer/redmini#6]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.16.6
## 重现步骤 和 复现问题的最小demo Github链接
<view class="navto" catchtap="{{jump ? 'onTapNavi' : ''}}" data-url="/pages/login/login">测试</view>
这样就会编译失败

## 期望结果 和 实际结果(必填)
期望编译通过，能使用三元元算

**Comment by Edge00** [comment]
无法复现
<img width="932" alt="image" src="https://user-images.githubusercontent.com/23715779/167237454-90970e7a-6f87-4323-b970-a6acc297bfa0.png">

**Comment by liangqingfengfeng** [comment]
`<view class="navto" catchtap="{{login ? 'onTapNavi' : ''}}" data-url="/pages/login/login">登录</view>`
用这个

**Comment by Edge00** [comment]
麻烦提供一个可以复现的持续片段，标题描述也不准确
<img width="832" alt="image" src="https://user-images.githubusercontent.com/23715779/167242520-dea5c192-82b2-4e32-9356-c91b9daee71b.png">

**Comment by Edge00** [comment]
@liangqingfengfeng 谢谢，问题已定位，下个版本修复，大概下周三发布 1.59.24 版本 IDE
