### ISSUE TITLE
无法设置样品，达人端目前看到无法支持拿样

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#602]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.79 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
无法设置样品，添加样品时提示获取信息失败，达人端看提示无法支持拿样
appid：627cb060d749de00012e08df
ItemID：64001e20ea98a500016acc48
ItemID：640045f6ea98a500016c00b1
ItemID：63d74927f886c700016fd1a6
![62c52c55-32a6-48ef-99bb-3976b2804390](https://user-images.githubusercontent.com/118496055/226786270-14eeb10d-5c01-4647-87ef-ebb587bbe512.png)
![22e5bd12-9ecf-4a98-8bd2-ce55baba7716](https://user-images.githubusercontent.com/118496055/226786297-caf103ec-8495-458b-8481-e73e07881f03.png)
+
## 期望结果 和 实际结果(必填) +
可以正常添加样品，无报错提示
 +

**Comment by Matthew-1996** [comment]
请提供一下所有有问题商品的out_product_id
