### ISSUE TITLE
专业号主页下，点击店铺，提示当前版本不支持此功能

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#604]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +

## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 
## 基础库版本或小红书APP版本(必填) +
app版本 v7.79
 
## 重现步骤 和 复现问题的最小demo Github链接 +
![d998f1cc6c400326f8aa02f503d806da](https://user-images.githubusercontent.com/35423514/226816350-d8675571-498e-4f97-a450-c371f6adf09d.jpg)
 +

**Comment by taiyiandr** [comment]
当前版本不支持此功能的，账号可以提供下吗？ 小红书-我-右上角菜单-复制链接

**Comment by taiyiandr** [comment]
经反馈升级App后已解决
