### ISSUE TITLE
swiper嵌套scroll-view，scroll-view无法滑动

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#61]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.26.0
## 重现步骤 和 复现问题的最小demo Github链接
swiper嵌套scroll-view
## 期望结果 和 实际结果(必填)
swiper嵌套scroll-view时，scroll-view可以滑动，不受外层swiper影响

**Comment by Hubmeat** [comment]
你好，swiper 和 scroll-view 独立实现，配合使用可能有手势冲突的问题。

先避免嵌套，使用一些其他方案把。

该问题会按照排期进行修复。

**Comment by Hubmeat** [comment]
为复现这个 case , 如果还有这个问题麻烦提供下完整的复现 demo 把

**Comment by LaoChen1994** [comment]
这个问题还是没有解决吗，swiper嵌套scroll view
