### ISSUE TITLE
webview 无法正常加载页面  链接：https://1368252mzwlh.sjdzp.cn/Miniwx/Index/index.html  已添加业务域名

### ISSUE THREAD

**Issue by 463601161** [redengineer/redmini#614]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [X] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
![image](https://user-images.githubusercontent.com/44021242/231205189-25154613-75bc-412b-9179-4820ab06e76e.png)
![image](https://user-images.githubusercontent.com/44021242/231205281-5c6c47dd-78bc-4a69-aa4c-5c2d377a953d.png)

 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by yanyunwu** [comment]
请问排查了是因为服务端在某些环境屏蔽了请求吗。目前请求是可以正常发送，但是返回空值

**Comment by yanyunwu** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/73828319/231335405-e327157e-5819-4124-a06a-eb24c69c2aa2.png">
![image](https://user-images.githubusercontent.com/73828319/231335435-34f52ce7-0e99-4421-a327-33c2ed065783.png)

**Comment by yanyunwu** [comment]
你们服务端屏蔽了iframe的网页请求

**Comment by 463601161** [comment]
> 你们服务端屏蔽了iframe的网页请求

小红书小程序的域名是哪个  加个白名单

**Comment by 463601161** [comment]
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/73828319/231337739-d915c0a9-865c-4426-971a-d188c00fad43.png">

是的   所以想明确下小程序的域名   然后加到我们的服务器配置中  改下响应头

**Comment by yanyunwu** [comment]
> > <img alt="image" width="746" src="https://user-images.githubusercontent.com/73828319/231337739-d915c0a9-865c-4426-971a-d188c00fad43.png">
> 
> 是的 所以想明确下小程序的域名 然后加到我们的服务器配置中 改下响应头

<img width="721" alt="image" src="https://user-images.githubusercontent.com/73828319/231340936-e40b9973-67cd-4f9c-9cb7-501f809404ed.png">
我们的webview中的iframe是注入在文件协议域名的，因为是在客户端啊，所以建议ifame全体开放就好了呀
