### ISSUE TITLE
张小辫儿 - 小程序测试 无法拉起订单支付

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#616]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
Android：v7.83.0.9179da9
IOS：v7.73.1（7731008）
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
有赞测试小程序【张小辫儿 - 小程序测试】，进入小程序后找个商品进行支付，在支付拉起过程中弹出
'显示支付凭证与订单应用不匹配'
目前该测试店铺无法走通下单链路

 +
## 期望结果 和 实际结果(必填) +
能够正常拉起支付
 +

**Comment by wdvxdr** [comment]
错误信息提示正确
开放接口同步的订单的APPID，与实际支付订单的APPID不匹配
