### ISSUE TITLE
首次进入白屏

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#62]
name | about | title | labels | assignees
-- | -- | -- | -- | --
首次进入白屏 | 7.42版本首次进入白屏问题在6.17中午12点修复后，6.18早上11点还是出现了这个问题 |   |   |  

## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小程序APP版本：7.42.0

## 期望结果 和 实际结果(必填)
不会出现白屏现象

## 重现步骤
手机型号：vivo X80

用户id：62a1d8c00000000021025841

![image](https://user-images.githubusercontent.com/33249100/174238855-9eec3421-68fc-489f-893e-239b35e4ffb3.png)

https://user-images.githubusercontent.com/33249100/174239395-09dfa17b-6694-4da6-8672-afb84786ed45.mp4

**Comment by Hubmeat** [comment]
您好，排查中。目前没有发现运行时的错误日志，怀疑可能和容器预载有关。

**Comment by WangYuTao3** [comment]
> name	about	title	labels	assignees
> 首次进入白屏	7.42版本首次进入白屏问题在6.17中午12点修复后，6.18早上11点还是出现了这个问题	 	 	 
> ## 系统环境(必填)
> * [ ]  IOS
> * [x]  Android
> * [ ]  IDE
> 
> ## 问题模块(必填)
> * [ ]  审核
> * [ ]  API & 组件 & 框架
> * [ ]  IDE
> * [x]  客户端
> * [ ]  管理后台
> 
> ## 基础库版本或小红书APP版本(必填)
> 小程序APP版本：7.42.0
> 
> ## 期望结果 和 实际结果(必填)
> 不会出现白屏现象
> 
> ## 重现步骤
> 手机型号：vivo X80
> 
> 用户id：62a1d8c00000000021025841
> 
> ![image](https://user-images.githubusercontent.com/33249100/174238855-9eec3421-68fc-489f-893e-239b35e4ffb3.png)
> 
>  c5b066ef27db08234162a6fbe0499ced.mp4
此问题已经修复，请升级至743版本

**Comment by WangYuTao3** [comment]
此问题已经修复，请升级至743版本
