### ISSUE TITLE
ios偶现输入框聚焦后输入法会出现右上角的完成按钮，当输入字母文字的时候会在最前面插入同一个输入的内容

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#621]
> ## 系统环境(必填[多选]) +
> * [x]  IOS +
> * [ ]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [ ]  小程序Api +
> * [x]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
> 
> 
> ## 基础库版本或小红书APP版本(必填) +
> v7.83.1 + +
> 
> ## 重现步骤 和 复现问题的最小demo Github链接 +
> 
ios偶现输入框聚焦后输入法会出现右上角的完成按钮，当输入字母文字的时候会在最前面插入同一个输入的内容
![inputbug-1](https://user-images.githubusercontent.com/18606361/232954167-a65ee1bc-5623-4cd5-ac22-a4426cdabfdb.jpg)
![inputbug-2](https://user-images.githubusercontent.com/18606361/232954186-bac1f40d-c346-4a54-909d-203cffb51c53.jpg)
![inputbug-3](https://user-images.githubusercontent.com/18606361/232954192-fa280dd6-278c-4673-8312-52748adfb5e1.jpg)

> 
> ## 期望结果 和 实际结果(必填) +
> 正常输入
> 
> ## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by yanyunwu** [comment]
请问是手机是什么版本的
