### ISSUE TITLE
多次调用权限，会弹出多个授权框，且获取定位的弹框描述和配置的不一致

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#622]
> ## 系统环境(必填[多选]) +
> * [ ]  IOS +
> * [x]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [x]  小程序Api +
> * [ ]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
> 
> 
> ## 基础库版本或小红书APP版本(必填) +
> v7.83.1 + +
> 
> ## 重现步骤 和 复现问题的最小demo Github链接 +
> 
多次调用权限，会弹出多个授权框，且获取定位的弹框描述和配置的不一致。ios是正常的 
https://user-images.githubusercontent.com/18606361/232985756-c60df293-bd8f-47fe-91a8-cc3600bc482a.mp4

> 
> ## 期望结果 和 实际结果(必填) +
> 只弹出一次授权框且正常显示秒数
> 
> ## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by taiyiandr** [comment]
Android 7.86 fix
