### ISSUE TITLE
 textarea焦点时键盘弹出会把整个页面容器顶上去

### ISSUE THREAD

**Issue by shiminJ** [redengineer/redmini#629]
> ## 系统环境(必填[多选]) +
> * [ ]  IOS +
> * [x]  Android +
> * [ ]  IDE +
> 
> ## 问题模块(必填[单选]) +
> * [ ]  小程序框架 +
> * [ ]  小程序Api +
> * [x]  小程序基础组件 +
> * [ ]  小程序开发者工具(IDE) +
> * [ ]  小程序容器(iOS) +
> * [ ]  小程序容器(Android) +
> * [ ]  小程序服务(服务后台) +
> * [ ]  小程序服务(文档平台) +
> * [ ]  小程序业务(需求/支付/服务号) +
> 
> 
> ## 服务商名称(必填[单选]) - 排名不分先后 +
> * [ ]  有赞 +
> * [ ]  微盟 +
> * [ ]  直客通 +
> * [ ]  民宿宝 +
> * [ ]  订单来了 +
> * [ ]  太目 +
> * [ ]  其他(自开发) +
> * [ ]  雅诗兰黛 +
> * [ ]  DIOR +
> * [ ]  longchamp +
> * [x]  领克 +
> * [ ]  猫眼 +
> * [ ]  自我游 +
> * [ ]  德比 +
> 
> 
> ## 基础库版本或小红书APP版本(必填) +
> v7.57.1 + +
> 
> ## 重现步骤 和 复现问题的最小demo Github链接 +
> textarea焦点时键盘弹出会把整个页面容器顶上去
> 
> ## 期望结果 和 实际结果(必填) +
> textarea焦点时键盘和input一样覆盖在页面容器上
> 
> ## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by yanyunwu** [comment]
目前小红书的textarea组件没有采用同层渲染的方案，所以这个表现需要等到后面组件更新后才能解决
