### ISSUE TITLE
onAppShow事件缺少参数

### ISSUE THREAD

**Issue by liuqingqing95** [redengineer/redmini#63]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 重现步骤 和 复现问题的最小demo Github链接
![image](https://user-images.githubusercontent.com/20039379/174248017-0d603b3a-0be1-41a4-8ebc-f259dba66ab6.png)
麻烦看看为何onAppShow没有 scene场景值

![image](https://user-images.githubusercontent.com/20039379/174247897-f70124c4-8e72-4de8-9b20-f66d8ba2c5de.png)
还有referrerInfo
微信小程序的onAppShow是[提供](https://developers.weixin.qq.com/miniprogram/dev/api/base/app/app-event/wx.onAppShow.html#%E8%BF%94%E5%9B%9E%E6%9C%89%E6%95%88%20referrerInfo%20%E7%9A%84%E5%9C%BA%E6%99%AF)了的，但是目前没有在小红书文档上看到
![image](https://user-images.githubusercontent.com/20039379/174251187-7d07af0d-7beb-4df2-9b9b-bddbf85d5839.png)

**Comment by Hubmeat** [comment]
referrerInfo 暂不支持，文档内这类字段可能有误，我们修复下。

**Comment by liuqingqing95** [comment]
那场景值呢？文档上看起来是有的

**Comment by Hubmeat** [comment]
也没有，scene code 如果新增可能也会与微信不同，会按照小红书引流策略来指定场景值。

文档确实有出入，已对内反馈了，会尽快修复下。
