### ISSUE TITLE
sku商品-批量删除 然后请求上架 还能返回成功

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#638]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
sku商品-批量删除 然后请求上架 还能返回成功 获取商品详情显示下架
 +

**Comment by wdvxdr** [comment]
删除接口为软删接口，商品下架使用对应「sku商品-批量下架」接口。具体重新上架case可以提供商品id具体排查

**Comment by deng12123** [comment]
> 删除接口为软删接口，商品下架使用对应「sku商品-批量下架」接口。具体重新上架case可以提供商品id具体排查
您好，请问如果时删除之后，想要同步上架和之前id一样的商品应该怎么处理呢。有能够彻底删除商品的接口吗或者能够恢复之前删除的商品。
