### ISSUE TITLE
打包预览报错 Cannot read property 'name' of null at isValidSlot

### ISSUE THREAD

**Issue by chengwen-zheng** [redengineer/redmini#64]
**系统环境(必填)**
 IDE
**问题模块(必填)**
 IDE

版本: 1.59.26
提交: f18b35c170b2e22772660d35ccdbc28f4107e2fd
日期: 2022-05-30T07:58:07.926Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 21.2.0

<img width="591" alt="wecom-temp-0bc32ce6ad28c402075a7ad3ab129d46" src="https://user-images.githubusercontent.com/24415870/174264757-68893339-ff25-4edc-9b28-c480d9b55c29.png">

基础库版本或小红书APP版本(必填)
3.23.7

**Comment by Hubmeat** [comment]
slot 节点不可添加 xhs:for, xhs:if 等编辑条件

**Comment by xutm** [comment]
定位下来根因是 slot 嵌套使用引起。在修复中，晚点同步 IDE 地址

```js
<price-format>
  <view slot="expect">
    dfdfdfdf
    <view slot="expect" bind:__l="__l">=====</view>
  </view>
</price-format>
```

**Comment by xutm** [comment]
最新版已经修复
