### ISSUE TITLE
plugin-platform-xhs 插件 css 样式未生效

### ISSUE THREAD

**Issue by vvcat0906** [redengineer/redmini#642]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
3.37.0
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
taro 框架 使用 plugin-platform-xhs  插件打包成小红书小程序，打包产物中的 app.css 底部 import 引入 common.css 导致样式失效
![image](https://user-images.githubusercontent.com/30825507/236152207-78eb2c1e-89ca-4545-aaaa-9d1f585cbb57.png)
 +
## 期望结果 和 实际结果(必填) +
将底部 import 语句移至顶部页面正常
 +

**Comment by Hubmeat** [comment]
你好，可以安装 @tarojs/plugin-platform-xhs@v1.1.0 的来修复这个问题
