### ISSUE TITLE
小程序支付时在Webview里跳转支付宝或微信h5支付链接拉不起支付宝或微信App

### ISSUE THREAD

**Issue by yinpeng633** [redengineer/redmini#644]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
APP 安卓版本：v7.86.0 有问题 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 小红书APP卸载重装 旧版本恢复正常，旧版本为：v7.60.0+
 +
## 期望结果 和 实际结果(必填) +
微信或支付宝链接能正常唤起 相应的支付APP +
 +

**Comment by yinpeng633** [comment]
补充一点，只有Android 小红书APP最新版本（v7.86.0）有问题，iOS 新老版本（v7.86、v7.71.2）均正常

**Comment by taiyiandr** [comment]
是哪一个小程序，请提供一下复现路径呢？

**Comment by taiyiandr** [comment]
我们这边 Android 7.86 版本没有复现

**Comment by yinpeng633** [comment]
> 
花筑民宿，复现路径就是下单支付时，跳到我们的支付过渡h5页，再redirect到微信或支付宝h5支付链接

**Comment by taiyiandr** [comment]
> > 
> 
> 花筑民宿，复现路径就是下单支付时，跳到我们的支付过渡h5页，再redirect到微信或支付宝h5支付链接

Android 7.86 支付功能正常，请按照官方文档确认你们的小程序支付流程是否正常。
支付过渡页，跳转支付宝或微信的支付链接，不需要调用 xhs.redirectTo，直接使用H5的链接跳转即可。
https://miniapp.xiaohongshu.com/docs/guide/rmpdeal
