### ISSUE TITLE
订单部分退款,状态都正确,但是提示"当前订单数据状态错误,无法结算"

### ISSUE THREAD

**Issue by yihonglou** [redengineer/redmini#645]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
应该最新版本
+
## 重现步骤 和 复现问题的最小demo Github链接 +
无
+
## 期望结果 和 实际结果(必填) +
E20220407015942009500003
大佬问下 这个订单部分退款 订单状态 和 售后单状态都对
因为是部分退款；实际应该是可以结算的
 +

## 补充(猜测可能的原因是什么，你有啥想法，选填) + 
E20220407015942009500003
大佬问下  这个订单部分退款    订单状态  和  售后单状态都对
但是去结算的时候还是提示：这个是为啥啊
<img width="291" alt="小红书订单结算异常" src="https://user-images.githubusercontent.com/132893316/236792167-30d3b805-b4b0-44dd-858e-1748707a98c4.png">

**Comment by Matthew-1996** [comment]
订单状态变动间隔时间较大，所以有的扫描任务没扫描间隔时间这么久的数据
历史数据清了一下，现在可以结算了

**Comment by yihonglou** [comment]
好的，收到

**Comment by yihonglou** [comment]
> 订单状态变化间隔时间比较大，所以有的扫描任务没有扫描间隔时间这么久的数据 历史数据清了一次，现在可以算了
大佬问下现在是不是我在调下结算接口，结算下
还是不用调你们哪里直接结算

**Comment by Matthew-1996** [comment]
你们再调一下结算

**Comment by yihonglou** [comment]
> 你们再调一下结算

![image](https://github.com/redengineer/redmini/assets/132893316/8f1e1296-15f5-4724-811d-37a0d6be600b)
大佬  我上次掉了下 然后提示：{"code":420307,"msg":"当前订单已经在结算中，请勿重复发起结算","success":false}
