### ISSUE TITLE
stopPullDownRefresh()无法结束下拉刷新动画

### ISSUE THREAD

**Issue by malanll** [redengineer/redmini#65]
## 系统环境(必填)
- [ ] IOS
- [x] Android
- [x] IDE
Android：mi 11
IDE:xhs-mpide-1.59.24

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台
- [ ] API & 组件 & 框架
## 基础库版本或小红书APP版本(必填)
开发工具版本：xhs-mpide-1.59.24
App版本：v.7.37.4.861ad9c

## 重现步骤 和 复现问题的最小demo Github链接
下拉刷新动画使用xhs.stopPullDownRefresh();关闭无效
## 期望结果 和 实际结果(必填)
期望结果，下拉刷新完成加载动画关闭
实际结果：数据已经刷新，加载动画依旧在
## 补充(猜测可能的原因是什么，你有啥想法，选填)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/107608649/174277586-6d87c969-3fda-4fe3-9b1d-7a25ca2368c7.png">

**Comment by xutm** [comment]
IDE 升级到最新版，再试试

**Comment by xutm** [comment]
https://github.com/redengineer/redmini/issues/25

**Comment by malanll** [comment]
点击检查更新没反应，刚从开发平台下载开发工具就是xhs-mpide-1.59.24版本，不知道是不是最新的？

**Comment by xutm** [comment]
> 点击检查更新没反应，刚从开发平台下载开发工具就是xhs-mpide-1.59.24版本，不知道是不是最新的？

再试试呢？
