### ISSUE TITLE
订单-新增/修改 获取佣金率设置失败

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#653]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

 +
## 期望结果 和 实际结果(必填) +
订单-新增/修改接口 接口返回获取佣金率设置失败
传参
![image](https://github.com/redengineer/redmini/assets/110969498/29a4bbd1-6f21-4a1f-80b9-0debb3b713fd)
返回参数
 "data": null,
        "success": false,
        "msg": "获取佣金率设置失败",
        "code": 420114
 +

**Comment by Matthew-1996** [comment]
提供一下专业号id或专业号名称或appid

**Comment by liyuanyuan-1** [comment]
> 提供一下专业号id或专业号名称或appid
小程序名称
四川雪趣科技发展有限公司
账号ID：640edd8400000000290172bb
小程序ID
6420efe38926b90040facbd3

**Comment by Matthew-1996** [comment]
请确认保证金已交。提交保证金后，请提供打款单据。收到单据财务核对后，会开通支付权限。

保证金规则：https://miniapp.xiaohongshu.com/docs/operation/depositManager
协议和打款账户（详见保证金收款账户）：https://miniapp.xiaohongshu.com/docs/operation/developer
