### ISSUE TITLE
商户转薯店，两笔订单结算失败

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#654]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
商户需退小程序转薯店，我方查下来有两笔订单结算失败
appid：6279c82c76cb1a00013b67bd
 订单号：184238142014286、184241890019086（提示：当前订单已经在结算中，请勿重复发起结算）
## 期望结果 和 实际结果(必填) +
提供商户未结算完成的订单号

**Comment by Matthew-1996** [comment]
专业号：PIT
目前没有需要结算的订单
