### ISSUE TITLE
xhs.request 预览模式请求触发fail  ide可正常请求

### ISSUE THREAD

**Issue by 463601161** [redengineer/redmini#657]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
v3.37.0+
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 
![9a995b4b4b3ef5f34fa40f19bc24990](https://github.com/redengineer/redmini/assets/44021242/5b7ce2a2-338f-49ff-87de-a04199e1467f)
![56df20f42b3401f5fa7678a37206d6a](https://github.com/redengineer/redmini/assets/44021242/4be79559-e329-45a5-b956-49cb35700c62)
+
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 期望正常请求获取返回内容+

**Comment by rib2333** [comment]
给的信息太少了，网络状态码为1有点奇怪，把你请求的代码po出来看看？

**Comment by rib2333** [comment]
应该是url格式不规范，真机模式下，端侧解析后报错
