### ISSUE TITLE
真机扫码报错

### ISSUE THREAD

**Issue by 463601161** [redengineer/redmini#658]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
 v3.37.0+
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 
![95ad68ba5749f371355943dbcb66358](https://github.com/redengineer/redmini/assets/44021242/b969338e-a26b-497e-999d-f109b4a5b10c)
+
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 真机扫码测试+

**Comment by jswbiubiu** [comment]
2023/05/16  小红书ide开发真机调试  安卓 小米10s 调试扫码进入 展示
logo
小程序加载失败
网络不给力，请稍后重试

**Comment by rib2333** [comment]
将手机和电脑连接到同一局域网内试试（即同一个wifi）

**Comment by jswbiubiu** [comment]
已经试过了的 还是不行&nbsp; 同事手机ios的也试了不行（iphone12）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redengineer/redmini] 真机扫码报错 (Issue #658)





 
将手机和电脑连接到同一局域网内试试（即同一个wifi）

**Comment by hhuwc** [comment]
你好，请问是否有pc是否有开启代理工具，若开启代理工具请将其关闭

**Comment by jswbiubiu** [comment]
> 你好，请问是否有pc是否有开启代理工具，若开启代理工具请将其关闭

怎么会  安卓还是苹果、流量还是wifi都确认过了。
![image](https://github.com/redengineer/redmini/assets/90231104/5ea1f54f-227b-4795-ad11-890706727d10)
![image](https://github.com/redengineer/redmini/assets/90231104/f1fe5ac6-c797-4176-9740-be755ff4f91b)

**Comment by jswbiubiu** [comment]
请问 问题还没得到解决吗？

**Comment by xutm** [comment]
真机调试能力预计在下个月底会开放出来

**Comment by mocerliu** [comment]
![image](https://github.com/redengineer/redmini/assets/30655615/5ff37c07-dead-455f-a260-07a026309b7a)

**Comment by mocerliu** [comment]
![image](https://github.com/redengineer/redmini/assets/30655615/b26c5e66-0270-440a-bb2a-e77f043dea01)
2023年11月13日
