### ISSUE TITLE
商品笔记-关联商品无法选中

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#659]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
微盟后台商品名称已同步成功，但是小红书发布笔记选品关联，无法关联到相关商品，辛苦帮忙查一下
{\"appid\":\"625ccbf0c2e2c000018693c1\",\"out_product_id\":\"107862330099153\"}"
商品名称：台台同款粗边大眼大直径DORAGINA复古芭比14.5 0-1000度
 +
## 期望结果 和 实际结果(必填) +
发布笔记可以关联商品，辛苦帮忙彻底排查下避免此情况发生。

**Comment by Matthew-1996** [comment]
尝试用小红书商品id：64056ef6ea98a500018e3cfd  精准搜索一下。如果仍没有，请提供对应录屏。

**Comment by Matthew-1996** [comment]
附：客户提供的录屏操作

**Comment by Matthew-1996** [comment]
附：微盟提供的原录屏

https://c.weimobwmc.com/weimob-csc-pc/d3102d44771c45d0a5c653a69d8e1003.mp4

**Comment by Matthew-1996** [comment]
排查结论：无产品问题。可能是带”芭比“名称的商品太多，导致搜索困难。
建议优化搜索或优化商品命名
