### ISSUE TITLE
服务商 获取不限制的小程序二维码接口返回二维码扫码报错

### ISSUE THREAD

**Issue by 463601161** [redengineer/redmini#661]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.86.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 接口地址：https://miniapp.xiaohongshu.com/api/rmp/tp/auth/apps/qrcode/unlimited +
 接口参数：{"scene":"1","width":600} +
![下载](https://github.com/redengineer/redmini/assets/44021242/f0361a9f-18d1-4b64-b392-8fe85b4f232f)
![微信图片_20230516170926](https://github.com/redengineer/redmini/assets/44021242/bfa3b4fb-721b-46af-b115-2a7861c6e65f)
+
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by wdvxdr** [comment]
提供下对应appId，当前未查询到相关已发布的小程序
