### ISSUE TITLE
查询关店的订单哪些售后单没有关闭或者取消

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#665]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
有赞这边的售后单是都已处理完成的，这边也排查了同步到小红书的售后单的日志记录，发现也都处理了。但是目前关店提示还有售后单未同步
appId: 63a2e61deb805d0001754883
 +
## 期望结果 和 实际结果(必填) +
需要给出哪些订单的售后单没完成
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
希望能有开放的接口，支持查询未结算的订单或者未关闭的售后单

**Comment by Matthew-1996** [comment]
外部售后单id：202303181949353952160796
外部订单号：E20230316213154079600007
内部订单号：Peb678973515340944251
