### ISSUE TITLE
swiper设置nextMargin后展示异常

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#666]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.87

## 重现步骤 和 复现问题的最小demo Github链接 +
swiper设置nextMargin后，下一帧显示空白

<img width="896" alt="image" src="https://github.com/redengineer/redmini/assets/35423514/4ca9d133-0066-4e79-a606-df3a9eb26947">

https://github.com/redengineer/redmini/assets/35423514/791702b4-8380-49be-8b88-1854fdf3ae9d

https://github.com/redengineer/redmini/assets/35423514/c9be44d6-f27f-4e79-9cb1-70a588abe7fa

## 期望结果 和 实际结果(必填) +
能正常显示后续swiper-item

**Comment by yanyunwu** [comment]
请问和微信的表现一致吗

**Comment by yanyunwu** [comment]
我们这边测试nextMargin的表现和微信一致

**Comment by dc980806** [comment]
> 我们这边测试nextMargin的表现和微信一致

我们这里测下来是跟微信不一致的  会不会是taro-xhs转码插件转换后有问题？

**Comment by yanyunwu** [comment]
可以提供一份taro能复现这个bug的最小demo的示例吗，我们去排查一下

**Comment by dc980806** [comment]
> 可以提供一份taro能复现这个bug的最小demo的示例吗，我们去排查一下

归档.zip   demo已提供  dist目录下有已经编译好的文件，依旧能浮现该问题

**Comment by Matthew-1996** [comment]
预计跟版7.92 上线
