### ISSUE TITLE
uniapp 的 vue3 支持

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#670]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

我在uniapp 的 [issue](https://github.com/dcloudio/uni-app/issues/4204 )上看到说，uniapp 的 vue3 支持是小红书这边提供，请问是否小红书这边提供支持？如果是的，请问有计划什么时候上线？

**Comment by jzhmcoo1** [comment]
https://github.com/dcloudio/uni-app/pull/4315

你好，这边PR已经提出。那边暂时还没人力帮忙review，持续跟进中。预计6月份可以使用

**Comment by PengfeiShi** [comment]
> 

请问小红书的vue3支持有进展了吗

**Comment by jzhmcoo1** [comment]
你好，uniapp那边发布了release，可以通过以下方式进行体验
`npx degit dcloudio/uni-preset-vue#vite-alpha uniapp-vue-xhs`
