### ISSUE TITLE
小红书商品添加/修改  同步成功 显示商品是下架状态

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#671]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +

 +
## 期望结果 和 实际结果(必填) +
小红书商品添加/修改  同步成功 商品-获取信息 显示商品是下架状态
商品-新增/修改-请求信息
{
    "biz_create_time": 1684739199,
    "biz_update_time": 1684739199,
    "category_id": "627a34be00ca5a00018c4c8c",
    "desc": "<p>【使用人群】：</p><p>【预定时间】：</p><p>【有效期】：</p><p>【费用包含】：</p><p>【适用条件】：</p><p>【取票方式】：</p><p>【其他须知】：</p><p>【联系电话】：</p>",
    "name": "小红书测试票-期票",
    "out_product_id": "1532",
    "path": "/page/index/index?ProductID=1532&appid=D_50536799&type=0&softyktsecrect=jfRXNbpbpLmTi3kNTcLOsXvqguSSufZO",
    "short_title": "小红书测试票-期票",
    "skus": [
        {
            "name": "小红书测试票-期票",
            "origin_price": 5000,
            "out_sku_id": "1532",
            "sale_price": 500,
            "sku_image": "https://jinfeiying.oss-cn-beijing.aliyuncs.com/Public/Product/117/1682416854935.png",
            "status": 1
        }
    ],
    "top_image": "https://jinfeiying.oss-cn-beijing.aliyuncs.com/Public/Product/117/1682416854935.png"
}
商品-新增/修改-返回信息
{"data":null,"success":true,"msg":"success","code":0}

商品-获取信息
{
    "data": {
        "out_product_id": "1532",
        "name": "小红书测试票-期票",
        "short_title": "小红书测试票-期票",
        "desc": "<p>【使用人群】：</p><p>【预定时间】：</p><p>【有效期】：</p><p>【费用包含】：</p><p>【适用条件】：</p><p>【取票方式】：</p><p>【其他须知】：</p><p>【联系电话】：</p>",
        "path": "/page/index/index?ProductID=1532&appid=D_50536799&type=0&softyktsecrect=jfRXNbpbpLmTi3kNTcLOsXvqguSSufZO",
        "top_image": "https://jinfeiying.oss-cn-beijing.aliyuncs.com/Public/Product/117/1682416854935.png",
        "category_id": "627a34be00ca5a00018c4c8c",
        "biz_create_time": 1684739199,
        "biz_update_time": 1684739199,
        "skus": null,
        "ext": null,
        "status": 0,
        "audit_info": null
    },
    "success": true,
    "msg": "success",
    "code": 0
}

 +

**Comment by wdvxdr** [comment]
该out_product_id对应的商品已删除，无法重新上架

**Comment by liyuanyuan-1** [comment]
那想上架 怎么办呢
