### ISSUE TITLE
商品多个规格同步，查询出来无sku，影响商品下单

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#673]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
外部商品id： 92596333_3070485511
复现步骤：
1. 有赞多sku商品同步到小红书 参数： 
{"biz_create_time":1684646862,"biz_update_time":1684740387,"category_id":"5a310e0a3f7d1712823ba046","desc":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","out_product_id":"92596333_3070485511","path":"packages/goods/detail/index?alias=3equnp2hoff8d6u","short_title":"甜美舒适真丝家居服连衣裙","skus":[{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180328","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1},{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180329","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1},{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180330","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1},{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180331","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1},{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180332","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1},{"name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","origin_price":98000,"out_sku_id":"92596333_3070485511_24398180333","sale_price":98000,"sku_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FkhTJDuUQAuyq7QLgT5L8RW62iO2.jpg","status":1}],"top_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FjOwDjxYO_JeZFGkRkLcRZRCozj2.jpg"}

2. 查询商品没有返回sku信息
{"data":{"out_product_id":"92596333_3070485511","name":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","short_title":"甜美舒适真丝家居服连衣裙","desc":"Mello Masion 23SS 女童夏季公主甜美舒适真丝家居服连衣裙 现货","path":"packages/goods/detail/index?alias=3equnp2hoff8d6u","top_image":"https://img01.yzcdn.cn/upload_files/2023/05/19/FjOwDjxYO_JeZFGkRkLcRZRCozj2.jpg","category_id":"5a310e0a3f7d1712823ba046","biz_create_time":1684646862,"biz_update_time":1684740387,"skus":null,"ext":null,"status":0,"audit_info":null},"success":true,"msg":"success","code":0}

3. 影响交易拉起支付收银台

 +
## 期望结果 和 实际结果(必填) +
1. 商品返回sku信息
2. 订单可以正常同步，拉起收银台

 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
小程序appId:  6461eeefe05d0100539078a0

**Comment by Matthew-1996** [comment]
问题定位：这个几SKU之前被删除，已删除的商品不支持更新
建议：更换新的skuid并同步
