### ISSUE TITLE
商户关闭小程序转薯店-订单结算状态排查

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#674]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
appid：63ef121474fa2a000175f100
订单号：
427797434000729
446933705000306
448052974000961
小红书商家关闭小程序开薯店，以上3笔订单我方反馈正逆向都已完结，辛苦帮忙查查还有问题么
 +
## 期望结果 和 实际结果(必填) +
商户正常关店，不影响后续流程

**Comment by Matthew-1996** [comment]
待结算订单：
427797434000729
446933705000306
448052974000961


如果结算异常，请提供“结算请求”和“查询结算”的Response

**Comment by Matthew-1996** [comment]
48小时未回复，问题关闭
