### ISSUE TITLE
后台已通过审核的商品，在小红书前端不显示

### ISSUE THREAD

**Issue by macoco** [redengineer/redmini#676]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [x] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.87.1 +
 +
问题：后台已通过审核的商品，在小红书前端不显示

产品信息：
酒景 id142934
产品id  3273721
 【六一·3折特惠！】广州融创水世界成人票（6月1~4日）
产品id 3273731
 【六一儿童专享·6.1元！】融创水世界儿童票（6月1~4日）

![后台](https://github.com/redengineer/redmini/assets/10053880/cee90dd1-841e-4eab-8692-b29d8c12130f)

![商品不显示](https://github.com/redengineer/redmini/assets/10053880/54fa52f8-2123-4e5f-b497-caff92617a81)

商品状态同步接口文档：https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-mp-deal-product-get
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by macoco** [comment]
找到原因了，是我们的问题

**Comment by Matthew-1996** [comment]
客户自查，问题关闭
