### ISSUE TITLE
APP笔记看不到产品头图  微信打开分享链接页面是可以看到头图的 out_product_id:"10983850_2756773"

### ISSUE THREAD

**Issue by 463601161** [redengineer/redmini#678]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
 
<img width="323" alt="微信图片_20230524101050" src="https://github.com/redengineer/redmini/assets/44021242/3d8cf4db-f100-4a2a-80b8-39a9c9e8c151">
<img width="358" alt="微信图片_20230524101056" src="https://github.com/redengineer/redmini/assets/44021242/115208fa-7d31-41c7-9d9b-94045f569a57">
+
## 期望结果 和 实际结果(必填) +
正常加载图片+
 +

**Comment by Matthew-1996** [comment]
麻烦提供一下：appid和笔记链接

**Comment by 463601161** [comment]
> 

appid:641a97ac5c16e60001b08c53
链接： 28 黑猫票儿发布了一篇小红书笔记，快来看吧！ 😆 1U61P9gc46AwhHJ 😆 http://xhslink.com/cm4ooq，复制本条信息，打开【小红书】App查看精彩内容！

**Comment by Matthew-1996** [comment]
排查结论：商品图片不支持gif格式，请修改

**Comment by 463601161** [comment]
头图都支持哪些格式呢
