### ISSUE TITLE
小红书主页商品TAB栏显示的商品价格与实际不符

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#679]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [x] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
商户名称：Natuzzi Editions
appid：642e3ae547e5e9004bf09905
商品id：106855226054462

商品tab栏展示的商品价格与商详实际售卖的价格不一致，且商品规格里也不存在1000元的规格选项
![image](https://github.com/redengineer/redmini/assets/118496055/a432031b-461d-4c94-9811-a839a39d5073)
![image](https://github.com/redengineer/redmini/assets/118496055/30ea0863-63ed-4b36-894e-5ed287ad346a)

 +
## 期望结果 和 实际结果(必填) +
正常显示商品价格
 +

**Comment by Matthew-1996** [comment]
这里展示的是，SPU下价格最低价格spu的价格。该spu下最低的sku价格确实是1000

请根据规则修改商品信息：https://miniapp.xiaohongshu.com/question/products
或调整专业号主页的商品排序：https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-display-home_page_item_tab

**Comment by mmeng1996** [comment]
商户把1000的SKU的规格禁用了也还是会显示最低的SKU价格是么
