### ISSUE TITLE
中间页无法显示

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#680]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [x] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
跳转h5中间页无法显示
![39bbd66dd96c7ed841aeac616733500](https://github.com/redengineer/redmini/assets/110969498/4f763996-e946-4e08-8842-2033ab1d7ef3)

 +

**Comment by Matthew-1996** [comment]
1、请问是指交易及支付组件的H5中间页吗？
2、请确认中间页已加域名
<img width="1118" alt="image" src="https://github.com/redengineer/redmini/assets/57560984/d9cc9cc8-3d59-40b3-ad77-32d3c6395ef2">

**Comment by liyuanyuan-1** [comment]
> 1、请问是指交易及支付组件的H5中间页吗？ 2、请确认中间页已加域名 <img alt="image" width="1118" src="https://user-images.githubusercontent.com/57560984/240862193-d9cc9cc8-3d59-40b3-ad77-32d3c6395ef2.png">
![image](https://github.com/redengineer/redmini/assets/110969498/9964ab81-36aa-4359-92cc-6f1c29f67bcc)
已添加呢

**Comment by liyuanyuan-1** [comment]
交易及支付组件的H5中间页 业务域名也已配置 小红书小程序打开无法访问 什么原因呢
