### ISSUE TITLE
交易h5中间页 显示无法访问

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#681]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
交易h5中间页 显示无法访问 业务域名已配置 
![image](https://github.com/redengineer/redmini/assets/110969498/f6a5fe76-23a5-4b6b-9659-9cdd3a0471ce)

 +

**Comment by xutm** [comment]
追加域名白名单了吗？

**Comment by liyuanyuan-1** [comment]
这个在哪里配置呢

**Comment by Matthew-1996** [comment]
问题合并  https://github.com/redengineer/redmini/issues/680

**Comment by Matthew-1996** [comment]
逻辑上，要么就是域名白名单没加全，或者H5页面本身就有问题。请再检查一下，确保域名添加无误。如果还有问题请提供录屏
 + 域名list + app_id/专业号id + 页面链接
