### ISSUE TITLE
交易支付 必须支付宝和微信都做吗 

### ISSUE THREAD

**Issue by liyuanyuan-1** [redengineer/redmini#685]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
交易支付 必须支付宝和微信都做吗  只做微信支付可以不
 +

**Comment by Matthew-1996** [comment]
可以只做微信支付

**Comment by liyuanyuan-1** [comment]
> 可以只做微信支付
支付宝url 怎么是必填的呢
![image](https://github.com/redengineer/redmini/assets/110969498/9b34592a-ebb5-47d2-90e0-520a8ce58d80)

**Comment by Matthew-1996** [comment]
不是必填
