### ISSUE TITLE
自研平台商品是否需要同步到小红书后才可显示，同步商品时日历商品怎么上传，无sku信息

### ISSUE THREAD

**Issue by huangpingwang** [redengineer/redmini#688]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by Matthew-1996** [comment]
1、需要同步到小红书
2、请先同步你的客户信息+具体场景/链路

商品相关内容参考：
https://miniapp.xiaohongshu.com/docs/api-backend/post-api-rmp-mp-deal-product-upsert
https://miniapp.xiaohongshu.com/question/products

**Comment by huangpingwang** [comment]
这个文档里面都是sku的商品，我需要门票类的商品，没有sku，需要满足不同的日期，门票结果及库存不一样

**Comment by huangpingwang** [comment]
日历上需要显示设置了日期。每个日期的金额及库存数

**Comment by Matthew-1996** [comment]
你描述的场景应该是在小程序内的商详页面吧？小程序内的商品信息不需要同步小红书

上面指的是在小红书商品笔记等场景下，需要同步的商品信息。这些场景下，会同步商品图片、名称和价格。但不展示日期，所以也不支持对不同的日期展示不同的价格。只需要同步一个通用的价格给SPU和你们自己在小程序内开发的商详页path即可

**Comment by Matthew-1996** [comment]
![image](https://github.com/redengineer/redmini/assets/57560984/a88265ea-ee92-4dd5-8ab6-0fdab45a202a)

**Comment by huangpingwang** [comment]
这个意思是不是指，我直接在小程序内调用自研系统的商品接口就可以

**Comment by Matthew-1996** [comment]
可以。小程序内，开发者自闭环。

**Comment by 1137882300** [comment]
小程序自闭环，那还需要同步商品给小红书吗？

**Comment by 1137882300** [comment]
> 可以。小程序内，开发者自闭环。

那还需要同步商品到小红书吗？
