### ISSUE TITLE
小红书跳转小程序如何实现

### ISSUE THREAD

**Issue by liuqingqing95** [redengineer/redmini#69]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 重现步骤 和 复现问题的最小demo Github链接
小红书跳转小程序没看明白如何跳转
![image](https://user-images.githubusercontent.com/20039379/174552112-012478f7-dd67-4e66-a0a1-f2240e94d1fc.png)
微信有跳转小程序的接口
![image](https://user-images.githubusercontent.com/20039379/174552182-1a4938a2-e426-4136-acc5-57a9f50bcd45.png)

**Comment by Hubmeat** [comment]
这个建议去网上先找下资料学习下，navigatorTo 是页面跳转，navigatorToMiniProgram 是跳转其他小程序。
navigatorToMiniProgram 小红书不支持。
