### ISSUE TITLE
在小红书客服界面发送图片，没有接收到图片相关的消息

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#690]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
- [x] 开放能力
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
1.  小红书小程序进入客服界面
2. 用户发送图片
3. 接受消息未收到图片 
 +
## 期望结果 和 实际结果(必填) +
期望可以正常获取到图片相关数据
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
以下是目前获取到的数据
![img_v2_7011aa86-6fa0-4f98-b61f-5d5085465bag](https://github.com/redengineer/redmini/assets/59149009/790f009c-004e-4222-8d37-73bf03e82f12)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d596ada1ea9dfa5053ba, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685360892, content=1, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d5d64b2bcf8f8f501185, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685360958, content=你好, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d5dceee0bae42120530c, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685360964, content=11, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d5df9f795874bfc01798, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685360967, content=12, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d64f2cb95874b6501697, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685361081, content=你好, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

【小红书】发送客服消息 sendMsg:XhsCustomerServiceMsg(msgId=6219d65fe0e1ea9df34052dd, fromOpenId=0dce99d8a074bc7a0125f7d356b6737718bd086e9e8dd79620efdbdacbf855f5, fansId=16142996233, toAppId=62454b862247ab00013fc407, kdtId=18176134, msgType=text, createTime=1685361098, content=你好, picUrl=null, videoUrl=null, goodsId=null, orderNo=null)

**Comment by Matthew-1996** [comment]
由于上报时间周期较长，小红书侧无法定位到日志
初步怀疑是内容没过机审导致的发送失败
请
1、再试尝试复现
2、若仍然复现，再次沟通，方便小红书再看一下日志情况
