### ISSUE TITLE
Taro3.4.8项目app.css文件下@import引入的样式没有生效

### ISSUE THREAD

**Issue by WeiJietao** [redengineer/redmini#7]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [X] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [X] IDE
- [ ] 客户端
- [ ] 管理后台

## 期望结果 和 实际结果(必填)

Taro3.4.8项目app.css @import同级目录下的common.css，发现样式并没有引入：

![截屏2022-05-07 下午12 04 06](https://user-images.githubusercontent.com/18640419/167237555-926c1ac1-4ad1-4b33-87e0-d4fd7779ff9a.png)
![截屏2022-05-07 下午12 04 18](https://user-images.githubusercontent.com/18640419/167237559-401c4657-4389-4285-b2d9-49f92d4f599c.png)

**Comment by WeiJietao** [comment]
把common.css的代码复制到app.css是可以生效的

**Comment by Edge00** [comment]
无法复现
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/23715779/167244294-cdad6c14-9e60-407e-a6ea-6117edfc9c55.png">

**Comment by Hubmeat** [comment]
css-loader 只解析顶层节点 @import 语法，调整下代码顺序。
