### ISSUE TITLE
基于 textarea 封装的自定义组件，其 input 事件会触发 2 次

### ISSUE THREAD

**Issue by NiuZhuang** [redengineer/redmini#70]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [x] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
基础库：3.28.0

## 重现步骤 和 复现问题的最小demo Github链接
1. 基于 textarea 封装的自定义组件，接收其 input 事件，并自行triggerEvent 一个 input 事件。

2. 在业务方，会收到  2 次 input 事件，且第二次的值不对。
线下已发 demo

**Comment by Hubmeat** [comment]
麻烦提供下小红书代码片段吧
