### ISSUE TITLE
不能配置业务域名

### ISSUE THREAD

**Issue by Yrz-ch** [redengineer/redmini#704]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
例如：//cdn2.xxx.com/xxxxxx.jpg +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +

**Comment by Matthew-1996** [comment]
<img width="465" alt="image" src="https://github.com/redengineer/redmini/assets/57560984/499f556e-52a7-4778-9a99-66cd96750c34">

**Comment by wdvxdr** [comment]
请提供一下appid、添加异常的截图

**Comment by Yrz-ch** [comment]
appid：641286f258acce0001f7c763
![image](https://github.com/redengineer/redmini/assets/55578483/2d771591-18d1-4f10-b56d-687f145c8a44)

**Comment by wdvxdr** [comment]
https无法访问
