### ISSUE TITLE
[小红书关店]-查询未结算的订单和未完成的售后单

### ISSUE THREAD

**Issue by sheldnme** [redengineer/redmini#707]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [X] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [X] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [X] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 小程序基础信息（选填） +
appid或专业号id:   appid:  61cd96e612bda00001d102ce
商品id、订单id:  +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
商家现在关店，需要查询哪些订单没有结算和哪些售后单没关闭

 +
## 期望结果 和 实际结果(必填) +
提供未结算和售后单未关闭的外部订单号
 +

**Comment by Matthew-1996** [comment]
外部售后单id
202202222154413952460514
202202222154413952470514
