### ISSUE TITLE
订单部分退款,状态都正确,但是提示"当前订单数据状态错误,无法结算"

### ISSUE THREAD

**Issue by yihonglou** [redengineer/redmini#708]
## 系统环境(必填[多选]) +
- [ ] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [x] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [x] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
应该最新版
 +
## 小程序基础信息（选填） +
appid或专业号id:  +appid： 621c552c2cdfc40001ca6ad2
商品id、订单id:  + 订单号：E20221130012716021500033
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
无
 +
## 期望结果 和 实际结果(必填) +
E20221130012716021500033
小红书订单状态查询7；也是已完成订单
大佬问下 这个订单部分退款 订单状态 和 售后单状态都对
因为是部分退款；实际应该是可以结算的
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
![image](https://github.com/redengineer/redmini/assets/132893316/32f815e2-dc45-49e0-aa02-7554a63bb0ab)
需要知道为啥；需要怎末做
还是我这里不用做；你们那里处理掉

**Comment by Matthew-1996** [comment]
问题定位：订单对应的商品已删除，导致订单无法结算。（该逻辑已修复）
现已处理异常订单，所有订单都已结算完成

如需关店，还有商品需要下架
