### ISSUE TITLE
首次进入小程序加载失败

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#71]
---
name: 首次进入小程序加载失败
about: 第一次进入某个小程序经常会出现加载失败页面，第二次又没问题
title: ''
labels: ''
assignees: ''

---

## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书APP版本：7.42.0

## 重现步骤 和 复现问题的最小demo Github链接
并不是每一次都能复现，偶尔第一次进入某个小程序会出现。第二次又没问题

出现时间：2022/06/20 20:23 至 2022/06/20 20:25
appuid：5c287b04000000000601cf2d

![origin_img_v2_00aaddaa-ce39-4e75-9870-89640a9b273g](https://user-images.githubusercontent.com/33249100/174603279-20fcdf31-1ec2-4070-bf9c-ed8f88ae3736.jpg)

## 期望结果 和 实际结果(必填)
正常进入

**Comment by taiyiandr** [comment]
请更新最新版本App，新版已处理。
