### ISSUE TITLE
获取手机号解密文档中，watermark.appid 字段和实际解析加密数据后的字段不一致

### ISSUE THREAD

**Issue by Matthew-1996** [redengineer/redmini#719]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [x] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
- [x] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
v7.45.1 +
 +
## 小程序基础信息（选填） +
服务商：企迈，无法打开issue，牛顿代提交 +
沟通群：霸王茶姬✘小红书官方小程序 +

appid或专业号id:  +
商品id、订单id:  +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
https://miniapp.xiaohongshu.com/docs/guide/openPhoneNumber +
小红书， 获取手机号解密文档中， watermark.appid 字段和实际解析加密数据后的字段不一致 +
文档中：appid +
![wecom-temp-322266-6be0b7babceae1bb8db2cf648dc193df](https://github.com/redengineer/redmini/assets/57560984/b46845f1-36a4-452a-87cd-5d8f05387d5f) +

实际解析后：appId +
<img width="342" alt="wecom-temp-44984-4905f2a92cffabace88169f657a6cc0e" src="https://github.com/redengineer/redmini/assets/57560984/2f2f81bc-e599-4b3a-a9b4-d56666dbbb5a"> +
 +
## 期望结果 和 实际结果(必填) +
正常加载出资源 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +

**Comment by rib2333** [comment]
字段已实际解析的为准，文档已修改
