### ISSUE TITLE
css加载失败

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#72]
---
name: css加载失败
about: 小程序版本更新后(之前进入过老版本)，首次进入会出现css丢失，第二次访问又没问题
title: ''
labels: ''
assignees: ''

---

## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
APP版本：7.43

## 重现步骤 和 复现问题的最小demo Github链接
好久不进某个小程序，且更新了APP后会出现css丢失，第二次访问又没问题
出现时间：2022/06/20 20:30 至 2022/06/20 20:32
appuid: 5c287b04000000000601cf2d

![origin_img_v2_4d2085b1-9ead-4195-939a-d2614c120c4g](https://user-images.githubusercontent.com/33249100/174604622-5116ebe1-d0ff-464f-af3b-10eaedd7a893.png)

## 期望结果 和 实际结果(必填)
正常展示页面

## 补充(猜测可能的原因是什么，你有啥想法，选填)
猜测可能是
css做了缓存，在小程序更新后的第一次访问使用了之前的css，导致css和类名不匹配

**Comment by Hubmeat** [comment]
是直接在小红书 app 进行更新后出现的是吗？

**Comment by haojiasheng** [comment]
> 是直接在小红书 app 进行更新后出现的是吗？

小程序更新

**Comment by panzequn** [comment]
按照上面的条件，现象暂未复现
