### ISSUE TITLE
teaxtarea聚焦失焦时，页面展示异常

### ISSUE THREAD

**Issue by dc980806** [redengineer/redmini#720]
## 系统环境(必填[多选]) +
- [x] IOS +
- [x] Android +
- [ ] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [x] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [x] 小程序容器(iOS) +
- [x] 小程序容器(Android) +
- [ ] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [ ] 雅诗兰黛 +
- [x] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
- [ ] 其他(自开发) +
 +
## 基础库版本或小红书APP版本(必填) +
app版本v7.89

## 小程序基础信息（选填） +
appid: 62c6a1671b7001000117ac6f

## 重现步骤 和 复现问题的最小demo Github链接 +
https://github.com/redengineer/redmini/assets/35423514/3357cfc9-1730-48e2-9acc-9d1dd2849c56

textarea第一次聚焦时，页面不会被抬起，后续聚焦时被抬起，fixed元素也被抬起，失焦时，fixed的元素还原了， 但是正常元素并没有随着页面还原而还原
 
## 期望结果 和 实际结果(必填) +
对齐其他平台，增加adjust-position属性，控制页面聚焦时是否被抬起

**Comment by yanyunwu** [comment]
这个问题我们正在查看，在后面的版本会修复
