### ISSUE TITLE
Taro @tarojs/plugin-platform-xhs 编译app.css @import 位置错误

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#75]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.28.0
## 重现步骤 和 复现问题的最小demo Github链接
![1655976334456](https://user-images.githubusercontent.com/63334662/175265894-55b91362-c164-4ce4-a048-07fb2ae45816.jpg)
在app.css生成的@import "./common.css" 在app.css 最后导致common.css 不生效
## 期望结果 和 实际结果(必填)
生成在app.css 最前面

**Comment by Hubmeat** [comment]
提供下 taro 的本地的配置吧（config/index.js），确认下你的配置方式

**Comment by collincheng** [comment]
import path from 'path'
const HOST = 'https://pms-t1.dingdanll.com'
const QiniuPlugin = require('qiniu-webpack-plugin');
const isDevelopEnv = process.env.NODE_ENV === 'development'
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

const config = {
    plugins: ['@tarojs/plugin-platform-xhs'],
    outputRoot: `dist/${process.env.TARO_ENV}`,
    projectName: 'myApp',
    date: '2021-4-14',
    designWidth: 750,
    terser: {
        enable: process.env.TERSER ? true : process.env.TARO_ENV !== 'alipay'
    },
    env: {
        TERSER: process.env.TERSER,
        NODE_ENV: '"development"'
    },
    deviceRatio: {
        640: 2.34 / 2,
        750: 1,
        828: 1.81 / 2
    },
    sourceRoot: 'src',
    defineConstants: {},
    copy: {
        patterns: [],
        options: {}
    },
    framework: 'vue3',
    mini: {
        enableSourceMap: false,
        postcss: {
            pxtransform: {
                enable: true,
                config: {}
            },
            url: {
                enable: true,
                config: {
                    limit: 1024 // 设定转换尺寸上限
                }
            }
        },
        miniCssExtractPluginOption: {
            //忽略css文件引入顺序
            ignoreOrder: true
        },
        webpackChain(chain, webpack) {
            if (process.env.TERSER) {
                chain.plugin('Bundle-analyzer-plugin').use(BundleAnalyzerPlugin)
            }
        }
    },
    h5: {
        publicPath: !isDevelopEnv ? 'https://js.dingdandao.com/' : '/',
        devServer: {
            proxy: {
                '/v2': {
                    target: HOST,
                    changeOrigin: true
                },
                '/ddll-mta': {
                    target: 'https://mta-t1.dingdanll.com',
                    changeOrigin: true
                }
            }
        },
        router: {
            mode: 'browser'
        },
        webpackChain(chain, webpack) {
            // chain.plugin('mini-css-extract-plugin').use(MiniCssExtractPlugin, [{
            //     filename: '[name].[hash].css',
            //     chunkFilename: '[name].[hash].css'
            // }])
            // css-loader
            // chain.module.rule('css').oneOf('0').use('0').loader(MiniCssExtractPlugin.loader)
            // chain.module.rule('css').oneOf('0').use('1').loader('css-loader').options({})
            if (!isDevelopEnv) {
                chain.output.filename('[name].[hash].js')
                chain.output.chunkFilename('[name].[hash].js')
                chain.plugin('qiniu-webpack-plugin').use(QiniuPlugin, [{
                    ACCESS_KEY: 'ugka1u1aAHUtxlOISFda60Sx1CISoxz5BwMPSQms',
                    SECRET_KEY: 'aoDSNYdmHvadOskwhk0UJvN1Ja0HLyHyLaXKVDBV',
                    bucket: 'dingdanlaile',
                    // path默认值是[hash]，此处不需要
                    path: ''
                }])
            }
        }
    },
    alias: {
        '@': path.resolve(__dirname, '..', 'src')
    }
}
module.exports = function (merge) {
    if (process.env.NODE_ENV === 'development') {
        return merge({}, config, require('./dev'))
    }
    return merge({}, config, require('./prod'))
}

**Comment by collincheng** [comment]
@Hubmeat 我这边同样的问题

**Comment by Hubmeat** [comment]
> @Hubmeat 我这边同样的问题

@echooys 
看起来是一个配置问题，麻烦可以提供下 Taro 可复现的 demo 压缩包，我这边跟进排查下
