### ISSUE TITLE
有赞域名下无法访问小红书视频文件

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#754]
## Issue类型
operator

## 问题模块
客服消息

## 所属的服务商
有赞

## 小红书版本信息
v7.73.1

## 运营场景描述
用户在通过小红书小程序客服向商家发送了一条视频消息
商家通过有赞客服后台收到该消息，点击播放，无法观看
经技术人员排查，发现是视频资源返回403错误导致
Request URL:
https://store.xiaohongshu.com/arkgoods/1000g0b82kt5qijmii00040s8maes768bgaikl18
Origin：
https://b-im.youzan.com
Referer:
https://b-im.youzan.com/ 

## 发生问题的时间 
2023-06-14 15:45:00 至 2023-06-14 15:50:00

## 期望结果
可以在部分有赞域名下正常访问 store.xiaohongshu.com 域名的视频资源
如上述运营场景中提到的 https://b-im.youzan.com

**Comment by Matthew-1996** [comment]
客户信息补充
有赞：视频资源访问403的问题，可以将这个其他域名无法访问的限制去除掉么？
![企业微信截图_19b36a0e-bdd7-4afa-bfc1-82b505884348](https://github.com/redengineer/redmini/assets/57560984/639c8e61-6be8-4742-9291-fc57a11148a8)

**Comment by Matthew-1996** [comment]
https://store.xiaohongshu.com/arkgoods/1000g0b82kt5qijmii00040s8maes768bgaikl18
这个域名访问有配置referer白名单，已添加 youzan的域名
