### ISSUE TITLE
textarea组件在内容变化后失焦之后会向外抛出change事件

### ISSUE THREAD

**Issue by Suntgr** [redengineer/redmini#757]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
微盟

## 平台
IOS, Android, IDE

## 小红书版本信息
7.89
 
## 基础库版本
v3.54.1

## 发生问题的时间 
2023-06-15 13:33:16 至 2023-06-15 13:33:16

## 问题描述
textarea组件在聚焦输入内容后，点击其他区域，失焦之后会往外抛出change事件。会影响到自定义组件的chang事件。

## 期望结果
失焦不要往外抛出change事件，因为文档没有写。

## 重现步骤和复现问题的最小demo Github链接
&lt;view bind:change&#x3D;&quot;test&quot;&gt;
  &lt;textarea placeholder&#x3D;&quot;textarea&quot; /&gt;
&lt;/view &gt;

**Comment by Hubmeat** [comment]
麻烦提供下代码片段可以吗？原生小红书语法的，我们排查下

**Comment by Suntgr** [comment]
> 麻烦提供下代码片段可以吗？原生小红书语法的，我们排查下

<view bind:change="test">
<textarea placeholder="textarea" />
</view >

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
