### ISSUE TITLE
编辑器保存后重新编译，编译失败，调试器报错vue is not defined

### ISSUE THREAD

**Issue by yintingwen** [redengineer/redmini#76]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [x] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
ide: 1.59.26
## 重现步骤 和 复现问题的最小demo Github链接
代码保存后ide重新编译，大概率编译出错白屏，调试器打印 vue is not found
![企业微信截图_05a055b4-a204-4ac5-8d05-2e0a4f28a814](https://user-images.githubusercontent.com/52306105/175508903-43173d68-2dc2-4498-b2eb-d4b0508e22ef.png)

## 期望结果 和 实际结果(必填)
保存后正常运行

**Comment by xutm** [comment]
请使用最新版 

https://picasso-static.xiaohongshu.com/electron-app-updater-cli/2f7ccadd-4c8c-4852-8d12-2a5dbda5d753/xhs-mpide-1.59.27.exe

https://picasso-static.xiaohongshu.com/electron-app-updater-cli/57ace10f-2f7e-49dd-9663-78940b211b46/xhs-mpide-1.59.27.dmg
