### ISSUE TITLE
自开发交易组件-商品新增/修改接口报错：商品同步失败，请使用「商品同步-生活服务」接口同步该账号商品

### ISSUE THREAD

**Issue by yinpeng633** [redengineer/redmini#761]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
花筑民宿

## 平台
IOS, Android

## 小红书版本信息
7.88
 
## 基础库版本
v3.54.3

## 发生问题的时间 
2023-06-01 09:11:50 至 2023-06-20 09:11:50

## 问题描述
之前一直正常，最近报的这个错误，小程序appid：63296f096f415000016a7cb9，请帮忙排查

## 期望结果
自开发交易组件-商品新增/修改接口 调用正常

## 重现步骤和复现问题的最小demo Github链接
服务后台接口问题，无需demo

**Comment by leihaodegg** [comment]
哥们你这个解决没
