### ISSUE TITLE
iOS小程序支付问题

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#767]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
有赞

## 小红书版本信息
7.73.1

## 运营场景描述
前提：用户在手机上安装了福村宝软件
用户发起支付-跳转至福村宝APP

 

## 用户ID 
558b9dc3352da571cebc990b

## 发生问题的时间 
2023-06-21 15:00:00 至 2023-06-21 15:15:52

## 期望结果
用户发起支付-可以正常跳转至支付宝支付

**Comment by wernerpeng** [comment]
scheme被福村宝占用，已反馈给支付宝，支付宝处理中，等几天再看看
