### ISSUE TITLE
小红书专业号后台，没有域名和推送这个菜单，无法配置webview域名

### ISSUE THREAD

**Issue by lxs3935** [redengineer/redmini#768]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
1号职场

## 平台
IDE

## 小红书版本信息
7.92
 
## 基础库版本
v3.53.0

## 发生问题的时间 
2023-06-25 09:51:40 至 2023-06-25 09:51:40

## 问题描述
小红书专业号后台管理，在店铺运营这一菜单下，没有《域名和推送》这个菜单

## 期望结果
期望可以配置小程序的请求域名和webview白名单

## 重现步骤和复现问题的最小demo Github链接
登陆小红书专业号后台，店铺运营这一菜单下，没有配置小程序开发信息的菜单，只有小程序信息的菜单

**Comment by lxs3935** [comment]
> 您好开发者, 我们已收到你的问题, 已通知开发团队进行处理！ 如您未阅读我们的开发文档，可先参阅开发文档 [小红书问题处置流程](https://miniapp.xiaohongshu.com/docs/guide/exceptionPerformanceWhiteScreen) ✨ 感谢您的提问！✨

您好，不仅仅是没有《域名和推送》这个菜单，而且还没有《版本管理》的这个菜单

**Comment by Matthew-1996** [comment]
已处理
