### ISSUE TITLE
商品未成功上架，也未收到审核不通过回调

### ISSUE THREAD

**Issue by Marmot93** [redengineer/redmini#770]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
粗门

## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.55.0

## 发生问题的时间 
2023-06-28 10:29:55 至 2023-06-28 10:29:55

## 问题描述
没有
https://miniapp.xiaohongshu.com/third/api-3rd-doc/pushProductAudit
对应的回调

## 期望结果
正确的发送商品审核回调

## 重现步骤和复现问题的最小demo Github链接
没有https://miniapp.xiaohongshu.com/third/api-3rd-doc/pushProductAudit
对应的服务端回调
第三方服务商appid: 631af81c7c9aee000172a776

**Comment by Matthew-1996** [comment]
<img width="1099" alt="image" src="https://github.com/redengineer/redmini/assets/57560984/fe9975fc-fd68-4a42-9c63-18a587e3adb5">

1、确认是IDA平台吗？
2、仅当商品审核不通过的时候才会回调。
如果出现这类case，麻烦同步一下对应的商品id，所属客户的appid

**Comment by Marmot93** [comment]
out_product_id: 0188ff99-38e8-deb5-75da-d7173600fbfb
客户appid: 63356dea7b379e0001d854ee
服务商appid: 631af81c7c9aee000172a776

最近一次同步时间：2023-06-28T10:42:31.009928346+08:00
response:
```
STATUS       : 200 OK
PROTO        : HTTP/2.0
RECEIVED AT  : 2023-06-28T10:42:31.009928346+08:00
TIME DURATION: 386.449998ms
HEADERS      :
	Cat-Msg-Id: openapiminiapp-gateway-default-ac14952d.0008266-468866-40955
	Content-Type: application/json;charset=UTF-8
	Date: Wed, 28 Jun 2023 02:42:30 GMT
	Server: openresty
	Via: kong/1.2.1
	X-Kong-Proxy-Latency: 0
	X-Kong-Upstream-Latency: 251
BODY         :
{
   "data": null,
   "success": true,
   "msg": "success",
   "code": 0
}
```

**Comment by Matthew-1996** [comment]
是不是把out_product_id和out_sku_id，同步了一样的id？两者不能一样
看一下商品新增的Body Parameters

**Comment by Marmot93** [comment]
out_product_id和out_sku_id 测试了一下，目前是可以一样的

**Comment by Matthew-1996** [comment]
两个id不要设置成一样，后续订单等都会报错的。

**Comment by Matthew-1996** [comment]
直接新同步一个商品过来吧，id和历史上传的不同，且out_product_id和out_sku_id 不一样

**Comment by Marmot93** [comment]
嗯嗯，这边已经修改了，非常感谢
小建议：这个接口检查一下，如果一致的话可以报个错
