### ISSUE TITLE
结算状态为7的订单的时候返回{"msg":"当前订单数据状态错误，不可结算","code":420308,"success":false}

### ISSUE THREAD

**Issue by myNameXxy** [redengineer/redmini#771]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微程之家

## 运营场景描述
结算状态为7的订单出问题 

## 发生问题的时间 
2023-06-28 16:10:25 至 2023-06-28 16:10:25

## 期望结果
找出结算不了订单的问题

## 业务基础信息（选填）
appid:646494a75a973600476e0f7c, orderid:O410630477057630

**Comment by Matthew-1996** [comment]
麻烦同步一下，结算请求部分
同步的代码，以及接口反馈的信息

**Comment by Matthew-1996** [comment]
涉及到结算逻辑算法，订单下单48小时后才可结算。请等48小时后再尝试结算。
