### ISSUE TITLE
支付的时候提示“小程序支付功能被禁用，请小程序开发者重新申请”

### ISSUE THREAD

**Issue by qiuyu-d** [redengineer/redmini#772]
## Issue类型
bug

## 问题模块
小程序业务(需求/支付/服务号)
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
v7.92
 
## 基础库版本
v3.54.3

## 发生问题的时间 
2023-06-29 17:44:48 至 2023-06-29 17:44:48

## 问题描述
下单支付，唤起收银台的时候，提升：“小程序支付功能被禁用，请小程序开发者重新申请“，抓包发现，是该接口： https://www.xiaohongshu.com/api/sns/v1/mp/red/pay?sid&#x3D;session.1688027278998200342501 返回：{
&quot;result&quot;
: 
420156,
&quot;success&quot;
: false,
 
&quot;msg&quot;
: 
&quot;小程序支付功能被禁用，请小程序开发者重新申请&quot;
 }
 

## 期望结果
点击支付后，正常唤起收银台，

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by Matthew-1996** [comment]
已处理

**Comment by panla** [comment]
@Matthew-1996 你好，请问这个问题是怎么解决的？

--------------
更新，接入担保支付

**Comment by zane418** [comment]
@Matthew-1996 你好，请问这个问题是怎么解决的？ +1

**Comment by panla** [comment]
> @Matthew-1996 你好，请问这个问题是怎么解决的？ +1

@zane418 
接入担保支付

**Comment by zane418** [comment]
@panla 担保支付只有支付宝可用，微信支付不可用，到现在官方一直说后续会扩展。有没有别的方法在小红书小程序接入微信的支付（无论任何方法）

**Comment by panla** [comment]
> @panla 担保支付只有支付宝可用，微信支付不可用，到现在官方一直说后续会扩展。有没有别的方法在小红书小程序接入微信的支付（无论任何方法）

我没有其他方案，除了担保还有其他？直连支付不是停了吗？

**Comment by zane418** [comment]
> > @panla 担保支付只有支付宝可用，微信支付不可用，到现在官方一直说后续会扩展。有没有别的方法在小红书小程序接入微信的支付（无论任何方法）
> 
> 我没有其他方案，除了担保还有其他？直连支付不是停了吗？

服务商的直连支付不知道有没有停，我以前见过小红书的小程序是可以用微信支付的。

**Comment by panla** [comment]
@zane418 
https://doc.weixin.qq.com/doc/w3_ATQAmwaeAFcSQyA0tVNSwujLaJBFU?scode=ANAAyQcbAAgDRtG8D8AQIAJgb4ANw
https://doc.weixin.qq.com/doc/w3_AOkATgbFAO0JOkPqs2WTR6TZM8XUs?scode=ANAAyQcbAAgia9BxTDAQIAJgb4ANw
