### ISSUE TITLE
咱家的编译相对较慢，是否可以加一个刷新按钮。

### ISSUE THREAD

**Issue by UserName123-123** [redengineer/redmini#775]
## Issue类型
feature

## 这个功能解决的问题
有时候我们只是手动清理了一下缓存，想重新访问一下页面看看状态，可以排除编译所带来的时间上的浪费，提高开发者效率。

**Comment by UserName123-123** [comment]
![image](https://github.com/redengineer/redmini/assets/58620103/41069466-1b8d-43fb-8df0-ed0a373dc531)
没有呀！

**Comment by hhuwc** [comment]
<img width="1920" alt="image" src="https://github.com/redengineer/redmini/assets/20037388/d6beff7f-4955-4ee4-ad4b-a982dfc4ebe9">
您好，等模拟器加载完毕后，右上角会有的
