### ISSUE TITLE
商户退小程序转薯店，部分订单未结算成功

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#776]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
V7.93

## 运营场景描述
appid：632c0831092216000166674c
商户退小程序转薯店，反馈还有订单没有结算，辛苦帮忙看下 

## 发生问题的时间 
2023-07-03 10:06:50 至 2023-07-04 10:06:50

## 期望结果
商户可以正常关小程序

**Comment by Matthew-1996** [comment]
未完成且未结算订单（外部订单id）：436141508000183
