### ISSUE TITLE
小程序审核失败，请帮忙看下具体原因

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#786]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
百居易

## 平台
IOS, Android, IDE

## 小红书版本信息
7.9.3
 
## 基础库版本
v3.53.0

## 发生问题的时间 
2023-07-05 15:41:43 至 2023-07-05 15:41:43

## 问题描述
将小程序的ext_json文件中的extEnable设置为false，发布小程序审核失败，返回原因是白屏，请帮忙看下具体失败原因是什么

## 期望结果
小程序审核通过，页面被正常展示

## 重现步骤和复现问题的最小demo Github链接
将小程序的ext_json文件中的extEnable设置为false，小程序在初始化页面会获取授权小程序的appid去后台服务校验是否已授权，猜测是这里获取的appid有问题，我尝试用getAccountInfoSync方法获取该appid和在api/rmp/tp/auth/code/upload接口中ext_json参数设置appid都失败了，下面是我调用该接口的完整请求：
{&quot;stats&quot;:{&quot;url&quot;:&quot;https://miniapp.xiaohongshu.com/api/rmp/tp/auth/code/upload?appid&#x3D;64478fc017525100014ab2b9&amp;auth_access_token&#x3D;cda4fdcbbe3f4c4e8bec25f83c614e71&amp;access_token&#x3D;cda4fdcbbe3f4c4e8bec25f83c614e71&quot;,&quot;content_type&quot;:&quot;application/json;charset&#x3D;UTF-8&quot;,&quot;http_code&quot;:200,&quot;header_size&quot;:317,&quot;request_size&quot;:432,&quot;filetime&quot;:-1,&quot;ssl_verify_result&quot;:0,&quot;redirect_count&quot;:0,&quot;total_time&quot;:0.362274,&quot;namelookup_time&quot;:0.008123,&quot;connect_time&quot;:0.207505,&quot;pretransfer_time&quot;:0.292305,&quot;size_upload&quot;:147,&quot;size_download&quot;:53,&quot;speed_download&quot;:146,&quot;speed_upload&quot;:405,&quot;download_content_length&quot;:-1,&quot;upload_content_length&quot;:147,&quot;starttransfer_time&quot;:0.362036,&quot;redirect_time&quot;:0,&quot;redirect_url&quot;:&quot;&quot;,&quot;primary_ip&quot;:&quot;212.129.159.36&quot;,&quot;certinfo&quot;:[],&quot;primary_port&quot;:443,&quot;local_ip&quot;:&quot;172.17.188.196&quot;,&quot;local_port&quot;:58278},&quot;method&quot;:&quot;POST&quot;,&quot;header&quot;:{&quot;Content-Length&quot;:[&quot;147&quot;],&quot;Host&quot;:[&quot;miniapp.xiaohongshu.com&quot;],&quot;User-Agent&quot;:[&quot;Hostex/V4.0.0&quot;],&quot;Content-Type&quot;:[&quot;application/json&quot;]},&quot;request&quot;:&quot;{\&quot;ext_json\&quot;:\&quot;{\\\&quot;ext\\\&quot;:{\\\&quot;appid\\\&quot;:\\\&quot;647962a0e2a945003cdf0b54\\\&quot;}}\&quot;,\&quot;template_id\&quot;:2388,\&quot;user_version\&quot;:\&quot;1.0.8\&quot;,\&quot;user_desc\&quot;:\&quot;\\u7b2c8\\u6b21\\u6d4b\\u8bd5\&quot;}&quot;,&quot;response&quot;:&quot;{\&quot;data\&quot;:null,\&quot;success\&quot;:true,\&quot;msg\&quot;:\&quot;success\&quot;,\&quot;code\&quot;:0}&quot;,&quot;error&quot;:0}

**Comment by xutm** [comment]
appid 多少

**Comment by xutm** [comment]
<img width="906" alt="企业微信截图_7afa04ec-e88a-4ac1-b300-5880129681d6" src="https://github.com/redengineer/redmini/assets/11706751/37e6fbc2-df4a-4545-ad23-0e9a66e55d08">
接口需要 https
