### ISSUE TITLE
安卓手机有的POST接口参数传不到后台，IOS没问题！（已确定前端肯定传了，但是后端收不到！！！）

### ISSUE THREAD

**Issue by baizhenjie** [redengineer/redmini#787]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
汽车之家

## 平台
Android

## 小红书版本信息
7.94.0
 
## 基础库版本
v3.34.3

## 发生问题的时间 
2023-05-01 10:12:22 至 2023-07-06 10:12:22

## 问题描述
安卓手机有的POST接口参数传不到后台，IOS没问题！（已确定前端肯定传了，但是后端收不到！！！已添加域名白名单）

## 期望结果
POST接口安卓和苹果可以正常传递和接收参数

## 重现步骤和复现问题的最小demo Github链接

接口：https://openapi.autohome.com.cn/autohome/openapi2/cloud/bdp/clue/clue4che168_buy
其中一个参数：push_app_key: 1

**Comment by taiyiandr** [comment]
提供一下复现场景或者代码片段呢？

**Comment by baizhenjie** [comment]
> 您好开发者，我们已收到您的问题，已通知开发团队进行处理！ 如果您未阅读我们的开发文档，可先参阅开发文档[小红书问题解决流程](https://miniapp.xiaohongshu.com/docs/guide/exceptionPerformanceWhiteScreen) ✨谢谢您的提问！✨



> 提供一下现场场景或者代码片段呢？
.xhsml
<view>

  <view>
    <text>接口</text>
    {{url}}
  </view>
  <view>
    <text>参数</text>
    {{params}}
  </view>
  <view class="but" bindtap="submit">请求</view>
    
</view>

.js

//Page Object
Page({
  data: {
    url: 'https://openapi.autohome.com.cn/autohome/openapi2/cloud/bdp/clue/clue4che168_buy',
    method: 'POST',
    params: {
      car_source_ids_other: "48339954,48191565,48006097",
      detail_page_url: "/detailpackage/pages/usedCar/carDetail/index",
      deviceid: "111111",
      extend7: "{\"auto_open_from\":\"\",\"appName\":\"小红书-汽车之家小程序\",\"uuid\":\"771cd7b84636ba21283ec3145427a300af1bcfce31bd425e2b7f2ef092f379e5\",\"__locationAuth\":0,\"__unAuthorized\":0,\"latitude\":0,\"longitude\":0}",
      keyExt4: "{\"plf\":5,\"col\":\"\",\"pvareaid\":\"\",\"eid\":\"\",\"page_name\":\"detailpackage/pages/usedCar/carDetail/index\",\"deviceid\":\"771cd7b84636ba21283ec3145427a300af1bcfce31bd425e2b7f2ef092f379e5\"}",
      keyUserid: 0,
      key_card_city_id: 110100,
      key_inside_linkid_id: "xs_wxapp_9999999999_WXQCZJSYXCMJK_0000_graUJRby",
      key_name: "客户",
      key_order_cityid: 110100,
      key_phone: "18510411908",
      key_supply_business_id: "111",
      key_used_car_business_id: 11,
      key_used_car_source_Id: "11",
      push_app_key: "111111",
      source_id: 4,
      v: "",
      validcode: "312312",
      _appid: "car",
      _sign: "FD1A50E92E8191B990CA85990DAF5A38",
      _timestamp: 1688612877,
      _v: "v0.0.1"
    }
  },
  //options(Object)
  onLoad: function (options) {

  },
  onReady: function () {

  },
  onShow: function () {

  },
  onHide: function () {

  },
  onUnload: function () {

  },
  submit() {
    const {
      url,
      params,
      method
    } = this.data;
    xhs.request({
      url: url,
      data: params,
      method,
      header: {
        'content-type': `application/x-www-form-urlencoded;charset=utf-8`
      },
      success(res) {
          console.log('----res---->', res)
          // 提示缺少必要参数push_app_key就是后端没收到（安卓）
          // 提示验证码不正确是正常的
      },
      fail(error) {
        console.log('----error---->', error)
      }

    });
  }
});

**Comment by taiyiandr** [comment]
收到，你先将 content-type 的值 就填 application/x-www-form-urlencoded 试试呢？

**Comment by baizhenjie** [comment]
> 收到，你先将 content-type 的值就填“application/x-www-form-urlencoded”试试呢？

可以啦，感谢

**Comment by taiyiandr** [comment]
Android 7.96 兼容修复
