### ISSUE TITLE
webview调试入口咨询

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#789]
## Issue类型
operator

## 问题模块
小程序开发者工具

## 所属的服务商
有赞

## 小红书版本信息
v7.94.0

## 运营场景描述
需要调试webview内嵌网页
 

## 发生问题的时间 
2023-07-06 10:31:15 至 2023-07-06 10:31:15

## 期望结果
是否有调试webview入口

如果没有后续是否会提供？

**Comment by hhuwc** [comment]
你好，目前调试webview内容建议使用vconsole，ide中调试尚未支持。

目前ide中webview 实现采用的是iframe 后续会切换成webview组件来支持调试。
