### ISSUE TITLE
小程序分享链接封面和描述都无法修改。

### ISSUE THREAD

**Issue by xieguanyuan** [redengineer/redmini#792]
## Issue类型
operator

## 问题模块
商品笔记

## 所属的服务商
天时同城

## 小红书版本信息
2.0.2

## 运营场景描述
分享小程序链接，链接的封面和文案为专业号头像，专业号名称，专业号描述，而不是我们商品页的商品标题和商品图 

## 用户ID 
5f745d93000000000100ba73

## 发生问题的时间 
2023-07-06 19:27:04 至 2023-07-06 19:27:04

## 期望结果
小程序分享链接，应该根据小程序页面的商品名和首图，作为封面和标题，描述。

**Comment by Matthew-1996** [comment]
请明确一下具体是什么场景的分享，小红书内 or 微信？
请参考：https://miniapp.xiaohongshu.com/docs/guide/openShare
<img width="1274" alt="image" src="https://github.com/redengineer/redmini/assets/57560984/a7f85eec-d34c-476a-a27e-a09ade2e0d0e">

找到对应分享类型，可以通过参数配置修改图片和描述

**Comment by xieguanyuan** [comment]
> 请明确一下具体是什么场景的分享，小红书内 or 微信？ 请参考：https://miniapp.xiaohongshu.com/docs/guide/openShare <img alt="图像" width="1274" src="https://user-images.githubusercontent.com/57560984/251630308-a7f85eec-d34c-476a-a27e-a09ade2e0d0e.png">
> 
> 找到对应分享类型，可以通过参数配置修改图片和描述

小红书内，把小程序分享给用户时
