### ISSUE TITLE
服务商无法收到客服消息的回调

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#795]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
有赞

## 平台
IDE

## 小红书版本信息
7.94.1
 
## 基础库版本
v3.56.0

## 发生问题的时间 
2023-07-07 00:00:00 至 2023-07-07 14:23:46

## 问题描述
小程序的客服消息模块，发送消息，服务商收不到客服消息的回调

## 期望结果
能够正常接收到客服消息的回调

## 重现步骤和复现问题的最小demo Github链接
1. 打开小程序
2. 点击客服模块
3. 输入框输入任何信息
4. 【期望】接受到刚输入文本信息的回调

**Comment by Matthew-1996** [comment]
https://github.com/redengineer/redmini/issues/794
请确认这两个issue是否同一个case，如果是后续合并为同一个issue

**Comment by Jonesau** [comment]
> 

794已关闭

**Comment by Jonesau** [comment]
62b6b876f29f6f00015982f0
621f7d3573f8b60001da143a
6214fa307c829000011628b4
已经有三个商家反馈了

**Comment by a-yahaha** [comment]
appid:  618e18fb4c1dd400016a8036
uid: 5fb1402300000000010012a4
可以测试复现

**Comment by a-yahaha** [comment]
> #794 请确认这两个issue是否同一个case，如果是后续合并为同一个issue

同一个问题，可以合并
