### ISSUE TITLE
审核结果回调的文字不在提审的商品中

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#796]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
7.94.1
 
## 基础库版本
v3.56.0

## 发生问题的时间 
2023-07-07 12:00:05 至 2023-07-07 12:20:05

## 问题描述
商品ID： 42610415_1918129273
2023-07-07 12:15:22 接收到商品的回调 
{&quot;Event&quot;:&quot;PRODUCT_AUDIT&quot;,&quot;OutProductId&quot;:&quot;42610415_1918129273&quot;,&quot;Status&quot;:2,&quot;AuditTime&quot;:1688703321,&quot;RejectReason&quot;:&quot;word:江青&quot;}
商品信息不包含任何 “江青”的文字

## 期望结果
提供具体审核失败的原因

## 重现步骤和复现问题的最小demo Github链接
1. 提审商品 商品ID： 42610415_1918129273
2. 商品审核回调异常

**Comment by Matthew-1996** [comment]
appid是？

**Comment by Matthew-1996** [comment]
机器误拒，已通过
