### ISSUE TITLE
蒲公英后台添加商品失败

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#797]
## Issue类型
operator

## 问题模块
直播

## 所属的服务商
微盟

## 小红书版本信息
V7.94

## 运营场景描述
appid：6399a270beef0d00019f020c
商品id：64a6867d87e21e0001ec8373
添加商品失败
[图片] 

## 发生问题的时间 
2023-07-07 16:47:36 至 2023-07-07 16:47:36

## 期望结果
该商品可以正常添加到池里

**Comment by Matthew-1996** [comment]
请明确一下，具体是哪个产品/功能下面的失效

提供截图或录屏

**Comment by Matthew-1996** [comment]
外部商品id：116230169101050，对吗

**Comment by mmeng1996** [comment]
> 外部商品id：116230169101050，对吗

是的

**Comment by Matthew-1996** [comment]
<img width="925" alt="企业微信截图_1688957622334" src="https://github.com/redengineer/redmini/assets/57560984/102bc8d7-9fcd-4386-8a97-0cc7e85af305">

**Comment by mmeng1996** [comment]
> <img alt="企业微信截图_1688957622334" width="925" src="https://user-images.githubusercontent.com/57560984/252201159-102bc8d7-9fcd-4386-8a97-0cc7e85af305.png">

想问一下无效的原因是什么
