### ISSUE TITLE
小程序关店，订单是否已全部结算

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#800]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
7.94.1

## 运营场景描述
商家需要开薯店，关闭小红书小程序店。需要检查订单是否都结算，商品是否都下架 

## 发生问题的时间 
2023-07-08 10:23:51 至 2023-07-08 10:23:51

## 期望结果
1，是否满足关店条件
2，未结算的订单有哪些
3，未同步的售后单有哪些

## 业务基础信息（选填）
小程序appId: 638808c6eb805d0001753c64

**Comment by Matthew-1996** [comment]
未结算订单：E20230328233314022400109
