### ISSUE TITLE
“我-商品”列表仍展示下架商品

### ISSUE THREAD

**Issue by ghost** [redengineer/redmini#805]
## Issue类型
operator

## 问题模块
商品列表

## 所属的服务商
有赞

## 小红书版本信息
V7.92

## 运营场景描述
小红书商品状态不可售，但是“我-商品”列表仍展示商品

## 发生问题的时间 
2023-07-10 17:15:25 至 2023-07-10 17:15:25

## 期望结果
商品状态不可售时，商品列表隐藏商品

## 业务基础信息（选填）
商品Id:79614517_443370080

**Comment by Matthew-1996** [comment]
1、是不是说的是专业号的主页

**Comment by Matthew-1996** [comment]
2、麻烦他提供appid 和相关截图
