### ISSUE TITLE
商户关闭小程序，未完成结算订单问题

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#808]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.56

## 运营场景描述
商户关闭小程序，仍有部分订单未完成结算，辛苦确认下还有哪几笔订单
appid：6312f9105245930001a7bbe6 

## 发生问题的时间 
2023-07-14 10:52:31 至 2023-07-14 10:52:31

## 期望结果
需要确认商户未结算的订单

**Comment by Matthew-1996** [comment]
436500750000713
465030788000826
468052160000820
470092038000844
470741254000857

**Comment by Matthew-1996** [comment]
未结算订单list
