### ISSUE TITLE
v7.45 的 cookie种不进去

### ISSUE THREAD

**Issue by malanll** [redengineer/redmini#81]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
小红书APP版本：v7.45
## 重现步骤 和 复现问题的最小demo Github链接
webview内嵌页面无法打开

## 期望结果 和 实际结果(必填)
实际结果：cookie种不进去，内嵌页面因为丢失身份信息都打不开
## 补充(猜测可能的原因是什么，你有啥想法，选填)
小红书新版对webview有修改吗？

**Comment by taiyiandr** [comment]
确认Android也有问题？

**Comment by xutm** [comment]
745 以下 web-view 是通过 iframe 实现，存在跨域问题。建议后端做下适配

**Comment by malanll** [comment]
Android没问题，已经取消勾选了
