### ISSUE TITLE
跳转H5页面返回页面报错

### ISSUE THREAD

**Issue by baizhenjie** [redengineer/redmini#810]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
汽车之家

## 平台
Android

## 小红书版本信息
7.95.0
 
## 基础库版本
v3.57.3

## 发生问题的时间 
2023-07-17 14:08:48 至 2023-07-17 14:08:48

## 问题描述
跳转一个h5页面 再返回后会有个toast提示&#x27;[null]域名校验失败&#x27;，已检查不是本地的接口报的错

## 期望结果
跳转成功后返回不再报错

## 重现步骤和复现问题的最小demo Github链接
点击跳转了一个H5页面再返回就报错

**Comment by taiyiandr** [comment]
这个错误提示是 非线上包，期望跳转至某个url 但未通过域名校验时 才会弹出，目的就是为了防止跳转到不正确的页面，请提供一下可复现的操作方式或者录屏呢？

**Comment by taiyiandr** [comment]
该toast不会影响线上版本，7.97修复该场景
