### ISSUE TITLE
商户关闭小程序，部分订单未结算完成

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#811]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
V765

## 运营场景描述
商户关闭小程序，部分订单未结算完成，需确认还有哪些订单需要结算
appid：622aeb0db284c10001bda265 

## 发生问题的时间 
2023-07-18 17:06:02 至 2023-07-18 17:06:02

## 期望结果
知晓商户还未结算的订单，便于我方处理

**Comment by Matthew-1996** [comment]
未结算订单

**Comment by Matthew-1996** [comment]
未结算订单
195098589018571
195098589018571
512053294000153

**Comment by Matthew-1996** [comment]
未完成订单
512053294000153
