### ISSUE TITLE
小程序开发中使用SJS 模块按照文档无法实现功能

### ISSUE THREAD

**Issue by biao-code** [redengineer/redmini#814]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
小蚁路书

## 平台
IDE

## 小红书版本信息
7.88
 
## 基础库版本
v3.52.4

## 发生问题的时间 
2023-07-19 11:06:17 至 2023-07-19 11:06:17

## 问题描述
按照文件创建SJS文件后，在XHSML中引用后，在页面中无法使用SJS中定义的数据。

## 期望结果
正常使用框架提供的SJS功能

## 重现步骤和复现问题的最小demo Github链接
按照框架创建index.SJS文件，代码如下：
var foo &#x3D; &quot;&#x27;hello world&#x27; from comm.SJS&quot;;
var bar &#x3D; function(d) {
  return d;
}
module.exports &#x3D; {
  foo: foo,
  bar: bar
};

index.xhsml文件代码如下：
&lt;view&gt;
    &lt;span&gt;test&lt;/span&gt;
    &lt;SJS src&#x3D;&quot;./index.SJS&quot; module&#x3D;&quot;tools&quot; /&gt;
    &lt;view&gt; {{tools.foo}} &lt;/view&gt;
    &lt;span&gt;test01&lt;/span&gt;
&lt;/view&gt;

index.SJS和index.xhsml在一个文件夹下

渲染后的页面没有tools.foo的值。

**Comment by biao-code** [comment]
![image](https://github.com/redengineer/redmini/assets/23007720/1a662af1-bca1-43be-a6f2-9a20ce2d59d0)
![image](https://github.com/redengineer/redmini/assets/23007720/9109beeb-4bcc-4fa5-9f0e-37d8a7d11b3e)

**Comment by Hubmeat** [comment]
.sjs 小写呢

可以先参考这个 demo 看看： https://github.com/Hubmeat/xhs-sjs-demo.git

**Comment by biao-code** [comment]
> .sjs 小写呢
> 
> 可以先参考这个 demo 看看： https://github.com/Hubmeat/xhs-sjs-demo.git

![image](https://github.com/redengineer/redmini/assets/23007720/fd3242d4-6001-4c35-8536-b2862ed128a2)
小写也不行

这个demo里的文件都是wxml，我都改成xhsml也没跑起来

**Comment by Hubmeat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
