### ISSUE TITLE
小程序无法关店

### ISSUE THREAD

**Issue by xiaokang2020** [redengineer/redmini#815]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
v7.89

## 运营场景描述
小程序关店，关闭不了，客服说订单没有关闭，我们把到支付订单找出来，调用同步订单状态接口，同步为已取消，提示：状态流转失败，不符合订单状态机规则。请辅助帮忙看下我们关店操作是否正确
 

## 用户ID 
7e5cc877979ac2124426ec6eeb2e3fdd616b014587194a69ee2bcd5a5913835e

## 发生问题的时间 
2023-07-19 14:03:12 至 2023-07-19 14:03:12

## 期望结果
期望协助查看关店失败原因，告知如何关店。我们这边需要处理哪些订单相关的问题。

## 业务基础信息（选填）
63de11732e3bbe0001922f9b

**Comment by xiaokang2020** [comment]
期望协助查看关店失败原因，告知如何关店。我们这边需要处理哪些订单相关的问题。

**Comment by Matthew-1996** [comment]
提供一下无法关闭的订单id，和报错code

**Comment by Matthew-1996** [comment]
未结算订单：
HMOrder001
2023021808424878718265100004
2023021809152674055005100004
2023021817194918859953
2023021817231334027077
2023021817384683000031
2023021818113432712222
2023021818145433120190
2023021818174298643735
2023021818212040607530
2023021820394061119626
2023022015502828637681
2023022111173515720077
2023022115141006346081
2023022115154502328412
2023022115164605402456
2023022115165135464955
2023022115182470916011
2023022115215974832735
2023022115241657321454
2023022118125377901182
2023022311140805705041
2023022321021285731554
2023030710294972016896
2023030710315823453272
2023030710345995936614
2023030710373686943405
2023030715393159401734
2023030716220548848097
2023030809260855513871
2023030908532732961592
2023030913542139052856
2023031301242807961510
2023031315585272447101
2023031413475995557018
2023031418054992716177
2023031418060498634138
2023031514590657520476
2023031515122536414467
2023031516065559962219
2023031517351935838773
2023031517570228529987
2023031518231149233491
2023031612084152215792
2023031615275139250263
2023031615280663203699
2023031617033612736878
2023031709215363500746
2023031709253461838727
2023031809171557139088
2023031808525519128882
2023031812570114855664
2023031814395962034065
2023031818133362347836
2023031818492438545150
2023031819094774436258
2023032008335775924952
2023033015402210802907
2023041313562135213931
