### ISSUE TITLE
小程序商品下架异常

### ISSUE THREAD

**Issue by qweqeer** [redengineer/redmini#816]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
有赞

## 平台
IDE

## 小红书版本信息
7.94.1
 
## 基础库版本
v3.57.4

## 发生问题的时间 
2023-07-18 16:40:56 至 2023-07-19 16:40:56

## 问题描述
小红书小程序商品调用下架接口完成下架后，再次调用列表查询接口显示商品未下架

## 期望结果
调用商品下架接口后查询列表接口商品应处于下架状态

## 重现步骤和复现问题的最小demo Github链接
商品ID：109517211_2245583018
appid：62caa5240d69a5000111520e
1、调用下架接口 https://miniapp.xiaohongshu.com/api/rmp/component/deal/product/sku/batch_offline
2、调用查询接口 https://miniapp.xiaohongshu.com/api/rmp/component/deal/product/batch_get

**Comment by Matthew-1996** [comment]
定位：SPU下无SKU
已处理下架
