### ISSUE TITLE
订单结算异常：订单或者售后单数据未同步

### ISSUE THREAD

**Issue by a-yahaha** [redengineer/redmini#817]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
有赞

## 平台
IDE

## 小红书版本信息
7.95.1
 
## 基础库版本
v3.57.4

## 发生问题的时间 
2023-07-19 16:46:17 至 2023-07-19 16:46:17

## 问题描述
订单号：
E20221022221616009306151
E20221025230524076500005
E20221230125916093600025
调动结算提示: 订单或者售后单数据未同步

查询售后单的状态和订单的状态都是正常同步过去的

## 期望结果
这些订单都是全额退款的，需要订单可以正常结算

## 重现步骤和复现问题的最小demo Github链接
订单号：E20221022221616009306151
售后单id： 202210271855130020100093, 202210271855400020050093, 202210271856020020500093, 202210271856233952260093, 202210272000140020550093, 202210272017530020350093 
结果： {&quot;code&quot;:420303,&quot;msg&quot;:&quot;订单或者售后单数据未同步&quot;,&quot;success&quot;:false}

订单号： E20221025230524076500005
售后单id： 202210282023463952160765, 202210282023463952170765, 202210291804013952260765
结果： {&quot;code&quot;:420303,&quot;msg&quot;:&quot;订单或者售后单数据未同步&quot;,&quot;success&quot;:false}

订单号： E20221230125916093600025
售后单id： 202212312130103952160936, 202212312159550020500936, 202301022133530020350936, 202301031317373952260936, 202301031317373952310936
结果： {&quot;code&quot;:420303,&quot;msg&quot;:&quot;订单或者售后单数据未同步&quot;,&quot;success&quot;:false}

**Comment by a-yahaha** [comment]
APPID: 6332ccb51de7df000196823f

**Comment by Matthew-1996** [comment]
<img width="1257" alt="image" src="https://github.com/redengineer/redmini/assets/57560984/ecf5cd3e-c0a1-487e-bcde-720dcbd365db">
提供一下这部分code

**Comment by Matthew-1996** [comment]
售后单是什么时候发起的？

**Comment by a-yahaha** [comment]
E20221022221616009306151
out_settle_id:  DPT-R221022221616009306151

E20221025230524076500005
out_settle_id:  DPT-R221025230524076500005

E20221230125916093600025
out_settle_id:  DPT-R221230125916093600025

结算时间 2023-07-19 15:00:00 ~ 2023-07-19 17:00:00

**Comment by Matthew-1996** [comment]
202210271856020020500093
202210271856233952260093
202210282023463952160765
202212312130103952160936
这四笔售后单是失败的，结算订单不要带上失败的售后单
