### ISSUE TITLE
接受不到智能客服消息

### ISSUE THREAD

**Issue by qweqeer** [redengineer/redmini#818]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
v7.95.1
 
## 基础库版本
v3.57.4

## 用户ID 
5f3a5fbc0000000001009a60

## 发生问题的时间 
2023-07-19 17:46:27 至 2023-07-19 17:46:27

## 问题描述
用户在小程序通过客服入口进行咨询，未接受到对应的消息回调

## 期望结果
期望用户发送的消息能正常推送给服务商

## 重现步骤和复现问题的最小demo Github链接
appid: 62f0cd214440da0013ca14d4
进入小程序后，发起点击客服入口，发送消息

**Comment by Matthew-1996** [comment]
问题定位：历史店铺关店，导致客服消息接受异常

已修复，可以再看一下还有无问题
