### ISSUE TITLE
调用商品同步接口后，接口返回成功，但是sku数据缺少

### ISSUE THREAD

**Issue by xuwenjie0505** [redengineer/redmini#819]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
自我游

## 平台
Android, IOS, IDE

## 小红书版本信息
7.82
 
## 基础库版本
v3.57.4

## 发生问题的时间 
2023-07-20 14:50:47 至 2023-07-20 14:52:47

## 问题描述
调用商品同步接口后，接口返回成功，但是sku数据缺少问题

## 期望结果
希望商品查询接口返回正常的sku数据

## 重现步骤和复现问题的最小demo Github链接
外部商品id&#x3D;71869868，appid&#x3D;64b20908ef60aa0039b9e23d，调用该接口https://miniapp.xiaohongshu.com/api/rmp/tp/poi/product/upsert 同步商品返回成功，但是通过https://miniapp.xiaohongshu.com/api/rmp/component/deal/product/get 接口可以查询到商品信息，但是sku数据为空，查询商品返回结果{&quot;data&quot;:{&quot;out_product_id&quot;:&quot;71869868&quot;,&quot;name&quot;:&quot;雅安碧峰峡野生动物世界门票+雅安旅游一卡通+餐饮套餐2大1小&quot;,&quot;short_title&quot;:&quot;雅安碧峰峡野生动物园&quot;,&quot;desc&quot;:&quot;雅安碧峰峡野生动物世界门票+雅安旅游一卡通+餐饮套餐2大1小&quot;,&quot;path&quot;:&quot;/product/detail/index?appId&#x3D;64b20908ef60aa0039b9e23d&amp;infoId&#x3D;71869868&quot;,&quot;top_image&quot;:&quot;http://qnimg.zowoyoo.com/img/15463/1432513697659.jpg&quot;,&quot;category_id&quot;:&quot;6135821dae64e60001af7405&quot;,&quot;biz_create_time&quot;:1689835877,&quot;biz_update_time&quot;:1689835877,&quot;skus&quot;:null,&quot;ext&quot;:null,&quot;status&quot;:0,&quot;audit_info&quot;:null},&quot;success&quot;:true,&quot;msg&quot;:&quot;success&quot;,&quot;code&quot;:0}

**Comment by xuwenjie0505** [comment]
查询商品返回结果 {"data":{"out_product_id":"71869868","name":"雅安碧峰峡野生动物世界门票+雅安旅游一卡通+餐饮套餐2大1小","short_title":"雅安碧峰峡野生动物园","desc":"雅安碧峰峡野生动物世界门票+雅安旅游一卡通+餐饮套餐2大1小","path":"/product/detail/index?appId=64b20908ef60aa0039b9e23d&infoId=71869868","top_image":"http://qnimg.zowoyoo.com/img/15463/1432513697659.jpg","category_id":"6135821dae64e60001af7405","biz_create_time":1689835877,"biz_update_time":1689835877,"skus":null,"ext":null,"status":0,"audit_info":null},"success":true,"msg":"success","code":0}

**Comment by Matthew-1996** [comment]
确认，该spu下的sku外部商品id是不是：71869868-6792599

该sku已删除，已删除商品状态不可逆。需要在spu下新增sku，请使用一个新的外部skuid上传。
