### ISSUE TITLE
[@xhs/runtime-core] load page module has uri error: not found xhs service, route: pages/saasWebview/index，已找小红书方确认app.json中存在pages/saasWebview/index，且内部代码正确

### ISSUE THREAD

**Issue by handsome025** [redengineer/redmini#82]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [x] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
APP7.44.1
## 期望结果 和 实际结果(必填)
能正确加载小程序版本
## 补充(猜测可能的原因是什么，你有啥想法，选填)
冷启动时小程序版本未加载到最新版本

**Comment by Hubmeat** [comment]
每次复现吗？是 IOS 还是 android 呢
