### ISSUE TITLE
审核模拟器首页切换h5后白屏，真机及开发工具都正常

### ISSUE THREAD

**Issue by KaKmi** [redengineer/redmini#820]
## Issue类型
feature

## 所属的服务商
微盟

## 这个功能解决的问题
希望改善审核模拟器逻辑，目前我们有些商户使用了我们平台第三方开发提供的组件库，未经适配在小红书可能存在问题，所以首页在进入小红书后切换成对应的h5页面，目前经过开发者工具及真机上测试均可正常运行，但是审核时出现白屏，希望保持审核模拟器跟真机或者开发者工具环境类似，减少这种非正式环境的白屏

**Comment by xutm** [comment]
appid 多少，我们看下

**Comment by KaKmi** [comment]
> appid 多少，我们看下
62872cd641ca0b0001e93dca 比如这个 我们7.4提交审核的
