### ISSUE TITLE
聚光平台的商品推广中uv数据为0，需要确认取值来源

### ISSUE THREAD

**Issue by wolove** [redengineer/redmini#821]
## Issue类型
bug

## 问题模块
小程序服务(服务后台)
 
## 所属的服务商
有赞

## 平台
IOS

## 小红书版本信息
7.88
 
## 基础库版本
v3.59.0

## 发生问题的时间 
2023-07-24 15:31:33 至 2023-07-24 15:31:33

## 问题描述
聚光平台的商品推广中有些uv数据为0，但是却有订单产生，需要确认uv的取值来源

## 期望结果
给出聚光平台的uv取值逻辑，配合商家确认数据是否来自有赞

## 重现步骤和复现问题的最小demo Github链接
无

**Comment by Matthew-1996** [comment]
同步一下商家uid、投放账号

**Comment by Matthew-1996** [comment]
同步一下有问题的广告投放创意

**Comment by Matthew-1996** [comment]
麻烦明确一下有些uv数据是指哪些数据字段？

**Comment by wolove** [comment]
![img_v2_2bedbab5-8566-448a-a433-4a9da291f2eg](https://github.com/redengineer/redmini/assets/17583618/bc291ed9-78c9-4c6b-a824-592abe6ec66f)
有疑问的字段

**Comment by wolove** [comment]
1】投放账号ID：426712
2】投放账号名：叁柒（格力高扁桃仁植物奶2）
3】投放笔记ID：64b6647a000000001c00c88a
4】投放笔记创意链接：http://xhslink.com/Se1Pus

**Comment by Matthew-1996** [comment]
商品访客量为0，但是却有订单产生的计划id是什么？

**Comment by wolove** [comment]
商家反馈 计划ID：13938157

**Comment by Matthew-1996** [comment]
该计划有rgmv时，访客量不为0。无异常
若后续还有问题请聚光平台
