### ISSUE TITLE
商户退小程序，未结算订单

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#824]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v76.5

## 运营场景描述
商户退店时仍有未下架的商品或订单，需要帮忙提供一下相关单号，商户appid：632c0831092216000166674c 

## 发生问题的时间 
2023-07-25 15:49:18 至 2023-07-25 15:49:18

## 期望结果
提供未下架的商品id或未完成结算的订单号，以便商户关闭小程序

**Comment by Matthew-1996** [comment]
未完成订单：
434144052000224
434089768000571
434098024000360
517386379000098
434121379000097
