### ISSUE TITLE
商户关闭小程序，部分未结算订单

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#825]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
V76.5

## 运营场景描述
帮忙查看一下未结算的订单 商户appid：6375f1fe76afb200012ba7d8 

## 发生问题的时间 
2023-07-25 16:20:25 至 2023-07-25 16:20:25

## 期望结果
提供未结算完成的订单，以便处理完商户可以关闭小程序

**Comment by Matthew-1996** [comment]
未结算订单：
514157236000365
514334787000579

**Comment by Matthew-1996** [comment]
未完成订单：
514157236000365
514334787000579
