### ISSUE TITLE
小程序发布版本一直在审核中

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#827]
## Issue类型
operator

## 问题模块
审核发布

## 所属的服务商
有赞

## 小红书版本信息
7.96

## 运营场景描述
小程序发布版本一直在审核中
小程序AppID：64b78722540fd8004c582403
小程序名称：厦门钓鲜文化
小程序审核版本：1.4.3 

## 发生问题的时间 
2023-07-19 15:17:15 至 2023-07-26 15:24:33

## 期望结果
获取一直在审核的原因，以及解决的办法

## 业务基础信息（选填）
小程序AppID：64b78722540fd8004c582403
小程序名称：厦门钓鲜文化
小程序审核版本：1.4.3

**Comment by Matthew-1996** [comment]
没查到有送审的推送，请同步一下提审代码和反馈
