### ISSUE TITLE
商家关闭小程序，仍有未结算订单待确认

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#829]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.96.1

## 运营场景描述
商户要关闭小红书小程序，有部分未结算订单明细需要小红书侧查询回复
appid：6312f9105245930001a7bbe6 

## 发生问题的时间 
2023-07-26 16:50:37 至 2023-07-26 16:50:37

## 期望结果
提供所有未结算/未完成订单

**Comment by Matthew-1996** [comment]
请确认一下appid，该小程序已关店
