### ISSUE TITLE
xhs.getMenuButtonBoundingClientRect();返回的top值不对

### ISSUE THREAD

**Issue by luochenwang** [redengineer/redmini#83]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [x] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.28.1
## 重现步骤 和 复现问题的最小demo Github链接
xhs.getMenuButtonBoundingClientRect(); 返回的top值不对

**Comment by Hubmeat** [comment]
提供小红书原生场景的 case 呢

**Comment by xutm** [comment]
最新版 1.61.0 已经修复
