### ISSUE TITLE
小红书小程序关店，仍有订单未结算/商品未下架

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#831]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.96.1

## 运营场景描述
小红书小程序关店，仍有未结算订单/未下架商品
appid： 622aeb0db284c10001bda265 

## 发生问题的时间 
2023-07-28 12:29:58 至 2023-07-28 12:29:58

## 期望结果
提供未结算订单及未下架商品id

**Comment by Matthew-1996** [comment]
未结算订单：

195098589018571
195098589018571

**Comment by Matthew-1996** [comment]
未下架商品：

114380687100686
145062860100686

**Comment by bonnie950123** [comment]
未下架商品：
114380687100686   已手动下架
145062860100686   商品不存在

**Comment by bonnie950123** [comment]
辛苦牛顿再看下商品是否都已经下架哈

**Comment by bonnie950123** [comment]
订单已处理
