### ISSUE TITLE
vue2 uniapp 编译到真机调用 this.$refs 报错，IOS 直接卡死退出小红书

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#833]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
test

## 平台
IOS, Android

## 小红书版本信息
7.97.2
 
## 基础库版本
v3.55.2

## 发生问题的时间 
2023-07-28 15:21:35 至 2023-07-28 15:30:35

## 问题描述
IOS 调用 this.$refs 直接卡死，退出APP

## 期望结果
能够正常调用 this.$refs

## 重现步骤和复现问题的最小demo Github链接
去年就提出过这个问题，今年这个问题还在，同样的报错同样的卡死退出APP
https://github.com/redengineer/redmini/issues/262

**Comment by jonsen-liu** [comment]
开发者工具  基础库版本    3.57.0  3.58.0  3.59.0 (其他未测) 就报错 Uncaught ReferenceError: vue is not defined

**Comment by jonsen-liu** [comment]
![1690530569143](https://github.com/redengineer/redmini/assets/26186472/37f08dfb-691d-48c2-9855-20e9f04182ed)

**Comment by Hubmeat** [comment]
你好，请问能明确是 $refs 相关实现的问题是吗？麻烦给下 uni 工程的相关代码吧。这个涉及到 uni 在小红书平台的表现问题，排查链路比较长我们这边协助你看下

**Comment by Cauho** [comment]
最新更新的1.61.6提到修复了vue is not defined 这个问题了
