### ISSUE TITLE
小程序白屏

### ISSUE THREAD

**Issue by qq280605311** [redengineer/redmini#84]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
7.45
## 重现步骤 和 复现问题的最小demo Github链接
反复跳转页面，快速返回，有概率会白屏

**Comment by AngryBrotherXiang** [comment]
7.48版本补充下全量日志，再有问题麻烦企微联系，回捞下日志
