### ISSUE TITLE
小红书小程序关店，仍有未结算/未完成订单待确认

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#840]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.97.2

## 运营场景描述
小红书小程序关店，仍有未下架商品/未结算订单待确认
appid：62d7cfb1f8fccf000148419c 

## 发生问题的时间 
2023-08-01 11:00:05 至 2023-08-01 11:00:05

## 期望结果
提供所有未结算/未完成订单id

**Comment by Matthew-1996** [comment]
未下架商品


1399549920194
2187758790194
2187758800194
2187758810194
2187758820194
2187758830194
2187758840194
1431751820194
2358649230194
2358649240194
2358649250194
2358649260194
2358649270194
2358649280194
107990277199794
128531048199794
128531049199794
128531810199794
128531811199794
128531812199794

**Comment by Matthew-1996** [comment]
共72个商品未下架，完成商品下架

**Comment by Matthew-1996** [comment]
[查询结果 (70).csv](https://github.com/redengineer/redmini/files/12224350/70.csv)
