### ISSUE TITLE
 小红书小程序关店，仍有商品未下架

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#841]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.97.2

## 运营场景描述
商家侧目前已在微盟后台下架小红书渠道所有商品
appid：62d7cfb1f8fccf000148419c 

## 发生问题的时间 
2023-08-01 14:36:04 至 2023-08-01 14:36:04

## 期望结果
提供目前关店进度，是否仍有未下架商品/未结算订单

**Comment by Matthew-1996** [comment]
未下架商品
[查询结果 (71).csv](https://github.com/redengineer/redmini/files/12225417/71.csv)
