### ISSUE TITLE
IDE无法使用 模拟器未显示 工程管理仅显示外框

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#843]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
东拼西凑

## 平台
IDE

## 小红书版本信息
1.61.6
 
## 基础库版本
v3.60.0

## 发生问题的时间 
2023-08-02 09:52:13 至 2023-08-02 09:52:13

## 问题描述
从1.61.1更新到1.61.6后就无法正常使用

版本: 1.61.6
提交: cc4287a32b5e3ebb4e33da7e085624f83e065e49
日期: 2023-07-31T01:05:37.200Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22621

## 期望结果
恢复正常使用,能正常打开工程.能正常调试

## 重现步骤和复现问题的最小demo Github链接
安装1.61.6IDE

**Comment by anaian** [comment]
这个版本可以正常使用,是从这个更新的. 上面问题描述错了
版本: 1.60.0
提交: 84b4e717d5fd7f063d7b16d58def2ee67b267beb
日期: 2022-10-13T07:58:04.554Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by hhuwc** [comment]
你好，请卸载一下, 然后安装1.61.6 版本

**Comment by anaian** [comment]
> 你好，请卸载一下, 然后安装1.61.6 版本

测试可以解决
