### ISSUE TITLE
从专业号里进入店铺页面是空白的

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#845]
## Issue类型
operator

## 问题模块
用户进入小程序

## 所属的服务商
有赞

## 小红书版本信息
7.92

## 运营场景描述
用户从专业号进入店铺，只加载了框架，内容没有加载出来，首页显示空白。想让小红书的大佬帮忙看一下，能不能查出是什么原因 

## 发生问题的时间 
2023-08-02 15:07:23 至 2023-08-02 15:07:23

## 期望结果
想知道为什么无法进入到小程序

## 业务基础信息（选填）
小程序AppID：
63f41d9e74fa2a000175f3ea
小红书号： 501399886
账号名称：生生不息宠物

**Comment by Matthew-1996** [comment]
这里头主页店铺进去没法复现，提供录屏、手机型号、小红书版本号、测试的小红书用户id
