### ISSUE TITLE
小程序关店，订单异常

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#847]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
7.96

## 运营场景描述
小程序关店，异常订单处理 

## 发生问题的时间 
2023-08-02 17:15:21 至 2023-08-02 17:15:21

## 期望结果
帮忙处理一下异常订单，满足关店流程

## 业务基础信息（选填）
&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  订单  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【订单状态】: [!!!]订单状态未同步数: 62
【异常同步订单】: 
 E20230417155435061100005
 E20230609212159049506165
 E20230425203517001806193
 E20230609223138059306173
 E20230414203149038606153
 E20230609184158060300061
 E20230513133629088600061
 E20230414204605041000043
 E20230513143104087906189
 E20230429110056057000039
 E20230512231244087406159
 E20230425003136077700099
 E20230414200632050100017
 E20230610100748045200015
 E20230421234718013906159
 E20230414201703044800093
 E20230602160816021200073
 E20230514001042006500043
 E20230416070808099200033
 E20230427085342089206153
 E20230424221452009700077
 E20230610105545078600049
 E20230602163907078500021
 E20230618102304074806233
 E20230414200457062906183
 E20230418131850067200139
 E20230609213742029806175
 E20230517180557064400127
 E20230430221814020006155
 E20230414204343010106179
 E20230425134851077606167
 E20230414204123092700107
 E20230424233258029800189
 E20230426175655049600025
 E20230513204542089206145
 E20230513115530068500065
 E20230414223722096900079
 E20230414221913024700005
 E20230414221827007200089
 E20230609184245049506191
 E20230414203236061200021
 E20230425202109069000097
 E20230609184125049500059
 E20230416220313053100037
 E20230421223843100806169
 E20230421234938013900007
 E20230425213842089400159
 E20230609183434018800011
 E20230419102426101206197
 E20230430162621069606181
 E20230514001112006500099
 E20230512192152009100101
 E20230428193659092900059
 E20230513184503065700041
 E20230414200333003006175
 E20230421205306101900075
 E20230421200549027600023
 E20230415151046085000059
 E20230414220036053700115
 E20230414203131061200081
 E20230415135726046500057
 E20230414200716095700111

&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  结算  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【结算状态】: [!!!]未结算订单数: 1
【异常结算订单】: 
 E20230414200716095700111

【店铺id】: 92216242
【APP_ID】:  621c97f180194700010a804d
【APP版本】:  7.96

**Comment by Matthew-1996** [comment]
未结算订单


[查询结果 (73).csv](https://github.com/redengineer/redmini/files/12273414/73.csv)
