### ISSUE TITLE
接受不到智能客服消息

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#848]
## Issue类型
operator

## 问题模块
客服消息

## 所属的服务商
有赞

## 小红书版本信息
7.97.2

## 运营场景描述
用户在小程序通过客服入口进行咨询，未接受到对应的消息回调 

## 发生问题的时间 
2023-08-03 09:59:45 至 2023-08-03 09:59:45

## 期望结果
期望用户发送的消息能正常推送给服务商

## 业务基础信息（选填）
appid: 64c76c414de537003f25a54a
进入小程序后，发起点击客服入口，发送消息

**Comment by Matthew-1996** [comment]
已恢复，看问题还能不能复现？

**Comment by lhwzqqz** [comment]
好的
