### ISSUE TITLE
小程序无法关店

### ISSUE THREAD

**Issue by lhwzqqz** [redengineer/redmini#849]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
7.96

## 运营场景描述
小程序无法关店，存在异常订单。 

## 发生问题的时间 
2023-08-03 15:36:23 至 2023-08-03 15:36:23

## 期望结果
期望协助完成关店要求

## 业务基础信息（选填）

【订单状态】: [!!!]订单状态未同步数: 15
【异常同步订单】: 
 E20221219123306030006175
 E20230507151745002700053
 E20230527115706004400077
 E20221216075637083806171
 E20230106102625057106203
 E20221210164619060106157
 E20221208091035071600085
 E20221208181311053406147
 E20221208115941049400095
 E20230425164538004506157
 E20230528184513077506157
 E20221210093051033000109
 E20221222211101029600061
 E20221209190258084000019
 E20221223204011028500101

【结算状态】: [!!!]未结算订单数: 4
【异常结算订单】: 
 E20221210230640049400101
 E20230425164538004506157
 E20230528184513077506157
 E20221228095224027606159

【店铺id】: 99604888
【APP_ID】:  638826bda9f15f000120585e

**Comment by Matthew-1996** [comment]
未结算订单

[查询结果 (74).csv](https://github.com/redengineer/redmini/files/12273426/74.csv)

**Comment by a-yahaha** [comment]
E20221210230640049400101 
这笔订单一直无法结算，订单是全额退款，售后单状态是正确的，订单的状态无法修改了，帮忙看看怎么处理？
postUrl:https://miniapp.xiaohongshu.com/api/rmp/component/deal/settle?appid=616e856cba1dc500014528fa&access_token=ffd56734f8a344538a41cc60cf784316
param:{"after_settle":0,"out_after_sales_order_ids":["202212102307403952210494"],"out_order_id":"E20221210230640049400101","out_settle_id":"2304272234322621580022"}, 
response:{"code":420308,"msg":"当前订单数据状态错误，不可结算","success":false}
