### ISSUE TITLE
Taro @tarojs/plugin-platform-xhs 编译 scroll-view onScrollToLower事件丢失

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#85]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 基础库版本或小红书APP版本(必填)
3.28.1
## 重现步骤 和 复现问题的最小demo Github链接
@tarojs/plugin-platform-xhs :0.0.3
taro:3.4.4
## 期望结果 和 实际结果(必填)
onScrollToLower事件正常相应

**Comment by echooys** [comment]
> 提供下代码片段



> 提供下代码片段

<img width="721" alt="image" src="https://user-images.githubusercontent.com/63334662/176621869-807ac921-510e-4f15-b124-53683dfcafef.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/63334662/176621925-32deef1b-5e15-4b63-99c2-4144f9c5363b.png">

**Comment by Hubmeat** [comment]
可以下 build 的产物，编译到小红书语法，事件名称变成了什么了？

**Comment by echooys** [comment]
> 可以下 build 的产物，编译到小红书语法，事件名称变成了什么了？

![image](https://user-images.githubusercontent.com/63334662/176810508-edd528cf-3c95-45fc-8d24-ae1013dd729e.png)
onscroll 是可以执行的

**Comment by Hubmeat** [comment]
目前看应该是 taro plugin 事件转换的问题，今天确定问题会提 PR 修掉，到时候更新插件就可以了

临时方案可以使用 scroll 事件配合视图区域 mock 下这个能力。我们会尽快修复。

**Comment by echooys** [comment]
> 目前看应该是 taro plugin 事件转换的问题，今天确定问题会提 PR 修掉，到时候更新插件就可以了
> 
> 临时方案可以使用 scroll 事件配合视图区域 mock 下这个能力。我们会尽快修复。

好的谢谢

**Comment by Hubmeat** [comment]
@tarojs/plugin-platform-xhs <= 0.0.3 版本存在兼容问题，
可以安装 > 0.0.3 版本。

< 0.0.3 版本临时解决方案：
[pwd]:node_modules/@tarojs/plugin-platform-xhs/dist/index.js

code:24 
```
    replacePropName(name, value, componentName) {
        if (value === 'eh') return name.toLowerCase() // 添加此行代码
        return name;
    }
```

**Comment by echooys** [comment]
好的，谢谢

**Comment by Hubmeat** [comment]
@tarojs/plugin-platform-xhs 0.0.4 已经发布了，可以通过下面命令安装更新：
```bash
npm install @tarojs/plugin-platform-xhs@latest
or 
yarn add @tarojs/plugin-platform-xhs@latest
```

**Comment by echooys** [comment]
> 
![image](https://user-images.githubusercontent.com/63334662/177090166-81b75308-0600-40ea-a839-6623ea19e82d.png)

你好！更新了之后一直报这个错。

**Comment by Hubmeat** [comment]
重启过么。之间使用 0.0.3 按照上面的流程修改代码后，有这个报错吗？

**Comment by echooys** [comment]
0.0.3 没修改，因为不影响开发

**Comment by echooys** [comment]
lock node_modules 都删了重装的

**Comment by Hubmeat** [comment]
这个报错可能是其他事件的转换规则在 taro 平台逻辑内的不兼容导致。

本地你先试用 0.0.3 开发。

0.0.4 的需要看下你报错页面的 xhsml 内容

**Comment by echooys** [comment]
是需要提供base.xhsml 内容吗

**Comment by Hubmeat** [comment]
嗯。可以定位到是哪个页面的问题么？

如果方便，可以简单做下排除法，注释掉部分组件内容，比如注释到 scroll-view 组件报错消失，那么可以提供下这部分的页面模板和事件绑定逻辑。

**Comment by echooys** [comment]
好的  我定位一下吧

**Comment by echooys** [comment]
> 嗯。可以定位到是哪个页面的问题么？
> 
> 如果方便，可以简单做下排除法，注释掉部分组件内容，比如注释到 scroll-view 组件报错消失，那么可以提供下这部分的页面模板和事件绑定逻辑。

我排查下来是 scroll-view 内如果有swiper 就会事件冲突

**Comment by echooys** [comment]
![image](https://user-images.githubusercontent.com/63334662/177105633-364ff763-3a02-4a9b-8f42-08b6c764d426.png)
![image](https://user-images.githubusercontent.com/63334662/177105671-d588e9e5-11a9-4c37-b581-4e64ee04a2a4.png)

**Comment by echooys** [comment]
大概什么时候能解决呀

**Comment by Hubmeat** [comment]
> > 嗯。可以定位到是哪个页面的问题么？
> > 如果方便，可以简单做下排除法，注释掉部分组件内容，比如注释到 scroll-view 组件报错消失，那么可以提供下这部分的页面模板和事件绑定逻辑。
> 
> 我排查下来是 scroll-view 内如果有swiper 就会事件冲突

好，我用原生看下能否复现你的场景。 
swiper 和 scroll-view 不推荐嵌套使用，会存在手势冲突问题。
这个问题的修复时间暂时不确定，如果是 swiper 和 scroll-view 场景下导致的问题，需要排期修复。
