### ISSUE TITLE
小红书小程序关店，确认是否还有未结算订单/未下架商品

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#853]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v7.97.2

## 运营场景描述
小红书小程序关店，确认是否还有未结算订单/未下架商品
appid：6250e5da5f1bf30001b6ae4b 

## 发生问题的时间 
2023-08-04 14:54:33 至 2023-08-04 14:54:33

## 期望结果
提供所有未结算订单id及未下架商品id

**Comment by Matthew-1996** [comment]
商品未下架、分销未关闭、订单未完成、订单未结算

**Comment by Matthew-1996** [comment]
未结算订单


95738007011536
195738007011536
192931907017436

**Comment by Matthew-1996** [comment]
未下架商品
[查询结果 (75).csv](https://github.com/redengineer/redmini/files/12273481/75.csv)

**Comment by Matthew-1996** [comment]
未完成订单


525597457000346
525597859000185
525597679000222
525598609000723
