### ISSUE TITLE
vue3 uniapp 子组件emit抛出事件，父组件无法监听触发

### ISSUE THREAD

**Issue by jonsen-liu** [redengineer/redmini#855]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
自我游

## 平台
IOS, Android, IDE

## 小红书版本信息
8.0.1
 
## 基础库版本
v3.56.0

## 发生问题的时间 
2023-08-04 17:08:40 至 2023-08-04 17:08:40

## 问题描述
vue3 uniapp 子组件emit抛出事件，父组件无法监听触发

## 期望结果
父组件能够监听触发子组件抛出的事件

## 重现步骤和复现问题的最小demo Github链接
https://github.com/jonsen-liu/vue3-uniapp-xhs

**Comment by jonsen-liu** [comment]
测试 uview-plus  ThorUI  FirstUI  三个UI框架编译到小红书环境，全都无法触发组件 Events 事件

**Comment by fanqidong** [comment]
遇到同样的问题，希望尽快解决 @Hubmeat

**Comment by jzhmcoo1** [comment]
https://github.com/dcloudio/uni-app/pull/4315#issuecomment-1671263637
你好，这边已经做了一版修复，可以参照这个链接下的方法本地替换看下效果
