### ISSUE TITLE
IDE代码上传时出现 整包zip包解析失败

### ISSUE THREAD

**Issue by anaian** [redengineer/redmini#857]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
东拼西凑

## 平台
IDE

## 小红书版本信息
1.61.7
 
## 基础库版本
v3.59.1

## 发生问题的时间 
2023-08-07 16:22:43 至 2023-08-07 16:22:43

## 问题描述
卸载1.61.6版本后,安装1.61.7版本.
上传代码时出现 整包zip包解析失败

## 期望结果
能正常上传代码.能正常使用

## 重现步骤和复现问题的最小demo Github链接
卸载1.61.6版本后,安装1.61.7版本.
上传代码时出现 整包zip包解析失败

版本: 1.61.7
提交: 3a85441a1a16d61b184086d23c19ff0df70a0df4
日期: 2023-08-07T07:37:54.742Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by hhuwc** [comment]
你好，是用下面的版本试试
https://picasso-static.xiaohongshu.com/electron-app-updater-cli/f5676bca-bf10-465c-abf4-093ba37e5ba8/xhs-mpide-1.61.9.exe
