### ISSUE TITLE
任务出现异常，error：整包zip包解析失败

### ISSUE THREAD

**Issue by HTHQ1234** [redengineer/redmini#858]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
比亚迪汽车海洋

## 平台
IDE

## 小红书版本信息
7.94
 
## 基础库版本
v3.59.1

## 用户ID 
5ce5623f0000000012014bdc

## 发生问题的时间 
2023-08-07 16:52:37 至 2023-08-07 16:52:37

## 问题描述
IDE点击预览或者上传的时候，出现弹窗任务出现异常，提示Error:整包zip包解析失败

## 期望结果
能正常显示IDE点击预览或者上传功能

## 重现步骤和复现问题的最小demo Github链接
在IDE点击预览或者上传的时候就可以重现了

**Comment by hhuwc** [comment]
IDE 版本多少

**Comment by hhuwc** [comment]
你好，已经推送了旧版本ide 可以使用旧版本ide 进行构建

**Comment by HTHQ1234** [comment]
> 你好，IDE版本多少

1.61.7版本

**Comment by hhuwc** [comment]
> > 你好，IDE版本多少
> 
> 1.61.7版本

你好，这边刚刚禁用了这个版本，请使用推送的新版本进行构建。

**Comment by HTHQ1234** [comment]
> > > 你好，IDE版本多少
> > 
> > 
> > 1.61.7版本
> 
> 你好，这边刚刚禁用了这个版本，请使用推送的新版本进行构建。

好的，更新了1.61.8版本可以了

**Comment by hhuwc** [comment]
> > > > 你好，IDE版本多少
> > > 
> > > 
> > > 1.61.7版本
> > 
> > 
> > 你好，这边刚刚禁用了这个版本，请使用推送的新版本进行构建。
> 
> 好的，更新了1.61.8版本可以了

你好，请问你在小红书合作群里嘛？方便私聊一下我们嘛？

**Comment by hhuwc** [comment]
或者可以加我微信 hhu-wc
