### ISSUE TITLE
api/rmp/component/deal/settle结算请求失败

### ISSUE THREAD

**Issue by worldunfair** [redengineer/redmini#86]
## 系统环境(必填)
linux

## 问题模块(必填)
- [ ] API & 组件 & 框架
结算接口报错（api/rmp/component/deal/settle）
入参：
"{"after_settle":0,"appid":"616d1d3e53d0ba0001db1529","out_after_sales_order_ids":[],"out_order_id":"193742026012421","out_settle_id":"193742026012421"}"
返回值：
{
"msg":"当前订单数据状态错误，不可结算"
"code":420308
"success":false
}
appid:620ccfeb6fce76000167bc2b
订单详情报文
{
  "msg": "success",
  "code": 0,
  "data": {
    "price_info": {
      "freight_price": 1,
      "order_price": 10
    },
    "path": "/pages/saasWebview/index?url=https%3A%2F%2Fn.weimob.com%2Fsaas%2Fpayment%2Fweixinpay%2Fretail_orderdetail%3ForderNo%3D193742026012421%26storeId%3D245244721%26pid%3D100000586721",
    "biz_update_time": 1656575228,
    "open_id": "e2b021028a0db46b4adef3f56252d9ba10649240b0cdfb28033b6ba143d8d7be",
    "out_order_id": "193742026012421",
    "product_infos": [
      {
        "out_sku_id": "1995996340121",
        "image": "https://qimg.xiaohongshu.com/b/58ea6aea-58cc-4d7e-8d43-f7412f7252d4",
        "num": 2,
        "out_product_id": "1347401070121",
        "real_price": 9,
        "sale_price": 600,
        "discount_infos": [
          {
            "price": 591,
            "num": 1,
            "name": "余额抵扣"
          }
        ]
      }
    ],
    "order_expired_time": 1656522097,
    "biz_create_time": 1656514897,
    "status": 7
  },
  "success": true
}

**Comment by wdvxdr** [comment]
见文档，
https://miniapp.xiaohongshu.com/third/api-3rd/post-api-rmp-component-deal-settle
“备注：每个订单在到达已完成+7后，进行首次结算并传0。”

结算需要在订单完成归因后才能发起，需要在订单创建的48小时才能结束。
