### ISSUE TITLE
小程序关店，订单状态呢异常

### ISSUE THREAD

**Issue by qiuyu-d** [redengineer/redmini#860]
## Issue类型
operator

## 问题模块
小程序关店

## 所属的服务商
有赞

## 小红书版本信息
7.96

## 运营场景描述
小程序关店，异常订单处理 

## 发生问题的时间 
2023-08-08 14:36:10 至 2023-08-08 14:36:10

## 期望结果
帮忙处理一下异常订单，满足关店流程

## 业务基础信息（选填）
【小红书关店结果通知】
【店铺id】: 93908867

&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  商品  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【商品状态】: 全部下架

&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  订单  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【订单状态】: [!!!]订单状态未同步数: 1
【异常同步订单】: 
 E20220804121731027506169

&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  结算  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【结算状态】: [!!!]未结算订单数: 0

&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;  小红书咨询  &#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;&#x3D;
【APP_ID】:  622af076b284c10001bda266
【APP版本】:  7.96

**Comment by Matthew-1996** [comment]
满足关店条件
