### ISSUE TITLE
小红书富文本组件特殊符号显示异常

### ISSUE THREAD

**Issue by fanqidong** [redengineer/redmini#861]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
魔方文娱

## 平台
IOS, Android, IDE

## 小红书版本信息
8.01
 
## 基础库版本
v3.24.1

## 发生问题的时间 
2023-08-08 17:28:35 至 2023-08-08 17:28:35

## 问题描述
小红书富文本组件特殊符号显示异常 很多特殊符号没有转义

## 期望结果
小红书富文本组件特殊符号显示正常

## 重现步骤和复现问题的最小demo Github链接

复现文本如下：
<img width="1195" alt="image" src="https://github.com/redengineer/redmini/assets/33058804/08567041-80e1-486d-ac1f-589a980c22f9">

&lt;p&gt;&lt;strong&gt;陈楚生&amp;ldquo;棱&amp;rdquo;2023巡回演唱会 &amp;mdash;广州站&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;陈楚生2023全新主题巡演解锁广州站，用音乐展现多&amp;ldquo;棱&amp;rdquo;色彩&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;陈楚生2023&amp;ldquo;棱&amp;rdquo;巡回演唱会广州站重磅来袭。上一轮&amp;ldquo;涂鸦森林&amp;rdquo;巡演场场售罄，一票难求的盛况，让陈楚生听到的歌迷们的呼唤，&amp;ldquo;棱&amp;rdquo;将在大型体育馆与大家相见。棱镜折射，这次生哥会以独特的几何视角带领大家进入一场光影拟梦的视听世界。&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img style&#x3D;&quot;max-width: 100%;&quot; src&#x3D;&quot;https://pxqsellerbff.piaoxingqiu.cn/image/prod/20230804_15/16911209572441362.jpg&quot;&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;概念海报多层寓意&amp;nbsp;&amp;nbsp;&amp;nbsp;全新主题&amp;ldquo;棱&amp;rdquo;惊艳来袭&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;

**Comment by jzhmcoo1** [comment]
你好，上述转义符（&ldquo;&rdquo;&mdash;）的支持预计会在小红书8.2版本上线。
另外如果有其他转义符也需要支持的话可以告诉我们一并修复
