### ISSUE TITLE
performance支持observer

### ISSUE THREAD

**Issue by KaKmi** [redengineer/redmini#862]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
微盟

## 平台
IOS, Android, IDE

## 小红书版本信息
8.0.1
 
## 基础库版本
v3.60.1

## 发生问题的时间 
2023-08-08 18:55:37 至 2023-08-08 18:55:37

## 问题描述
getPerformance不支持observer，无法确定消费数据时间，目前数据搜集需要时间，

## 期望结果
加入observer api返回 observe，observe可以订阅相关entryTye，具体api可以参考微信

## 重现步骤和复现问题的最小demo Github链接
   setInterval(() &#x3D;&gt; {
      const entries &#x3D; xhs.getPerformance &amp;&amp; xhs.getPerformance().getEntries()
      console.log(&#x27;entries&#x27;,entries)

      for (let i &#x3D; 0, len &#x3D; entries.length; i &lt; len; i++) {
        console.log(&quot;entry name: &quot; + entries[i].name);
        console.log(&quot;entry entryType: &quot; + entries[i].entryType);
        console.log(&quot;entry startTime: &quot; + entries[i].startTime);
        console.log(&quot;entry duration: &quot; + entries[i].duration);
        console.log(&quot;entry value: &quot; + entries[i].value);
      }
    }, 1000);
获取的数据 前面是3条后续是7条，时间不定，需要多次获取才能获取完整的数据，时机不定时

**Comment by Hubmeat** [comment]
收到
