### ISSUE TITLE
小红书小程序关店，提示商品未下架

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#866]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.0.1

## 运营场景描述
小红书小程序关店，提示商品未下架
appid：6322fef022f7940001ef359d 

## 发生问题的时间 
2023-08-09 15:05:32 至 2023-08-09 15:05:32

## 期望结果
提供所有未下架商品id

**Comment by Matthew-1996** [comment]
满足关店条件
