### ISSUE TITLE
小红书小程序关店，关店进度待确认

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#867]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.0.1

## 运营场景描述
小红书小程序关店，仍有商品未下架及订单待结算问题
appid：624eac098a505100010adbcb 

## 发生问题的时间 
2023-08-09 15:06:36 至 2023-08-09 15:06:36

## 期望结果
提供所有未下架商品id及未结算订单id

**Comment by Matthew-1996** [comment]
满足关店条件
