### ISSUE TITLE
小红书小程序关店，提示商品未下架

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#868]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.0.1

## 运营场景描述
小红书小程序关店，提示商品未下架
appid：62d7cfb1f8fccf000148419c 

## 发生问题的时间 
2023-08-09 15:08:59 至 2023-08-09 15:08:59

## 期望结果
提供所有未下架商品id

**Comment by Matthew-1996** [comment]
[查询结果 (77).csv](https://github.com/redengineer/redmini/files/12308466/77.csv)
商品未下架
