### ISSUE TITLE
小红书小程序体验版右上角关闭按钮不显示

### ISSUE THREAD

**Issue by yueweiliu** [redengineer/redmini#87]
## 系统环境(必填)
- [x] Android
Redmi K30 

## 问题模块(必填)
- [ ] API & 组件 & 框架

## 基础库版本或小红书APP版本(必填)
![1656662585111](https://user-images.githubusercontent.com/30645049/176853298-1623c128-049a-49f9-a9e2-3e859dc9a50b.jpg)
![1221602e7a16850c6be0aff62c3791f](https://user-images.githubusercontent.com/30645049/176853342-bfd4c2bf-4609-490d-a586-108405ec480e.jpg)

## 期望结果 和 实际结果(必填)
关闭按钮显示出来

## 补充(猜测可能的原因是什么，你有啥想法，选填)
关闭按钮样式被挤压隐藏了

**Comment by taiyiandr** [comment]
7.49 客户端已修复
