### ISSUE TITLE
使用uniapp开发小红书小程序，web-view 没有监听到bindmessage

### ISSUE THREAD

**Issue by dandelion-Chen** [redengineer/redmini#871]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
Klook

## 平台
IOS

## 小红书版本信息
8.0.1
 
## 基础库版本
v3.61.0

## 发生问题的时间 
2023-08-09 21:30:46 至 2023-08-09 21:49:46

## 问题描述
使用uniapp开发小红书小程序，web-view 没有监听到bindmessage
具体描述可见：https://github.com/redengineer/redmini/issues/870

## 期望结果
H5页面Postmessage后，分享时可以触发 bindmessage 事件

## 重现步骤和复现问题的最小demo Github链接
demo: https://github.com/dandelion-Chen/test_xhs
1. 扫码进入首页，点击【xhs 原生分享】按钮进行postmessage
2. 点击右上角进行分享页面
结果：只会触发 onShareAppMessage，没有监听到 bindmessage 事件
期望结果：分享时可以正常触发 bindmessage 事件

**Comment by jzhmcoo1** [comment]
你好，这边排查下来：
1. 原生语法调用失败是因为xhs的webview sdk没有正常被引入，不过我看你们的sdk里有xhs的sdk的相关逻辑，可以排查下是哪里的条件没有生效。
<img width="928" alt="CleanShot 2023-08-10 at 11 22 19@2x" src="https://github.com/redengineer/redmini/assets/55695299/4ea8d549-6bf4-4ff1-a080-cc6974cabd5e">
2. 使用uni.xxx方法调用的时候依赖uniapp的webview sdk，这边排查下来未对xhs的条件做判断，需要uniapp更新下webview sdk支持
<img width="936" alt="CleanShot 2023-08-10 at 11 23 56@2x" src="https://github.com/redengineer/redmini/assets/55695299/758b288b-fb8c-4e6c-88e3-12dfbdf53e25">

**Comment by dandelion-Chen** [comment]
> 你好，这边排查下来：
> 
> 1. 原生语法调用失败是因为xhs的webview sdk没有正常被引入，不过我看你们的sdk里有xhs的sdk的相关逻辑，可以排查下是哪里的条件没有生效。
> 
> <img alt="CleanShot 2023-08-10 at 11 22 19@2x" width="928" src="https://user-images.githubusercontent.com/55695299/259612147-4ea8d549-6bf4-4ff1-a080-cc6974cabd5e.png"> 2. 使用uni.xxx方法调用的时候依赖uniapp的webview sdk，这边排查下来未对xhs的条件做判断，需要uniapp更新下webview sdk支持 <img alt="CleanShot 2023-08-10 at 11 23 56@2x" width="936" src="https://user-images.githubusercontent.com/55695299/259612310-758b288b-fb8c-4e6c-88e3-12dfbdf53e25.png">

**Comment by dandelion-Chen** [comment]
在h5页面使用原生的方式 xhs.miniProgram.postMessage，在开发者工具上执行了bindmessage，但iOS手机上没有执行bindmessage。具体代码如下图：
![image](https://github.com/redengineer/redmini/assets/11973539/bf3cc863-8160-4733-867b-e7065d6a85ed)
![image](https://github.com/redengineer/redmini/assets/11973539/7976843c-61c8-4ee1-baa1-47da9c7c0c61)
![image](https://github.com/redengineer/redmini/assets/11973539/31acff6f-e57e-4da1-a2b0-53adcd2219f2)

**Comment by jzhmcoo1** [comment]
你好这个问题我们已经定位到了，预计跟版小红书8.3版本，你也可以用这个二维码试下，用小红书App扫码替换基础库，然后再打开小程序页面

![image](https://github.com/redengineer/redmini/assets/55695299/792dd29f-b0fa-4ecb-8c78-047ad40b059d)

**Comment by dandelion-Chen** [comment]
谢谢，切换基础库后可以监听到 bindmessage 事件了。

**Comment by gicbeenLee** [comment]
楼主你好,你这边更换到哪个基础库可以监听到事件了?
