### ISSUE TITLE
view点击事件未生效

### ISSUE THREAD

**Issue by muluolanke** [redengineer/redmini#877]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
上汽大众

## 平台
IOS

## 小红书版本信息
v7.97.2
 
## 基础库版本
v3.61.0

## 发生问题的时间 
2023-08-01 20:48:24 至 2023-08-11 20:48:24

## 问题描述
app未升级以前，view绑定事件均可正常跳转。升级为最新版本后，部分view绑定跳转事件点击无反应（第一次点击正常，跳转后再次点击同样事件，未生效），但是view标签中覆盖image时，可点击

## 期望结果
希望view只有文字或其他元素时也可进行正常跳转。

## 重现步骤和复现问题的最小demo Github链接
https://github.com/muluolanke/test-xhs

步骤：
扫码进入后，点击“精彩活动”中的按钮，第一次可能会跳转，但返回后，点击按钮没反应，点击图片可跳转

**Comment by jzhmcoo1** [comment]
请问上述最小demo的依赖对镜像源有要求吗，这边 @sx/flattern-ui-weapp 拉不下来

**Comment by muluolanke** [comment]
> 请问上述最小demo的依赖对镜像源有要求吗，这边 @sx/flattern-ui-weapp 拉不下来

git上删掉了这个，麻烦重新下拉下查看最新，谢谢
