### ISSUE TITLE
小红书小程序关店进度查询

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#880]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.1

## 运营场景描述
小红书小程序关店进度查询
appid：6233ee6c1f73530001c668c2 

## 发生问题的时间 
2023-08-14 17:19:50 至 2023-08-14 17:19:50

## 期望结果
提供目前未完成的关店步骤，有无未结算/未完成订单、未下架商品

**Comment by Matthew-1996** [comment]
未完成订单
[查询结果 (79).csv](https://github.com/redengineer/redmini/files/12364929/79.csv)

**Comment by Matthew-1996** [comment]
未结算订单
[查询结果 (84).csv](https://github.com/redengineer/redmini/files/12364980/84.csv)
