### ISSUE TITLE
小红书小程序关店，订单待结算问题

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#884]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.1

## 运营场景描述
小红书小程序关店，仍有订单待结算
appid：632c0831092216000166674c 

## 发生问题的时间 
2023-08-16 15:00:31 至 2023-08-16 15:00:31

## 期望结果
提供所有未结算订单号，并协同微盟侧处理未结算订单

**Comment by Matthew-1996** [comment]
436141508000183
