### ISSUE TITLE
小红书小程序关店，仍有未结算订单和未下架商品

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#889]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.1

## 运营场景描述
小红书小程序关店，仍有未结算订单和未下架商品
appid：6250e5da5f1bf30001b6ae4b 

## 发生问题的时间 
2023-08-16 15:09:10 至 2023-08-16 15:09:10

## 期望结果
提供所有未结算订单id和未下架商品id

**Comment by Matthew-1996** [comment]
未下架商品
[查询结果 (85).csv](https://github.com/redengineer/redmini/files/12364991/85.csv)

**Comment by Matthew-1996** [comment]
未计算订单
192931907017436
