### ISSUE TITLE
小红书小程序关店，仍有未结算订单和未下架商品

### ISSUE THREAD

**Issue by bonnie950123** [redengineer/redmini#890]
## Issue类型
operator

## 问题模块
订单/佣金结算

## 所属的服务商
微盟

## 小红书版本信息
v8.1

## 运营场景描述
小红书小程序关店，仍有未结算订单和未下架商品
appid：63880e1514e05500018b96aa 

## 发生问题的时间 
2023-08-16 15:10:22 至 2023-08-16 15:10:23

## 期望结果
提供所有未结算订单id及未下架商品id

**Comment by Matthew-1996** [comment]
未下架商品
[查询结果 (86).csv](https://github.com/redengineer/redmini/files/12364995/86.csv)

**Comment by Matthew-1996** [comment]
未结算订单
398860323000636
