### ISSUE TITLE
小红书支持mp-html

### ISSUE THREAD

**Issue by heiyantutu** [redengineer/redmini#899]
## Issue类型
feature

## 这个功能解决的问题
mp-html是一个支持多平台的富文本组件 小程序本身的富文本能力有限 此插件扩展了图片预览 地址跳转等功能 这样可以使用同一份的富文本 运行在多个平台上

**Comment by Hubmeat** [comment]
editor 组件是否可以满足需求呢？

**Comment by heiyantutu** [comment]
> editor 组件是否可以满足需求呢？

editor 组件无法在里面复制链接打开第三方链接 而且我这边只是做页面的富文本显示 不需要编辑 并且mp-html也支持更多的editor 无法满足的需求 比如外部样式对内的定义 占位图 懒加载等 如能支持 用户体验更佳

**Comment by jzhmcoo1** [comment]
在uniapp中使用mp-html开发小红书小程序目前应该是支持的。
排查了下，是image组件在mp-html的渲染策略下有些bug，导致展示不出来。我们会尽快修复下。

**Comment by jzhmcoo1** [comment]
已支持
