### ISSUE TITLE
授权二维码扫描后无反应

### ISSUE THREAD

**Issue by tanchidahuilang** [redengineer/redmini#90]
## 系统环境(必填)
- [ ] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [x] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 基础库版本或小红书APP版本(必填)
手机型号：华为  tas-TL00
小红书app版本：v.7.45.0.40b092f
用户扫码小红书appUid=623143a900000000210252c6

## 期望结果 和 实际结果(必填)
 - 期望结果: 扫码成功
 - 实际结果: 扫描二维码无反应
 已经更换了手机，将二维码放大 仍然没有反应

## 补充(猜测可能的原因是什么，你有啥想法，选填)
![飞书20220706-094805](https://user-images.githubusercontent.com/77264526/177450272-b4f44ff9-5e65-4acc-8a14-a8500b381603.png)

**Comment by taiyiandr** [comment]
辛苦贴一下二维码

**Comment by tanchidahuilang** [comment]
二维码已贴
