### ISSUE TITLE
橱窗商品已下架，但C端仍展示

### ISSUE THREAD

**Issue by mmeng1996** [redengineer/redmini#913]
## Issue类型
operator

## 问题模块
商品笔记

## 所属的服务商
微盟

## 小红书版本信息
v8.3.1

## 运营场景描述
商户已在后台将商品下架，但是商品橱窗仍然可以看到商品。
我方查到商品获取信息接口返回的字段SPU是 &quot;status&quot;: 0下架 状态
appId &#x3D; 626f79feb57d07000196a0e3 
out_product_id &#x3D; 118765123099908  
 
![7fd8ed63-8053-4da9-8222-5611cf0f3911](https://github.com/redengineer/redmini/assets/118496055/c7d3284b-0d7f-4239-a680-2d3cd3e754ca)

## 发生问题的时间 
2023-08-24 09:37:13 至 2023-08-25 09:37:13

## 期望结果
商户已下架的SPU级商品在橱窗页不展示

**Comment by xutm** [comment]
https://miniapp.xiaohongshu.com/third/api-3rd/post-api-rmp-tp-display-home_page_item_tab 
自定义商品tab后，目前没有过滤下架状态，需要同步更新下这里的商品Id
