### ISSUE TITLE
支付组件唤起后白屏，个别型号机型无法支付

### ISSUE THREAD

**Issue by zhoufeng133435** [redengineer/redmini#914]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
太目

## 平台
IOS, Android

## 小红书版本信息
8.3.1
 
## 基础库版本
v1.0.0

## 发生问题的时间 
2023-08-25 10:53:29 至 2023-08-25 10:53:29

## 问题描述
支付组件唤起后，小程序页面出现白屏1~2秒的情况，再跳转到支付平台的app。个人机型oppo find x6pro白屏后无法跳转进行支付。

## 期望结果
希望贵司尽快修复，支付组件无法正常运行，影响严重，各位辛苦！

## 重现步骤和复现问题的最小demo Github链接
小红书小程序内搜索【几何】，首页任选一个商品进行购买，到支付页面唤起支付组件即可复现此问题，建议用不同机型尝试，oppo find x6pro问题比较严重，无法正常跳转。希望尽快修复。

**Comment by taiyiandr** [comment]
小程序开发者的 H5 因网络问题加载较慢，已确认切换网络环境后问题不存在。
