### ISSUE TITLE
onShow调用时机不正常

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#920]
## Issue类型
operator

## 问题模块
生命周期调用异常

## 所属的服务商
有赞

## 小红书版本信息
v8.3

## 运营场景描述
用户在交易组件页面，点击支付跳转支付宝后，调用了onShow 当中的事件，按理应该在支付完成后回跳才会触发的节点

表现结果为：等到真正支付完成，跳转回来页面已经执行支付失败的回调，跳转到对应的支付结果页了，正常应该是支付完成跳转回来再调用这个方法，预期结果跳转支付成功页 

## 发生问题的时间 
2023-09-04 15:44:46 至 2023-09-04 17:44:46

## 期望结果
跳转支付宝后不触发交易组件所在页面onShow 中的事件
具体可判断事件调用接口为 wsctrade/order/payresult/checkPay.json

## 业务基础信息（选填）
商家appid：62c3cfdc1b7001000117ab20
测试appid: 62454b862247ab00013fc407
以上小程序均可复现

**Comment by taiyiandr** [comment]
iOS还是Android？

**Comment by taiyiandr** [comment]
支付中间页关闭并拉起外部支付应用的时候，是有可能导致上一个页面onShow的，试试用app 的 onShow应该没这问题。

**Comment by Jonesau** [comment]
> 支付中间页关闭并拉起外部支付应用的时候，是有可能导致上一个页面onShow的，试试用app 的 onShow应该没这问题。

可以通过xhs.onAppShow事件实现
可能存在的问题，用户如果未安装支付宝，停留在网页是否可以完成支付，支付完成后不会触发onAppShow事件？
