### ISSUE TITLE
开发者工具构建问题

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#921]
## Issue类型
operator

## 问题模块
开发者工具构建

## 所属的服务商
有赞

## 小红书版本信息
v8.4.1

## 运营场景描述
1. 小程序接口流程依赖getExtConfigSync()当中填写的appid数据，
project.config.json 与 ext.json 当中的 appId 不相同
project.config.json：61696cf8c52bb0000110bad2
ext.json：62454b862247ab00013fc407
基于以上情况、最新版开发者工具预览时，会提示&quot;Error：整包zip包目录不是61696cf8c52bb0000110bad2&quot;

如果同时填写61696cf8c52bb0000110bad2
模拟器是可以正常展示的（未请求相关接口 auth.json）-预览可以正常构建，但是实际到手机上体验，接口会报错

同时填写62454b862247ab00013fc407，无法打包 

## 发生问题的时间 
2023-09-05 10:34:26 至 2023-09-05 10:34:26

## 期望结果
1. 模拟器表现与手机端一致，
2. 能够在手机端正常预览

**Comment by helwodlrol** [comment]
开发者工具升级到2.0后有同样的问题。

**Comment by yujon** [comment]
升级到2.0.2，已经修复

**Comment by yujon** [comment]
> 开发者工具升级到2.0后有同样的问题。

升级到2.0.2，已经修复
