### ISSUE TITLE
iOS onAppShow 未触发问题

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#926]
## Issue类型
operator

## 问题模块
小程序应用级事件

## 所属的服务商
有赞

## 小红书版本信息
v8.4.1

## 运营场景描述
在iOS下
交易组件所在 Page onLoad 中调用
xhs.onAppShow(() &#x3D;&gt; {console.log(&#x27; --- Page xhs onAppShow --- &#x27;);/* 此处调用相关接口 */})
查看vconsole，有打印 &#x27; --- App onShow --- &#x27;，在xhs.onAppShow回调中信息均未触发

安卓暂时没办法抓包测试，可以帮忙一起看下 

## 发生问题的时间 
2023-09-06 15:53:09 至 2023-09-06 15:53:09

## 期望结果
1、iOS Page 下 调用 xhs.onAppShow 能够正常触发传入回调

**Comment by wernerpeng** [comment]
appshow时机是在onload前，pageshow时机是在onload后
顺序：
onAppshow -> Page onload ->Page show
