### ISSUE TITLE
开发者工具相关问题

### ISSUE THREAD

**Issue by Jonesau** [redengineer/redmini#927]
## Issue类型
operator

## 问题模块
开发者工具

## 所属的服务商
有赞

## 小红书版本信息
v8.4.0

## 运营场景描述
1、昨天下午五点左右开始，通过预览构建出的产物
双端在交易组件页获取不到query
iOS报错表现为没有orderNo
安卓报错表现为没有payToken
2、手机端报错时，开发者工具有时会自动断点，无法对开发者工具调试器做任何操作
3、无法使用鼠标在编辑器当中框选代码 

## 用户ID 
6164ec64000000000201d961

## 发生问题的时间 
2023-09-06 14:53:04 至 2023-09-07 10:00:00

## 期望结果
1、交易组件可以正常获取query
2、断点时可以正常使用调试器

**Comment by yujon** [comment]
升级到2.0.2，问题3已经修复。问题1、2我们继续跟进处理

**Comment by Jonesau** [comment]
问题一非开发者工具问题，已解决
