### ISSUE TITLE
小红书小程序后台配置业务域名，第三方服务器验签无法设置导致接口调用失败

### ISSUE THREAD

**Issue by yueweiliu** [redengineer/redmini#93]
## 系统环境(必填)
- [ ] IDE

## 问题模块(必填)
- [ ] 管理后台

## 重现步骤 和 复现问题的最小demo Github链接
目前小红书后台，要求配置的业务域名，必须配置验签文件；但是小程序调用的第三方域名，我们没法配置验签文件，导致接口调不通，希望增加服务器域名配置，可以不增加验签也能配置访问，参考百度：
服务器域名：
https://smartprogram.baidu.com/docs/third/domain/set_server/

业务域名：
https://smartprogram.baidu.com/docs/third/domain/set_biz/

## 期望结果 和 实际结果(必填)
第三方域名接口校验能够拆解开

**Comment by yueweiliu** [comment]
![8005b4e7243c18f94eedafcb2710eef](https://user-images.githubusercontent.com/30645049/177266001-14c6b7f6-ea64-4678-8504-b8d53e789d0e.png)

**Comment by wdvxdr** [comment]
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/3895399/177266989-63c7a01a-ace1-40f3-ada6-07675e433c24.png">
https://miniapp.xiaohongshu.com/third/api-3rd-doc/createThrid 业务域名目前只对web-view做限制，不包含服务端请求域名
