### ISSUE TITLE
小程序reuqest请求参数携带中文，真机上url参数未转义

### ISSUE THREAD

**Issue by fanqidong** [redengineer/redmini#935]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
魔方文娱

## 平台
IOS

## 小红书版本信息
8.6
 
## 基础库版本
v3.64.8

## 发生问题的时间 

2023-09-18 14:15:42 至 2023-09-18 14:15:42

## 问题描述
小程序reuqest请求参数携带中文，真机上url参数未转义

## 期望结果
小程序reuqest请求参数携带中文，真机上url参数正常转义

## 重现步骤和复现问题的最小demo Github链接
![test](https://github.com/redengineer/redmini/assets/33058804/5e0f5bda-b0e9-4bd2-a9b6-ee904cc64e55)

![test2](https://github.com/redengineer/redmini/assets/33058804/58e021c2-dedd-499e-97f3-a317f184a198)

**Comment by yanyunwu** [comment]
能给个最小demo的链接吗
