### ISSUE TITLE
小程序升级成功后即新版小程序发布成功后，冷启动或者重新进入小程序还是加载老版本小程序，需要多次清缓存、杀app进程后加载出新版本小程序

### ISSUE THREAD

**Issue by handsome025** [redengineer/redmini#94]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [ ] API & 组件 & 框架
- [ ] IDE
- [x] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [ ] 有赞
- [x] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 服务主体（如：小红书）
小红书
## 基础库版本或小红书APP版本(必填)
7.45.1
## 期望结果 和 实际结果(必填)
小程序冷启动或重新打开小程序能正常加载最新版本小程序
## 补充(猜测可能的原因是什么，你有啥想法，选填)
缓存或者下载小程序包失败

**Comment by AngryBrotherXiang** [comment]
默认加载本地业务资源包，异步去下载新的。

**Comment by xutm** [comment]
750 会提供包管理能力相关 API。帮助开发者管理小程序包更新
