### ISSUE TITLE
input的value值更新后，渲染滞后一趴

### ISSUE THREAD

**Issue by Suntgr** [redengineer/redmini#940]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
微盟

## 平台
IOS

## 小红书版本信息
8.6
 
## 基础库版本
v3.65.2

## 发生问题的时间 
2023-09-20 14:13:48 至 2023-09-20 14:13:48

## 问题描述
一个input组件，我将value属性更新之后，input组件没有重新渲染，我再次更新value之后，input却显示了前一次更新的value值。渲染慢了一趴

## 期望结果
input组件在value值每次更新之后都会重新渲染

## 重现步骤和复现问题的最小demo Github链接
https://github.com/Suntgr/xhs-demo/blob/master/page/view/index.xhsml

**Comment by Suntgr** [comment]
我发现给input添加一个key=“{{value}}”可以解决。但是这个应该你们底层去处理

**Comment by jzhmcoo1** [comment]
你好，我这边用你给的demo在IOS真机上跑了下，点击增加，没有复现你所描述的一直出现旧值的情况

你那边升级下IOS到小红书8.7版本看看能否解决呢？

**Comment by Suntgr** [comment]
@jzhmcoo1 你单击第一次增加的时候，你看一下看控制。这时候其实value值已经加1了、但是页面里的input没有变化

**Comment by a13837811459** [comment]
一个月了。问题还是没解决 @jzhmcoo1
