### ISSUE TITLE
新增商品报错类目不存在

### ISSUE THREAD

**Issue by Wang-Xijie** [redengineer/redmini#95]
## 系统环境(必填)
- [ ] IOS
- [ ] Android
- [x] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [x] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 基础库版本或小红书APP版本(必填)
api问题

## 重现步骤 和 复现问题的最小demo Github链接
curl --location --request POST 'https://miniapp.xiaohongshu.com/api/rmp/component/deal/product/upsert?appid=616e856cba1dc500014528fa&access_token=155cc0bc0d904e6cbe5e88b7574661e4' \
--header 'Content-Type: application/json' \
--data-raw '{
    "biz_create_time":1656861483,
    "biz_update_time":1656986606,
    "category_id":"5ff7e373d6fe200001e87b8b",
    "desc":"捷克带回Antique｜复古色调｜街景回忆",
    "name":"捷克Antique水彩小画",
    "out_product_id":"45429401_594742633",
    "path":"packages/goods/detail/index?alias=2ofdtpunvdlnd",
    "short_title":"捷克Antique水彩小",
    "skus":[
        {
            "name":"捷克Antique水彩小画",
            "origin_price":16500,
            "out_sku_id":"45429401_594742633_36592662",
            "sale_price":16500,
            "sku_image":"https://img01.yzcdn.cn/upload_files/2022/07/03/Fti8DDzsJqg92419m2PYigkrdGEb.jpg",
            "status":1
        }
    ],
    "top_image":"https://img01.yzcdn.cn/upload_files/2022/07/03/Fti8DDzsJqg92419m2PYigkrdGEb.jpg"
}'

调用商品更新修改接口报错类目不存在
类目id：5ff7e373d6fe200001e87b8b

## 期望结果 和 实际结果(必填)
新增商品 
报错：类目不存在

**Comment by wdvxdr** [comment]
内部类目发生变更，部分历史类目已废弃。小红书运营同学将统一同步一份类目到服务商侧。
