### ISSUE TITLE
在安卓上正常的样式在苹果上却出现异常

### ISSUE THREAD

**Issue by kele1314** [redengineer/redmini#950]
## Issue类型
bug

## 问题模块
小程序容器(iOS)
 
## 所属的服务商
百居易

## 平台
IOS, Android, IDE

## 小红书版本信息
8.7.1
 
## 基础库版本
v3.53.0

## 发生问题的时间 
2023-09-25 10:47:18 至 2023-09-25 10:47:18

## 问题描述
最近查看小程序时发现在苹果机器上出现顶部样式异常，但是在安卓机器却正常展示，开发者工具没有明显的报错

## 期望结果
所有平台都能正常显示

## 重现步骤和复现问题的最小demo Github链接
比如打开轻氧民宿店铺小程序，查看房源列表等页面

**Comment by xutm** [comment]
发一个截图，看看具体表现

**Comment by kele1314** [comment]
> 发一个截图，看看具体表现

![image](https://github.com/redengineer/redmini/assets/30413110/1c5b5c3a-4310-4d27-9333-a39f82283316)
这是 IOS
![image](https://github.com/redengineer/redmini/assets/30413110/ff969116-6f61-474f-b288-58eebcc30f56)
 这是安卓

**Comment by wernerpeng** [comment]
验证下来每次冷启的第一次打开会有问题，之后打开是正常的。每次打开容器侧的逻辑是一样的，建议检查下相关逻辑，第一次打开和之后打开是否有区别

**Comment by xutm** [comment]
3.66.3 修复，本周 四左右会发版

**Comment by kele1314** [comment]
> 验证下来每次冷启的第一次打开会有问题，之后打开是正常的。每次打开容器侧的逻辑是一样的，建议检查下相关逻辑，第一次打开和之后打开是否有区别

顶部 header 调试使用到的方法有xhs.getMenuButtonBoundingClientRect()，xhs.getSystemInfo，有空看下这两个方法获取的值在不同机型里是否是正确的

**Comment by wernerpeng** [comment]
已修复，预计跟版8.9版本；

**Comment by kele1314** [comment]
> 已修复，预计跟版8.9版本；

OK
