### ISSUE TITLE
调用xhs.requestOrderPayment接口时，提示：payMethod不合法

### ISSUE THREAD

**Issue by xiaoxu519** [redengineer/redmini#952]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
广西智语蔚来科技有限公司

## 平台
IOS, Android, IDE

## 小红书版本信息
8.5.0
 
## 基础库版本
v3.56.0

## 发生问题的时间 
2023-09-26 10:39:14 至 2023-09-26 10:39:14

## 问题描述
在小程序中调用xhs.requestOrderPayment接口拉起支付时，提示：payMethod不合法。根据文档的描述，目前仅支持直连支付 third，但当我调用该接口并且设置payMethod为third时，就会提示：payMethod不合法的。

## 期望结果
小程序能够正常拉起支付

## 重现步骤和复现问题的最小demo Github链接
调用接口时的代码：
xhs.requestOrderPayment({
    orderInfo: {
        orderId: &#x27;xxxxxx&#x27;,
        payToken: &#x27;xxxxxx&#x27;,
        payMehtod: &#x27;third&#x27;,
        wxUrl: &#x27;xxxxxx&#x27;,
        zfbUrl: &#x27;xxxxxx&#x27;
    },
    success(res) {
        console.log(res)
    },
    fail(err) {
        console.log(err)
    }
})

**Comment by xutm** [comment]
`payMehtod` 单词写错了
