### ISSUE TITLE
获取小程序的授权信息(调用凭证)失败

### ISSUE THREAD

**Issue by haojiasheng** [redengineer/redmini#96]
## 系统环境(必填)
- [x] IOS
- [ ] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [x] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 基础库版本或小红书APP版本(必填)
7.38

## 重现步骤 和 复现问题的最小demo Github链接
商家扫码授权时获取小程序的授权信息(调用凭证)失败，返回：{code: 410103, msg: 授权码不匹配}

auth_code：801d6d1d1e6e4e4cb4024b7f425997f5
appid：62b56d940ad3770001f495dc

## 期望结果 和 实际结果(必填)
调用成功

## 补充(猜测可能的原因是什么，你有啥想法，选填)
猜测是authcodo过期，但是扫码授权就几秒，过期不太合理吧

**Comment by haojiasheng** [comment]
> 

那怎么处理呢，需要你们帮助解除授权，然后商家重新授权吗

**Comment by wdvxdr** [comment]
重新获取auth_code，https://miniapp.xiaohongshu.com/third/api-3rd/post-api-rmp-tp-auth-apps-auth_code
