### ISSUE TITLE
【uni-app】vue3项目编译小红书真机扫码不显示内容， IDE正常显示

### ISSUE THREAD

**Issue by fanqidong** [redengineer/redmini#969]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
魔方文娱

## 平台
IOS, Android

## 小红书版本信息
8.9
 
## 基础库版本
v3.67.0

## 发生问题的时间 
2023-10-10 19:49:37 至 2023-10-10 19:49:37

## 问题描述
vue3项目编译小红书真机扫码不显示内容， IDE正常显示
IDE表现
![image](https://github.com/redengineer/redmini/assets/33058804/2efd0c88-126f-40de-b72f-3188b48e04da)
真机表现
![image](https://github.com/redengineer/redmini/assets/33058804/b092f3c5-3be6-4996-99b0-976ac56c7de3)

## 期望结果
vue3项目编译小红书真机扫码正常显示内容

## 重现步骤和复现问题的最小demo Github链接
[uni-preset-vue-vite-ts.zip](https://github.com/redengineer/redmini/files/12856784/uni-preset-vue-vite-ts.zip)

**Comment by jzhmcoo1** [comment]
IDE和真机的基础库版本一致吗，分别是多少

**Comment by fanqidong** [comment]
IDE 基础库是3.65.6 真机不知道怎么看 @jzhmcoo1
