### ISSUE TITLE
IDE同时运行两个不同项目，会展示相同的内容

### ISSUE THREAD

**Issue by fanqidong** [redengineer/redmini#974]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
魔方文娱

## 平台
IDE

## 小红书版本信息
8.9
 
## 基础库版本
v3.67.0

## 发生问题的时间 
2023-10-11 16:33:23 至 2023-10-11 16:33:23

## 问题描述
IDE同时运行两个不同项目，会展示相同的内容

## 期望结果
IDE同时运行项展示内容正常

## 重现步骤和复现问题的最小demo Github链接
![image](https://github.com/redengineer/redmini/assets/33058804/a6fd95fb-416f-4d77-8b44-92c1a20c079b)
![image](https://github.com/redengineer/redmini/assets/33058804/68a7eca5-1193-4894-a75a-3dbf5cde711a)

**Comment by yujon** [comment]
已修复
