### ISSUE TITLE
小程序webview中的网页使用navigator.getUserMedia报错，不能打开摄像头

### ISSUE THREAD

**Issue by lenmon54231** [redengineer/redmini#977]
## Issue类型
bug

## 问题模块
小程序基础组件
 
## 所属的服务商
其他（自开发）

## 平台
Android

## 小红书版本信息
8.8.1
 
## 基础库版本
v3.67.1

## 发生问题的时间 
2023-10-13 19:21:52 至 2023-10-13 19:21:52

## 问题描述
小程序webview接入https://project.kivisense.com/helper-tools/test-open-camera.html，会打不开摄像头，navigator.getUserMedia报错

## 期望结果
期望可以正常打开摄像头

## 重现步骤和复现问题的最小demo Github链接
https://project.kivisense.com/helper-tools/test-open-camera.html

**Comment by taiyiandr** [comment]
已处理，跟Android 8.12版本。
