### ISSUE TITLE
真机预览POST接口响应403

### ISSUE THREAD

**Issue by echooys** [redengineer/redmini#98]
## 系统环境(必填)
- [x] IOS
- [x] Android
- [ ] IDE

## 问题模块(必填)
- [ ] 审核
- [x] API & 组件 & 框架
- [ ] IDE
- [ ] 客户端
- [ ] 管理后台

## 是否是服务商开发者(服务商必填)[排名不分先后]
- [x] 有赞
- [ ] 微盟
- [ ] 直客通
- [ ] 民宿宝
- [ ] 订单来了
- [ ] 太目

## 服务主体（如：小红书）
小红书
## 基础库版本或小红书APP版本(必填)
基础库版本:3.28.1
小红书APP版本:7.45.0
## 重现步骤 和 复现问题的最小demo Github链接
![image](https://user-images.githubusercontent.com/63334662/177297380-18ae8912-9846-4101-8b59-02a557f0c6f8.png)
![image](https://user-images.githubusercontent.com/63334662/177297996-810332a3-aea4-4501-803f-bc71fd5a670d.png)
模拟器可以正常请求post接口，真机预览post接口响应403
## 期望结果 和 实际结果(必填)
真机预览正常响应post接口

**Comment by yueweiliu** [comment]
真机调试出现403，排查下来，小红书小程序真机请求中的header头部分参数缺失，accept-language为空被cdn安全策略拦截掉了

**Comment by AngryBrotherXiang** [comment]
accept-language需要开发者在调用xhs.request的时候自行往header上添加

**Comment by AngryBrotherXiang** [comment]
开发者没传Accept-Language，Android、iOS会添加默认的Accept-Language，7.48版本

**Comment by yueweiliu** [comment]
真机环境，在header中添加的参数，在后端请求接收是header为空，接口中设置的header不生效

![968cb5ea121023a40f50ec9ac52eea6](https://user-images.githubusercontent.com/30645049/177679698-abaf8cde-7f01-464e-862a-38970c326e95.png)
![c3ddfa9468a4b3dc691d2a24399cb04](https://user-images.githubusercontent.com/30645049/177679704-e471ddfa-44cf-49f7-b62c-d14bd9a13988.png)

**Comment by xutm** [comment]
`Referer` 不支持配置。

Android 本地做了验证是 ok 的
