### ISSUE TITLE
IDE  storage获取不到值

### ISSUE THREAD

**Issue by hhuwc** [redengineer/redmini#985]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
微盟

## 平台
IDE

## 小红书版本信息
8.10
 
## 基础库版本
v3.67.1

## 发生问题的时间 
2023-10-23 10:35:46 至 2023-10-23 10:35:46

## 问题描述
ide  local storage有值，但是通过getSorageSync一定概率拿不到

## 期望结果
正确获取到storage中存储的值

## 重现步骤和复现问题的最小demo Github链接
![企业微信截图_16977962181060](https://github.com/redengineer/redmini/assets/20037388/ca26b0ee-3be4-438c-8cb6-41cf7081a85d)
![企业微信截图_16977962447544](https://github.com/redengineer/redmini/assets/20037388/b117c770-9307-4f53-b13d-a4344ff51ef7)

**Comment by yujon** [comment]
没复现
