### ISSUE TITLE
打开小程序报错小红书app版本过低

### ISSUE THREAD

**Issue by zhoufeng133435** [redengineer/redmini#986]
## Issue类型
bug

## 问题模块
小程序框架
 
## 所属的服务商
太目

## 平台
IOS, Android

## 小红书版本信息
V8.10.0
 
## 基础库版本
v3.67.2

## 发生问题的时间 
2023-10-23 14:37:06 至 2023-10-23 14:37:06

## 问题描述
一加11机型，打开小程序报错小红书app版本过低，但小红书app已经是最高版本

## 期望结果
修复问题，可以正常唤起小程序即可

## 重现步骤和复现问题的最小demo Github链接
已经录屏发送到小红书研发同学

**Comment by taiyiandr** [comment]
小程序在开发后台配置的基础库版本要求高于线上所有版本，已通知开发者设置到 3.65.1
