### ISSUE TITLE
【IDE】模拟器左下角页面路径显示问题

### ISSUE THREAD

**Issue by hhuwc** [redengineer/redmini#990]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)
 
## 所属的服务商
微盟

## 平台
IDE

## 小红书版本信息
8.10
 
## 基础库版本
v3.67.2

## 发生问题的时间 
2023-10-25 14:08:03 至 2023-10-25 14:08:03

## 问题描述
模拟器 左下角页面路径显示不全，无法看全query参数

## 期望结果
提供一个复制按钮可以将当前的路径以及query参数复制出来

## 重现步骤和复现问题的最小demo Github链接
<img width="447" alt="image" src="https://github.com/redengineer/redmini/assets/20037388/f9438007-d3e5-4aa1-88c4-d837ecd474a3">

**Comment by yujon** [comment]
可以切换页面参数
<img width="672" alt="image" src="https://github.com/redengineer/redmini/assets/16963584/1ae8f563-3c88-4c53-893b-4442abc203d4">
