### ISSUE TITLE
小程序提审，报错：存在正在上传中的代码

### ISSUE THREAD

**Issue by kieedvra6192** [redengineer/redmini#993]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
8.10
 
## 基础库版本
v3.67.2

## 发生问题的时间 
2023-10-26 15:45:00 至 2023-10-26 15:47:00

## 问题描述
商家appId：6539e0cfe1507a0054283fdf
小程序名称：南澳岛环畅浠汐里海景民宿
提审返回结果：
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;存在正在上传中的代码&quot;,&quot;code&quot;:410208}

## 期望结果
小程序提审成功，小程序提审成功

## 重现步骤和复现问题的最小demo Github链接
商家appId：6539e0cfe1507a0054283fdf
小程序名称：南澳岛环畅浠汐里海景民宿
提审返回结果：
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;存在正在上传中的代码&quot;,&quot;code&quot;:410208}

**Comment by xutm** [comment]
代码还没上传完，加个 delay 试试

**Comment by kieedvra6192** [comment]
> 代码还没上传完，加个 delay 试试
hello，现在重新提审之后，报错信息如下：
result:{"data":null,"success":false,"msg":"上一份代码上传失败","code":410209}

出现这个问题，后续该咋处理呢

**Comment by kieedvra6192** [comment]
> 代码还没上传完，加个 delay 试试

hello，现在重新提审之后，报错信息如下：
result:{"data":null,"success":false,"msg":"上一份代码上传失败","code":410209}
出现这个问题，后续该咋处理呢？麻烦删除下这份提审数据，我们这边重新发起提审
