### ISSUE TITLE
小程序提审，报错：上一份代码上传失败 

### ISSUE THREAD

**Issue by kieedvra6192** [redengineer/redmini#996]
## Issue类型
bug

## 问题模块
小程序Api
 
## 所属的服务商
订单来了

## 平台
IDE

## 小红书版本信息
8.10
 
## 基础库版本
v3.67.2

## 发生问题的时间 
2023-10-27 14:26:24 至 2023-10-27 14:28:24

## 问题描述
商家appId：6539e0cfe1507a0054283fdf
小程序名称：南澳岛环畅浠汐里海景民宿
提审返回结果：
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;上一份代码上传失败&quot;,&quot;code&quot;:410209}

## 期望结果
小程序提审成功，小程序提审成功

## 重现步骤和复现问题的最小demo Github链接
商家appId：6539e0cfe1507a0054283fdf
小程序名称：南澳岛环畅浠汐里海景民宿
提审返回结果：
{&quot;data&quot;:null,&quot;success&quot;:false,&quot;msg&quot;:&quot;上一份代码上传失败&quot;,&quot;code&quot;:410209}

**Comment by xutm** [comment]
因为网络原因，上传失败，建议重新上传下
